### ISSUE TITLE
Jenkins ephemeral template (installed to dedicated hack machine) doesn't have edit permission

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#10257]
On ded-int-gcp.openshift.com I tried to install and run the jenkins ephemeral template and it failed, because the service account can't create deployments.  The templates aren't much use installed this way - if this is also the case for 1.3 (without them being auto deployed) I don't think we have a very good story to just install them.

```
Started by user Jenkins Admin
Building in workspace /var/lib/jenkins/jobs/OpenShift Sample/workspace


Starting "Scale OpenShift Deployment" with deployment config "frontend" from the project "test".
  Scaling to "0" replicas ...
ERROR: Build step failed with exception
com.openshift.restclient.authorization.ResourceForbiddenException: User "system:serviceaccount:test:default" cannot get deploymentconfigs in project "test"
	at com.openshift.internal.restclient.DefaultClient.createOpenShiftException(DefaultClient.java:483)
	at com.openshift.internal.restclient.DefaultClient.get(DefaultClient.java:312)
	at com.openshift.jenkins.plugins.pipeline.OpenShiftScaler.coreLogic(OpenShiftScaler.java:110)
	at com.openshift.jenkins.plugins.pipeline.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:116)
	at com.openshift.jenkins.plugins.pipeline.IOpenShiftPlugin.doIt(IOpenShiftPlugin.java:129)
	at com.openshift.jenkins.plugins.pipeline.OpenShiftBaseStep.perform(OpenShiftBaseStep.java:98)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: com.openshift.internal.restclient.http.HttpClientException: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:serviceaccount:test:default\" cannot get deploymentconfigs in project \"test\"",
  "reason": "Forbidden",
  "details": {
    "name": "frontend",
    "kind": "deploymentconfigs"
  },
  "code": 403
}
```

**Comment by bparees** [comment]
yes the readme for those templates explicitly tells you to grant service account permissions:
https://github.com/openshift/origin/blob/master/examples/jenkins/README.md (see step 2).

However as part of the work i'm doing to update the templates for 3.3 and combine them w/ the pipeline templates, this will be fixed (by having these templates create a jenkins service account), you can see the PR here:
https://github.com/openshift/origin/pull/10260

**Comment by cameron-scrace** [comment]
The link above has been edited and step 2 was removed. Looking through the history I was able to find what it said previously.  

Add the `edit` role to the `default` service account in the `test` project:
  $ oc policy add-role-to-user edit -z default
 This will allow the service account Jenkins uses to run builds and tag images.

**Comment by bparees** [comment]
@cameron-scrace it was edited because that step is no longer necessary as the template now creates the service account w/ the correct permissions.  that was the fix to this issue.

**Comment by cameron-scrace** [comment]
Our template must be out of date then, because that command fixed our issue.
