### ISSUE TITLE
Can't push images to 1.3.0-alpha3 docker-registry

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#10324]
Unable to push images to docker registry openshift/origin-docker-registry:v1.3.0-alpha.3
Downgrading back to origin-docker-registry:v1.3.0-alpha.3 does not have this issue.

Error:
```
Pushing image 172.30.144.124:5000/test/test:latest ...
Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: EOF
```

Config file (s3)
```
version: 0.1
log:
  level: info
http:
  addr: :5000
storage:
  cache:
    layerinfo: inmemory
  s3:
      accesskey: 
      secretkey: 
      region: 
      bucket: 
      encrypt: false
      secure: true
      v4auth: true
      chunksize: 26214400
      rootdirectory: /registry
  delete:
    enabled: true
auth:
  openshift:
    realm: openshift
middleware:
  repository:
    - name: openshift
http:
  tls:
    certificate: /etc/secrets/registry.crt
    key: /etc/secrets/registry.key
```

docker-registry log

```
time="2016-08-10T07:29:06.882023903Z" level=panic msg="Configuration error: OpenShift registry middleware not activated" 
2016-08-10 07:29:06.882174 I | http: panic serving 10.131.0.1:34558: &{0xc820010680 map[] 2016-08-10 07:29:06.882023903 +0000 UTC panic Configuration error: OpenShift registry middleware not activated}
goroutine 226 [running]:
net/http.(*conn).serve.func1(0xc8206f2300)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x1da2380, 0xc82052c6c0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/openshift/origin/vendor/github.com/Sirupsen/logrus.(*Entry).log(0xc82052c6c0, 0x0, 0xc82052c700, 0x40)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/Sirupsen/logrus/entry.go:103 +0x60f
github.com/openshift/origin/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc82052c6c0, 0xc8207b4d60, 0x1, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/Sirupsen/logrus/entry.go:148 +0x7c
github.com/openshift/origin/vendor/github.com/Sirupsen/logrus.(*Logger).Panic(0xc820010680, 0xc8207b4d60, 0x1, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/Sirupsen/logrus/logger.go:155 +0xed
github.com/openshift/origin/vendor/github.com/Sirupsen/logrus.Panic(0xc8207b4d60, 0x1, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/Sirupsen/logrus/exported.go:102 +0x41
github.com/openshift/origin/pkg/cmd/dockerregistry.panicHandler.func1.1()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/dockerregistry/dockerregistry.go:254 +0x1a1
panic(0x16e7cc0, 0xc8205f9c60)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/openshift/origin/pkg/dockerregistry/server.init.4.func1(0x7f999f3ea6a0, 0xc820318a20, 0x7f999f408290, 0xc820549960, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/dockerregistry/server/repositorymiddleware.go:97 +0xd8
github.com/openshift/origin/vendor/github.com/docker/distribution/registry/middleware/repository.Get(0x7f999f3ea6a0, 0xc820318a20, 0xc820447a80, 0x9, 0x0, 0x7f999f408290, 0xc820549960, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/middleware/repository/middleware.go:35 +0xf7
github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers.applyRepoMiddleware(0x7f999f3ea6e0, 0xc820318a20, 0x7f999f408290, 0xc820549960, 0xc82031dae0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers/app.go:923 +0x175
github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers.(*App).dispatcher.func1(0x7f999f406758, 0xc820874500, 0xc82064bdc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers/app.go:670 +0x1e99
net/http.HandlerFunc.ServeHTTP(0xc82026ec60, 0x7f999f406758, 0xc820874500, 0xc82064bdc0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/openshift/origin/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc820012be0, 0x7f999f406758, 0xc820874500, 0xc82064bdc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers.(*App).ServeHTTP(0xc820318a20, 0x7f999f406758, 0xc820874500, 0xc82064bdc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers/app.go:602 +0x30e
github.com/openshift/origin/pkg/cmd/dockerregistry.alive.func1(0x7f999f3ed2b8, 0xc820551860, 0xc82064bdc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/dockerregistry/dockerregistry.go:243 +0x131
net/http.HandlerFunc.ServeHTTP(0xc82018e8a0, 0x7f999f3ed2b8, 0xc820551860, 0xc82064bdc0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/openshift/origin/pkg/cmd/dockerregistry.alive.func1(0x7f999f3ed2b8, 0xc820551860, 0xc82064bdc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/dockerregistry/dockerregistry.go:243 +0x131
net/http.HandlerFunc.ServeHTTP(0xc82018e8d0, 0x7f999f3ed2b8, 0xc820551860, 0xc82064bdc0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/openshift/origin/vendor/github.com/docker/distribution/health.Handler.func1(0x7f999f3ed2b8, 0xc820551860, 0xc82064bdc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/health/health.go:271 +0x19a
net/http.HandlerFunc.ServeHTTP(0xc8204d7660, 0x7f999f3ed2b8, 0xc820551860, 0xc82064bdc0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/openshift/origin/pkg/cmd/dockerregistry.panicHandler.func1(0x7f999f3ed2b8, 0xc820551860, 0xc82064bdc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/dockerregistry/dockerregistry.go:257 +0x77
net/http.HandlerFunc.ServeHTTP(0xc8204d7680, 0x7f999f3ed2b8, 0xc820551860, 0xc82064bdc0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/openshift/origin/vendor/github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f999f3cd358, 0xc820022010, 0x7f999f3cd780, 0xc8204d7680, 0x7f999f3ed210, 0xc82026b520, 0xc82064bdc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/gorilla/handlers/handlers.go:88 +0x1af
github.com/openshift/origin/vendor/github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc8204d76a0, 0x7f999f3ed210, 0xc82026b520, 0xc82064bdc0)
	<autogenerated>:15 +0xb4
net/http.serverHandler.ServeHTTP(0xc82005bc00, 0x7f999f3ed210, 0xc82026b520, 0xc82064bdc0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8206f2300)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

```

**Comment by miminar** [comment]
@andrewklau please update your config file according to [docs](https://docs.openshift.org/latest/install_config/install/docker_registry.html#docker-registry-deploying-updated-configuration).

Your middleware section needs to contain at least following entries:

```
  registry:
    - name: openshift
  repository:
    - name: openshift
  storage:
    - name: openshift
```

I'll make it clear in the docs.

**Comment by andrewklau** [comment]
@miminar thanks, I'll try it in the morning. 

If that's the case the ansible installer should also be updated. I'll open an issue there.

**Comment by andrewklau** [comment]
Yep that fixes it!
