### ISSUE TITLE
[travis] internal compiler error: schedule does not include all values

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#10445]
```
 github.com/openshift/origin/vendor/github.com/prometheus/common/model
vendor/github.com/prometheus/common/model/value.go:404: invalid instruction: 00651 (/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/prometheus/common/model/time.go:189)	IMULQ	$60000000000, AX
vendor/github.com/prometheus/common/model/value.go:404: invalid instruction: 00763 (/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/prometheus/common/model/time.go:187)	IMULQ	$3600000000000, AX
vendor/github.com/prometheus/common/model/value.go:404: invalid instruction: 00838 (/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/prometheus/common/model/time.go:185)	IMULQ	$86400000000000, AX
vendor/github.com/prometheus/common/model/value.go:404: invalid instruction: 01166 (/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/prometheus/common/model/time.go:183)	IMULQ	$604800000000000, AX
# github.com/openshift/origin/vendor/google.golang.org/grpc/transport
vendor/google.golang.org/grpc/transport/http_util.go:271: internal compiler error: schedule does not include all values

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0xa0c844, 0x24, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/gc/subr.go:165 +0x248
cmd/compile/internal/gc.(*ssaExport).Fatalf(0xce6668, 0xc400000844, 0xa0c844, 0x24, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/gc/ssa.go:4569 +0x74
cmd/compile/internal/ssa.(*Config).Fatalf(0xc421184000, 0x844, 0xa0c844, 0x24, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/ssa/config.go:271 +0x6e
cmd/compile/internal/ssa.(*Func).Fatalf(0xc42124fb30, 0xa0c844, 0x24, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/ssa/func.go:397 +0x6b
cmd/compile/internal/ssa.schedule(0xc42124fb30)
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/ssa/schedule.go:257 +0x11ef
cmd/compile/internal/ssa.Compile(0xc42124fb30)
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/ssa/compile.go:64 +0x323
cmd/compile/internal/gc.buildssa(0xc420ec6fc0, 0x0)
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/gc/ssa.go:235 +0xc5e
cmd/compile/internal/gc.compile(0xc420ec6fc0)
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/gc/pgen.go:405 +0x1370
cmd/compile/internal/gc.funccompile(0xc420ec6fc0)
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x186
cmd/compile/internal/gc.Main()
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/gc/main.go:465 +0x19ab
cmd/compile/internal/amd64.Main()
	/home/travis/.gimme/versions/go/src/cmd/compile/internal/amd64/galign.go:93 +0x2fa
main.main()
	/home/travis/.gimme/versions/go/src/cmd/compile/main.go:33 +0x2a3
```
https://travis-ci.org/openshift/origin/jobs/152607332

**Comment by liggitt** [comment]
https://github.com/golang/go/issues/16741

**Comment by liggitt** [comment]
only an issue on go tip (1.8 devel branch)

**Comment by liggitt** [comment]
fixed by travis changes in https://github.com/openshift/origin/pull/10472 or #10458

**Comment by rhcarvalho** [comment]
Seen again in #9926 (https://travis-ci.org/openshift/origin/jobs/152996573) today.
