### ISSUE TITLE
TestClusterQuotaFuzzer times out

### ISSUE THREAD

**Issue by miminar** [openshift/origin#10738]
Here's a snippet from a failed job:

```
In suite "github.com/openshift/origin/pkg/quota/controller/clusterquotamapping", test case "TestClusterQuotaFuzzer" failed:
=== RUN   TestClusterQuotaFuzzer
I0831 06:33:21.122258   23248 clusterquotamapping.go:96] Shutting down quota mapping controller
I0831 06:33:22.103245   23248 clusterquotamapping.go:96] Shutting down quota mapping controller
....
panic: test timed out after 2m0s

goroutine 3483 [running]:
panic(0x1a82c40, 0xc82234f310)
    /usr/lib/golang/src/runtime/panic.go:481 +0x3ff
testing.startAlarm.func1()
    /usr/lib/golang/src/testing/testing.go:725 +0x184
created by time.goFunc
    /usr/lib/golang/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 2 minutes]:
testing.RunTests(0x2590d70, 0x3091ee0, 0x1, 0x1, 0x3098d01)
    /usr/lib/golang/src/testing/testing.go:583 +0xb39
testing.(*M).Run(0xc820038f10, 0x30bb500)
    /usr/lib/golang/src/testing/testing.go:515 +0x11e
main.main()
    github.com/openshift/origin/pkg/quota/controller/clusterquotamapping/_test/_testmain.go:102 +0x386

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
    /usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/openshift/origin/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x30bbb60)
    /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:879 +0x8c
created by github.com/openshift/origin/vendor/github.com/golang/glog.init.1
    /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:410 +0x2ba
...
```

See the failed job https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/5648/console of parent https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/8574/.

**Comment by kargakis** [comment]
Back: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_check/1770/consoleFull#181393306558b6e51eb7608a5981914356
