### ISSUE TITLE
Extended image test failing because of a 500 error from S3 storage

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#11103]
Error from test log:

```
com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: FDA75CE7260213BE), S3 Extended Request ID: MOolM46HVF61fRV7DJVHdMbCyRnCdSIp9x1Iy1oZ5c4/8zHc66Uy04M6IGSPrOr+qmdtDKbqr+0=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3659)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1422)
        at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:131)
        at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123)
        at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:139)
        at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:47)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Build step 'Publish artifacts to S3 Bucket' marked build as failure
```

Failed test:
https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/origin_extended_image_tests/588/

**Comment by csrwng** [comment]
@dobbymoodge

**Comment by csrwng** [comment]
@gabemontero fyi

**Comment by dobbymoodge** [comment]
It looks like the S3 plugin has a PR and bug report for this, but it was never merged: https://github.com/jenkinsci/s3-plugin/pull/53

https://issues.jenkins-ci.org/browse/JENKINS-27284
