### ISSUE TITLE
Discovery client seems to be getting back cached data twice

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#11111]
```
I0927 10:32:54.894447    6391 cached_discovery.go:80] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/servergroups.json
I0927 10:32:54.894800    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/apps/v1alpha1/serverresources.json
I0927 10:32:54.895102    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/authentication.k8s.io/v1beta1/serverresources.json
I0927 10:32:54.895463    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/autoscaling/v1/serverresources.json
I0927 10:32:54.895734    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/batch/v1/serverresources.json
I0927 10:32:54.896042    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/batch/v2alpha1/serverresources.json
I0927 10:32:54.896402    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/certificates.k8s.io/v1alpha1/serverresources.json
I0927 10:32:54.896711    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/extensions/v1beta1/serverresources.json
I0927 10:32:54.897019    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/policy/v1alpha1/serverresources.json
I0927 10:32:54.897316    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/storage.k8s.io/v1beta1/serverresources.json
I0927 10:32:54.897839    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/v1/serverresources.json
I0927 10:32:54.899035    6391 cached_discovery.go:80] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/servergroups.json
I0927 10:32:54.899457    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/apps/v1alpha1/serverresources.json
I0927 10:32:54.899788    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/authentication.k8s.io/v1beta1/serverresources.json
I0927 10:32:54.900067    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/autoscaling/v1/serverresources.json
I0927 10:32:54.900406    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/batch/v1/serverresources.json
I0927 10:32:54.900670    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/batch/v2alpha1/serverresources.json
I0927 10:32:54.900944    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/certificates.k8s.io/v1alpha1/serverresources.json
I0927 10:32:54.901943    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/extensions/v1beta1/serverresources.json
I0927 10:32:54.902387    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/policy/v1alpha1/serverresources.json
I0927 10:32:54.902845    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/storage.k8s.io/v1beta1/serverresources.json
I0927 10:32:54.903390    6391 cached_discovery.go:38] returning cached discovery info from /home/vagrant/.kube/10.0.2.15_8443/v1/serverresources.json
```

cc: @deads2k @liggitt

**Comment by liggitt** [comment]
once from `pkg/cmd/util/clientcmd.NewShortcutExpander()`:
```
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/Users/jliggitt/.gvm/gos/go1.6/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/Users/jliggitt/.gvm/gos/go1.6/src/runtime/debug/stack.go:16 +0x18
github.com/openshift/origin/pkg/cmd/util/clientcmd.(*CachedDiscoveryClient).ServerGroups(0xc8202f34d0, 0xc8207723f0, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/util/clientcmd/cached_discovery.go:75 +0x39
github.com/openshift/origin/pkg/cmd/util/clientcmd.(*CachedDiscoveryClient).ServerResources(0xc8202f34d0, 0x0, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/util/clientcmd/cached_discovery.go:58 +0x42
github.com/openshift/origin/pkg/cmd/util/clientcmd.NewShortcutExpander(0x6a04180, 0xc8202f34d0, 0x55b7e88, 0xc820772400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/util/clientcmd/shortcut_restmapper.go:22 +0xa0
github.com/openshift/origin/pkg/cmd/util/clientcmd.NewFactory.func1(0xc820760401, 0x0, 0x0, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/util/clientcmd/factory.go:236 +0x9a6
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.RunGet(0xc82019e120, 0x55931c0, 0xc820032010, 0x55931c0, 0xc820032018, 0xc820760480, 0xc820719510, 0x1, 0x1, 0xc8205dc060, ...)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:159 +0x511
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdGet.func1(0xc820760480, 0xc820719510, 0x1, 0x1)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:103 +0xa7
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc820760480, 0xc820719480, 0x1, 0x1, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x896
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8207a9680, 0xc820760480, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x55c
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8207a9680, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2d
main.main()
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:33 +0x1a6
```

once from `pkg/cmd/util/clientcmd.ShortcutExpander.AliasesForResource()`
```
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/Users/jliggitt/.gvm/gos/go1.6/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/Users/jliggitt/.gvm/gos/go1.6/src/runtime/debug/stack.go:16 +0x18
github.com/openshift/origin/pkg/cmd/util/clientcmd.(*CachedDiscoveryClient).ServerGroups(0xc8202f34d0, 0x39a1448, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/util/clientcmd/cached_discovery.go:75 +0x39
github.com/openshift/origin/pkg/api/restmapper.(*discoveryRESTMapper).getDelegate(0xc82026cb70, 0x0, 0x0, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/api/restmapper/discovery.go:36 +0x115
github.com/openshift/origin/pkg/api/restmapper.(*discoveryRESTMapper).AliasesForResource(0xc82026cb70, 0x7fff5fbff56f, 0x4, 0x0, 0x0, 0x0, 0x20)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/api/restmapper/discovery.go:163 +0x3c
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl.ShortcutExpander.AliasesForResource(0x6a041d8, 0xc82026cb70, 0x7fff5fbff56f, 0x4, 0x0, 0x0, 0x0, 0xc8205ffa50)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/kubectl.go:137 +0x1d0
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl.(*ShortcutExpander).AliasesForResource(0xc820772400, 0x7fff5fbff56f, 0x4, 0x0, 0x0, 0x0, 0x1)
	<autogenerated>:1123 +0xbd
github.com/openshift/origin/pkg/cmd/util/clientcmd.ShortcutExpander.AliasesForResource(0x55b7e88, 0xc820772400, 0xc820a97d00, 0x8, 0x8, 0x7fff5fbff56f, 0x4, 0x0, 0x0, 0x0, ...)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/util/clientcmd/shortcut_restmapper.go:102 +0x39b
github.com/openshift/origin/pkg/cmd/util/clientcmd.(*ShortcutExpander).AliasesForResource(0xc8202faba0, 0x7fff5fbff56f, 0x4, 0x0, 0x0, 0x0, 0xc8205ffa50)
	<autogenerated>:42 +0xc3
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl.(*OutputVersionMapper).AliasesForResource(0xc8202fabd0, 0x7fff5fbff56f, 0x4, 0x0, 0x0, 0x0, 0x1)
	<autogenerated>:1101 +0x78
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).replaceAliases(0xc820a6f790, 0x7fff5fbff56f, 0x4, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:365 +0x159
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).ResourceTypeOrNameArgs(0xc820a6f790, 0x1, 0xc820719510, 0x1, 0x1, 0xc820a6f790)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:339 +0x545
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.RunGet(0xc82019e120, 0x55931c0, 0xc820032010, 0x55931c0, 0xc820032018, 0xc820760480, 0xc820719510, 0x1, 0x1, 0xc8205dc060, ...)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:287 +0xfa2
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdGet.func1(0xc820760480, 0xc820719510, 0x1, 0x1)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:103 +0xa7
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc820760480, 0xc820719480, 0x1, 0x1, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x896
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8207a9680, 0xc820760480, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x55c
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8207a9680, 0x0, 0x0)
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2d
main.main()
	/Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:33 +0x1a6
```

**Comment by deads2k** [comment]
I don't feel too bad about reading files twice from a cache, but even if someone else does, be aware that this code is likely to be affected by the next rebase where these are included in the upstream code.
