### ISSUE TITLE
Tito auto generated provides fails with arugment list too long

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#11125]
```
$ tito build --test --rpm
    Building package [v0.0.1]
    Traceback (most recent call last):
      File "/usr/bin/tito", line 23, in <module>
        CLI().main(sys.argv[1:])
      File "/usr/lib/python3.4/site-packages/tito/cli.py", line 202, in main
        return module.main(argv)
      File "/usr/lib/python3.4/site-packages/tito/cli.py", line 367, in main
        return builder.run(self.options)
      File "/usr/lib/python3.4/site-packages/tito/builder/main.py", line 147, in run
        self.rpm()
      File "/usr/lib/python3.4/site-packages/tito/builder/main.py", line 463, in rpm
        self._setup_test_specfile()
      File "/home/skuznets/Documents/go/src/github.com/openshift/origin/.tito/lib/origin/builder/__init__.py", line 113, in _setup_test_specfile
        print(run_command(update_provides_list))
      File "/usr/lib/python3.4/site-packages/tito/common.py", line 419, in run_command
        (status, output) = getstatusoutput(command)
      File "/usr/lib/python3.4/site-packages/tito/compat.py", line 59, in getstatusoutput
        return subprocess.getstatusoutput(cmd)
      File "/usr/lib64/python3.4/subprocess.py", line 717, in getstatusoutput
        data = check_output(cmd, shell=True, universal_newlines=True, stderr=STDOUT)
      File "/usr/lib64/python3.4/subprocess.py", line 607, in check_output
        with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
      File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.4/subprocess.py", line 1457, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    OSError: [Errno 7] Argument list too long
```

##### Version
master branch

##### Steps To Reproduce
1. tito build --test

##### Current Result
```
      File "/usr/lib64/python3.4/subprocess.py", line 1457, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    OSError: [Errno 7] Argument list too long
```

##### Expected Result
things build

**Comment by sdodson** [comment]
@maxamillion mind taking a look if you have time?
@stevekuznetsov fyi

**Comment by maxamillion** [comment]
This is because the list of bundled libraries is hitting the upper bounds that we can pass subprocess (also hits the limit on how large of a string you can pass a shell and causes sed to fail outright). It's failing to build for other reasons now but my PR fixes tito.

**Comment by maxamillion** [comment]
Pull request to fix this has merged, closing.
