### ISSUE TITLE
CLI: using an output other than yaml or json with 'oc set' commands results in an error

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#11439]
Version: 
```
oc v1.4.0-alpha.0+10ab30d
kubernetes v1.4.0+776c994
```

```
$ oc set env dc/simple-ruby VAR1=value1 -o wide
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1dfb4d]

goroutine 1 [running]:
panic(0x1f621a0, 0xc4200120c0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/openshift/origin/pkg/cmd/cli/cmd/set.RunEnv(0xc420530ae0, 0x3588380, 0xc420034008, 0x35883c0, 0xc420034010, 0xc420785200, 0xc4205c8100, 0x2, 0x4, 0x0, ...)
	/Users/cewong/Code/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/set/env.go:493 +0x1ebd
github.com/openshift/origin/pkg/cmd/cli/cmd/set.NewCmdEnv.func1(0xc420785200, 0xc4205c8100, 0x2, 0x4)
	/Users/cewong/Code/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/set/env.go:83 +0xd0
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420785200, 0xc4205c80c0, 0x4, 0x4, 0xc420785200, 0xc4205c80c0)
	/Users/cewong/Code/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x439
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4207c86c0, 0xc420034008, 0xc420034018, 0xc4207c86c0)
	/Users/cewong/Code/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4207c86c0, 0x2, 0xc4207c86c0)
	/Users/cewong/Code/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/Users/cewong/Code/go/src/github.com/openshift/origin/cmd/oc/oc.go:33 +0x165
```

**Comment by csrwng** [comment]
@juanvallejo @fabianofranz

**Comment by juanvallejo** [comment]
It looks like the issue is happening [here](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/set/env.go#L493). Upstream [returns a `nil` value for `wide` printers](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L137), as well as a `nil` value for the error, so when the values returned by `kubectl.GetPrinter...` [are checked for a nil](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/set/env.go#L488) error, the printer is assumed to exist. Is this panic happening with other `set` subcommands as well?

**Comment by csrwng** [comment]
Yes, I believe it happens with all of them
