### ISSUE TITLE
`concurrent map read and map write` panic seen deleting namespaces

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#11584]
I created three namespaces, waited about a minute, then deleted all three, and saw this in the server logs:

```
fatal error: concurrent map read and map write

goroutine 32367 [running]:
runtime.throw(0xa08fca0, 0x21)
    /Users/jliggitt/.gvm/gos/go1.6/src/runtime/panic.go:530 +0x90 fp=0xc82f3c3130 sp=0xc82f3c3118
runtime.mapaccess1(0x8feac80, 0xc8252d7a70, 0xc82f3c3390, 0xc82f3c3268)
    /Users/jliggitt/.gvm/gos/go1.6/src/runtime/hashmap.go:289 +0x5a fp=0xc82f3c3178 sp=0xc82f3c3130
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace.listCollection(0xc82741a620, 0xc8252d7a70, 0x0, 0x0, 0xc8284af450, 0x2, 0xc826c5c2b0, 0x8, 0xc828f3f8d9, 0x3, ...)
    /Users/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller_utils.go:200 +0x34c fp=0xc82f3c33d8 sp=0xc82f3c3178
```

**Comment by liggitt** [comment]
this also exits the apiserver process

**Comment by ncdc** [comment]
The opCache is a typedef'd map and it's used read-write in multiple goroutines :-(

**Comment by ncdc** [comment]
I tried a bit but wasn't able to repro locally. Must not have been doing the same things you did.

**Comment by ncdc** [comment]
https://github.com/kubernetes/kubernetes/pull/36248
