### ISSUE TITLE
oc binary crashes due to panic

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#11744]
The ``oc`` program panic'd and crashed.

```
$ oc new-build --name dunnies --binary --strategy=source
    * A source build using binary input will be created
      * The resulting image will be pushed to image stream "dunnies:latest"
      * Use 'start-build --from-dir=DIR|--from-repo=DIR|--from-file=FILE' to trigger a new build
      * WARNING: a binary build was created, you must specify one of --from-dir|--from-file|--from-repo when starting builds

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0xcba36b]

goroutine 1 [running]:
panic(0x2036520, 0xc8200140d0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/openshift/origin/pkg/generate/app.(*ImageRef).ObjectReference(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/app/imageref.go:173 +0x3b
github.com/openshift/origin/pkg/generate/app.(*BuildStrategyRef).BuildStrategy(0xc8206e3de0, 0xc82058fd70, 0xc82086e5f0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/app/app.go:217 +0x3f1
github.com/openshift/origin/pkg/generate/app.(*BuildRef).BuildConfig(0xc82058ffb0, 0x1f61e00, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/app/app.go:249 +0x3fe
github.com/openshift/origin/pkg/generate/app.(*Pipeline).Objects(0xc82086e5a0, 0x4168770, 0xc82007e3f8, 0x4168798, 0xc8208691e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/app/pipeline.go:199 +0x4b0
github.com/openshift/origin/pkg/generate/app/cmd.(*AppConfig).Run(0xc820019b80, 0xc82007e008, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/app/cmd/newapp.go:659 +0xf3e
github.com/openshift/origin/pkg/cmd/cli/cmd.(*NewBuildOptions).Run(0xc82013a460, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/newbuild.go:195 +0x95
github.com/openshift/origin/pkg/cmd/cli/cmd.NewCmdNewBuild.func1(0xc82059bb00, 0xc8200c0400, 0x0, 0x4)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/newbuild.go:109 +0x110
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc82059bb00, 0xc8200c03c0, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x896
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc82055cd80, 0xc82059bb00, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x55c
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc82055cd80, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2d
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:29 +0x180
```
##### Version

```
$ oc version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce

Run the command:

```
oc new-build --binary --strategy=source --name sunnies
```

##### Current Result

Crashes as above.

##### Expected Result

Should create binary build.

##### Additional Information

The command works if drop the ``--strategy=source`` argument.

**Comment by GrahamDumpleton** [comment]
Appears to be a transient issue. I could replicate it a number of times, but when came back later to do a run with ``--loglevel=9`` it then would succeed.

**Comment by GrahamDumpleton** [comment]
This is on MacOS X, bit not Sierra.

```
Darwin grumpy-old-man.fritz.box 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
```

**Comment by GrahamDumpleton** [comment]
Run where crashes and have logging enabled.

```
I1103 13:43:38.818096    6479 loader.go:330] Config loaded from file /Users/graham/.kube/config
I1103 13:43:38.824671    6479 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v1.3.1 (darwin/amd64) openshift/dad658d" -H "Authorization: Bearer JHGI8mYpHyt9oaQI9aM-ZTNYO3wXFs1N4qg55KGHmuI" https://127.0.0.1:8443/oapi
I1103 13:43:38.963683    6479 round_trippers.go:318] GET https://127.0.0.1:8443/oapi 200 OK in 138 milliseconds
I1103 13:43:38.963710    6479 round_trippers.go:324] Response Headers:
I1103 13:43:38.963716    6479 round_trippers.go:327]     Cache-Control: no-store
I1103 13:43:38.963721    6479 round_trippers.go:327]     Content-Type: application/json
I1103 13:43:38.963725    6479 round_trippers.go:327]     Date: Thu, 03 Nov 2016 02:43:38 GMT
I1103 13:43:38.963729    6479 round_trippers.go:327]     Content-Length: 93
I1103 13:43:38.963800    6479 request.go:901] Response Body: {"kind":"APIVersions","apiVersion":"v1","versions":["v1"],"serverAddressByClientCIDRs":null}
I1103 13:43:38.964928    6479 round_trippers.go:299] curl -k -v -XGET  -H "Authorization: Bearer JHGI8mYpHyt9oaQI9aM-ZTNYO3wXFs1N4qg55KGHmuI" -H "Accept: application/json, */*" -H "User-Agent: oc/v1.3.1 (darwin/amd64) openshift/dad658d" https://127.0.0.1:8443/version
I1103 13:43:38.967082    6479 round_trippers.go:318] GET https://127.0.0.1:8443/version 200 OK in 2 milliseconds
I1103 13:43:38.967101    6479 round_trippers.go:324] Response Headers:
I1103 13:43:38.967107    6479 round_trippers.go:327]     Cache-Control: no-store
I1103 13:43:38.967112    6479 round_trippers.go:327]     Content-Type: application/json
I1103 13:43:38.967116    6479 round_trippers.go:327]     Date: Thu, 03 Nov 2016 02:43:38 GMT
I1103 13:43:38.967120    6479 round_trippers.go:327]     Content-Length: 235
I1103 13:43:38.967156    6479 request.go:901] Response Body: {
  "major": "1",
  "minor": "3",
  "gitVersion": "v1.3.0+52492b4",
  "gitCommit": "52492b4",
  "gitTreeState": "clean",
  "buildDate": "2016-10-15T23:44:12Z",
  "goVersion": "go1.6.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
I1103 13:43:38.968667    6479 cached_discovery.go:80] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/servergroups.json
I1103 13:43:38.968998    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/apps/v1alpha1/serverresources.json
I1103 13:43:38.969301    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/authentication.k8s.io/v1beta1/serverresources.json
I1103 13:43:38.969592    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/autoscaling/v1/serverresources.json
I1103 13:43:38.969871    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/batch/v1/serverresources.json
I1103 13:43:38.970143    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/batch/v2alpha1/serverresources.json
I1103 13:43:38.970474    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/extensions/v1beta1/serverresources.json
I1103 13:43:38.971192    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/v1/serverresources.json
I1103 13:43:38.971341    6479 round_trippers.go:299] curl -k -v -XGET  -H "Authorization: Bearer JHGI8mYpHyt9oaQI9aM-ZTNYO3wXFs1N4qg55KGHmuI" -H "Accept: application/json, */*" -H "User-Agent: oc/v1.3.1 (darwin/amd64) openshift/dad658d" https://127.0.0.1:8443/version
I1103 13:43:38.973334    6479 round_trippers.go:318] GET https://127.0.0.1:8443/version 200 OK in 1 milliseconds
I1103 13:43:38.973360    6479 round_trippers.go:324] Response Headers:
I1103 13:43:38.973365    6479 round_trippers.go:327]     Cache-Control: no-store
I1103 13:43:38.973370    6479 round_trippers.go:327]     Content-Type: application/json
I1103 13:43:38.973374    6479 round_trippers.go:327]     Date: Thu, 03 Nov 2016 02:43:38 GMT
I1103 13:43:38.973378    6479 round_trippers.go:327]     Content-Length: 235
I1103 13:43:38.973420    6479 request.go:901] Response Body: {
  "major": "1",
  "minor": "3",
  "gitVersion": "v1.3.0+52492b4",
  "gitCommit": "52492b4",
  "gitTreeState": "clean",
  "buildDate": "2016-10-15T23:44:12Z",
  "goVersion": "go1.6.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
I1103 13:43:38.973619    6479 cached_discovery.go:80] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/servergroups.json
I1103 13:43:38.973688    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/apps/v1alpha1/serverresources.json
I1103 13:43:38.973734    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/authentication.k8s.io/v1beta1/serverresources.json
I1103 13:43:38.973786    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/autoscaling/v1/serverresources.json
I1103 13:43:38.973835    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/batch/v1/serverresources.json
I1103 13:43:38.973891    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/batch/v2alpha1/serverresources.json
I1103 13:43:38.973981    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/extensions/v1beta1/serverresources.json
I1103 13:43:38.974246    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/v1/serverresources.json
I1103 13:43:38.975247    6479 round_trippers.go:299] curl -k -v -XGET  -H "Authorization: Bearer JHGI8mYpHyt9oaQI9aM-ZTNYO3wXFs1N4qg55KGHmuI" -H "User-Agent: oc/v1.3.1 (darwin/amd64) openshift/dad658d" -H "Accept: application/json, */*" https://127.0.0.1:8443/version
I1103 13:43:38.977004    6479 round_trippers.go:318] GET https://127.0.0.1:8443/version 200 OK in 1 milliseconds
I1103 13:43:38.977019    6479 round_trippers.go:324] Response Headers:
I1103 13:43:38.977024    6479 round_trippers.go:327]     Cache-Control: no-store
I1103 13:43:38.977029    6479 round_trippers.go:327]     Content-Type: application/json
I1103 13:43:38.977033    6479 round_trippers.go:327]     Date: Thu, 03 Nov 2016 02:43:38 GMT
I1103 13:43:38.977037    6479 round_trippers.go:327]     Content-Length: 235
I1103 13:43:38.977068    6479 request.go:901] Response Body: {
  "major": "1",
  "minor": "3",
  "gitVersion": "v1.3.0+52492b4",
  "gitCommit": "52492b4",
  "gitTreeState": "clean",
  "buildDate": "2016-10-15T23:44:12Z",
  "goVersion": "go1.6.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
I1103 13:43:38.977270    6479 cached_discovery.go:80] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/servergroups.json
I1103 13:43:38.977328    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/apps/v1alpha1/serverresources.json
I1103 13:43:38.977378    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/authentication.k8s.io/v1beta1/serverresources.json
I1103 13:43:38.977451    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/autoscaling/v1/serverresources.json
I1103 13:43:38.977530    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/batch/v1/serverresources.json
I1103 13:43:38.977675    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/batch/v2alpha1/serverresources.json
I1103 13:43:38.977792    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/extensions/v1beta1/serverresources.json
I1103 13:43:38.978169    6479 cached_discovery.go:38] returning cached discovery info from /Users/graham/.kube/127.0.0.1_8443/v1/serverresources.json
I1103 13:43:38.979088    6479 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v1.3.0+52492b4 (darwin/amd64) kubernetes/52492b4" -H "Authorization: Bearer JHGI8mYpHyt9oaQI9aM-ZTNYO3wXFs1N4qg55KGHmuI" https://127.0.0.1:8443/api
I1103 13:43:38.980934    6479 round_trippers.go:318] GET https://127.0.0.1:8443/api 200 OK in 1 milliseconds
I1103 13:43:38.980950    6479 round_trippers.go:324] Response Headers:
I1103 13:43:38.980955    6479 round_trippers.go:327]     Cache-Control: no-store
I1103 13:43:38.980960    6479 round_trippers.go:327]     Content-Type: application/json
I1103 13:43:38.980964    6479 round_trippers.go:327]     Date: Thu, 03 Nov 2016 02:43:38 GMT
I1103 13:43:38.980969    6479 round_trippers.go:327]     Content-Length: 135
I1103 13:43:38.981020    6479 request.go:901] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"192.168.65.2:8443"}]}
I1103 13:43:38.983615    6479 round_trippers.go:299] curl -k -v -XGET  -H "Authorization: Bearer JHGI8mYpHyt9oaQI9aM-ZTNYO3wXFs1N4qg55KGHmuI" -H "User-Agent: oc/v1.3.0+52492b4 (darwin/amd64) kubernetes/52492b4" -H "Accept: application/json, */*" https://127.0.0.1:8443/apis
I1103 13:43:38.985427    6479 round_trippers.go:318] GET https://127.0.0.1:8443/apis 200 OK in 1 milliseconds
I1103 13:43:38.985445    6479 round_trippers.go:324] Response Headers:
I1103 13:43:38.985450    6479 round_trippers.go:327]     Cache-Control: no-store
I1103 13:43:38.985455    6479 round_trippers.go:327]     Content-Type: application/json
I1103 13:43:38.985459    6479 round_trippers.go:327]     Date: Thu, 03 Nov 2016 02:43:38 GMT
I1103 13:43:38.985463    6479 round_trippers.go:327]     Content-Length: 1377
I1103 13:43:38.985500    6479 request.go:901] Response Body: {"kind":"APIGroupList","groups":[{"name":"apps","versions":[{"groupVersion":"apps/v1alpha1","version":"v1alpha1"}],"preferredVersion":{"groupVersion":"apps/v1alpha1","version":"v1alpha1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"192.168.65.2:8443"}]},{"name":"authentication.k8s.io","versions":[{"groupVersion":"authentication.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"authentication.k8s.io/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"192.168.65.2:8443"}]},{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"192.168.65.2:8443"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"192.168.65.2:8443"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"192.168.65.2:8443"}]}]}
I1103 13:43:38.992525    6479 resolve.go:167] Code []
I1103 13:43:38.992807    6479 resolve.go:168] Components [dunnies]
I1103 13:43:38.994005    6479 newapp.go:292] found group: dunnies
I1103 13:43:38.994029    6479 newapp.go:301] will add "" secrets into a build for a source build of ""
I1103 13:43:38.994053    6479 newapp.go:322] will use "dunnies" as the base image for a source build of ""
    * A source build using binary input will be created
      * The resulting image will be pushed to image stream "dunnies:latest"
      * Use 'start-build --from-dir=DIR|--from-repo=DIR|--from-file=FILE' to trigger a new build
      * WARNING: a binary build was created, you must specify one of --from-dir|--from-file|--from-repo when starting builds

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0xcba36b]

goroutine 1 [running]:
panic(0x2036520, 0xc8200140d0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/openshift/origin/pkg/generate/app.(*ImageRef).ObjectReference(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/app/imageref.go:173 +0x3b
github.com/openshift/origin/pkg/generate/app.(*BuildStrategyRef).BuildStrategy(0xc8201cde60, 0xc8205b7500, 0xc820788a50, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/app/app.go:217 +0x3f1
github.com/openshift/origin/pkg/generate/app.(*BuildRef).BuildConfig(0xc8205b7740, 0x1f61e00, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/app/app.go:249 +0x3fe
github.com/openshift/origin/pkg/generate/app.(*Pipeline).Objects(0xc820788a00, 0x415de40, 0xc820286238, 0x415de68, 0xc8208185c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/app/pipeline.go:199 +0x4b0
github.com/openshift/origin/pkg/generate/app/cmd.(*AppConfig).Run(0xc820018840, 0xc82007c008, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/app/cmd/newapp.go:659 +0xf3e
github.com/openshift/origin/pkg/cmd/cli/cmd.(*NewBuildOptions).Run(0xc8202fc460, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/newbuild.go:195 +0x95
github.com/openshift/origin/pkg/cmd/cli/cmd.NewCmdNewBuild.func1(0xc820587440, 0xc820017400, 0x0, 0x5)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/newbuild.go:109 +0x110
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc820587440, 0xc8200173b0, 0x5, 0x5, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x896
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc820572900, 0xc820587440, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x55c
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc820572900, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2d
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:29 +0x180
```

**Comment by bparees** [comment]
@GrahamDumpleton oc version?

**Comment by bparees** [comment]
sorry, I see it's up there.

**Comment by bparees** [comment]
This seems like it should be a validation error anyway since you're not specifying a builder image, so you can't do an s2i build.

**Comment by bparees** [comment]
@GrahamDumpleton what did you actually expect the resulting buildconfig to do?  (not that i'm saying a panic is the right response, of course).

**Comment by bparees** [comment]
(works correctly if you specify a builder image to use:  oc new-build --name dunnies --binary --strategy=source centos)

marking p2 because the panic is ugly, but the invocation is invalid anyway.

**Comment by bparees** [comment]
looks like maybe the intended behavior is for the --name argument to be used as the image since no other image was explicitly specified.  not sure i love that behavior.

**Comment by GrahamDumpleton** [comment]
You are correct that the image name was left off by mistake, but still shouldn't crash which is the point of the report.

Even so, the message displayed before the crash is also misleading anyway. That is, it still said:

```
$ oc new-build --binary  --name dunnies --strategy=source
    * A source build using binary input will be created
      * The resulting image will be pushed to image stream "dunnies:latest"
      * Use 'start-build --from-dir=DIR|--from-repo=DIR|--from-file=FILE' to trigger a new build
      * WARNING: a binary build was created, you must specify one of --from-dir|--from-file|--from-repo when starting builds
```

This implies it would have gone on to create something, but what?

If you leave off the ``--strategy=source`` option it will default to ``docker`` build strategy and set up build configuration appropriately for that.

So two things to do. Fix the crash and once that is fixed work out what it then tries to do, and if it doesn't provide an error if it is an invalid request, fix that as well.
