### ISSUE TITLE
Docker builder panics

### ISSUE THREAD

**Issue by hansmi** [openshift/origin#11966]
I'm attempting to use `openshift/origin-docker-builder` for a custom build (there'd be more around it, but for the sake of reproducibility I tried to reduce everything to a minimal example). Unfortunately the builder panics at `pkg/build/builder/docker.go:180` with `invalid memory address or nil pointer dereference`.

##### Version
```
$ oc version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://console.appuio.ch:443
kubernetes v1.2.0-36-g4a3f9c5
```

##### Steps To Reproduce
1. Set up Git repository. In my case with a single `Dockerfile`:

```
$ git describe --all --always --long; echo ---; git ls-tree -r HEAD; echo ---; cat Dockerfile
heads/panictest-0-g018a02f
---
100644 blob f61cfe9b95a0e22fd9df4032b80967adc5ca2ee9    Dockerfile
---
FROM docker.io/centos:7
RUN exit 99
```

2. Create custom build configuration:

```
apiVersion: v1
kind: BuildConfig
metadata:
  name: aedifex-docker-builder
spec:
  output:
    to:
      kind: ImageStreamTag
      name: aedifex-docker-builder:latest
  source:
    git:
      ref: panictest
      uri: git@[…]/aedifex.git
    sourceSecret:
      name: source-auth
    type: Git
  strategy:
    customStrategy:
      forcePull: true
      from:
        kind: DockerImage
        name: openshift/origin-docker-builder:v1.3.1
    type: Custom
  triggers:
  - type: ConfigChange
```

3. Start build: `oc start-build aedifex-docker-builder --wait --follow`

##### Current Result
```
$ oc start-build aedifex-docker-builder --wait --follow
build "aedifex-docker-builder-28" started
Cloning "git@[…]/aedifex.git" ...
        Commit: 018a02f69555f42273fbd7caded28332dd823752 (Panic test)
        Author: […]
        Date:   Fri Nov 18 13:07:28 2016 +0100
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1b02687]

goroutine 1 [running]:
panic(0x41fe940, 0xc82000a080)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/openshift/origin/pkg/build/builder.(*DockerBuilder).addBuildParameters(0xc8209659d0, 0xc82007e400, 0x1a, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/docker.go:180 +0x397
github.com/openshift/origin/pkg/build/builder.(*DockerBuilder).Build(0xc8209659d0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/docker.go:76 +0x2b9
github.com/openshift/origin/pkg/build/builder/cmd.dockerBuilder.Build(0x7f4ac44e1e20, 0xc8202c0e10, 0x4f68560, 0x1b, 0x7f4ac44e1b48, 0xc8202b1980, 0xc82006e280, 0x7f4ac44e1ea0, 0xc82007e0a0, 0xc820937380, ...)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:195 +0x1aa
github.com/openshift/origin/pkg/build/builder/cmd.(*dockerBuilder).Build(0x85843c8, 0x7f4ac44e1e20, 0xc8202c0e10, 0x4f68560, 0x1b, 0x7f4ac44e1b48, 0xc8202b1980, 0xc82006e280, 0x7f4ac44e1ea0, 0xc82007e0a0, ...)
        <autogenerated>:2 +0x11f
github.com/openshift/origin/pkg/build/builder/cmd.(*builderConfig).execute(0xc82035c230, 0x7f4ac44e16e8, 0x85843c8, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:155 +0x3ea
github.com/openshift/origin/pkg/build/builder/cmd.runBuild(0x7f4ac4445118, 0xc82007c010, 0x7f4ac44e16e8, 0x85843c8, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:210 +0x86
github.com/openshift/origin/pkg/build/builder/cmd.RunDockerBuild(0x7f4ac4445118, 0xc82007c010, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:215 +0x90
github.com/openshift/origin/pkg/cmd/infra/builder.NewCommandDockerBuilder.func1(0xc8200c9d40, 0x85843c8, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/infra/builder/builder.go:51 +0x43
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc8200c9d40, 0xc82006c140, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x896
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8200c9d40, 0xc8200c9d40, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x55c
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8200c9d40, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2d
main.main()
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:33 +0x199
error: The build hansmi-builder-test/aedifex-docker-builder-28 status is "Failed"
```

##### Expected Result
While there may be an issue with how I'm trying to use the builder, the process should not panic.

##### Additional Information
Setting the `BUILD_LOGLEVEL` env variable on the custom build has no visible effect in terms of output from the builder.

**Comment by hansmi** [comment]
> While there may be an issue with how I'm trying to use the builder, […]

Reading through the code indicates that the builder written in Go can only handle Docker builds (`dockerStrategy`), not custom builds (`customStrategy`). A error message would be much nicer than a backtrace.

**Comment by bparees** [comment]
custom build says "bring us an image that can run by itself and perform your build logic" and the docker-builder image is not such a thing, nor does it claim to be.  I'm not sure what lead you to attempt this and perhaps there is room to improve the documentation that lead you down this path, but you could run into this problem (attempting to run an image w/o providing all its prereqs such that it panics or otherwise terminates in an unfriendly way) with any image you decided to use w/ the custom build strategy.  I don't see value in updating the docker-builder image to attempt to detect this scenario and report a more useful error.  The same claim could be made for any image you might attempt to use.
