### ISSUE TITLE
Vagrant openshift plugin error

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#12116]
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/8848/console:

```
+ vagrant sync-origin -s
/var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.8/lib/vagrant-openshift/action/prepare_ssh_config.rb:39:in `initialize': Text file busy - /var/lib/jenkins/.ssh/vagrant_openshift_ssh_override (Errno::ETXTBSY)
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.8/lib/vagrant-openshift/action/prepare_ssh_config.rb:39:in `open'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.8/lib/vagrant-openshift/action/prepare_ssh_config.rb:39:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.8/lib/vagrant-openshift/command/repo_sync_origin.rb:63:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.8/lib/vagrant-openshift/command/repo_sync_origin.rb:61:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

**Comment by stevekuznetsov** [comment]
@soltysh can you open this against `vagrant-openshift`, please? I think this may be a symptom of the SSH override race /cc @danmcp and therefore not something we're going to spend time on fixing, as it's pretty rare.

**Comment by soltysh** [comment]
Moved to https://github.com/openshift/vagrant-openshift/issues/523.
