### ISSUE TITLE
oc cluster up does not work with docker-1.12.4-3.el7

### ISSUE THREAD

**Issue by phracek** [openshift/origin#12372]
I have installed docker engine (docker-1.12.4-3.el7) and during ```oc cluster up``` I see this traceback
~~~


    -- Checking for available ports ... FAIL
       Error: Cannot get TCP port information from Kubernetes host
       Caused By:
         Error: Docker run error rc=2
         Details:
           Image: openshift/origin:v1.3.1
           Entrypoint: [/bin/bash]
           Command: [-c cat /proc/net/tcp /proc/net/tcp6]
           Error Output:
             panic: standard_init_linux.go:175: exec user process caused "permission denied" [recovered]
                    panic: standard_init_linux.go:175: exec user process caused "permission denied"
     
             goroutine 1 [running, locked to thread]:
             panic(0x6f2ea0, 0xc42013f3b0)
                    /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
             github.com/urfave/cli.HandleAction.func1(0xc420075748)
                    /builddir/build/BUILD/docker-1b5971af3003488d3fd8add80de5125ee1e096ee/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x247
             panic(0x6f2ea0, 0xc42013f3b0)
                    /usr/lib/golang/src/runtime/panic.go:458 +0x243
             github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc420075198, 0xc42001e0c8, 0xc420075238)
                    /builddir/build/BUILD/docker-1b5971af3003488d3fd8add80de5125ee1e096ee/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x18f
             github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc420047630, 0xaac9c0, 0xc42013f3b0)
                    /builddir/build/BUILD/docker-1b5971af3003488d3fd8add80de5125ee1e096ee/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x353
             main.glob..func8(0xc420078a00, 0x0, 0x0)
                    /builddir/build/BUILD/docker-1b5971af3003488d3fd8add80de5125ee1e096ee/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/main_unix.go:26 +0x66
             reflect.Value.call(0x6ddc20, 0x769b48, 0x13, 0x73c049, 0x4, 0xc420075708, 0x1, 0x1, 0x4d1728, 0x731ea0, ...)
                    /usr/lib/golang/src/reflect/value.go:434 +0x5c8
             reflect.Value.Call(0x6ddc20, 0x769b48, 0x13, 0xc420075708, 0x1, 0x1, 0xac2700, 0xc4200756e8, 0x4da706)
                    /usr/lib/golang/src/reflect/value.go:302 +0xa4
             github.com/urfave/cli.HandleAction(0x6ddc20, 0x769b48, 0xc420078a00, 0x0, 0x0)
                    /builddir/build/BUILD/docker-1b5971af3003488d3fd8add80de5125ee1e096ee/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x1e0
             github.com/urfave/cli.Command.Run(0x73c215, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x74d852, 0x51, 0x0, ...)
                    /builddir/build/BUILD/docker-1b5971af3003488d3fd8add80de5125ee1e096ee/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xc3b
             github.com/urfave/cli.(*App).Run(0xc420096000, 0xc42000c120, 0x2, 0x2, 0x0, 0x0)
                    /builddir/build/BUILD/docker-1b5971af3003488d3fd8add80de5125ee1e096ee/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x611
             main.main()
                    /builddir/build/BUILD/docker-1b5971af3003488d3fd8add80de5125ee1e096ee/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/main.go:137 +0xbd6

~~~

If I switch selinux to ```disable```, it works well.

##### Version
[phracek@localhost ~]$ sudo oc version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.122.248:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4
[phracek@localhost ~]$ 

##### Steps To Reproduce
1. Install docker for RHEL-7
2. Download oc preinstalled binaries from OpenShift
3. Run sudo oc cluster up

##### Current Result
oc cluster up does not work at all
##### Expected Result
oc cluster up show work
##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by csrwng** [comment]
@phracek can you please include the output of running `oc cluster up --loglevel=5` ? I tried locally with RHEL 7.3, docker-latest package `docker-latest-1.12.3-10.el7.x86_64` and cannot reproduce.

Also, how did you install your docker version? The latest package I found in the RHEL repo is the one I mentioned above.

**Comment by phracek** [comment]
@csrwng Strange, I am not able to reproduce it. I will start with clean machine.
~~~
-- Checking for available ports ... 
   WARNING: Binding DNS on port 8053 instead of 53, which may be not be resolvable from all clients.
-- Checking type of volume mount ... 
~~~
