### ISSUE TITLE
pod jenkins failed to run a job 

### ISSUE THREAD

**Issue by astondevops** [openshift/origin#12419]
[provide a description of the issue]

##### Version  
oc v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.1.44:8443
openshift v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994

##### Steps To Reproduce
version: '2'
services:
 jenkins:
    image: jenkins
    ports:
      - "18080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /opt/jenkins/lib:/var/lib/jenkins/
      - /opt/jen:/var/jenkins_home

oc import docker-compose -f docker-compose .
Create a job in jenkins to build a github repository but failed with user /passwd error 
##### Current Result

 git fetch --tags --progress https://github.com/astondevops/spring-petclinic.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/astondevops/spring-petclinic.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:803)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1063)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1094)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/astondevops/spring-petclinic.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to look up current user in the passwd file: no such user

##### Expected Result
a build
##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by csrwng** [comment]
@astondevops please make sure that in your Jenkins job you set the following variables:
```GIT_COMMITTER_NAME```
```GIT_COMMITTER_EMAIL```

**Comment by sengaya** [comment]
I ran into the same problem. It seems that for some reason git expects a user with an username. The [OpenShift Jenkins Docker Image](https://github.com/openshift/jenkins) solves this by [adding an entry to /etc/passwd](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/jenkins-common.sh#L12-L22). The passwd file need to be [accessible by the root group](https://github.com/openshift/jenkins/blob/master/2/Dockerfile#L53).

**Comment by bparees** [comment]
thanks @sengaya 

closing as i think this is the issue, @astondevops please comment back if you are still having trouble.
