### ISSUE TITLE
e2e panic in origin-docker-registry pod:  "panic: StorageDriver not registered: gcs"

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#12412]
```
FAILURE after 0.785s: test/end-to-end/core.sh:176: executing 'docker run -e REGISTRY_STORAGE="gcs: {}" openshift/origin-docker-registry:f401455' expecting failure and text 'No bucket parameter provided': the output content test failed
There was no output from the command.
Standard error from the command:
time="2017-01-06T21:56:59.729007223Z" level=info msg="version=v2.5.1+unknown" 
panic: StorageDriver not registered: gcs

goroutine 1 [running]:
panic(0x1c5b640, 0xc4204ae470)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers.NewApp(0x7fde487ee3c8, 0x2cb8740, 0xc420521340, 0x7fde487ee3c8)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers/app.go:121 +0x2f6b
github.com/openshift/origin/pkg/cmd/dockerregistry.Execute(0x2c51c80, 0xc4203443d8)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/dockerregistry/dockerregistry.go:61 +0x292
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/dockerregistry/main.go:58 +0x1e9
[ERROR] PID 29903: hack/lib/cmd.sh:229: `return "${return_code}"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/cmd.sh:229: `return "${return_code}"`
[INFO] 		  2: test/end-to-end/core.sh:176: os::cmd::expect_failure_and_text
[INFO]   Exiting with code 1.
[ERROR] PID 28770: hack/test-end-to-end-docker.sh:91: `${OS_ROOT}/test/end-to-end/core.sh` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/test-end-to-end-docker.sh:91: `${OS_ROOT}/test/end-to-end/core.sh`
[INFO]   Exiting with code 1.
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/9834/consoleFull#-4796457835762928fe4b031e1b25ced2a

**Comment by pweil-** [comment]
@legionus can you check this and make sure it isn't a 3.4 regression? 

cc @mfojtik

**Comment by legionus** [comment]
Error message:
```
panic: StorageDriver not registered: gcs
```
means that someone built the server without these flags: https://github.com/openshift/origin/blob/master/hack/common.sh#L37 . If code has changed (there was no gcs support), the test would not flake, but it would be constantly broken.

**Comment by smarterclayton** [comment]
This has been fixed, right?  Builds didn't have right tags?

**Comment by mfojtik** [comment]
@sdodson did we rebuilt the server with this tag? I think we had similar problem with 1.3 release but I thought we solved it permanently by adding the required build tag.

**Comment by sdodson** [comment]
I'm not familiar enough with the origin CI tests to track down if something has changed there.

**Comment by smarterclayton** [comment]
This has been fixed.

**Comment by deads2k** [comment]
@stevekuznetsov I'm seeing this locally running the e2e test.  Did we lose something splitting out image-registry?

**Comment by stevekuznetsov** [comment]
@deads2k can you `set -o xtrace` at the top of `hack/build-go.sh` and figure out what flags are being passed to `go install`?

**Comment by smarterclayton** [comment]
It means we aren't passing the right tags into the docker image build

**Comment by smarterclayton** [comment]
I mean, the go build for the image.

**Comment by smarterclayton** [comment]
Constants.sh needs:

readonly OS_GOFLAGS_TAGS="include_gcs include_oss"
