### ISSUE TITLE
Panic in docker registry end-to-end

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#12998]
Seen this in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration_future/258/consoleFull:

```
08:30:06 [INFO] Docker registry start with GCS
08:30:06 Running test/end-to-end/core.sh:183: executing 'docker run -e REGISTRY_STORAGE="gcs: {}" openshift/origin-docker-registry:fea7095' expecting failure and text 'No bucket parameter provided'...
08:30:07 SUCCESS after 1.431s: test/end-to-end/core.sh:183: executing 'docker run -e REGISTRY_STORAGE="gcs: {}" openshift/origin-docker-registry:fea7095' expecting failure and text 'No bucket parameter provided'
08:30:07 There was no output from the command.
08:30:07 Standard error from the command:
08:30:07 time="2017-02-16T13:30:07.238056427Z" level=info msg="version=v2.5.1+unknown" 
08:30:07 panic: No bucket parameter provided
08:30:07 
08:30:07 goroutine 1 [running]:
08:30:07 panic(0x1716be0, 0xc42024ada0)
08:30:07 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
08:30:07 github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers.NewApp(0x7f466288d6c0, 0xc42040c330, 0xc4200b4840, 0x7f466288d6c0)
08:30:07 	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers/app.go:121 +0x2f6b
08:30:07 github.com/openshift/origin/pkg/cmd/dockerregistry.Execute(0x2521cc0, 0xc42011c068)
08:30:07 	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/dockerregistry/dockerregistry.go:63 +0x370
08:30:07 main.main()
08:30:07 	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/dockerregistry/main.go:58 +0x1e9
08:30:07 
08:30:07 [INFO] Docker registry start with OSS
08:30:07 Running test/end-to-end/core.sh:186: executing 'docker run -e REGISTRY_STORAGE="oss: {}" openshift/origin-docker-registry:fea7095' expecting failure and text 'No accesskeyid parameter provided'...
08:30:08 SUCCESS after 1.327s: test/end-to-end/core.sh:186: executing 'docker run -e REGISTRY_STORAGE="oss: {}" openshift/origin-docker-registry:fea7095' expecting failure and text 'No accesskeyid parameter provided'
08:30:08 There was no output from the command.
08:30:08 Standard error from the command:
08:30:08 time="2017-02-16T13:30:08.599428225Z" level=info msg="version=v2.5.1+unknown" 
08:30:08 panic: No accesskeyid parameter provided
08:30:08 
08:30:08 goroutine 1 [running]:
08:30:08 panic(0x1716be0, 0xc4200c6590)
08:30:08 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
08:30:08 github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers.NewApp(0x7fecf0252950, 0xc4204612c0, 0xc42014e840, 0x7fecf0252950)
08:30:08 	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers/app.go:121 +0x2f6b
08:30:08 github.com/openshift/origin/pkg/cmd/dockerregistry.Execute(0x2521cc0, 0xc42011c058)
08:30:08 	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/dockerregistry/dockerregistry.go:63 +0x370
08:30:08 main.main()
08:30:08 	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/dockerregistry/main.go:58 +0x1e9
08:30:08 
08:30:08 [INFO] Docker pull from istag
08:30:08 Running test/end-to-end/core.sh:189: executing 'oc import-image --confirm --from=hello-world:latest -n test hello-world:pullthrough' expecting success...
08:30:09 SUCCESS after 0.431s: test/end-to-end/core.sh:189: executing 'oc import-image --confirm --from=hello-world:latest -n test hello-world:pullthrough' expecting success
08:30:09 Standard output from the command:
08:30:09 The import completed successfully.
```

@legionus @miminar shouldn't there be some nice error and not panic there, this looks like missing key when accessing s3.

**Comment by legionus** [comment]
No. There is no other way how to learn the loaded backends. The check was always like this. And Yes, it crashes due to the fact that not all the necessary parameters passed.

**Comment by legionus** [comment]
This is not a flake.

**Comment by soltysh** [comment]
After talking to Alexey on IRC: this is expected behavior, thus I'm closing.
