### ISSUE TITLE
test flake: TestBlobDescriptorServiceIsApplied times out sometimes

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13360]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin/161/testReport/junit/github/com_openshift_origin_pkg_dockerregistry_server/TestBlobDescriptorServiceIsApplied/

```
=== RUN   TestBlobDescriptorServiceIsApplied
time="2017-03-11T22:44:23Z" level=info msg="OpenShift middleware for storage driver initializing" 
time="2017-03-11T22:44:23Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.4 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=info msg="redis not configured" go.version=go1.7.4 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=info msg="Starting upload purge in 13m0s" go.version=go1.7.4 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.4 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=info msg="OpenShift registry middleware initializing" 
time="2017-03-11T22:44:23Z" level=info msg="quota enforcement disabled" go.version=go1.7.4 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=info msg="response completed" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=7b1c3a6e-b017-4bff-914b-b467228ad4cc http.request.method=POST http.request.remoteaddr="127.0.0.1:48558" http.request.uri="/v2/user/app/blobs/uploads/" http.request.useragent="Go-http-client/1.1" http.response.duration=32.840648ms http.response.status=202 http.response.written=0 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=info msg="response completed" go.version=go1.7.4 http.request.contenttype="application/octet-stream" http.request.host="127.0.0.1:37617" http.request.id=b23503a9-dd0b-43ab-8282-8a14737ebd0d http.request.method=PATCH http.request.remoteaddr="127.0.0.1:48558" http.request.uri="/v2/user/app/blobs/uploads/e6220f43-6648-438c-99c7-8f4b1343815a?_state=6YH6mTu_25H5XLbUcEMcLVMokrh4IGQ9l4eqztXG8PF7Ik5hbWUiOiJ1c2VyL2FwcCIsIlVVSUQiOiJlNjIyMGY0My02NjQ4LTQzOGMtOTljNy04ZjRiMTM0MzgxNWEiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMDMtMTFUMjI6NDQ6MjMuNjUyMDEyNjM2WiJ9" http.request.useragent="Go-http-client/1.1" http.response.duration=26.053469ms http.response.status=202 http.response.written=0 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=info msg="response completed" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=b6cd29dd-b664-4cce-8717-a474eefc0ad8 http.request.method=PUT http.request.remoteaddr="127.0.0.1:48558" http.request.uri="/v2/user/app/blobs/uploads/e6220f43-6648-438c-99c7-8f4b1343815a?_state=WZFAH2GbSfCIOarotwjTxbmPsVB_gUVNjIPs_o9804h7Ik5hbWUiOiJ1c2VyL2FwcCIsIlVVSUQiOiJlNjIyMGY0My02NjQ4LTQzOGMtOTljNy04ZjRiMTM0MzgxNWEiLCJPZmZzZXQiOjQwOTYsIlN0YXJ0ZWRBdCI6IjIwMTctMDMtMTFUMjI6NDQ6MjNaIn0%3D&digest=sha256%3Afbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" http.response.duration=27.714248ms http.response.status=201 http.response.written=0 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=info msg="response completed" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=134bfd0d-82fd-46cb-86b4-1c8a3f34f8d0 http.request.method=HEAD http.request.remoteaddr="127.0.0.1:48558" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/octet-stream" http.response.duration=9.457754ms http.response.status=200 http.response.written=0 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=error msg="failed to retrieve repository from context" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=4379f893-9c69-41fa-85a8-6470f8874ccf http.request.method=GET http.request.remoteaddr="127.0.0.1:48558" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.digest="sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" vars.name="user/app" 
time="2017-03-11T22:44:23Z" level=error msg="Failed to find blob \"sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb\": &errors.errorString{s:\"failed to retrieve repository from context\"}" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=4379f893-9c69-41fa-85a8-6470f8874ccf http.request.method=GET http.request.remoteaddr="127.0.0.1:48558" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.digest="sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" vars.name="user/app" 
time="2017-03-11T22:44:23Z" level=error msg="response completed with error" err.code=unknown err.detail="failed to retrieve repository from context" err.message="unknown error" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=4379f893-9c69-41fa-85a8-6470f8874ccf http.request.method=GET http.request.remoteaddr="127.0.0.1:48558" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=9.130319ms http.response.status=500 http.response.written=70 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.digest="sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" vars.name="user/app" 
time="2017-03-11T22:44:23Z" level=info msg="response completed" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=87fe9e13-7f98-4159-9f1c-b482a16bd05e http.request.method=GET http.request.remoteaddr="127.0.0.1:48558" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/octet-stream" http.response.duration=16.591237ms http.response.status=200 http.response.written=4096 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=error msg="failed to retrieve repository from context" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=451d987c-9d61-4117-9d24-7a8fc4528fb0 http.request.method=HEAD http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.digest="sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" vars.name="user/app" 
time="2017-03-11T22:44:23Z" level=error msg="Failed to find blob \"sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb\": &errors.errorString{s:\"failed to retrieve repository from context\"}" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=451d987c-9d61-4117-9d24-7a8fc4528fb0 http.request.method=HEAD http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.digest="sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" vars.name="user/app" 
time="2017-03-11T22:44:23Z" level=error msg="response completed with error" err.code=unknown err.detail="failed to retrieve repository from context" err.message="unknown error" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=451d987c-9d61-4117-9d24-7a8fc4528fb0 http.request.method=HEAD http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=43.405767ms http.response.status=500 http.response.written=70 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.digest="sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" vars.name="user/app" 
time="2017-03-11T22:44:23Z" level=info msg="response completed" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=c0c750aa-d2cf-4194-bd1c-0559029a47b6 http.request.method=HEAD http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/octet-stream" http.response.duration=9.443734ms http.response.status=200 http.response.written=0 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=error msg="failed to retrieve repository from context" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=6a963721-35a0-437c-a0f9-186447d4bac7 http.request.method=DELETE http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.digest="sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" vars.name="user/app" 
time="2017-03-11T22:44:23Z" level=error msg="Unknown error deleting blob: failed to retrieve repository from context" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=6a963721-35a0-437c-a0f9-186447d4bac7 http.request.method=DELETE http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.digest="sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" vars.name="user/app" 
time="2017-03-11T22:44:23Z" level=error msg="response completed with error" err.code=unknown err.message="failed to retrieve repository from context" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=6a963721-35a0-437c-a0f9-186447d4bac7 http.request.method=DELETE http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=8.899604ms http.response.status=500 http.response.written=70 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.digest="sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" vars.name="user/app" 
time="2017-03-11T22:44:23Z" level=info msg="response completed" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=dac6d976-d05b-45ee-b3e9-522b6680a8ae http.request.method=DELETE http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/blobs/sha256:fbe89fea53b61f9150115927b42364988f8f1ce221f6997f083e7a096bc9cfdb" http.request.useragent="Go-http-client/1.1" http.response.duration=26.622574ms http.response.status=202 http.response.written=0 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=info msg="(*repository).getImage: got image sha256:bff08d8da5a030fc39fdfcddd533fac4bc76d877d1a33bc336f8115e18d9081b" go.version=go1.7.4 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=error msg="failed to retrieve repository from context" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=44e5b0fa-7313-4fb3-ad76-f32bc3b8149e http.request.method=GET http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/manifests/latest" http.request.useragent="Go-http-client/1.1" instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.name="user/app" vars.reference=latest 
time="2017-03-11T22:44:23Z" level=error msg="unable to get manifest from storage: failed to retrieve repository from context" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=44e5b0fa-7313-4fb3-ad76-f32bc3b8149e http.request.method=GET http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/manifests/latest" http.request.useragent="Go-http-client/1.1" instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.name="user/app" vars.reference=latest 
time="2017-03-11T22:44:23Z" level=error msg="response completed with error" err.code="manifest unknown" err.detail="failed to retrieve repository from context" err.message="manifest unknown" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=44e5b0fa-7313-4fb3-ad76-f32bc3b8149e http.request.method=GET http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/manifests/latest" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=17.848826ms http.response.status=404 http.response.written=82 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.name="user/app" vars.reference=latest 
time="2017-03-11T22:44:23Z" level=info msg="(*repository).getImage: got image sha256:bff08d8da5a030fc39fdfcddd533fac4bc76d877d1a33bc336f8115e18d9081b" go.version=go1.7.4 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=info msg="response completed" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=6bc90322-f9a8-49a3-a39a-94a0305dc3bd http.request.method=GET http.request.remoteaddr="127.0.0.1:48560" http.request.uri="/v2/user/app/manifests/latest" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/vnd.docker.distribution.manifest.v1+prettyjws" http.response.duration=19.114656ms http.response.status=200 http.response.written=1130 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae 
time="2017-03-11T22:44:23Z" level=error msg="failed to retrieve repository from context" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=07a68939-8af6-4309-9165-90ca21cceb10 http.request.method=DELETE http.request.remoteaddr="127.0.0.1:48562" http.request.uri="/v2/user/app/manifests/sha256:bff08d8da5a030fc39fdfcddd533fac4bc76d877d1a33bc336f8115e18d9081b" http.request.useragent="Go-http-client/1.1" instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.name="user/app" vars.reference="sha256:bff08d8da5a030fc39fdfcddd533fac4bc76d877d1a33bc336f8115e18d9081b" 
time="2017-03-11T22:44:23Z" level=error msg="response completed with error" err.code=unknown err.message="unknown error" go.version=go1.7.4 http.request.host="127.0.0.1:37617" http.request.id=07a68939-8af6-4309-9165-90ca21cceb10 http.request.method=DELETE http.request.remoteaddr="127.0.0.1:48562" http.request.uri="/v2/user/app/manifests/sha256:bff08d8da5a030fc39fdfcddd533fac4bc76d877d1a33bc336f8115e18d9081b" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=9.953675ms http.response.status=500 http.response.written=58 instance.id=685ca61f-ac86-4356-8ec5-0a89511d27ae vars.name="user/app" vars.reference="sha256:bff08d8da5a030fc39fdfcddd533fac4bc76d877d1a33bc336f8115e18d9081b" 
panic: test timed out after 2m0s

goroutine 179 [running]:
panic(0x1f8ec00, 0xc420400a60)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:918 +0x14e
created by time.goFunc
	/usr/local/go/src/time/sleep.go:154 +0x78

goroutine 1 [chan receive, 1 minutes]:
testing.(*T).Run(0xc4203fd980, 0x228475a, 0x22, 0x249d188, 0x57b001)
	/usr/local/go/src/testing/testing.go:647 +0x56e
testing.RunTests.func1(0xc4203fd980)
	/usr/local/go/src/testing/testing.go:793 +0xba
testing.tRunner(0xc4203fd980, 0xc420601d20)
	/usr/local/go/src/testing/testing.go:610 +0xca
testing.RunTests(0x24a5040, 0x305f660, 0x1c, 0x1c, 0xc4201f7d98)
	/usr/local/go/src/testing/testing.go:799 +0x4bb
testing.(*M).Run(0xc420601ef0, 0x30)
	/usr/local/go/src/testing/testing.go:743 +0x130
main.main()
	github.com/openshift/origin/pkg/dockerregistry/server/_test/_testmain.go:206 +0x2f9

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 19 [chan receive]:
github.com/openshift/origin/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x306f160)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:879 +0x9e
created by github.com/openshift/origin/vendor/github.com/golang/glog.init.1
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:410 +0x23b

goroutine 6 [syscall, 2 minutes]:
os/signal.signal_recv(0x466f31)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x30
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x4f

goroutine 27 [select]:
net/http.(*persistConn).roundTrip(0xc4201e2100, 0xc4209c2700, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1840 +0xc85
net/http.(*Transport).RoundTrip(0xc4200e4000, 0xc4203d04b0, 0xc4200e4000, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:380 +0x73e
net/http.send(0xc4203d04b0, 0x2fe5460, 0xc4200e4000, 0x0, 0x0, 0x0, 0x606bfd, 0xc42077d2a8, 0x0)
	/usr/local/go/src/net/http/client.go:256 +0x2ff
net/http.(*Client).send(0xc42077d280, 0xc4203d04b0, 0x0, 0x0, 0x0, 0xc4201677a8, 0x74, 0x74)
	/usr/local/go/src/net/http/client.go:146 +0x1c8
net/http.(*Client).Do(0xc42077d280, 0xc4203d04b0, 0xc420167600, 0x74, 0x0)
	/usr/local/go/src/net/http/client.go:189 +0xd4
github.com/openshift/origin/pkg/dockerregistry/server.TestBlobDescriptorServiceIsApplied.func2(0x22663ed, 0xf, 0x225831a, 0x6, 0x225c0df, 0x8, 0xc420711440, 0x4, 0x4, 0x0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/dockerregistry/server/blobdescriptorservice_test.go:136 +0x2f3
github.com/openshift/origin/pkg/dockerregistry/server.TestBlobDescriptorServiceIsApplied(0xc42069e180)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/dockerregistry/server/blobdescriptorservice_test.go:324 +0x2634
testing.tRunner(0xc42069e180, 0x249d188)
	/usr/local/go/src/testing/testing.go:610 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x530
```

**Comment by smarterclayton** [comment]
@legionus

**Comment by smarterclayton** [comment]
Dupe of #13288
