### ISSUE TITLE
oauth server printing informational stack for 302?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13438]
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/438/consoleText

```
I0318 18:57:16.567309   21686 panics.go:76] GET /oauth/authorize?response_type=token&client_id=openshift-challenging-client: (5.254694ms) 302
goroutine 15286 [running]:
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc422507180, 0x12e)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xbb
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc422507180, 0x12e)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x35
github.com/openshift/origin/vendor/github.com/RangelReale/osin.OutputJSON(0xc42c1f5170, 0x91e1e60, 0xc422507180, 0xc42ca5d2c0, 0xc422507180, 0x6def00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/RangelReale/osin/response_json.go:24 +0x23e
github.com/openshift/origin/pkg/oauth/server/osinserver.(*Server).handleAuthorize(0xc421005740, 0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oauth/server/osinserver/osinserver.go:101 +0x106
github.com/openshift/origin/pkg/oauth/server/osinserver.(*Server).(github.com/openshift/origin/pkg/oauth/server/osinserver.handleAuthorize)-fm(0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oauth/server/osinserver/osinserver.go:47 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42187fae0, 0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/vendor/github.com/gorilla/context.ClearHandler.func1(0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/gorilla/context/context.go:141 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc42172b760, 0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4204db230, 0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.(*ServeMux).ServeHTTP(0xc421b658c0, 0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
github.com/openshift/origin/pkg/cmd/server/origin.WithPatternsHandler.func1(0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master.go:1096 +0xcd
net/http.HandlerFunc.ServeHTTP(0xc421b70980, 0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/pkg/cmd/server/origin.WithAssetServerRedirect.func1(0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:212 +0x7f
net/http.HandlerFunc.ServeHTTP(0xc421ba43f0, 0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/genericapiserver/filters.WithCORS.func1(0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/genericapiserver/filters/cors.go:77 +0x1a2
net/http.HandlerFunc.ServeHTTP(0xc421ba6060, 0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/genericapiserver/filters.WithPanicRecovery.func1(0x91e1e60, 0xc422507180, 0xc42ca5d2c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:75 +0x24a
net/http.HandlerFunc.ServeHTTP(0xc421ba4540, 0x7f70dc045ce8, 0xc425519760, 0xc42ca5d2c0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP.func1(0xc420fa9140, 0x91ea0a0, 0xc425519760, 0xc42ca5d2c0, 0xc432169d40)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:78 +0x8d
created by github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:80 +0x1db
```

**Comment by mfojtik** [comment]
@deads2k I think we discussed this panic and you said it is not an error :-)

**Comment by deads2k** [comment]
I think it was part of some http log call.

**Comment by enj** [comment]
Did we need that to get better debug info out of osin?

**Comment by deads2k** [comment]
> Did we need that to get better debug info out of osin?

Probably not.  I'd expect the default predicate to limit itself to server errors for the stacks.

**Comment by deads2k** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/43377 to tighten the stack behavior since I was already there.

**Comment by smarterclayton** [comment]
Fixed upstream.

**Comment by deads2k** [comment]
didn't have it in 3.6.  Opened #14173
