### ISSUE TITLE
workqueue.TestSimpleQueue test timed out after 2m0s

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13614]
Seen: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_check/786/consoleFull#-73190926656bf4006e4b05b79524e5923

Snip:

```
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/workqueue/_test/_testmain.go:142 +0x2f9
goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
goroutine 19 [chan receive]:
github.com/openshift/origin/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1844340)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:879 +0x9e
created by github.com/openshift/origin/vendor/github.com/golang/glog.init.1
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:410 +0x23b
goroutine 7 [semacquire]:
sync.runtime_notifyListWait(0xc42036a190, 0x0)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc42036a180)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/workqueue.(*Type).Get(0xc420016370, 0x0, 0x0, 0x0)
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/workqueue/_test/_obj_test/queue.go:125 +0x178
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/workqueue.(*delayingType).Get(0xc420058070, 0x121706d, 0x11, 0x0)
	<autogenerated>:44 +0x69
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/workqueue.TestSimpleQueue(0xc420096780)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/workqueue/delaying_queue_test.go:49 +0x2e1
testing.tRunner(0xc420096780, 0x1309880)
	/usr/local/go/src/testing/testing.go:610 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x530
goroutine 8 [select]:
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/workqueue.(*delayingType).waitingLoop(0xc420058070)
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/workqueue/_test/_obj_test/delaying_queue.go:164 +0xc7c
created by github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/workqueue.newDelayingQueue
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/workqueue/_test/_obj_test/delaying_queue.go:44 +0x33d
```

**Comment by derekwaynecarr** [comment]
@jboyd01 -- can you try to see if you can reproduce this flake in the current upstream (run the tests 1000s of times).
