### ISSUE TITLE
k8s Unit Test Flake: TestServiceRegistryExternalTrafficBetaAnnotationHealthCheckNodePortUserAllocation

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#13693]
```
=== RUN   TestServiceRegistryExternalTrafficBetaAnnotationHealthCheckNodePortUserAllocation
--- FAIL: TestServiceRegistryExternalTrafficBetaAnnotationHealthCheckNodePortUserAllocation (0.00s)
	rest_test.go:1012: Unexpected failure creating service Internal error occurred: Failed to allocate requested HealthCheck nodePort 30200: provided port is already allocated
panic: interface conversion: interface is nil, not *api.Service [recovered]
	panic: interface conversion: interface is nil, not *api.Service

goroutine 86 [running]:
panic(0x16cc7a0, 0xc4201c30c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
testing.tRunner.func1(0xc42041d440)
	/usr/local/go/src/testing/testing.go:579 +0x474
panic(0x16cc7a0, 0xc4201c30c0)
	/usr/local/go/src/runtime/panic.go:458 +0x271
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/core/service.TestServiceRegistryExternalTrafficBetaAnnotationHealthCheckNodePortUserAllocation(0xc42041d440)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/core/service/rest_test.go:1014 +0x58c
testing.tRunner(0xc42041d440, 0x198a298)
	/usr/local/go/src/testing/testing.go:610 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x530
```

seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_check/963/testReport/junit/github.com_openshift_origin_vendor_k8s/io_kubernetes_pkg_registry_core_service/TestServiceRegistryExternalTrafficBetaAnnotationHealthCheckNodePortUserAllocation/)

upstream: https://github.com/kubernetes/kubernetes/issues/37982

**Comment by derekwaynecarr** [comment]
this is fixed upstream:
https://github.com/kubernetes/kubernetes/pull/46060

we could pick this in origin or wait for next rebase.  since flakes slow everyone down, i am inclined to pick it after master goes out.

@jboyd01 -- can you look at picking this change from upstream kube to origin?  it's relatively small, and is a good example to teach you of the process.

**Comment by stevekuznetsov** [comment]
Picked up in the rebase

/close
