### ISSUE TITLE
panic on "oc set triggers"

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#13805]
I have tried to set a trigger and I get a panic

##### Version
````
oc v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
````

Also:

````
oc v3.6.0-alpha.1+46942ad
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
````

Also:
````
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
````

##### Steps To Reproduce
Execute all this in a terminal against minishift or oc cluster up (any of the above versions):

````
oc new-project go-scratch
oc import-image jorgemoralespou/s2i-go --confirm
oc new-build s2i-go~https://github.com/jorgemoralespou/ose-chained-builds --context-dir=/go-scratch/hello_world --name=builder

sleep 1

# watch the logs
oc logs -f bc/builder --follow

# Generated artifact is located in /opt/app-root/src/go/src/main/main
oc new-build --name=runtime --docker-image=scratch --source-image=builder --source-image-path=/opt/app-root/src/go/src/main/main:. --dockerfile=$'FROM scratch\nCOPY main /main\nEXPOSE 8080\nENTRYPOINT ["/main"]' --strategy=docker

sleep 1

oc logs -f bc/runtime --follow


# Add a trigger to automatically rebuild on change to builder
oc set triggers bc/runtime --from-image=builder:latest
````

##### Current Result
I get a panic:

````
oc set triggers bc/runtime --from-image=go-scratch/builder:latest
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22fa2f]

goroutine 1 [running]:
panic(0x1af1e40, 0xc4200100c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/openshift/origin/pkg/cmd/cli/cmd/set.(*TriggerDefinition).Apply(0xc420ba4ea0, 0x2e84d40, 0xc4206dea00, 0xc420a0d970, 0x10cf8)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/set/triggers.go:620 +0x82f
github.com/openshift/origin/pkg/cmd/cli/cmd/set.UpdateTriggersForObject(0x2e84d40, 0xc4206dea00, 0xc420b99790, 0x0, 0x0, 0xc4202069a0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/set/triggers.go:781 +0x1f8
github.com/openshift/origin/pkg/cmd/cli/cmd/set.(*TriggersOptions).Run.func2(0xc4201c6b80, 0xc4200a54d0, 0x2e84d40, 0xc4206dea00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/set/triggers.go:285 +0x41
github.com/openshift/origin/pkg/cmd/cli/cmd/set.CalculatePatches(0xc420ba0060, 0x1, 0x1, 0x37d26b0, 0xc4200a54d0, 0xc420a0dbd8, 0xc4200a53b0, 0xc420010c88, 0xa)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/set/helper.go:146 +0x190
github.com/openshift/origin/pkg/cmd/cli/cmd/set.(*TriggersOptions).Run(0xc4202399e0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/set/triggers.go:286 +0x181
github.com/openshift/origin/pkg/cmd/cli/cmd/set.NewCmdTriggers.func1(0xc42032f680, 0xc420786920, 0x1, 0x2)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/set/triggers.go:121 +0xb3
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc42032f680, 0xc4207867e0, 0x2, 0x2, 0xc42032f680, 0xc4207867e0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x439
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420364000, 0xc420030008, 0xc420030018, 0xc420364000)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420364000, 0x2, 0xc420364000)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:36 +0x196
````

##### Expected Result
Trigger to be set.

**Comment by smarterclayton** [comment]
strategyTrigger is nil because there is no upstream image.  Line 620 should skip setting strategyTrigger.Auto if it is nil.

**Comment by jorgemoralespou** [comment]
Also I would expect a test on this since it's been broken since 1.4 at least, so I would assume had never worked.
