### ISSUE TITLE
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.TestCancelAndReadd

### ISSUE THREAD

**Issue by bparees** [openshift/origin#13966]
```
=== RUN   TestCancelAndReadd
panic: sync: negative WaitGroup counter

goroutine 352 [running]:
panic(0x23a2620, 0xc4204598b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
sync.(*WaitGroup).Add(0xc4204596c0, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:75 +0x27c
sync.(*WaitGroup).Done(0xc4204596c0)
	/usr/local/go/src/sync/waitgroup.go:100 +0x42
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.TestCancelAndReadd.func1(0xc420be1f20, 0xe00000001, 0x20)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/timed_workers_test.go:118 +0x65
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.(*TimedWorkerQueue).getWrappedWorkerFunc.func1(0xc420be1f20, 0x0, 0x0)
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/_test/_obj_test/timed_workers.go:90 +0xb6
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.CreateWorker.func1()
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/_test/_obj_test/timed_workers.go:49 +0x72
created by time.goFunc
	/usr/local/go/src/time/sleep.go:154 +0x78
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_check/1568

**Comment by dmage** [comment]
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.TestCancel (from github.com_openshift_origin_vendor_k8s.io_kubernetes_pkg_controller_node)
```
Stacktrace

=== RUN   TestCancel
panic: sync: negative WaitGroup counter

goroutine 350 [running]:
panic(0x23d8100, 0xc42036f250)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
sync.(*WaitGroup).Add(0xc4203b5df0, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:75 +0x27c
sync.(*WaitGroup).Done(0xc4203b5df0)
	/usr/local/go/src/sync/waitgroup.go:100 +0x42
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.TestCancel.func1(0xc4201338a0, 0x1, 0x1c)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/timed_workers_test.go:88 +0x65
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.(*TimedWorkerQueue).getWrappedWorkerFunc.func1(0xc4201338a0, 0x0, 0x0)
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/_test/_obj_test/timed_workers.go:90 +0xb6
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.CreateWorker.func1()
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/_test/_obj_test/timed_workers.go:49 +0x72
created by time.goFunc
	/usr/local/go/src/time/sleep.go:154 +0x78
```
Seen there: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1444/

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_unit/1187/testReport/junit/github.com_openshift_origin_vendor_k8s/io_kubernetes_pkg_controller_node/TestCancelAndReadd/

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_unit/1852/

**Comment by deads2k** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16251/test_pull_request_origin_unit/2349/

**Comment by kargakis** [comment]
```
=== RUN   TestCancel
panic: sync: negative WaitGroup counter

goroutine 390 [running]:
sync.(*WaitGroup).Add(0xc420277990, 0xffffffffffffffff)
	/usr/lib/golang/src/sync/waitgroup.go:75 +0x255
sync.(*WaitGroup).Done(0xc420277990)
	/usr/lib/golang/src/sync/waitgroup.go:100 +0x42
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.TestCancel.func1(0xc42014fa60, 0xc400000001, 0xc40000001c)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/timed_workers_test.go:88 +0x61
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.(*TimedWorkerQueue).getWrappedWorkerFunc.func1(0xc42014fa60, 0x0, 0x0)
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/_test/_obj_test/timed_workers.go:81 +0xb6
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.CreateWorker.func1()
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/_test/_obj_test/timed_workers.go:44 +0x72
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:170 +0x52
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16214/test_pull_request_origin_unit/2412/

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15199/test_pull_request_origin_unit/2441/

**Comment by smarterclayton** [comment]
I thought this was fixed upstream???

**Comment by kargakis** [comment]
They are literally ignoring it upstream: https://github.com/kubernetes/kubernetes/issues/51704

/shrug

This flake is becoming really annoying. @derekwaynecarr can we push forward either fixing it (here or upstream I don't care) or disable?

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/6141/consoleFull#141320619656cbb9a5e4b02b88ae8c2f77
