### ISSUE TITLE
[builds][Slow] openshift pipeline build Pipeline using jenkins-client-plugin [It] should build and complete successfully

### ISSUE THREAD

**Issue by oatmealraisin** [openshift/origin#14057]
[Link to the failure](https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/51/consoleFull#-169259343956c60d7be4b02b88ae8c268b)

We've decided that this flake in the build tests is different from #13984. 

Although this test is failing at the same place
```
• Failure [868.626 seconds]
[builds][Slow] openshift pipeline build
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:395
  Pipeline using jenkins-client-plugin
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:182
    should build and complete successfully [It]
    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:181

    Expected
        <bool>: false
    to be true

    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:176
``
this seems to have a different cause. Some new exception being thrown are:
```
WARNING: already completed CpsStepContext[49:_OcWatch]:Owner[extended-test-jenkins-pipeline-vdr9h-7c5jx-sample-pipeline-openshift-client-plugin/1:extended-test-jenkins-pipeline-vdr9h-7c5jx-sample-pipeline-openshift-client-plugin #1]
java.lang.IllegalStateException: delivered here
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.completed(CpsStepContext.java:352)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.onSuccess(CpsStepContext.java:332)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
May 04, 2017 12:52:58 PM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
INFO: new success: null
May 04, 2017 12:52:58 PM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
INFO: previously delivered here
java.lang.Throwable
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.completed(CpsStepContext.java:340)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.onFailure(CpsStepContext.java:328)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:176)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:70)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
May 04, 2017 12:52:58 PM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
INFO: earlier failure
java.util.concurrent.ExecutionException: java.lang.InterruptedException: sleep interrupted
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.get(CpsBodyExecution.java:297)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:138)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:70)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:203)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:138)
	... 8 more
```

@gabemontero fyi

**Comment by gabemontero** [comment]
To be more precise, it is possible the same as https://github.com/openshift/origin/issues/13984 with the SSL difficulties.

but I wanted to focus on this piece from the job for a bit:

```
[Pipeline] timeout
Timeout set to expire in 5 min 0 sec
[Pipeline] {
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcWatch
Entering watch
Running watch closure body
[Pipeline] {
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
Cancelling nested steps due to timeout
[Pipeline] }
[Pipeline] // _OcWatch
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.util.concurrent.ExecutionException: java.lang.InterruptedException: sleep interrupted
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.get(CpsBodyExecution.java:297)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:138)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:70)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:203)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:138)
	... 8 more
Finished: FAILURE
```

And confirm whether we are doing the right thing in openshift-client on the watch timeout.  If we are, I'll close this out.  If we are not, an openshift-client PR will ensue.

**Comment by gabemontero** [comment]
OK,

a) I'm convinced client plugin is doing the right thing ... it is doing an `oc get pods -w` equivalent for the mongodb pod, which seems successfully deployed, 

b) both sync plugin / k8s and openshift-client's use of the oc binary start seeing ssl related comm issues
like in the other flake

c) on the master side ... more of the same ... the jenkins server starts failing its readiness/liveness checks (though the event does not get generated because of a known k8s upstream issue)

d) java gc on jenkins looks fine .... it is almost like a general env issue;  looked at some of the env reposrts (io, mem, cpu) generated as part of the run;  nothing seems crazy, but i honestly don't have the required context to know what would be *bad* in that space.

Closing this one out then as a dup of https://github.com/openshift/origin/issues/13984

Getting to the point where I need to huddle up with some folks, get some second opinions on how to debug.
