### ISSUE TITLE
merge PR test failed to download artifacts

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#14083]
see https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_networking_minimal/1774/console

Snippet from log:

```
########## FINISHED STAGE: FAILURE: DOWNLOAD ARTIFACTS FROM THE REMOTE HOST ##########
Build step 'Execute a set of scripts' changed build result to FAILURE
Build step 'Execute a set of scripts' marked build as failure
Archiving artifacts
ERROR: Failed to archive artifacts: .config/origin-ci-tool/logs/junit/*.xml,artifacts/**/*.xml
java.io.IOException: Failed to create a directory at /var/lib/jenkins/jobs/test_pull_request_origin_extended_networking_minimal/builds/1774/archive/.config/origin-ci-tool/logs/junit
	at hudson.util.IOUtils.mkdirs(IOUtils.java:66)
	at hudson.FilePath.mkdirsE(FilePath.java:2914)
	at hudson.FilePath.access$2000(FilePath.java:195)
	at hudson.FilePath$42$1.visit(FilePath.java:2133)
	at hudson.util.DirScanner.scanSingle(DirScanner.java:49)
	at hudson.FilePath$ExplicitlySpecifiedDirScanner.scan(FilePath.java:2804)
	at hudson.FilePath$42.invoke(FilePath.java:2128)
	at hudson.FilePath$42.invoke(FilePath.java:2121)
	at hudson.FilePath.act(FilePath.java:996)
	at hudson.FilePath.act(FilePath.java:974)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2121)

```

**Comment by gabemontero** [comment]
I finally noticed https://github.com/openshift/origin/issues/14044 ... looks close enough to this one.
Closing this one as a dup.
