### ISSUE TITLE
Jenkins fails: java.io.IOException: Failed to create a temp file

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#14082]
See https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/1743/consoleFull

Snippet from log:

```
TASK [openshift_hosted : Set facts for secure registry] ******TASK [openshift_hosted : Set facts for secure registry] ************************
ok: [localhost] => {

ok: [localhost] => {

task path: /usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/registry/registry.yml:98
skipping: [localhost] => {

skipping: [localhost] => {

changed: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => (item=/usr/share/ansible/openshift-ansible/roles/openshift_metrics/vars/default_images.yml)  => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => (item=/usr/share/ansible/openshift-ansible/roles/openshift_logging/vars/default_images.yml)  => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {
skipping: [localhost] => {

skipping: [localhost] => {

ok: [localhost] => {

changed: [localhost] => {

ok: [localhost] => {

ok: [localhost] => {
ok: [localhost] => {

changed: [localhost] => {

ok: [localhost] => {
META: ran handlers
skipping: [localhost] => {
ok: [localhost] => {

skipping: [localhost] => {
ok: [localhost] => {

ok: [localhost] => {

ok: [localhost] => {

ok: [localhost] => {
skipping: [localhost] => {
skipping: [localhost] => {
skipping: [localhost] => {
skipping: [localhost] => {


ok: [localhost] => (item=iproute) => {
ok: [localhost] => (item=python-dbus) => {
ok: [localhost] => (item=PyYAML) => {
ok: [localhost] => (item=yum-utils) => {

skipping: [localhost] => (item=atomic)  => {
skipping: [localhost] => (item=ostree)  => {
skipping: [localhost] => (item=runc)  => {

ok: [localhost] => {

                       "region=infra", 
ok: [localhost] => {

skipping: [localhost] => {

ok: [localhost] => {

skipping: [localhost] => {


skipping: [localhost] => {
ok: [localhost] => {

ok: [localhost] => {

skipping: [localhost] => {

ok: [localhost] => {

ok: [localhost] => (item={u'dest': u'/etc/pki/rpm-gpg/', u'src': u'origin/gpg_keys/openshift-ansible-CentOS-SIG-PaaS'}) => {
ok: [localhost] => (item={u'dest': u'/etc/yum.repos.d/', u'src': u'origin/repos/openshift-ansible-centos-paas-sig.repo'}) => {

skipping: [localhost] => {

task path: /usr/share/ansible/openshift-ansible/roles/openshift_repos/tasks/main.yaml:52
skipping: [localhost] => {

ok: [localhost] => {

ok: [localhost] => {

ok: [localhost] => {

ok: [localhost] => {

skipping: [localhost] => {

skipping: [localhost] => {

ok: [localhost] => {

skipping: [localhost] => {

ok: [localhost] => {

skipping: [localhost] => {
META: ran handlers
+ set +o xtrace
FATAL: Unable to produce a script file
java.io.IOException: Failed to create a temp file on /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install/workspace
	at hudson.FilePath.createTextTempFile(FilePath.java:1385)
	at hudson.tasks.CommandInterpreter.createScriptFile(CommandInterpreter.java:161)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:93)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:65)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
```

**Comment by pweil-** [comment]
@mfojtik in the spirit of handling more installer items sending this your way.  @sdodson FYI

**Comment by sdodson** [comment]
I'm honestly not sure if that's ansible or jenkins that's at fault here. I'd expect ansible to have dumped a summary before exiting so I suspect ansible aborted but maybe it just aborted because jenkins hosts's FS was full as evidenced by the java stacktrace?

**Comment by mfojtik** [comment]
@stevekuznetsov any ideas?

**Comment by stevekuznetsov** [comment]
@dobbymoodge does this ring any bells?

**Comment by dobbymoodge** [comment]
@stevekuznetsov I'm sorry, but your hunchback is in another cathedral. No, it doesn't ring any bells for me.

**Comment by stevekuznetsov** [comment]
Well, if @dobbymoodge wasn't touching the file descriptors and the world isn't coming to an end this just looks like a flake on Jenkins' part to create a tmp file. Maybe a cosmic ray hit the server. We can re-visit this if it happens again but it doesn't look like we can do much about it.

**Comment by bparees** [comment]
closing due to cosmic rays.

/close
