### ISSUE TITLE
FAILURE: BUILD AN OPENSHIFT-ANSIBLE RELEASE

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#14122]
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/260/consoleFull#-157296560358b6e51eb7608a5981914356

I think this happened because the tag is on the stage branch but this PR is against master?

```
########## STARTING STAGE: BUILD AN OPENSHIFT-ANSIBLE RELEASE ##########
+ [[ -s /var/lib/jenkins/jobs/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/workspace/activate ]]
+ source /var/lib/jenkins/jobs/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/workspace/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/b58d70e4ba8547fb716da04deb467ce17ccf4345
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/b58d70e4ba8547fb716da04deb467ce17ccf4345
++ export PATH=/var/lib/jenkins/origin-ci-tool/b58d70e4ba8547fb716da04deb467ce17ccf4345/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/b58d70e4ba8547fb716da04deb467ce17ccf4345/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/workspace/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/workspace/.config
++ mktemp
+ script=/tmp/tmp.SXCuZksfW9
+ cat
+ chmod +x /tmp/tmp.SXCuZksfW9
+ scp -F ./.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.SXCuZksfW9 openshiftdevel:/tmp/tmp.SXCuZksfW9
+ ssh -F ./.config/origin-ci-tool/inventory/.ssh_config -t openshiftdevel 'bash -l -c "/tmp/tmp.SXCuZksfW9"'
+ cd /data/src/github.com/openshift/openshift-ansible
+ tito_tmp_dir=tito
+ mkdir -p tito
+ tito tag --offline --accept-auto-changelog
Creating output directory: /tmp/tito
Tagging new version of openshift-ansible: 3.6.62-1 -> 3.6.63-1
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 202, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 666, in main
    return tagger.run(self.options)
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 114, in run
    self._tag_release()
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 136, in _tag_release
    self._check_tag_does_not_exist(self._get_new_tag(new_version))
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 501, in _check_tag_does_not_exist
    raise Exception("Tag %s already exists!" % new_tag)
Exception: Tag openshift-ansible-3.6.63-1 already exists!
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: BUILD AN OPENSHIFT-ANSIBLE RELEASE ##########
```

**Comment by sdodson** [comment]
I think I've fixed this by tagging stage 3.6.65.0 and master 3.6.66

**Comment by stevekuznetsov** [comment]
Yeah, we need to be using that four-number workaround until we have a better solution, but this isn't necessarily a tooling or testing issue -- we just need to have a method for making unique tags.

**Comment by sdodson** [comment]
Well, we should use tools to handle the stage branching, so just making sure you guys are aware of that and we add .0 to the current version while branching and tagging stage.

**Comment by stevekuznetsov** [comment]
Is this problem solved? Are the people reporting this above doing so from old failures? Do we need to take action right now?

**Comment by sdodson** [comment]
Those are old failures. I fixed it at

```
commit 5bd4ca446711fc7faa53ad0d6d3f2183857938d1
Author: Scott Dodson <sdodson@redhat.com>
Date:   Wed May 10 08:50:14 2017 -0400

    Automatic commit of package [openshift-ansible] release [3.6.66-1].
    
    Created by command:
    
    /usr/bin/tito tag --keep-version
```

**Comment by tnozicka** [comment]
seems like it's still there: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/713/console

**Comment by mfojtik** [comment]
Note that this happened exactly when the new tag was cut for OSE and the versions in error matches, so maybe just bad timing.

**Comment by tnozicka** [comment]
https://github.com/openshift/origin/pull/14322 hit it again - https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/853/

This seem to be serious :)

**Comment by sdodson** [comment]
On stage branch set rpm specfile version to 3.6.88.0, tag and pushed to github.
On master branch set rpm specfile version to 3.6.89, tag and pushed to github.

We need to fix the stage branch tooling to append a fourth version segment when forking that branch.

Looks like @jupierce  built the jobs for that, assigning to him.

**Comment by jupierce** [comment]
@sdodson I think the only patch that will hold up through stagecut is adding a .0 to the openshift-ansible.spec in **master**. A change in the stage branch will be wiped out every time we build stage (since the o-a spec version is always replaced by the ose spec version). When stagecut ends and we return to master, the .0 will similarly be wiped out. 
Discussing longer term solutions with @stevekuznetsov to determine the best route.

**Comment by jupierce** [comment]
Should be fixed with https://github.com/openshift/aos-cd-jobs/commit/ca7f5b24d09d465f10aa25ab9c2e392432d6b7aa

**Comment by enj** [comment]
Seen in #14853 https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1111/

```
########## FINISHED STAGE: SUCCESS: DETERMINE THE RELEASE COMMIT FOR ORIGIN IMAGES [00h 00m 14s] ##########
[workspace] $ /bin/bash /tmp/hudson1315612192578537421.sh
########## STARTING STAGE: BUILD AN OPENSHIFT-ANSIBLE RELEASE ##########
+ [[ -s /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace/activate ]]
+ source /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890
++ export PATH=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace/.config
++ mktemp
+ script=/tmp/tmp.4YCB5OYOuv
+ cat
+ chmod +x /tmp/tmp.4YCB5OYOuv
+ scp -F ./.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.4YCB5OYOuv openshiftdevel:/tmp/tmp.4YCB5OYOuv
+ ssh -F ./.config/origin-ci-tool/inventory/.ssh_config -t openshiftdevel 'bash -l -c "/tmp/tmp.4YCB5OYOuv"'
+ cd /data/src/github.com/openshift/openshift-ansible
+ tito_tmp_dir=tito
+ mkdir -p tito
+ tito tag --offline --accept-auto-changelog
Creating output directory: /tmp/tito
Tagging new version of openshift-ansible: 3.6.123-1 -> 3.6.124-1
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 202, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 666, in main
    return tagger.run(self.options)
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 114, in run
    self._tag_release()
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 136, in _tag_release
    self._check_tag_does_not_exist(self._get_new_tag(new_version))
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 501, in _check_tag_does_not_exist
    raise Exception("Tag %s already exists!" % new_tag)
Exception: Tag openshift-ansible-3.6.124-1 already exists!
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: BUILD AN OPENSHIFT-ANSIBLE RELEASE [00h 00m 02s] ##########
Build step 'Execute shell' marked build as failure
[PostBuildScript] - Execution post build scripts.
[workspace] $ /bin/bash /tmp/hudson2579696756842582650.sh
```

**Comment by jupierce** [comment]
Fixed again. The present workaround relies on careful management of Jenkins job scheduling. Working on a more robust solution.

**Comment by jupierce** [comment]
@stevekuznetsov I think I asked this before during our discussion, but I'll lay it out there again. Addressing this completely outside of CI is tricky. I think a simple and effective approach would be for CI to sed append .1000 to any version it found in openshift-ansible.spec before doing tito tag. This is effectively what has to happen outside of CI to avoid this problem, but performing it outside of CI involves git commits and adds complexity to entering and exiting stagecut.

**Comment by stevekuznetsov** [comment]
Not the cleanest thing in the world but we can try that on Monday.

**Comment by jupierce** [comment]
We should now have a reliable fix in place:

- master branches will build with three fields (3.6.X)
- stage branches will build with four fields (3.6.X.Y). https://github.com/openshift/openshift-ansible/commit/f9c47bffe9a5592ac9bb4994da18d8f9453963c8
- enterprise branches will build will five fields (3.6.X.Y.Z)
