### ISSUE TITLE
API server panic due to garbage collection requiring delete strategy

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#14198]
Edits by @enj

1. The following resources in origin have a `nil` `store.DeleteStrategy`:

```
clusterpolicies.authorization.openshift.io
clusterpolicybindings.authorization.openshift.io
policies.authorization.openshift.io
policybindings.authorization.openshift.io
images.image.openshift.io
imagestreams.image.openshift.io
clusternetworks.network.openshift.io
egressnetworkpolicies.network.openshift.io
hostsubnets.network.openshift.io
netnamespaces.network.openshift.io
oauthaccesstokens.oauth.openshift.io
oauthauthorizetokens.oauth.openshift.io
oauthclientauthorizations.oauth.openshift.io
oauthclients.oauth.openshift.io
routes.route.openshift.io
templates.template.openshift.io
groups.user.openshift.io
identities.user.openshift.io
users.user.openshift.io
```

2. `store.EnableGarbageCollection` is `true` for all resources now.

1 and 2 combined with any of the following `DeleteOptions`:

- `OrphanDependents` = `true`
- `PropagationPolicy` = `DeletePropagationOrphan`
- `PropagationPolicy` = `DeletePropagationForeground`

Lead to a `panic` in the API server because it tries to a do a graceful deletion and finalization which dereferences `DeleteStrategy`.

We have some protection from https://github.com/openshift/origin/commit/54d84e6a8db4c07f78fb2823508fed7751ebf1bd but we need to reconsider.  Upstream does not carry this patch at all.

---

I'm seeing a panic trying to delete a route in the web console. We're passing `propagationPolicy: "Foreground"` (which we've switched to passing for all requests).

```
$ oc version
oc v3.6.0-alpha.1+b581bfe-566
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.1+b581bf
```

HTTP Request:

```
DELETE /oapi/v1/namespaces/node/routes/asdfasdf
Content-Type: application/json
...
{"kind":"DeleteOptions","apiVersion":"v1","propagationPolicy":"Foreground"}
```

Response:

```
Status: 500
...
This request caused apisever to panic. Look in log for details.
```

Logs:

```
E0515 16:23:22.567079   26140 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:479
/usr/local/go/src/runtime/panic.go:458
/usr/local/go/src/runtime/panic.go:62
/usr/local/go/src/runtime/sigpanic_unix.go:24
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/registry/rest/create.go:128
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/registry/rest/delete.go:66
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:761
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/util.go:38
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:485
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:292
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/cacher.go:529
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:799
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:879
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:936
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:1102
/usr/local/go/src/runtime/asm_amd64.s:2086
E0515 16:23:22.567424   26140 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:479
/usr/local/go/src/runtime/panic.go:458
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:1118
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:939
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:102
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/emicklei/go-restful/container.go:272
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/emicklei/go-restful/container.go:120
/usr/local/go/src/net/http/server.go:1726
/usr/local/go/src/net/http/server.go:2022
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/handlers/authorization.go:64
/usr/local/go/src/net/http/server.go:1726
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/handlers/impersonation.go:30
/usr/local/go/src/net/http/server.go:1726
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/handlers/authentication.go:32
/usr/local/go/src/net/http/server.go:1726
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:97
/usr/local/go/src/net/http/server.go:1726
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:65
/usr/local/go/src/net/http/server.go:1726
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/gorilla/context/context.go:141
/usr/local/go/src/net/http/server.go:1726
/usr/local/go/src/net/http/server.go:2022
/usr/local/go/src/net/http/server.go:2022
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master.go:1109
/usr/local/go/src/net/http/server.go:1726
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:211
/usr/local/go/src/net/http/server.go:1726
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/cors.go:75
/usr/local/go/src/net/http/server.go:1726
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41
/usr/local/go/src/net/http/server.go:1726
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91
/usr/local/go/src/runtime/asm_amd64.s:2086
E0515 16:23:22.567807   26140 wrap.go:34] APIServer panic'd on DELETE /oapi/v1/namespaces/node/routes/asdfasdf: runtime error: invalid memory address or nil pointer dereference
goroutine 49727 [running]:
runtime/debug.Stack(0xa78f1e0, 0xc4314185b0, 0x55689ed)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1.1(0x4be09a0, 0xc420012050)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:34 +0x74
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc42bd83ec8, 0x1, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:54 +0xe5
panic(0x4be09a0, 0xc420012050)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers.finishRequest(0x6fc23ac00, 0xc431d860a0, 0x24, 0x0, 0x0, 0xa75bba0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:1118 +0x3aa
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers.DeleteResource.func1(0xc42e215680, 0xc430297860)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:939 +0x420
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc42e215680, 0xc430297860)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:102 +0x1f8
github.com/openshift/origin/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc422eeb830, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/emicklei/go-restful/container.go:272 +0xba0
github.com/openshift/origin/vendor/github.com/emicklei/go-restful.(*Container).(github.com/openshift/origin/vendor/github.com/emicklei/go-restful.dispatch)-fm(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4279d1780, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4237a7530, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
github.com/openshift/origin/pkg/cmd/server/handlers.AuthorizationFilter.func1(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/handlers/authorization.go:64 +0x113
net/http.HandlerFunc.ServeHTTP(0xc4237b6ec0, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/pkg/cmd/server/handlers.ImpersonationFilter.func1(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/handlers/impersonation.go:30 +0x3142
net/http.HandlerFunc.ServeHTTP(0xc4237cb2c0, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/pkg/cmd/server/handlers.AuthenticationHandlerFilter.func1(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/handlers/authentication.go:32 +0x2ba
net/http.HandlerFunc.ServeHTTP(0xc4237b6f00, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/pkg/cmd/server/origin.namespacingFilter.func1(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:97 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc423820420, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/pkg/cmd/server/origin.cacheControlFilter.func1(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:65 +0xc2
net/http.HandlerFunc.ServeHTTP(0xc423820450, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/vendor/github.com/gorilla/context.ClearHandler.func1(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/gorilla/context/context.go:141 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc4214d37c0, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc423820e40, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.(*ServeMux).ServeHTTP(0xc4212488d0, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
github.com/openshift/origin/pkg/cmd/server/origin.WithPatternsHandler.func1(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master.go:1109 +0xcd
net/http.HandlerFunc.ServeHTTP(0xc422ed45c0, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/pkg/cmd/server/origin.WithAssetServerRedirect.func1(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:211 +0x7f
net/http.HandlerFunc.ServeHTTP(0xc422012e10, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithCORS.func1(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/cors.go:75 +0x1a2
net/http.HandlerFunc.ServeHTTP(0xc4203e4540, 0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0xa78f1e0, 0xc4314185b0, 0xc42f507590)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x11b
net/http.HandlerFunc.ServeHTTP(0xc4234b3480, 0x7f93fd7ab688, 0xc429f4ef20, 0xc42f507590)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc4234b34c0, 0xa7a55e0, 0xc429f4ef20, 0xc42f507590, 0xc430296780)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91 +0x8d
created by github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x1d1
```

Route YAML:

```yaml
apiVersion: v1
kind: Route
metadata:
  name: asdfasdf
  namespace: node
  selfLink: /oapi/v1/namespaces/node/routes/asdfasdf
  uid: 2a70d1d2-398a-11e7-8813-12fcae64f2c0
  resourceVersion: '2821'
  creationTimestamp: '2017-05-15T16:18:43Z'
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: asdfasdf-node.127.0.0.1.nip.io
  to:
    kind: Service
    name: mongodb
    weight: 100
  port:
    targetPort: mongodb
  wildcardPolicy: None
status:
  ingress:
    - host: asdfasdf-node.127.0.0.1.nip.io
      routerName: router
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2017-05-15T16:18:43Z'
      wildcardPolicy: None
```

cc @deads2k @jwforres @knobunc

**Comment by jwforres** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1452569

**Comment by enj** [comment]
cc @openshift/api-review See https://github.com/openshift/origin/issues/14198#issue-228772005 for details on this.

**Comment by enj** [comment]
A temporary solution would be to have `store.CompleteWithOptions` default `DeleteStrategy` using `CreateStrategy` or `UpdateStrategy`.

**Comment by deads2k** [comment]
> A temporary solution would be to have store.CompleteWithOptions default DeleteStrategy using CreateStrategy or UpdateStrategy.

Those are supposed to be different interfaces.  Have it fail with a clear message about a coding mistake and update our resources.  You should also be able to write a unit test with some reflection magic against the storage map we make when we wire up the API server to catch these.

**Comment by enj** [comment]
@deads2k I thought delete strategy was supposed to be optional?  And in most places it is just used as a typer.  It may be time to change that into the interface we actually expect.

cc @mfojtik @soltysh @sttts @ncdc

**Comment by smarterclayton** [comment]
DeleteStrategy should not be optional if you implement delete.

Rest/test was supposed to have reflection stuff like this.
