### ISSUE TITLE
pkg/build/builder/util.go failed to compile on RHEL

### ISSUE THREAD

**Issue by jupierce** [openshift/origin#14718]
Recent changes to pkg/build/builder/util.go prevented RHEL 3.6 build. 

```
Executing command: ['bash', '--login', '-c', 'rpmbuild -bb --target x86_64 --nodeps builddir/build/SPECS/origin.spec']
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.3emmY0
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf atomic-openshift-git-0.a660965
+ /usr/bin/gzip -dc /builddir/build/SOURCES/atomic-openshift-git-0.a660965.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd atomic-openshift-git-0.a660965
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.kzPxTw
+ umask 022
+ cd /builddir/build/BUILD
+ cd atomic-openshift-git-0.a660965
+ OS_GIT_MINOR=6+
+ OS_GIT_MAJOR=3
+ OS_GIT_VERSION=v3.6.115
+ OS_GIT_TREE_STATE=clean
+ OS_BUILD_LDFLAGS_DEFAULT_IMAGE_STREAMS=rhel7
+ OS_IMAGE_PREFIX=registry.access.redhat.com/openshift3/ose
+ OS_GIT_COMMIT=a660965
+ hack/build-cross.sh
++ Building go targets for linux/amd64: images/pod cmd/dockerregistry cmd/gitserver vendor/k8s.io/kubernetes/cmd/hyperkube pkg/sdn/plugin/sdn-cni-plugin vendor/github.com/containernetworking/cni/plugins/ipam/host-local vendor/github.com/containernetworking/cni/plugins/main/loopback examples/hello-openshift
++ Building go targets for linux/amd64: cmd/openshift cmd/oc cmd/kubefed
++ Building go targets for darwin/amd64: cmd/openshift cmd/oc cmd/kubefed
# github.com/openshift/origin/pkg/build/builder
pkg/build/builder/util.go:180: undefined: cgroups.ParseCgroupFile
[ERROR] PID 120970: hack/lib/build/binaries.sh:223: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -pkgdir "${OS_OUTPUT_PKGDIR}/${platform}" -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags="${local_ldflags}" "${goflags[@]:+${goflags[@]}}" "${nonstatics[@]}"` exited with status 2.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/build/binaries.sh:223: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -pkgdir "${OS_OUTPUT_PKGDIR}/${platform}" -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags="${local_ldflags}" "${goflags[@]:+${goflags[@]}}" "${nonstatics[@]}"`
[INFO] 		  2: hack/lib/build/binaries.sh:158: os::build::internal::build_binaries
[INFO] 		  3: hack/build-cross.sh:79: os::build::build_binaries
[INFO]   Exiting with code 2.
[ERROR] PID 93277: hack/lib/build/binaries.sh:152: `local -a binaries=("$@")` exited with status 2.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/build/binaries.sh:152: `local -a binaries=("$@")`
[INFO] 		  2: hack/build-cross.sh:79: os::build::build_binaries
[INFO]   Exiting with code 2.
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.kzPxTw (%build)
    Bad exit status from /var/tmp/rpm-tmp.kzPxTw (%build)
Child returncode was: 1
EXCEPTION: Command failed. See logs for output.
 # ['bash', '--login', '-c', 'rpmbuild -bb --target x86_64 --nodeps builddir/build/SPECS/origin.spec']
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mockbuild/trace_decorator.py", line 70, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.6/site-packages/mockbuild/util.py", line 345, in do
    raise mockbuild.exception.Error, ("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # ['bash', '--login', '-c', 'rpmbuild -bb --target x86_64 --nodeps builddir/build/SPECS/origin.spec']
LEAVE do --> EXCEPTION RAISED
```

**Comment by jupierce** [comment]
FYI @bparees

**Comment by bparees** [comment]
@jupierce thanks, @liggitt caught this last night and has a fix in the queue here:
https://github.com/openshift/origin/pull/14717
