### ISSUE TITLE
Unable to force update a DC using force=true

### ISSUE THREAD

**Issue by aslakknutsen** [openshift/origin#15017]
In an attempt to forcefully update a given resource the client panic on nil ref.

##### Version

```
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.starter-us-east-2.openshift.com:443
openshift v3.5.5.19
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce

Current server state:

```
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-branch: release-v3.0.31
    fabric8.io/git-commit: 2a5725583e872bdf865fda19c41e915e6a261b02
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=content-repository&var-version=3.0.31
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/content-repository
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/content-repository
    fabric8.io/scm-tag: fabric8-team-components-1.0.0
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/content-repository
    maven.fabric8.io/source-url: jar:file:/root/.mvnrepository/io/fabric8/fabric8-team-components/apps/content-repository/3.0.31/content-repository-3.0.31.jar!/META-INF/fabric8/openshift.yml
  creationTimestamp: 2017-04-29T23:54:01Z
  generation: 4
  labels:
    group: io.fabric8.devops.apps
    project: content-repository
    provider: fabric8
    version: 3.0.31
  name: content-repository
  namespace: manderse-jenkins
  resourceVersion: "223418698"
  selfLink: /oapi/v1/namespaces/manderse-jenkins/deploymentconfigs/content-repository
  uid: 1e8e180a-2d37-11e7-9954-02e52a0be43d
spec:
  replicas: 1
  selector:
    group: io.fabric8.fabric8-team-components.apps
    project: content-repository
    provider: fabric8
    version: 3.0.31
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      annotations:
        fabric8.io/git-branch: release-v3.0.31
        fabric8.io/git-commit: 2a5725583e872bdf865fda19c41e915e6a261b02
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=content-repository&var-version=3.0.31
        fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/content-repository
        fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/content-repository
        fabric8.io/scm-tag: fabric8-team-components-1.0.0
        fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/content-repository
      creationTimestamp: null
      labels:
        group: io.fabric8.fabric8-team-components.apps
        project: content-repository
        provider: fabric8
        version: 3.0.31
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: fabric8/caddy-server:v9274a15
        imagePullPolicy: IfNotPresent
        name: content-repository
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9180
          name: prometheus
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/www/html
          name: content
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: content-repository
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-04-29T23:55:45Z
    lastUpdateTime: 2017-04-29T23:56:24Z
    message: replication controller "content-repository-3" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2017-06-30T00:25:59Z
    lastUpdateTime: 2017-06-30T00:25:59Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 3
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
```

Apply state:

```
---
apiVersion: v1
kind: Template
metadata:
  labels:
    provider: fabric8
    project: fabric8-online-jenkins
    version: 1.0.186
    group: io.fabric8.online.packages
  name: fabric8-online-jenkins
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg
      fabric8.io/git-commit: 6a70b818f9db0596f9d423ca5bb3774312ea66c2
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=content-repository&var-version=3.0.43
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/content-repository
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/content-repository
      fabric8.io/git-branch: release-v3.0.43
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/content-repository
      fabric8.io/scm-tag: fabric8-team-components-1.0.0
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepository/io/fabric8/fabric8-team-components/apps/content-repository/3.0.43/content-repository-3.0.43.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: content-repository
      version: 3.0.43
      group: io.fabric8.devops.apps
    name: content-repository
  spec:
    replicas: 1
    selector:
      project: content-repository
      provider: fabric8
      group: io.fabric8.fabric8-team-components.apps
    strategy:
      recreateParams:
        timeoutSeconds: 7200
      type: Recreate
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 6a70b818f9db0596f9d423ca5bb3774312ea66c2
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=content-repository&var-version=3.0.43
          fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/content-repository
          fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/content-repository
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg
          fabric8.io/git-branch: release-v3.0.43
          fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/content-repository
          fabric8.io/scm-tag: fabric8-team-components-1.0.0
        labels:
          provider: fabric8
          project: content-repository
          version: 3.0.43
          group: io.fabric8.fabric8-team-components.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fabric8/caddy-server:v9274a15
          imagePullPolicy: IfNotPresent
          name: content-repository
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 9180
            name: prometheus
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          volumeMounts:
          - mountPath: /var/www/html
            name: content
            readOnly: false
        volumes:
        - name: content
          persistentVolumeClaim:
            claimName: content-repository
    triggers:
    - type: ConfigChange
```

##### Current Result

No force

```
cat max.yaml | oc process -f - --namespace=manderse-jenkins | oc apply -f -  --overwrite=true --namespace=manderse-jenkins
```
```
The DeploymentConfig "content-repository" is invalid: spec.template.metadata.labels: Invalid value: {"group":"io.fabric8.fabric8-team-components.apps","project":"content-repository","provider":"fabric8","version":"3.0.43"}: `selector` does not match template `labels`
```

With force=true

```
cat max.yaml | oc process -f - --namespace=manderse-jenkins | oc apply -f -  --overwrite=true --force=true --namespace=manderse-jenkins
```

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xd6f60b]

goroutine 1 [running]:
panic(0x1f970a0, 0xc420012140)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*Helper).Delete(0xc42101cb40, 0x7ffd66737c7b, 0x10, 0xc420d54180, 0x12, 0xc4202d5ce0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/helper.go:97 +0x3b
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.runDelete(0x7ffd66737c7b, 0x10, 0xc420d54180, 0x12, 0xc4210067e0, 0x0, 0x0, 0xc420ff8a80, 0x1, 0xffffffffffffffff, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:484 +0x22b
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.(*patcher).delete(0xc4207029a0, 0x7ffd66737c7b, 0x10, 0xc420d54180, 0x12, 0x1a6, 0xc420bf4fd0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:497 +0x9c
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.(*patcher).deleteAndCreate(0xc4207029a0, 0xc421082000, 0x1ad9, 0x1ad9, 0x7ffd66737c7b, 0x10, 0xc420d54180, 0x12, 0x7ffd66737c7b, 0x10, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:568 +0x63
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.(*patcher).patch(0xc4207029a0, 0x35bd4c0, 0xc42040ef00, 0xc421082000, 0x1ad9, 0x1ad9, 0x0, 0x0, 0x7ffd66737c7b, 0x10, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:562 +0x3c1
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.RunApply.func1(0xc42101e100, 0x0, 0x0, 0x9, 0xd79101)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:275 +0x694
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit.func1(0xc42101e100, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:345 +0x153
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit.func1(0xc42101e100, 0x0, 0x0, 0xc420d74060, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:321 +0xe5
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit.func1(0xc4201e3980, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:409 +0x31e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit.func1(0xc4201e3980, 0x0, 0x0, 0xc000, 0x226f098)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:204 +0x153
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*StreamVisitor).Visit(0xc420c0c440, 0xc420c1dcc0, 0xc4200a0000, 0x5)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:545 +0x326
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*FileVisitor).Visit(0xc420c1dac0, 0xc420c1dcc0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:494 +0xd9
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc42026d010, 0x1, 0x1, 0xc420c20690, 0x1, 0xc420c20690)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:208 +0xf4
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0xc420c1db60, 0xc420c20690, 0x0, 0x2586762)
	<autogenerated>:124 +0x6e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x35cad40, 0xc420c1db60, 0xc420c0c400, 0xc420c0c4c0, 0xc420c1dc01, 0xc420c0c4c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:414 +0x94
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc420c1db80, 0xc420c0c4c0, 0x18, 0x18)
	<autogenerated>:140 +0x6e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x35cadc0, 0xc420c1db80, 0xc420c1dbe0, 0x4, 0x4, 0xc420c1dc80, 0x1, 0xc420c1dc80)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:322 +0xd6
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc420c20600, 0xc420c1dc80, 0x7fb8ce1cf000, 0xc41ff9ecff)
	<autogenerated>:160 +0x78
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x35cacc0, 0xc420c20600, 0xc420c26000, 0x7fb8ce1cf000, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:349 +0xf1
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc42026d030, 0xc420c26000, 0x413678, 0x90)
	<autogenerated>:155 +0x65
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc420178d90, 0xc420c26000, 0x0, 0xc420c20660)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/result.go:81 +0x4e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.RunApply(0x35f5ac0, 0xc4202ad0e0, 0xc4202b8480, 0x35c7d80, 0xc4200a0008, 0xc420b19e60, 0x4, 0x258fe28)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:300 +0x722
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdApply.func1(0xc4202b8480, 0xc420b81d10, 0x0, 0x5)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:103 +0x168
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202b8480, 0xc420b81cc0, 0x5, 0x5, 0xc4202b8480, 0xc420b81cc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x439
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420292fc0, 0xc4200a0000, 0xc4200a0010, 0xc420292fc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420292fc0, 0x2, 0xc420292fc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:36 +0x196
```

##### Expected Result

The new yaml to be applied regardless of current server state.

**Comment by pweil-** [comment]
@mfojtik fixed by your controller update maybe?

**Comment by mfojtik** [comment]
@pweil- no, this seems like a CLI problem :-)

**Comment by fabianofranz** [comment]
I have a fix upstream in https://github.com/kubernetes/kubernetes/pull/48481, @liggitt this is a blocker so should I open an UPSTREAM pull request here?

**Comment by liggitt** [comment]
yeah, pick here and add a test

**Comment by fabianofranz** [comment]
Fix is in https://github.com/openshift/origin/pull/15066.
