### ISSUE TITLE
panic inside the deployer pod

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15049]
```
2017-07-05T06:19:09.173515000Z panic: runtime error: invalid memory address or nil pointer dereference
2017-07-05T06:19:09.173861000Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x22c333b]
2017-07-05T06:19:09.174474000Z goroutine 1 [running]:
2017-07-05T06:19:09.174734000Z panic(0x4ce17e0, 0xc420016050)
2017-07-05T06:19:09.174969000Z 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-07-05T06:19:09.175219000Z github.com/openshift/origin/pkg/deploy/strategy/support.makeHookPod(0xc420dcd8f0, 0xc420891a20, 0xc420f98900, 0xc420f8a880, 0x553ef63, 0x8, 0x0, 0x0, 0x0)
2017-07-05T06:19:09.175459000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:339 +0x90b
2017-07-05T06:19:09.175894000Z github.com/openshift/origin/pkg/deploy/strategy/support.(*hookExecutor).executeExecNewPod(0xc420dcb200, 0xc420dcd8f0, 0xc420891a20, 0x553ef63, 0x8, 0x55337fe, 0x3, 0x0, 0x0)
2017-07-05T06:19:09.176182000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:193 +0x1f1
2017-07-05T06:19:09.176453000Z github.com/openshift/origin/pkg/deploy/strategy/support.(*hookExecutor).Execute(0xc420dcb200, 0xc420dcd8f0, 0xc420891a20, 0x553ef63, 0x8, 0x55337fe, 0x3, 0xc420e95850, 0x413aa8)
2017-07-05T06:19:09.176748000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:100 +0x11c2
2017-07-05T06:19:09.177188000Z github.com/openshift/origin/pkg/deploy/strategy/rolling.(*RollingDeploymentStrategy).Deploy(0xc420d83600, 0x0, 0xc420891a20, 0x2, 0x0, 0x0)
2017-07-05T06:19:09.177441000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/pkg/deploy/strategy/rolling/rolling.go:139 +0x384
2017-07-05T06:19:09.177702000Z github.com/openshift/origin/pkg/cmd/infra/deployer.(*Deployer).Deploy(0xc420dca540, 0xc42001410f, 0x28, 0xc42001216a, 0x13, 0xc420026010, 0xaa0bea0)
2017-07-05T06:19:09.177945000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/infra/deployer/deployer.go:252 +0x9fe
2017-07-05T06:19:09.178198000Z github.com/openshift/origin/pkg/cmd/infra/deployer.(*config).RunDeployer(0xc420c57720, 0xaa0bea0, 0xc420026018)
2017-07-05T06:19:09.178568000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/infra/deployer/deployer.go:116 +0x19d
2017-07-05T06:19:09.178828000Z github.com/openshift/origin/pkg/cmd/infra/deployer.NewCommandDeployer.func1(0xc4201fe900, 0xc4202150e0, 0x0, 0x1)
2017-07-05T06:19:09.179082000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/infra/deployer/deployer.go:75 +0x9a
2017-07-05T06:19:09.179357000Z github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201fe900, 0xc42000c250, 0x1, 0x1, 0xc4201fe900, 0xc42000c250)
2017-07-05T06:19:09.179640000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x439
2017-07-05T06:19:09.180312000Z github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4201fe900, 0xc420026008, 0xc420026018, 0xc4201fe900)
2017-07-05T06:19:09.180573000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x367
2017-07-05T06:19:09.180872000Z github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4201fe900, 0x10, 0xc4201fe900)
2017-07-05T06:19:09.181283000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
2017-07-05T06:19:09.181523000Z main.main()
2017-07-05T06:19:09.181800000Z 	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originn2lCmv/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:36 +0x196---
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/4085/testReport/junit/(root)/Extended/deploymentconfigs_with_revision_history_limits__Conformance__should_never_persist_more_old_deployments_than_acceptable_after_being_observed_by_the_controller/

@mfojtik @tnozicka 

@smarterclayton you were asking about this job - [3 out of 4 deployment test failures](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/4085/) include this panic

**Comment by kargakis** [comment]
Doesn't seem the cause for the flaked tests though, lowering priority and removing the flake label

**Comment by kargakis** [comment]
@mfojtik since you added the client call inside the deployer which ends up returning a 404 that results in the panic

**Comment by kargakis** [comment]
> Doesn't seem the cause for the flaked tests though, lowering priority and removing the flake label

Not sure at which point the panic kicks off (is it the start or the end of the deployment)? If it's the start, then this is causing the flake in the history limit test, adding flake label back.

ps. that test should probably tolerate failed deployments since we only want to test RC garbage colletion.

**Comment by smarterclayton** [comment]
Panic in running code should always p1

**Comment by smarterclayton** [comment]
Putting this in 3.6.0

**Comment by kargakis** [comment]
Yeah on [this test](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/4085/testReport/junit/(root)/Extended/deploymentconfigs_reaper__Conformance__should_delete_all_failed_deployer_pods_and_hook_pods/) it seems that the panic takes place before creating the pre-hook....

**Comment by kargakis** [comment]
We either need https://github.com/kubernetes/kubernetes/issues/36813 or we can [note the time a deployer starts](https://github.com/openshift/origin/blob/be5e626c6ae4f4138ffee0bd08023acdcc47d7b1/pkg/cmd/infra/deployer/deployer.go#L171), pass that around in the strategies to create the hook pods, and kick the client call out of the deployer.

**Comment by smarterclayton** [comment]
Investigating this

**Comment by smarterclayton** [comment]
@sjenning @derekwaynecarr in this test the pod exists but has StartTime empty.  In theory, this is our pod (i.e. we are code running inside a pod that exists, but has StartTime unset).  I think this is a race caused by status not being updated as fast as the running code.

If that's the case, then in our lookup we'll have to tolerate startTime being unset until 36813 gets corrected.
