### ISSUE TITLE
jsonpath filter failure can generate panic and go stack traces from oc

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#15075]
If you are using ``oc get`` with ``jsonpath`` with output format, and specify a filter which does array index, if the index requirement can't be satisfied, the ``oc`` program panics and generates a GO stack trace.

##### Version

oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://localhost:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce

Run:

```
oc get pods --selector app=doesnotexist -o jsonpath='{.items[-1:].metadata.name}'
```

##### Current Result

```
panic: reflect.Value.Slice: slice index out of bounds

goroutine 1 [running]:
panic(0x35917a0, 0xc4202609f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
reflect.Value.Slice(0x3537020, 0xc4210e1020, 0x97, 0xffffffffffffffff, 0x0, 0x97, 0xc420260900, 0xc42111f168)
	/usr/local/go/src/reflect/value.go:1554 +0x20c
github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).evalArray(0xc420bce9a0, 0xc4210e1060, 0x1, 0x1, 0xc420733fc0, 0xc4210e1060, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:271 +0x494
github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).walk(0xc420bce9a0, 0xc4210e1060, 0x1, 0x1, 0x61b6320, 0xc420733fc0, 0xc4210e1060, 0x1, 0x1, 0x0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:146 +0x88a
github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).evalList(0xc420bce9a0, 0xc4210e1040, 0x1, 0x1, 0xc4210e0680, 0x73f84b0, 0x0, 0x0, 0xc420b0d680, 0x18)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:200 +0x94
github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).walk(0xc420bce9a0, 0xc4210e1040, 0x1, 0x1, 0x61b64e0, 0xc4210e0680, 0x18, 0xc4210e1020, 0x0, 0xd40000c420032800, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:140 +0xae2
github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).FindResults(0xc420bce9a0, 0x3789b60, 0xc420f2c840, 0x0, 0x3537020, 0xc4210e1020, 0x3e5d1eb, 0x5)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:87 +0x1c7
github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).Execute(0xc420bce9a0, 0x61aace0, 0xc420030010, 0x3789b60, 0xc420f2c840, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:65 +0x49
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/printers.(*JSONPathPrinter).PrintObj(0xc4210e08a0, 0x619f860, 0xc4210e0f20, 0x61aace0, 0xc420030010, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/printers/jsonpath.go:145 +0x19b
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.RunGet(0x61ecaa0, 0xc420ac9da0, 0x61aace0, 0xc420030010, 0x61aace0, 0xc420030018, 0xc4202ec480, 0xc420cf7f40, 0x1, 0x5, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:372 +0x1d52
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdGet.func1(0xc4202ec480, 0xc420cf7f40, 0x1, 0x5)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:115 +0x95
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202ec480, 0xc420cf7ef0, 0x5, 0x5, 0xc4202ec480, 0xc420cf7ef0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x439
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42033bd40, 0xc420030008, 0xc420030018, 0xc42033bd40)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42033bd40, 0x2, 0xc42033bd40)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:36 +0x196

```

##### Expected Result

A nice error message rather than a panic and stack trace.

##### Additional Information

None.

**Comment by enj** [comment]
@openshift/cli-review
