### ISSUE TITLE
os::build::version::get_vars: command not found flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15200]
```
+ sjb/gcs/started.py
/tmp/origin_version.sh: line 2: os::build::version::get_vars: command not found
[ERROR] PID 11369: /tmp/origin_version.sh:2: `os::build::version::get_vars` exited with status 127.
[INFO] 		Stack Trace: 
[INFO] 		  1: /tmp/origin_version.sh:2: `os::build::version::get_vars`
[INFO]   Exiting with code 127.
Traceback (most recent call last):
  File "sjb/gcs/started.py", line 58, in <module>
    cwd=join(repository_base_dir, "origin")
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/tmp/origin_version.sh']' returned non-zero exit status 127
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/4364/consoleFull#5959220465898c58db7602c31c0eab717

**Comment by stevekuznetsov** [comment]
Eh, I'm ok with this one -- it's going to silently fail and only thing that will happen is we won't have GCS artifacts. We'd have to push the Bash refactor into 1.5 to fix it. Not super interested in that.

**Comment by stevekuznetsov** [comment]
Also to be clear this does not fail the job.

**Comment by kargakis** [comment]
Yeah, lowering priority
