### ISSUE TITLE
[ERROR] PID 16377: hack/update-generated-clientsets.sh:29: `client-gen --clientset-path="${grouppkg}/generated" --input-base="${package}" --output-base="../../.." --clientset-name="${name}" --go-header-file=hack/boilerplate.txt "$@"` exited with status 255.

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15444]
```
F0724 08:56:58.103443   17314 main.go:253] Error: Failed executing generator: some packages had errors:
errors in package "github.com/openshift/origin/pkg/security/generated/internalclientset/typed/security/internalversion":
output for "internalversion/security_client.go" differs; first existing/expected diff: 
  "\trest \"k8s.io/client-go/rest\"\n)\n\ntype SecurityInterface interface {\n\tRESTClient() rest.Interface\n\tSe"
  ")\n"
output for "internalversion/generated_expansion.go" differs; first existing/expected diff: 
  "\ntype SecurityContextConstraintsExpansion interface{}\n"
  ""
errors in package "github.com/openshift/origin/pkg/security/generated/internalclientset/typed/security/internalversion/fake":
output for "fake/fake_security_client.go" differs; first existing/expected diff: 
  "\trest \"k8s.io/client-go/rest\"\n\ttesting \"k8s.io/client-go/testing\"\n)\n\ntype FakeSecurity struct {\n\t*te"
  ")\n"
goroutine 1 [running]:
github.com/openshift/origin/vendor/github.com/golang/glog.stacks(0xc428b02700, 0xc425462800, 0x3a1, 0x3f6)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:766 +0xa7
github.com/openshift/origin/vendor/github.com/golang/glog.(*loggingT).output(0x864440, 0xc400000003, 0xc4284be840, 0x84420b, 0x7, 0xfd, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:717 +0x348
github.com/openshift/origin/vendor/github.com/golang/glog.(*loggingT).printf(0x864440, 0x3, 0x6ffbf1, 0x9, 0xc428fd3de0, 0x1, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:655 +0x14f
github.com/openshift/origin/vendor/github.com/golang/glog.Fatalf(0x6ffbf1, 0x9, 0xc428fd3de0, 0x1, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/cmd/libs/go2idl/client-gen/main.go:253 +0x734
```
/assign @sttts @mfojtik 
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1367/

**Comment by mfojtik** [comment]
@deads2k bumped the k8s level yesterday, I bet there were some changes in client-gen that might break @php-coder PR... @php-coder can you try to regenerate the clients once again?

**Comment by mfojtik** [comment]
closing this as non-issue, this was coding problem :)
