### ISSUE TITLE
flake: Failed to deprovision cluster: GCENodeDriver object has no attribute '_ex_populate_dict'

### ISSUE THREAD

**Issue by jsafrane** [openshift/origin#15451]
```
+ ../../bin/local.sh ansible-playbook playbooks/terminate.yaml
Activated service account credentials for: [jenkins-ci-provisioner@openshift-gce-devel.iam.gserviceaccount.com]
ERROR! Attempted to execute "/usr/share/ansible/openshift-ansible-gce/inventory.sh" as inventory script: Inventory script (/usr/share/ansible/openshift-ansible-gce/inventory.sh) had an execution error: Traceback (most recent call last):
  File "/usr/share/ansible/openshift-ansible-gce/inventory/gce/hosts/gce.py", line 400, in <module>
    GceInventory()
  File "/usr/share/ansible/openshift-ansible-gce/inventory/gce/hosts/gce.py", line 132, in __init__
    print(self.json_format_dict(self.group_instances(zones),
  File "/usr/share/ansible/openshift-ansible-gce/inventory/gce/hosts/gce.py", line 320, in group_instances
    nodes = self.driver.list_nodes()
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 2419, in list_nodes
    use_disk_cache=ex_use_disk_cache)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 8366, in _to_node
    bd['name'], bd['zone'], use_cache=use_disk_cache)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 7109, in ex_get_volume
    return self._ex_lookup_volume(name, zone)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 7405, in _ex_lookup_volume
    self._ex_populate_dict()
AttributeError: 'GCENodeDriver' object has no attribute '_ex_populate_dict'
 
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: DEPROVISION TEST CLUSTER [00h 00m 08s] ##########
Build step 'Execute a set of scripts' changed build result to FAILURE
Build step 'Execute a set of scripts' marked build as failure
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/4726/consoleFull

**Comment by stevekuznetsov** [comment]
This is #14575
