### ISSUE TITLE
kubernetes/pkg/master.TestValidOpenAPISpec unit test failure when DETECT_RACES=false

### ISSUE THREAD

**Issue by detiber** [openshift/origin#15679]
kubernetes/pkg/master.TestValidOpenAPISpec unit test failure when DETECT_RACES=false

##### Version
master

##### Steps To Reproduce
1. hack/env JUNIT_REPORT=true DETECT_RACES=false make test-unit WHAT=vendor/k8s.io/kubernetes/pkg/master

##### Current Result
TestValidOpenAPISpec test fails

##### Expected Result
All mater unit tests pass

##### Additional Information
vendor/k8s.io/kubernetes/pkg/master/master_openapi_test.go contains a build tag to not run when race detection is enabled, so the test is only run when race detection is disabled.

```
=== RUN   TestValidOpenAPISpec
2017-08-07 21:01:50.183646 I | integration: launching 4092330108149737152 (unix://localhost:40923301081497371520)
2017-08-07 21:01:50.185956 I | etcdserver: name = 4092330108149737152
2017-08-07 21:01:50.185989 I | etcdserver: data dir = /openshifttmp/etcd290723678
2017-08-07 21:01:50.186001 I | etcdserver: member dir = /openshifttmp/etcd290723678/member
2017-08-07 21:01:50.186006 I | etcdserver: heartbeat = 10ms
2017-08-07 21:01:50.186012 I | etcdserver: election = 100ms
2017-08-07 21:01:50.186017 I | etcdserver: snapshot count = 0
2017-08-07 21:01:50.186041 I | etcdserver: advertise client URLs = unix://127.0.0.1:2100208215
2017-08-07 21:01:50.186050 I | etcdserver: initial advertise peer URLs = unix://127.0.0.1:2100108215
2017-08-07 21:01:50.186068 I | etcdserver: initial cluster = 4092330108149737152=unix://127.0.0.1:2100108215
2017-08-07 21:01:50.190225 I | etcdserver: starting member ff8ef7f79a0ad7e9 in cluster 5b5ca184e35ef77b
2017-08-07 21:01:50.190291 I | raft: ff8ef7f79a0ad7e9 became follower at term 0
2017-08-07 21:01:50.190311 I | raft: newRaft ff8ef7f79a0ad7e9 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017-08-07 21:01:50.190319 I | raft: ff8ef7f79a0ad7e9 became follower at term 1
2017-08-07 21:01:50.210080 W | auth: simple token is not cryptographically signed
2017-08-07 21:01:50.214067 I | etcdserver: set snapshot count to default 100000
2017-08-07 21:01:50.225109 I | etcdserver: starting server... [version: 3.2.1, cluster version: to_be_decided]
2017-08-07 21:01:50.225685 I | integration: launched 4092330108149737152 (unix://localhost:40923301081497371520)
2017-08-07 21:01:50.227801 I | etcdserver/membership: added member ff8ef7f79a0ad7e9 [unix://127.0.0.1:2100108215] to cluster 5b5ca184e35ef77b
2017-08-07 21:01:50.300638 I | raft: ff8ef7f79a0ad7e9 is starting a new election at term 1
2017-08-07 21:01:50.300735 I | raft: ff8ef7f79a0ad7e9 became candidate at term 2
2017-08-07 21:01:50.300767 I | raft: ff8ef7f79a0ad7e9 received MsgVoteResp from ff8ef7f79a0ad7e9 at term 2
2017-08-07 21:01:50.300794 I | raft: ff8ef7f79a0ad7e9 became leader at term 2
2017-08-07 21:01:50.300818 I | raft: raft.node: ff8ef7f79a0ad7e9 elected leader ff8ef7f79a0ad7e9 at term 2
2017-08-07 21:01:50.301199 I | etcdserver: setting up the initial cluster version to 3.2
2017-08-07 21:01:50.306045 N | etcdserver/membership: set the initial cluster version to 3.2
2017-08-07 21:01:50.306182 I | etcdserver/api: enabled capabilities for version 3.2
2017-08-07 21:01:50.306211 I | etcdserver: published {Name:4092330108149737152 ClientURLs:[unix://127.0.0.1:2100208215]} to cluster 5b5ca184e35ef77b
[restful] 2017/08/07 21:01:50 log.go:33: [restful/swagger] listing is available at http://192.168.10.4:443/swaggerapi
[restful] 2017/08/07 21:01:50 log.go:33: [restful/swagger] http://192.168.10.4:443/swaggerui/ is mapped to folder /swagger-ui/
F0807 21:01:50.516916    8215 openapi.go:38] Failed to register open api spec for root: cannot find model definition for k8s.io/kubernetes/pkg/api/v1.Endpoints. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again.
goroutine 149 [running]:
github.com/openshift/origin/vendor/github.com/golang/glog.stacks(0xc420818c00, 0xc422dfedc0, 0x113, 0x285)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:766 +0xa7
github.com/openshift/origin/vendor/github.com/golang/glog.(*loggingT).output(0x5457700, 0xc400000003, 0xc420224420, 0x526091c, 0xa, 0x26, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:717 +0x348
github.com/openshift/origin/vendor/github.com/golang/glog.(*loggingT).printf(0x5457700, 0xc400000003, 0x235310c, 0x2d, 0xc422f018e8, 0x1, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:655 +0x14f
github.com/openshift/origin/vendor/github.com/golang/glog.Fatalf(0x235310c, 0x2d, 0xc422f018e8, 0x1, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:1145 +0x67
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/routes.OpenAPI.Install(0xc4207d7200, 0xc4207d7440, 0xc42008a4d0, 0xc42168c008)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/routes/openapi.go:38 +0xc6
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareOpenAPIService(0xc420896500, 0xc42168c008, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:288 +0x7c
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc420896500, 0x1f44de0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:274 +0x3b
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/master.TestValidOpenAPISpec(0xc420868000)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/master/master_openapi_test.go:71 +0x51e
testing.tRunner(0xc420868000, 0x23cfb10)
	/usr/lib/golang/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:697 +0x2ca
```

**Comment by detiber** [comment]
@deads2k most recent commits in this area seem to be attributed to you

**Comment by deads2k** [comment]
> @deads2k most recent commits in this area seem to be attributed to you

My general thoughts on openapi stuff is just disable it because it probably never worked.

**Comment by detiber** [comment]
@deads2k it passed prior to the rebase, I'll see if I can track down a fix post-rebase

**Comment by detiber** [comment]
@deads2k I think I tracked down the issue, just not a fix yet. It looks like upstream release-1.7 is generating openapi paths like this: k8s.io/kubernetes/pkg/api/v1.ComponentStatus and we are generating them like this: k8s.io/api/core/v1.ComponentStatus

**Comment by detiber** [comment]
@deads2k What is the process for regenerating ./vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go ?

I've tried to run `make update` and `hack/update-generated-openapi.sh`, but have not been able to successfully run either command.

**Comment by deads2k** [comment]
> @deads2k What is the process for regenerating ./vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go ?

The upstream file is done in the openshift/kubernetes fork. You'll probably need to sync all upstream patches from openshift/origin, then merge them into the upstream fork, then pull the upstream fork (it won't build), then generate the files locally, then cherry-pick the changes into openshift (again locally), and then open an origin pull.  It seems crazy when you're doing it.  It seems even crazier saying it out loud.
