### ISSUE TITLE
Jenkins plugin extended tests failing

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15823]
Bunch of extended test failures related to the jenkins plugin and image tags:
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/177/

Also it seems like those tests are not doing a good job of dumping the pipeline job logs when things fail.

**Comment by bparees** [comment]
I reran the suite and all the same tests failed, so this is not a flake.
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/178

**Comment by gabemontero** [comment]
On Thu, Aug 17, 2017 at 2:51 PM, Ben Parees <notifications@github.com>
wrote:

> I reran the suite and all the same tests failed, so this is not a flake.
> https://ci.openshift.redhat.com/jenkins/job/test_branch_
> origin_extended_image_ecosystem/178
>
When I circle to this I'll run the latest jenkins image against 3.6 GA to
confirm whether it works with earlier
versions of openshift or not.  That should be the be close to what the last
PR test run did.

I'm guessing it will work, and we'll have to track down what changed wrt
the image apis,
but we'll see and go from there.

**Comment by enj** [comment]
Assigning myself in case this is related to #15021 or #15721

@gabemontero let me know if see anything odd related to auth or storage registry.

**Comment by gabemontero** [comment]
OK, in addition to the image tagging stuff, the basic `oc create` equivalent for jenkins-plugin got broke by whatever happened in the underlying origin stuff.  My guess is it is separate from the image tagging.

Looking at that one first, it fails attempting to hit  `https://172.30.0.1/swaggerapi//api/v1` ... in other words, mistakingly putting in consecutive slashes ... looks like the master used to be tolerant of the `//` but no longer is.

When I fix the plugin to correct the swaggerapi URI and only have 1 slash (i.e. https://172.30.0.1/swaggerapi/api/v1) it works again.

I have the change ready to start the plugin PR / update plugin version / update jenkins image process, but will dive into the image stream tagging stuff beforehand and see if additional plugin changes are needed.

**Comment by gabemontero** [comment]
I take it back :-) ... forgot the image tagging has to use the create.

Same root cause:

```
Starting "Tag OpenShift Image" with the source [image stream:tag] "multitag3:prod8" from the project "extended-test-jenkins-plugin-68732-90w5h" and destination stream(s) "multitag4, multitag5, multitag6" with tag(s) "prod9, prod10, prod11" from the project "extended-test-jenkins-plugin-68732-90w5h".


Starting "Create OpenShift Resource(s)" with the project "extended-test-jenkins-plugin-68732-90w5h".
com.openshift.restclient.NotFoundException: Not Found
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:112)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:65)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.httpGet(IOpenShiftPlugin.java:720)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftApiObjHandler.fetchApiJsonFromApiServer(IOpenShiftApiObjHandler.java:23)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftApiObjHandler.updateApiTypes(IOpenShiftApiObjHandler.java:66)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftCreator.coreLogic(IOpenShiftCreator.java:69)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftImageTagger.coreLogic(IOpenShiftImageTagger.java:245)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:309)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doIt(IOpenShiftPlugin.java:327)
	at com.openshift.jenkins.plugins.pipeline.OpenShiftBaseStep.perform(OpenShiftBaseStep.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
ERROR: "Tag OpenShift Image" failed
Finished: FAILURE
```

I'll start the plugin fix train.
