### ISSUE TITLE
flake in cmd: etcdserver: request timed out

### ISSUE THREAD

**Issue by dmage** [openshift/origin#16248]
```
serviceaccount "registry" created
deploymentconfig "docker-registry" created
Error from server: etcdserver: request timed out
Error from server (InternalError): Internal error occurred: failed to allocate a serviceIP: etcdserver: request timed out
[INFO] No compiled `junitreport` binary was found. Attempting to build one using:
[ERROR] PID 20181: hack/lib/start.sh:636: `oc create --config="${ADMIN_KUBECONFIG}" -f -` exited with status 1.
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15796/test_pull_request_origin_cmd/2378/

/kind test-flake

**Comment by kargakis** [comment]
@mfojtik this is flaking a lot these past days, ptal

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_cmd/2558/
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_cmd/2553/
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_cmd/2531/
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_cmd/2543/

**Comment by eparis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15061/test_pull_request_origin_cmd/2704/

**Comment by smarterclayton** [comment]
Seeing this on a ton of builds, it looks like something is wrong with etcd:

https://storage.googleapis.com/origin-ci-test/logs/test_branch_origin_cmd/434/artifacts/scripts/test-cmd/logs/openshift.log

```
logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x123\n\x04\n\x00\x12\x00\x12\aFailure\x1a\x1detcdserver: request timed out\"\x000\xf4\x03\x1a\x00\"\x00"
 [[openshift/v1.7.0+80709908fd (linux/amd64) kubernetes/930b5c4/serviceaccount-tokens-controller] 172.17.0.2:60630]
E0916 07:20:13.105227   20748 tokens_controller.go:322] error populating serviceaccount token default/default-token-kppgn for service account default: etcdserver: request timed out
I0916 07:20:13.106051   20748 trace.go:76] Trace[1113016360]: "Update /api/v1/namespaces/kube-public/secrets/default-token-dw48r" (started: 2017-09-16 07:20:06.103270759 +0000 UTC) (total time: 7.002760726s):
Trace[1113016360]: [41.186Âµs] [41.186Âµs] About to convert to expected version
Trace[1113016360]: [62.555Âµs] [21.369Âµs] Conversion done
Trace[1113016360]: [66.193Âµs] [3.638Âµs] About to store object in database
Trace[1113016360]: [7.002760726s] [7.002694533s] END
I0916 07:20:13.106099   20748 wrap.go:42] PUT /api/v1/namespaces/kube-public/secrets/default-token-dw48r: (7.003275778s) 500
goroutine 40589 [running]:
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc42e8e7960, 0x1f4)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc42e8e7960, 0x1f4)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*responseWriterDelegator).WriteHeader(0xc431169fb0, 0x1f4)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:135 +0x45
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x5a0bb54, 0x23, 0x7fdf0cf70928, 0xc42f2ee000, 0xeeaa8e0, 0xc4310b39d8, 0xc432b17400, 0x1f4, 0xee6eae0, 0xc42a0ccf00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:91 +0x8d
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x7fdf08282d10, 0xc42f0fcd80, 0xeebe2a0, 0xc423cfdbc0, 0x0, 0x0, 0x594e823, 0x2, 0xeeaa8e0, 0xc4310b39d8, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:116 +0x29e
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x7fdf08282d10, 0xc42f0fcd80, 0xee82ee0, 0xc427e9d260, 0xeebe2a0, 0xc423cfdbc0, 0x0, 0x0, 0x594e823, 0x2, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:135 +0x165
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(0xc430195cc0, 0xee82ee0, 0xc427e9d260, 0xeeaa8e0, 0xc4310b39d8, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:80 +0x10e
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers.UpdateResource.func1(0xeeaa8e0, 0xc4310b39d8, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:903 +0xfb2
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints.restfulUpdateResource.func1(0xc431169ef0, 0xc42f436900)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1045 +0xd5
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc431169ef0, 0xc42f436900)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:104 +0x1cf
github.com/openshift/origin/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc422fd0c60, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/emicklei/go-restful/container.go:277 +0xb8d
github.com/openshift/origin/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc422fd0c60, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x5974e63, 0xe, 0xc422fd0c60, 0xc4278f6310, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x6e7
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc425628a60, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	<autogenerated>:72 +0x86
github.com/openshift/origin/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc433011300, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:91 +0x122
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc422dc8000, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x3dd
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc42e11fea0, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x72
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x597ad20, 0xf, 0xc426adefc0, 0xc42e11fea0, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x301
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4312d4880, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	<autogenerated>:72 +0x86
github.com/openshift/origin/pkg/cmd/server/origin.namespacingFilter.func1(0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:96 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc431216e10, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:50 +0x30c
net/http.HandlerFunc.ServeHTTP(0xc431282980, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:96 +0x311
net/http.HandlerFunc.ServeHTTP(0xc4312829c0, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:47 +0x226a
net/http.HandlerFunc.ServeHTTP(0xc431282a00, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:73 +0x2b0
net/http.HandlerFunc.ServeHTTP(0xc4311291d0, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
net/http.HandlerFunc.ServeHTTP(0xc4312d48a0, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithCORS.func1(0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/cors.go:75 +0x189
net/http.HandlerFunc.ServeHTTP(0xc4311e58c0, 0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0xeeaa960, 0xc42e8e7960, 0xc432b17400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x11b
net/http.HandlerFunc.ServeHTTP(0xc4312d4a60, 0x7fdf08282d78, 0xc4310b39c8, 0xc432b17400)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc4312d4aa0, 0xeec1ee0, 0xc4310b39c8, 0xc432b17400, 0xc42f436720)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91 +0x8d
created by github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x1c0

logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x123\n\x04\n\x00\x12\x00\x12\aFailure\x1a\x1detcdserver: request timed out\"\x000\xf4\x03\x1a\x00\"\x00"
 [[openshift/v1.7.0+80709908fd (linux/amd64) kubernetes/930b5c4/serviceaccount-tokens-controller] 172.17.0.2:60630]
E0916 07:20:13.106287   20748 tokens_controller.go:322] error populating serviceaccount token kube-public/default-token-dw48r for service account default: etcdserver: request timed out
I0916 07:20:13.108411   20748 trace.go:76] Trace[1439852980]: "GuaranteedUpdate etcd3: *api.Secret" (started: 2017-09-16 07:20:06.107524851 +0000 UTC) (total time: 7.000870372s):
Trace[1439852980]: [39.176Âµs] [39.176Âµs] initial value restored
Trace[1439852980]: [196.989Âµs] [157.813Âµs] Transaction prepared
Trace[1439852980]: [7.000870372s] [7.000673383s] END
E0916 07:20:13.108437   20748 status.go:62] apiserver received an error that is not an metav1.Status: etcdserver: request timed out
I0916 07:20:13.108660   20748 trace.go:76] Trace[1645446665]: "Update /api/v1/namespaces/kube-system/secrets/default-token-f6wcp" (started: 2017-09-16 07:20:06.10740497 +0000 UTC) (total time: 7.001239426s):
```

Failures after exactly 7 seconds, implies some sort of timeout on either end.  I think we have an etcd server or client bug.  This may be related to the issues seen on us-west-1 (where certain calls time out after a while from the API server, but not directly to etcd).

Raising priority.

**Comment by smarterclayton** [comment]
Also note:

```
E0916 07:20:29.530005   20748 leaderelection.go:263] Failed to update lock: etcdserver: request timed out
```

@deads2k in unified master mode leader election failures shouldn't be terminating the process, which is likely making this problem worse.  The new "split controller" logic should not be on when leader election is not on.

**Comment by mfojtik** [comment]
There are just [few places](https://gist.github.com/mfojtik/7f13af1d72735f10e58725ae97e58a38) in the etcd code that returns "request timed out". Most of them seems to be related to leader election and the watch.

**Comment by mfojtik** [comment]
@smarterclayton my candidates:
This one I believe we picked recently (@rrati), wonder if this is a side-effect or this issue pre-dates this: 
https://github.com/coreos/etcd/commit/15e9510d2c0674675333008ec8524c1df5d05328

Other:
https://github.com/coreos/etcd/pull/8545/commits/efd7800e0fd5b3e5342479a04a90fca8cb017954

Except these two I don't see anything related to this issue in release-3.2 branch...

**Comment by mfojtik** [comment]
@smarterclayton also for the 7s timeout:

https://github.com/mfojtik/origin/blob/b76b0a9d66ca1ab477ab381a3b9b5297e6333c35/vendor/github.com/coreos/etcd/etcdserver/config.go#L138

```
  // 5s for queue waiting, computation and disk IO delay
  // + 2 * election timeout for possible leader election
```

**Comment by mfojtik** [comment]
@deads2k said this could be the tmpfs issue as the `/tmp` we create [here](https://github.com/openshift/aos-cd-jobs/blob/36526fe969471ef7f73b18f323fb82368169c96e/sjb/config/common/test_cases/origin.yml#L52) is not used when we run the test/cmd [here](https://github.com/openshift/aos-cd-jobs/blob/36526fe969471ef7f73b18f323fb82368169c96e/sjb/config/test_cases/test_branch_origin_cmd.yml#L11)

I wonder if we should add `OS_BUILD_ENV_TMP_VOLUME` into above to make sure we use the host `/tmp` and we don't create empty Docker volume.... @stevekuznetsov ?

**Comment by mfojtik** [comment]
@stevekuznetsov closing this as the issue was the tmpfs and it was fixed in ci-cd repo.
