### ISSUE TITLE
TestStoreCreateInitializedFailed

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16264]
```
=== RUN   TestStoreCreateInitializedFailed
2017-09-09 14:38:08.536538 I | integration: launching 3668440042620281349 (unix://localhost:36684400426202813490)
2017-09-09 14:38:08.546379 I | etcdserver: name = 3668440042620281349
2017-09-09 14:38:08.546446 I | etcdserver: data dir = /tmp/etcd936296964
2017-09-09 14:38:08.546504 I | etcdserver: member dir = /tmp/etcd936296964/member
2017-09-09 14:38:08.546547 I | etcdserver: heartbeat = 10ms
2017-09-09 14:38:08.546592 I | etcdserver: election = 100ms
2017-09-09 14:38:08.546632 I | etcdserver: snapshot count = 0
2017-09-09 14:38:08.546687 I | etcdserver: advertise client URLs = unix://127.0.0.1:2101803367
2017-09-09 14:38:08.546743 I | etcdserver: initial advertise peer URLs = unix://127.0.0.1:2101703367
2017-09-09 14:38:08.546829 I | etcdserver: initial cluster = 3668440042620281349=unix://127.0.0.1:2101703367
2017-09-09 14:38:08.559552 I | etcdserver: starting member d47a8f5eb304e6e6 in cluster 7308610b0ebf525f
2017-09-09 14:38:08.559692 I | raft: d47a8f5eb304e6e6 became follower at term 0
2017-09-09 14:38:08.559791 I | raft: newRaft d47a8f5eb304e6e6 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017-09-09 14:38:08.559856 I | raft: d47a8f5eb304e6e6 became follower at term 1
2017-09-09 14:38:08.595076 W | auth: simple token is not cryptographically signed
2017-09-09 14:38:08.615107 I | etcdserver: set snapshot count to default 100000
2017-09-09 14:38:08.615199 I | etcdserver: starting server... [version: 3.2.1, cluster version: to_be_decided]
2017-09-09 14:38:08.617261 I | etcdserver/membership: added member d47a8f5eb304e6e6 [unix://127.0.0.1:2101703367] to cluster 7308610b0ebf525f
2017-09-09 14:38:08.619045 I | integration: launched 3668440042620281349 (unix://localhost:36684400426202813490)
2017-09-09 14:38:08.654001 I | raft: d47a8f5eb304e6e6 is starting a new election at term 1
2017-09-09 14:38:08.654140 I | raft: d47a8f5eb304e6e6 became candidate at term 2
2017-09-09 14:38:08.654225 I | raft: d47a8f5eb304e6e6 received MsgVoteResp from d47a8f5eb304e6e6 at term 2
2017-09-09 14:38:08.654334 I | raft: d47a8f5eb304e6e6 became leader at term 2
2017-09-09 14:38:08.654422 I | raft: raft.node: d47a8f5eb304e6e6 elected leader d47a8f5eb304e6e6 at term 2
2017-09-09 14:38:08.657223 I | etcdserver: setting up the initial cluster version to 3.2
2017-09-09 14:38:08.666142 N | etcdserver/membership: set the initial cluster version to 3.2
2017-09-09 14:38:08.666960 I | etcdserver: published {Name:3668440042620281349 ClientURLs:[unix://127.0.0.1:2101803367]} to cluster 7308610b0ebf525f
panic: test timed out after 2m0s

goroutine 796 [running]:
testing.startAlarm.func1()
	/usr/lib/golang/src/testing/testing.go:1023 +0x139
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:170 +0x52

goroutine 1 [chan receive, 1 minutes]:
testing.(*T).Run(0xc420291860, 0x1dcf9d0, 0x20, 0x1e39588, 0xc4205bbb01)
	/usr/lib/golang/src/testing/testing.go:698 +0x582
testing.runTests.func1(0xc420291860)
	/usr/lib/golang/src/testing/testing.go:882 +0xab
testing.tRunner(0xc420291860, 0xc4205bbce8)
	/usr/lib/golang/src/testing/testing.go:657 +0x108
testing.runTests(0xc4201aa540, 0x28ee380, 0x1a, 0x1a, 0x148)
	/usr/lib/golang/src/testing/testing.go:888 +0x4e1
testing.(*M).Run(0xc4208a3f28, 0xc4205bbe40)
	/usr/lib/golang/src/testing/testing.go:822 +0x1c4
main.main()
	github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/registry/generic/registry/_test/_testmain.go:144 +0x33e

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2197 +0x1
```

from: 
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_unit/2401/

**Comment by mfojtik** [comment]
Haven't recurred in a month, probably just infra flake.
