### ISSUE TITLE
panic: sync: negative WaitGroup counter in k8s.io/kubernetes/pkg/controller/node	

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#16404]
Seen today here: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/16390/test_pull_request_origin_unit/2793/build-log.txt

```
=== RUN   TestCancel
panic: sync: negative WaitGroup counter
goroutine 400 [running]:
sync.(*WaitGroup).Add(0xc420392540, 0xffffffffffffffff)
	/usr/lib/golang/src/sync/waitgroup.go:75 +0x255
sync.(*WaitGroup).Done(0xc420392540)
	/usr/lib/golang/src/sync/waitgroup.go:100 +0x42
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.TestCancel.func1(0xc420318d80, 0x1, 0x1c)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/timed_workers_test.go:88 +0x61
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.(*TimedWorkerQueue).getWrappedWorkerFunc.func1(0xc420318d80, 0x0, 0x0)
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/_test/_obj_test/timed_workers.go:81 +0xb6
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.CreateWorker.func1()
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/_test/_obj_test/timed_workers.go:44 +0x72
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:170 +0x52
FAIL	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node	37.948s
```

**Comment by enj** [comment]
We just need to disable these tests in origin:

#16077
https://github.com/kubernetes/kubernetes/issues/51704
https://github.com/kubernetes/kubernetes/pull/51705

**Comment by soltysh** [comment]
I don't feel that's a good approach. Disabling tests is our last resort, followed immediately by a proper/temporary fix (if it's big). Why not increasing those timeouts even more?

**Comment by soltysh** [comment]
SGTM, will you open a PR or shall I?

**Comment by mfojtik** [comment]
Seen this 4x today, raising to P0.
