### ISSUE TITLE
logging-es-data-master-f1evf6kf-8-qvl16    0/1       CrashLoopBackOff

### ISSUE THREAD

**Issue by pennpeng** [openshift/origin#17379]
##### Version
```
# oc version 
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift-361-1:8443
kubernetes v1.6.1+5115d708d7

```

##### Steps To Reproduce
```
[root@openshift-361-1 ~]# oc project logging 
Already on project "logging" on server "https://openshift-361-1:8443".
[root@openshift-361-1 ~]# 
[root@openshift-361-1 ~]# 
[root@openshift-361-1 ~]# oc get pod
NAME                                       READY     STATUS             RESTARTS   AGE
logging-curator-2-tkw73                    1/1       Running            41         2d
logging-es-data-master-f1evf6kf-8-deploy   1/1       Running            0          5m
logging-es-data-master-f1evf6kf-8-qvl16    0/1       CrashLoopBackOff   5          5m
logging-fluentd-0jgw4                      1/1       Running            35         2d
logging-fluentd-1z3gx                      1/1       Running            34         2d
logging-fluentd-fsx94                      1/1       Running            33         2d
logging-fluentd-qpf5k                      1/1       Running            35         2d
[root@openshift-361-1 ~]# oc log
login   logout  logs    
[root@openshift-361-1 ~]# oc logs logging-es-data-master-f1evf6kf-8-qvl16
[2017-11-20 02:28:43,100][INFO ][container.run            ] Begin Elasticsearch startup script
[2017-11-20 02:28:43,104][INFO ][container.run            ] Comparing the specified RAM to the maximum recommended for Elasticsearch...
[2017-11-20 02:28:43,105][INFO ][container.run            ] Inspecting the maximum RAM available...
[2017-11-20 02:28:43,108][INFO ][container.run            ] ES_HEAP_SIZE: '2048m'
[2017-11-20 02:28:43,110][INFO ][container.run            ] Setting heap dump location /elasticsearch/persistent/heapdump.hprof
[2017-11-20 02:28:43,111][INFO ][container.run            ] Checking if Elasticsearch is ready on https://localhost:9200
Exception in thread "main" java.lang.IllegalArgumentException: Unknown Discovery type [kubernetes]
	at org.elasticsearch.discovery.DiscoveryModule.configure(DiscoveryModule.java:100)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
Refer to the log for complete error details.
[root@openshift-361-1 ~]# oc get pod -o wide
NAME                                       READY     STATUS             RESTARTS   AGE       IP             NODE
logging-curator-2-tkw73                    1/1       Running            41         2d        10.128.154.4   openshift-361-4
logging-es-data-master-f1evf6kf-8-deploy   1/1       Running            0          5m        10.128.154.6   openshift-361-4
logging-es-data-master-f1evf6kf-8-qvl16    0/1       CrashLoopBackOff   5          5m        10.128.154.7   openshift-361-4
logging-fluentd-0jgw4                      1/1       Running            35         2d        10.128.42.2    openshift-361-1
logging-fluentd-1z3gx                      1/1       Running            34         2d        10.128.100.4   openshift-361-3
logging-fluentd-fsx94                      1/1       Running            33         2d        10.128.104.2   openshift-361-2
logging-fluentd-qpf5k                      1/1       Running            35         2d        10.128.154.3   openshift-361-4

```

```
[root@openshift-361-1 ~]# oc describe pod logging-es-data-master-f1evf6kf-8-qvl16
Name:			logging-es-data-master-f1evf6kf-8-qvl16
Namespace:		logging
Security Policy:	restricted
Node:			openshift-361-4/192.168.150.12
Start Time:		Mon, 20 Nov 2017 10:24:23 +0800
Labels:			component=es
			deployment=logging-es-data-master-f1evf6kf-8
			deploymentconfig=logging-es-data-master-f1evf6kf
			logging-infra=elasticsearch
			provider=openshift
Annotations:		kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"logging","name":"logging-es-data-master-f1evf6kf-8","uid":"e979a315-cd...
			openshift.io/deployment-config.latest-version=8
			openshift.io/deployment-config.name=logging-es-data-master-f1evf6kf
			openshift.io/deployment.name=logging-es-data-master-f1evf6kf-8
			openshift.io/scc=restricted
Status:			Running
IP:			10.128.154.7
Controllers:		ReplicationController/logging-es-data-master-f1evf6kf-8
Containers:
  elasticsearch:
    Container ID:	docker://fdc87b6ef332192e11678b9e9b49cc5fb9cb0b3bfdedc47ede3ec2c0d850566a
    Image:		docker.io/openshift/origin-logging-elasticsearch:v3.6.1
    Image ID:		docker-pullable://docker.io/openshift/origin-logging-elasticsearch@sha256:12be6c72c14dfe9c64f7b85f1730d8f371c5720725ac36338b77a6b690e02605
    Ports:		9200/TCP, 9300/TCP
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Mon, 20 Nov 2017 10:31:36 +0800
      Finished:		Mon, 20 Nov 2017 10:31:39 +0800
    Ready:		False
    Restart Count:	6
    Limits:
      memory:	4Gi
    Requests:
      cpu:	1
      memory:	4Gi
    Readiness:	exec [/usr/share/java/elasticsearch/probe/readiness.sh] delay=10s timeout=30s period=5s #success=1 #failure=3
    Environment:
      DC_NAME:			logging-es-data-master-f1evf6kf
      NAMESPACE:		logging (v1:metadata.namespace)
      KUBERNETES_TRUST_CERT:	true
      SERVICE_DNS:		logging-es-cluster
      CLUSTER_NAME:		logging-es
      INSTANCE_RAM:		4Gi
      HEAP_DUMP_LOCATION:	/elasticsearch/persistent/heapdump.hprof
      NODE_QUORUM:		1
      RECOVER_EXPECTED_NODES:	1
      RECOVER_AFTER_TIME:	5m
      READINESS_PROBE_TIMEOUT:	30
      POD_LABEL:		component=es
      IS_MASTER:		true
      HAS_DATA:			true
    Mounts:
      /elasticsearch/persistent from elasticsearch-storage (rw)
      /etc/elasticsearch/secret from elasticsearch (ro)
      /usr/share/java/elasticsearch/config from elasticsearch-config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from aggregated-logging-elasticsearch-token-tqlpl (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  elasticsearch:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	logging-elasticsearch
    Optional:	false
  elasticsearch-config:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	logging-elasticsearch
    Optional:	false
  elasticsearch-storage:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	logging-es-0
    ReadOnly:	false
  aggregated-logging-elasticsearch-token-tqlpl:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	aggregated-logging-elasticsearch-token-tqlpl
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----				-------------			--------	------		-------
  9m		9m		1	default-scheduler						Normal		Scheduled	Successfully assigned logging-es-data-master-f1evf6kf-8-qvl16 to openshift-361-4
  9m		9m		1	attachdetach							Warning		FailedMount	Failed to attach volume "pvc-914263b1-cd99-11e7-9ed8-fa163ef89a9a" on node "openshift-361-4" with: volume 4045a069-71f4-43da-8a84-7b48e75ce0e2 is not attached to f35a14ca-632d-489a-b7f8-059a0a3c8b28
  9m		9m		1	kubelet, openshift-361-4	spec.containers{elasticsearch}	Normal		Pulling		pulling image "docker.io/openshift/origin-logging-elasticsearch:v3.6.1"
  8m		8m		1	kubelet, openshift-361-4	spec.containers{elasticsearch}	Normal		Pulled		Successfully pulled image "docker.io/openshift/origin-logging-elasticsearch:v3.6.1"
  8m		7m		4	kubelet, openshift-361-4	spec.containers{elasticsearch}	Normal		Created		Created container
  8m		7m		3	kubelet, openshift-361-4	spec.containers{elasticsearch}	Normal		Pulled		Container image "docker.io/openshift/origin-logging-elasticsearch:v3.6.1" already present on machine
  8m		7m		4	kubelet, openshift-361-4	spec.containers{elasticsearch}	Normal		Started		Started container
  8m		7m		6	kubelet, openshift-361-4					Warning		FailedSync	Error syncing pod
  8m		4m		18	kubelet, openshift-361-4	spec.containers{elasticsearch}	Warning		BackOff		Back-off restarting failed container

```

**Comment by jcantrill** [comment]
@pennpeng The image is out of sync with the version of openshift-ansible used to install logging.  https://github.com/openshift/openshift-ansible/issues/5497#issuecomment-331372471

**Comment by afrouzMashaykhi** [comment]
@pennpeng  there is no image openshift/origin-oauth-proxy:v1.0.0 change the yaml file to
image: 'openshift/oauth-proxy:v1.0.0' for es pod
