### ISSUE TITLE
Aggregated logging deployment for origin v3.7 not functional with problems/errors in fluentd, logging-curator and kibana

### ISSUE THREAD

**Issue by wdbasson** [openshift/origin#18107]
Deploying aggregated logging with openshift-logging.yml playbook results in a non-functional EFK cluster. Errors are present in logging-curator, fluentd and kibana.

##### Version
[wdbasson@navi ~]$ oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://example.com:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. ansible hosts file with:
```
openshift_logging_install_logging=True
openshift_logging_curator_script_log_level=debug
openshift_logging_curator_log_level=debug
openshift_logging_kibana_proxy_debug=True
```
2. run ansible play
```
$ ansible-playbook ./playbooks/byo/openshift-cluster/openshift-logging.yml
```

##### Current Result

- logging-curator status in CrashLoopBackOff with error:
`No handlers could be found for logger "root"`
- accessing kibana dashboard via route give an authentication error during oauth2callback:
`An authentication error occurred.`
- port-forward of kibana displays dashboard but has no index patterns
~~- fluentd spews 1000s of unformatted unavailable_shards_exception(s):~~
```
request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5dst\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5dsu\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5dsv\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5dsw\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5dsx\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5dsy\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5dsz\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5ds0\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5ds1\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5ds2\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5ds3\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [.operations.2018.01.13] containing [7255] requests]\"}}}, {\"create\"=>{\"_index\"=>\".operations.2018.01.13\", \"_type\"=>\"com.redhat.viaq.common\", \"_id\"=>\"AWD5GcyV0KcDq5Oo5ds4\", \"status\"=>503, \"error\"=>{\"type\"=>\"unavailable_shards_exception\", \"reason\"=>\"[.operations.2018.01.13][0] primary shard is not active Timeout: [1m], request:
```

##### Expected Result
A working EFK cluster with index patterns in Kibana dash.

##### Additional Information
~~Storage is backed by gluster~~ and using self signed certificates.

```
[wdbasson@navi ~]$ oc get pods
NAME                                      READY     STATUS             RESTARTS   AGE
logging-curator-1-tt5fg                   0/1       CrashLoopBackOff   8          20m
logging-es-data-master-vfj3sxzt-1-c8mgr   2/2       Running            0          19m
logging-fluentd-2nkgz                     1/1       Running            0          20m
logging-fluentd-2zz64                     1/1       Running            0          20m
logging-fluentd-5jjkg                     1/1       Running            0          20m
logging-fluentd-qzxdl                     1/1       Running            0          20m
logging-fluentd-rgzjt                     1/1       Running            0          20m
logging-fluentd-ss2fd                     1/1       Running            0          20m
logging-fluentd-vs69f                     1/1       Running            0          20m
logging-fluentd-vvwbq                     1/1       Running            0          20m
logging-fluentd-wbtsp                     1/1       Running            0          20m
logging-fluentd-xp52w                     1/1       Running            0          20m
logging-fluentd-xxkdl                     1/1       Running            0          20m
logging-kibana-1-pt5qp                    2/2       Running            0          21m
```

**Update**: Initial deployment used gluster and separate ops cluster. Now using ephemeral and single cluster for simplicity. Strikethrough from gluster backed deployment. All other issues remain the same.

**Comment by Neikius** [comment]
`oc rsh -c elasticsearch logging-es-data-master-pa89yfys-1-qf54g ` then check logs in /elasticsearch/logging-es/logs/logging-es.log - I had problems with searchguard that were only visible from that log (and the fact that you couldn't connect to elastic). Reason for my problem was I was running it on glusterfs, also the installation never completed for me... https://github.com/openshift/origin/issues/18034 Probably your issue is unrelated.

**Comment by wdbasson** [comment]
@Neikius: Thanks! There was nothing in the pod's logs but I see some searchguard warnings followed by CorruptIndexException(s):

```
sh-4.2$ cat /elasticsearch/logging-es/logs/logging-es.log
[2018-01-15 12:17:43,889][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] project.glusterfs.dec046fc-f57d-11e7-9b6b-28924a2bfd84.2018.01.14 does not exist in cluster metadata
[2018-01-15 12:17:43,906][INFO ][cluster.metadata         ] [logging-es-data-master-ubjdd04u] [project.glusterfs.dec046fc-f57d-11e7-9b6b-28924a2bfd84.2018.01.14] creating index, cause [auto(bulk api)], templates [com.redhat.viaq-openshift-project.template.json], shards [1]/[0], mappings [_default_]
[2018-01-15 12:17:44,515][INFO ][cluster.routing.allocation] [logging-es-data-master-ubjdd04u] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[project.glusterfs.dec046fc-f57d-11e7-9b6b-28924a2bfd84.2018.01.14][0]] ...]).
[2018-01-15 12:17:44,631][INFO ][cluster.metadata         ] [logging-es-data-master-ubjdd04u] [project.glusterfs.dec046fc-f57d-11e7-9b6b-28924a2bfd84.2018.01.14] create_mapping [com.redhat.viaq.common]
[2018-01-15 12:17:46,456][WARN ][index.engine             ] [logging-es-data-master-ubjdd04u] [project.openshift-template-service-broker.70e2e435-f581-11e7-9b6b-28924a2bfd84.2018.01.13][0] failed engine [refresh failed]
org.apache.lucene.index.CorruptIndexException: misplaced codec footer (file truncated?): remaining=8, expected=16 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/elasticsearch/persistent/logging-es/data/logging-es/nodes/0/indices/project.openshift-template-service-broker.70e2e435-f581-11e7-9b6b-28924a2bfd84.2018.01.13/0/index/_3.cfs") [slice=_3.fdx]))
	at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:411)
	at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:330)
	at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:364)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.<init>(CompressingStoredFieldsReader.java:140)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsReader(CompressingStoredFieldsFormat.java:121)
	at org.apache.lucene.codecs.lucene50.Lucene50StoredFieldsFormat.fieldsReader(Lucene50StoredFieldsFormat.java:173)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:117)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:65)
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:145)
	at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:197)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:99)
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:435)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:286)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:261)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:251)
	at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:104)
	at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:137)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:154)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:669)
	at org.elasticsearch.index.shard.IndexShard.refresh(IndexShard.java:665)
	at org.elasticsearch.index.shard.IndexShard$EngineRefresher$1.run(IndexShard.java:1347)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-01-15 12:17:46,540][WARN ][index.shard              ] [logging-es-data-master-ubjdd04u] [project.openshift-template-service-broker.70e2e435-f581-11e7-9b6b-28924a2bfd84.2018.01.13][0] Failed to perform scheduled engine refresh
[project.openshift-template-service-broker.70e2e435-f581-11e7-9b6b-28924a2bfd84.2018.01.13][[project.openshift-template-service-broker.70e2e435-f581-11e7-9b6b-28924a2bfd84.2018.01.13][0]] RefreshFailedEngineException[Refresh failed]; nested: CorruptIndexException[misplaced codec footer (file truncated?): remaining=8, expected=16 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/elasticsearch/persistent/logging-es/data/logging-es/nodes/0/indices/project.openshift-template-service-broker.70e2e435-f581-11e7-9b6b-28924a2bfd84.2018.01.13/0/index/_3.cfs") [slice=_3.fdx]))];
	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:677)
	at org.elasticsearch.index.shard.IndexShard.refresh(IndexShard.java:665)
	at org.elasticsearch.index.shard.IndexShard$EngineRefresher$1.run(IndexShard.java:1347)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.lucene.index.CorruptIndexException: misplaced codec footer (file truncated?): remaining=8, expected=16 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/elasticsearch/persistent/logging-es/data/logging-es/nodes/0/indices/project.openshift-template-service-broker.70e2e435-f581-11e7-9b6b-28924a2bfd84.2018.01.13/0/index/_3.cfs") [slice=_3.fdx]))
	at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:411)
	at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:330)
	at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:364)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.<init>(CompressingStoredFieldsReader.java:140)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsReader(CompressingStoredFieldsFormat.java:121)
	at org.apache.lucene.codecs.lucene50.Lucene50StoredFieldsFormat.fieldsReader(Lucene50StoredFieldsFormat.java:173)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:117)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:65)
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:145)
	at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:197)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:99)
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:435)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:286)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:261)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:251)
	at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:104)
	at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:137)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:154)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:669)
	... 5 more
```

Storage is backed by gluster so I'm wondering if its relates to cluster.consistent-metadata being off by default which used to be an issue in the past. I just assumed with gluster being part of the advanced installer and openshift_logging_storage_kind=dynamic the storage wouldn't be an issue. I've tested with ephemeral storage now and no more errors in /elasticsearch/logging-es/logs/logging-es.log or fluentd.

However I can't port-forward to kibana anymore and going via the route still gives the same authorization error, but I'm getting closer.

**Comment by jcantrill** [comment]
Please run [1] so we can get an idea of what your topology looks like.  @pweil-  who from the storage team can chime in here?  I am unaware of logging being supported on gluster

[1] https://github.com/openshift/origin-aggregated-logging/blob/master/hack/logging-dump.sh

**Comment by wdbasson** [comment]
[logging-20180126_133926.tar.gz](https://github.com/openshift/origin/files/1667596/logging-20180126_133926.tar.gz)

Deployed with ephemeral storage.

**Comment by pweil-** [comment]
@openshift/sig-storage
