### ISSUE TITLE
Failed STI build pod marked as succeeded

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#1818]
My registry generated a 500 when receiving the image but the STI pod was marked as a success and no deployment was triggered. Seems the build pod should be marked as Failed?

```
[alice@ose3 beta3]$ osc get pods
POD                   IP        CONTAINER(S)   IMAGE(S)                                                                                HOST                                     LABELS                                                                                           STATUS      CREATED
ruby-sample-build-1             sti-build      docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-sti-builder:v0.4.3.2   ose3.os1.phx2.redhat.com/172.16.156.11   build=ruby-sample-build-1,buildconfig=ruby-sample-build,template=application-template-stibuild   Succeeded   28 minutes
ruby-sample-build-2             sti-build      docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-sti-builder:v0.4.3.2   ose3.os1.phx2.redhat.com/172.16.156.11   build=ruby-sample-build-2,buildconfig=ruby-sample-build,template=application-template-stibuild   Succeeded   19 minutes
```

```
2015-04-20T19:24:18.366396346Z I0420 15:24:18.364338       1 sti.go:235] Successfully built 172.30.17.31:5000/wiring/origin-ruby-sample
2015-04-20T19:24:18.366504703Z I0420 15:24:18.364372       1 sti.go:236] Tagged 4f3b4712ecc3db125d25ce467c89afd8c26f50561fbcffde1013c97c20815f4a as 172.30.17.31:5000/wiring/origin-ruby-sample
2015-04-20T19:24:18.537510751Z I0420 15:24:18.535363       1 cleanup.go:24] Removing temporary directory /tmp/sti356931651
2015-04-20T19:24:18.537572979Z I0420 15:24:18.535406       1 fs.go:99] Removing directory '/tmp/sti356931651'
2015-04-20T19:24:18.542332500Z E0420 15:24:18.540254       1 cfg.go:50] /root/.dockercfg: stat /root/.dockercfg: no such file or directory
2015-04-20T19:24:18.542369814Z I0420 15:24:18.540302       1 sti.go:78] Pushing 172.30.17.31:5000/wiring/origin-ruby-sample image ...
2015-04-20T19:24:22.809771398Z E0420 15:24:22.806521       1 sti.go:80] Failed to push image: Error: Status 500 trying to push repository wiring/origin-ruby-sample: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>\n"
```

**Comment by ncdc** [comment]
I've seen something like this before as well but was caught up in other things and forgot to open an issue :frowning: . Thanks for doing this.

**Comment by sdodson** [comment]
The docker registry 500 stack trace, not worth debugging given the pending move to v2, but i'll post it here encase it's interesting to someone.

```
20/Apr/2015:15:24:22 +0000 ERROR: Exception on /v1/repositories/wiring/origin-ruby-sample/ [PUT]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 277, in wrapper
    return f(namespace=namespace, repository=repository, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 251, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker_registry/index.py", line 98, in put_repository
    update_index_images(namespace, repository, flask.request.data)
  File "/usr/lib/python2.7/site-packages/docker_registry/index.py", line 79, in update_index_images
    value=json.loads(data.decode('utf8')))
  File "/usr/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/lib/python2.7/site-packages/docker_registry/lib/index/db.py", line 93, in _handle_repository_created
    session.commit()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 765, in commit
    self.transaction.commit()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 370, in commit
    self._prepare_impl()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 350, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1903, in flush
    self._flush(objects)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2021, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 57, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1985, in _flush
    flush_context.execute()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 370, in execute
    rec.execute(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 523, in execute
    uow
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
    mapper, table, insert)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 594, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 817, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1108, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 940, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) column name is not unique u'INSERT INTO repository (name, description) VALUES (?, ?)' ('wiring/origin-ruby-sample', '')
10.1.0.1 - - [20/Apr/2015:15:24:22 -0400] "PUT /v1/repositories/wiring/origin-ruby-sample/ HTTP/1.1" 500 291 "-" "docker/1.6.0-rc6 go/go1.3.1 kernel/3.10.0-229.1.2.el7.x86_64 os/linux arch/amd64"
```

**Comment by ncdc** [comment]
That shouldn't happen but there are some race conditions in the v1 registry

**Comment by danmcp** [comment]
Still an issue?

**Comment by danmcp** [comment]
@sdodson We believe this is fixed.  Please reopen if still an issue.

**Comment by bparees** [comment]
was fixed here:
https://github.com/openshift/origin/commit/129f2cb4f3f7cd19686d96350db06774a6896b1e#diff-b9627ec6ab0689e50e5fa3e5d958c1d3
