### ISSUE TITLE
3.7.1 oc cluster up can't run pods

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#18262]
`oc cluster up --version=v3.7.1`
after 5 minutes all container are stuck on containerCreating

```
$ oc version
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
Errors I see:
```
...
E0121 09:02:24.670718   20676 controllers.go:118] Server isn't healthy yet. Waiting a little while.
...
E0121 09:02:25.730358   20676 controllers.go:118] Server isn't healthy yet. Waiting a little while.
...
E0121 09:02:26.709610   20676 controllers.go:118] Server isn't healthy yet. Waiting a little while.
...
I0121 09:02:30.695068   20676 wrap.go:42] GET /healthz: (1.146458ms) 500
goroutine 3378 [running]:
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc42bc96a10, 0x1f4)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc42bc96a10, 0x1f4)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
net/http.Error(0xf2d5180, 0xc42bc96a10, 0xc423620c00, 0x552, 0x1f4)
	/usr/lib/golang/src/net/http/server.go:1954 +0xda
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/healthz.handleRootHealthz.func1(0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:110 +0x3cb
net/http.HandlerFunc.ServeHTTP(0xc42fb17820, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc42fb1f180, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x567
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc429ecb420, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x72
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x5bda3bb, 0xf, 0xc424eee1b0, 0xc429ecb420, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x301
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc42f6faac0, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	<autogenerated>:72 +0x86
github.com/openshift/origin/pkg/cmd/server/origin.namespacingFilter.func1(0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:52 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc42f6e3cb0, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:50 +0x30c
net/http.HandlerFunc.ServeHTTP(0xc42f74f340, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:98 +0x5a0
net/http.HandlerFunc.ServeHTTP(0xc42f74f380, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:47 +0x226a
net/http.HandlerFunc.ServeHTTP(0xc42f74f3c0, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:73 +0x2b0
net/http.HandlerFunc.ServeHTTP(0xc42f65b040, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
net/http.HandlerFunc.ServeHTTP(0xc42f6faae0, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithCORS.func1(0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/cors.go:75 +0x189
net/http.HandlerFunc.ServeHTTP(0xc42f6dd1a0, 0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0xf2d5180, 0xc42bc96a10, 0xc427531500)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x11b
net/http.HandlerFunc.ServeHTTP(0xc42f6fac60, 0x7fed0c9bc638, 0xc425fd7d20, 0xc427531500)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc42f6fac80, 0xf2eca40, 0xc425fd7d20, 0xc427531500, 0xc42427a300)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:106 +0x8d
created by github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originRJxMkg/BUILD/origin-3.7.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x1ca
logging error output: "[+]ping ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/start-apiextensions-informers ok\n[+]poststarthook/start-apiextensions-controllers ok\n[+]poststarthook/quota.openshift.io-clusterquotamapping ok\n[+]poststarthook/project.openshift.io-projectcache ok\n[+]poststarthook/project.openshift.io-projectauthorizationcache ok\n[-]poststarthook/security.openshift.io-bootstrapscc failed: reason withheld\n[-]poststarthook/authorization.openshift.io-ensureSARolesDefault failed: reason withheld\n[-]poststarthook/authorization.openshift.io-ensureopenshift-infra failed: reason withheld\n[-]poststarthook/bootstrap-controller failed: reason withheld\n[-]poststarthook/ca-registration failed: reason withheld\n[+]poststarthook/start-kube-aggregator-informers ok\n[+]poststarthook/apiservice-registration-controller ok\n[+]poststarthook/apiservice-status-available-controller ok\n[+]poststarthook/kube-apiserver-autoregistration ok\n[-]autoregister-completion failed: reason withheld\n[-]poststarthook/template.openshift.io-sharednamespace failed: reason withheld\n[-]poststarthook/authorization.openshift.io-bootstrapclusterroles failed: reason withheld\n[+]poststarthook/openshift.io-AdmissionInit ok\n[+]poststarthook/openshift.io-StartInformers ok\n[-]poststarthook/oauth.openshift.io-EnsureBootstrapOAuthClients failed: reason withheld\nhealthz check failed\n"
 [[openshift/v1.7.6+a08f5eeb62 (linux/amd64) kubernetes/c84beff] 127.0.0.1:32864]
E0121 09:02:30.695558   20676 controllers.go:118] Server isn't healthy yet. Waiting a little while.
...
W0121 09:02:30.697640   20676 network.go:234] Failed to retrieve node info: nodes "localhost" not found
E0121 09:02:31.112752   20676 reflector.go:216] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: Failed to list *api.Endpoints: User "system:node:localhost" cannot list endpoints at the cluster scope: User "system:node:localhost" cannot list all endpoints in the cluster (get endpoints)
...
E0121 09:02:31.239610   20676 kubelet.go:1705] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
E0121 09:02:31.239634   20676 kubelet.go:1713] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /
...
E0121 09:02:31.242433   20676 container_manager_linux.go:543] [ContainerManager]: Fail to get rootfs information unable to find data for container /
...
E0121 09:02:31.449341   20676 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"localhost.150bc7c5a42b59f7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"localhost", UID:"localhost", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"localhost"}, FirstTimestamp:v1.Time{Time:time.Time{sec:63652122151, nsec:217093111, loc:(*time.Location)(0x111f1de0)}}, LastTimestamp:v1.Time{Time:time.Time{sec:63652122151, nsec:217093111, loc:(*time.Location)(0x111f1de0)}}, Count:1, Type:"Normal"}': 'namespaces "default" not found' (will not retry!)
...
E0121 09:02:58.037241   20676 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/secret/d6383911-fe89-11e7-a027-42010a14003a-deployer-token-5v2g5\" (\"d6383911-fe89-11e7-a027-42010a14003a\")" failed. No retries permitted until 2018-01-21 09:03:14.037219434 +0000 UTC (durationBeforeRetry 16s). Error: MountVolume.SetUp failed for volume "deployer-token-5v2g5" (UniqueName: "kubernetes.io/secret/d6383911-fe89-11e7-a027-42010a14003a-deployer-token-5v2g5") pod "router-1-deploy" (UID: "d6383911-fe89-11e7-a027-42010a14003a") : exit status 1
...
E0121 09:04:50.394608   20676 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/secret/d6417841-fe89-11e7-a027-42010a14003a-deployer-token-5v2g5\" (\"d6417841-fe89-11e7-a027-42010a14003a\")" failed. No retries permitted until 2018-01-21 09:06:52.394577031 +0000 UTC (durationBeforeRetry 2m2s). Error: MountVolume.SetUp failed for volume "deployer-token-5v2g5" (UniqueName: "kubernetes.io/secret/d6417841-fe89-11e7-a027-42010a14003a-deployer-token-5v2g5") pod "docker-registry-1-deploy" (UID: "d6417841-fe89-11e7-a027-42010a14003a") : exit status 1
```

Looks like the case is the mount issue again (https://github.com/openshift/origin/issues/17638) but the other errors shouldn't be there as well like /healthz panicking

Full log is here https://travis-ci.org/tnozicka/openshift-acme/jobs/331402532#L2383

/cc @joelsmith

**Comment by tnozicka** [comment]
@mfojtik any chance you recall us fixing panic in /healthz in any of the following releases?

**Comment by php-coder** [comment]
Could it be the same as https://github.com/kubernetes/kubernetes/issues/58348 ? Looks very similar.

**Comment by tnozicka** [comment]
@php-coder I think you are right, thx.

Let's triage the rest:
`W0121 09:02:30.697640   20676 network.go:234] Failed to retrieve node info: nodes "localhost" not found`
_not sure who owns that_

`E0121 09:02:31.112752   20676 reflector.go:216] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: Failed to list *api.Endpoints: User "system:node:localhost" cannot list endpoints at the cluster scope: User "system:node:localhost" cannot list all endpoints in the cluster (get endpoints)`
either bad permissions or we don't wait properly when starting the controllers? @mo @mfojtik 

`E0121 09:02:31.239610   20676 kubelet.go:1705] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /`
@sjenning ?

`E0121 09:02:31.449341   20676 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"localhost.150bc7c5a42b59f7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"localhost", UID:"localhost", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"localhost"}, FirstTimestamp:v1.Time{Time:time.Time{sec:63652122151, nsec:217093111, loc:(*time.Location)(0x111f1de0)}}, LastTimestamp:v1.Time{Time:time.Time{sec:63652122151, nsec:217093111, loc:(*time.Location)(0x111f1de0)}}, Count:1, Type:"Normal"}': 'namespaces "default" not found' (will not retry!)`
@sjenning ?

`E0121 09:02:58.037241   20676 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/secret/d6383911-fe89-11e7-a027-42010a14003a-deployer-token-5v2g5\" (\"d6383911-fe89-11e7-a027-42010a14003a\")" failed. No retries permitted until 2018-01-21 09:03:14.037219434 +0000 UTC (durationBeforeRetry 16s). Error: MountVolume.SetUp failed for volume "deployer-token-5v2g5" (UniqueName: "kubernetes.io/secret/d6383911-fe89-11e7-a027-42010a14003a-deployer-token-5v2g5") pod "router-1-deploy" (UID: "d6383911-fe89-11e7-a027-42010a14003a") : exit status 1`
Likely the fatal issue - looks similar to https://github.com/openshift/origin/issues/17638
@joelsmith

**Comment by tnozicka** [comment]
closing as dupe of https://github.com/openshift/origin/issues/17638 as that seems to be the root cause
