### ISSUE TITLE
oc cluster up broken in 3.9.0

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#18369]
```
$ oc cluster up 
Starting OpenShift using openshift/origin:v3.9.0-alpha.3 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v3.9.0-alpha.3 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... 
   WARNING: Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients.
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
FAIL
   Error: could not start OpenShift container "origin"
   Details:
     Last 10 lines of "origin" container log:
     github.com/openshift/origin/pkg/cmd/server/start.NewCommandStartAllInOne.func1(0xc42029c000, 0xc420ca8900, 0x0, 0x2)
     	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_allinone.go:89 +0x125
     github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc42029c000, 0xc420ca8780, 0x2, 0x2, 0xc42029c000, 0xc420ca8780)
     	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x234
     github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42041b680, 0xc420088008, 0xc42041b680, 0x4)
     	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
     github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42041b680, 0x9, 0xc42041b680)
     	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
     main.main()
     	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:36 +0x24b
```
@openshift/sig-master

**Comment by kargakis** [comment]
Logs from the container
```
I0202 13:41:32.037074   22951 run.go:81] Started etcd at 127.0.0.1:4001
2018-02-02 13:41:32.037326 I | embed: serving client requests on [::]:4001
2018-02-02 13:41:32.051801 I | etcdserver/api/v3rpc: Failed to dial 0.0.0.0:4001: connection error: desc = "transport: remote error: tls: bad certificate"; please retry.
W0202 13:41:32.052430   22951 run_components.go:49] Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients
W0202 13:41:32.052626   22951 server.go:85] Unable to keep dnsmasq up to date, 0.0.0.0:8053 must point to port 53
I0202 13:41:32.052692   22951 logs.go:41] skydns: ready for queries on cluster.local. for tcp4://0.0.0.0:8053 [rcache 0]
I0202 13:41:32.052702   22951 logs.go:41] skydns: ready for queries on cluster.local. for udp4://0.0.0.0:8053 [rcache 0]
I0202 13:41:32.153202   22951 run_components.go:75] DNS listening at 0.0.0.0:8053
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x4144536]

goroutine 1 [running]:
github.com/openshift/origin/pkg/cmd/server/origin.(*MasterConfig).buildHandlerChain.func1(0xef81600, 0xc420c9c480, 0xc420cca700, 0xc420c9c480, 0x51ee3c0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master.go:288 +0x146
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.completedConfig.New.func1(0xef81600, 0xc420c9c480, 0xef81600, 0xc420c9c480)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/config.go:437 +0x45
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.NewAPIServerHandler(0x5773af6, 0x17, 0xef92d80, 0xc420367400, 0xefc01c0, 0xc4218b13e0, 0xc420c9c440, 0x0, 0x0, 0x7f650ba416c8)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/handler.go:103 +0x338
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.completedConfig.New(0xc420cca700, 0x0, 0x0, 0x5773af6, 0x17, 0xefdabe0, 0xc420aecef0, 0x524a560, 0xc421161001, 0xc420c9c420)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/config.go:439 +0x149
github.com/openshift/origin/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.completedConfig.New(0xc420c9c420, 0xc420c9c3a8, 0xefdabe0, 0xc420aecef0, 0x0, 0x0, 0x0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:125 +0x87
github.com/openshift/origin/pkg/cmd/server/origin.createAPIExtensionsServer(0xc420c9c3a0, 0xefdabe0, 0xc420aecef0, 0xc4217d7890, 0xef81280, 0xc4210f5120)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/apiextensions.go:35 +0x5d
github.com/openshift/origin/pkg/cmd/server/origin.(*MasterConfig).withAPIExtensions(0xc420591b00, 0xefdabe0, 0xc420aecef0, 0xc4206d1860, 0xc421211a40, 0xef73440, 0xc4217d7890, 0xef81280, 0xc4210f5120, 0x0, ...)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master.go:109 +0xf9
github.com/openshift/origin/pkg/cmd/server/origin.(*MasterConfig).Run(0xc420591b00, 0xefc6e40, 0xc4212942d0, 0xc4200920c0, 0x34, 0xc420545680)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master.go:220 +0x122
github.com/openshift/origin/pkg/cmd/server/start.StartAPI(0xc420591b00, 0xefc6e40, 0xc4212942d0, 0x1, 0x1)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:571 +0xb2
github.com/openshift/origin/pkg/cmd/server/start.(*Master).Start(0xc420b1a6f0, 0xc420b1a6f0, 0x0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:542 +0x9de
github.com/openshift/origin/pkg/cmd/server/start.MasterOptions.RunMaster(0xc420234c00, 0x1, 0x2da, 0x721, 0x7fff3a7b6e43, 0x40, 0xef7abc0, 0xc42000e018, 0x0, 0x0, ...)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:303 +0x2ef
github.com/openshift/origin/pkg/cmd/server/start.AllInOneOptions.StartAllInOne(0xc4209ba120, 0xc420c90200, 0x2da, 0x721, 0x0, 0x576f0c2, 0x16, 0x7fff3a7b6e92, 0x46, 0x0, ...)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_allinone.go:305 +0x1ea
github.com/openshift/origin/pkg/cmd/server/start.NewCommandStartAllInOne.func1(0xc420086d80, 0xc420f20620, 0x0, 0x2)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_allinone.go:89 +0x125
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420086d80, 0xc420f204a0, 0x2, 0x2, 0xc420086d80, 0xc420f204a0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x234
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420086240, 0xc42000e018, 0xc420086240, 0x4)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420086240, 0x9, 0xc420086240)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:36 +0x24b
```

**Comment by deads2k** [comment]
Pull head and try again. My guess is bad tag.  Eventually, the rolling tag will help.

**Comment by mfojtik** [comment]
I cannot reproduce this with openshift HEAD binary mounted into alpha4. Can you try with alpha4 ?

**Comment by kargakis** [comment]
Yeah, works fine on alpha4
