### ISSUE TITLE
How to resolve the below error?

### ISSUE THREAD

**Issue by reemanaik24** [openshift/origin#18520]
I copied and pasted mapspipeline.yaml and started the pipeline. I got below error in the jenkins.
In progressConsole Output
OpenShift Build hello/openshift-jee-sample-1
[Pipeline] timeout
Timeout set to expire in 20 min
[Pipeline] {
[Pipeline] node
Running on master in /var/lib/jenkins/jobs/hello-openshift-jee-sample/workspace
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Initialize)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] node
Still waiting to schedule task
Jenkins doesn’t have label maven

**Comment by reemanaik24** [comment]
Do we need to configure maven in jenkins??

**Comment by bparees** [comment]
How did you deploy jenkins?  our jenkins image has a slave configuration labeled "maven" out of the box.

**Comment by reemanaik24** [comment]
I deployed it through openshift console.I have shared the screenshot of the same below.

https://user-images.githubusercontent.com/24244859/36012818-c06a131c-0d86-11e8-9d19-2be70adfe254.png

When I am creating pipeline which has maven as the node it throws the below error:
Otherwise it works fine.

Still waiting to schedule task
maven-a6ad246e934d is offline
Running on maven-a6ad246e934d in /tmp/workspace/hello-openshift-jee-sample
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Checkout)
[Pipeline] git
Cloning the remote Git repository
Cloning repository https://github.com/openshift/openshift-jee-sample.git
 > git init /tmp/workspace/hello-openshift-jee-sample # timeout=10
Fetching upstream changes from https://github.com/openshift/openshift-jee-sample.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/openshift/openshift-jee-sample.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/openshift/openshift-jee-sample.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/openshift/openshift-jee-sample.git/': Failed connect to github.com:443; No route to host

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1877)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1596)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:348)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:545)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:748)
	at ......remote call to JNLP4-connect connection from 10.1.0.1/10.1.0.1:52412(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
	at com.sun.proxy.$Proxy102.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1067)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1107)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
in catch block
[Pipeline] echo
Caught: hudson.AbortException
[Pipeline] End of Pipeline
ERROR: null
Finished: FAILURE

**Comment by bparees** [comment]
> hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/openshift/openshift-jee-sample.git +refs/heads/:refs/remotes/origin/" returned status code 128:
stdout:
stderr: fatal: unable to access 'https://github.com/openshift/openshift-jee-sample.git/': Failed connect to github.com:443; No route to host

Well this is different than your original issue so i'm not sure which one we're debugging, but this issue is caused by DNS/networking configuration issues in your cluster.  It sounds like your pods are unable to access remote hosts.  Can you oc rsh into a pod on your cluster and see if you can access github from there?
