### ISSUE TITLE
retried pre-deployment hook doesn't progress deployment

### ISSUE THREAD

**Issue by bparees** [openshift/origin#18618]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18597/test_pull_request_origin_extended_conformance_gce/16232/

As best I can tell, the deployment attempted to run a pre deployment step, that failed(?) then it retried it(?) and it succeeded, but the deployment got stuck anyway:

here's the deployment pod logs:
```
Feb 14 14:16:49.730: INFO: Log for pod "cakephp-mysql-example-1-deploy"/"deployment"
---->
--> pre: Running hook pod ...
--> pre: Retrying hook pod (retry #1)
Generating database schema 'cake schema generate' ...

Welcome to CakePHP v2.9.3 Console
---------------------------------------------------------------
App : app
Path: /opt/app-root/src/app/
---------------------------------------------------------------
Cake Schema Shell
---------------------------------------------------------------
Generating Schema...
Error: Database connection "Mysql" is missing, or could not be created.
#0 /opt/app-root/src/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /opt/app-root/src/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /opt/app-root/src/lib/Cake/Model/CakeSchema.php(201): ConnectionManager::getDataSource('default')
#3 /opt/app-root/src/lib/Cake/Console/Command/SchemaShell.php(148): CakeSchema->read(Array)
#4 /opt/app-root/src/lib/Cake/Console/Shell.php(458): SchemaShell->generate()
#5 /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('generate', Array)
#6 /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /opt/app-root/src/app/Console/cake.php(47): ShellDispatcher::run(Array)
#8 {main}
<----end of log for "cakephp-mysql-example-1-deploy"/"deployment"
```

here's the current pre-deploy pod logs (note that they don't report the same thing as the deployment logs):
```
Feb 14 14:16:50.313: INFO: Log for pod "cakephp-mysql-example-1-hook-pre"/"lifecycle"
---->
Generating database schema 'cake schema generate' ...

Welcome to CakePHP v2.9.3 Console
---------------------------------------------------------------
App : app
Path: /opt/app-root/src/app/
---------------------------------------------------------------
Cake Schema Shell
---------------------------------------------------------------
Generating Schema...
Schema file: schema.php generated
Migrating database 'cake schema create' ...

Welcome to CakePHP v2.9.3 Console
---------------------------------------------------------------
App : app
Path: /opt/app-root/src/app/
---------------------------------------------------------------
Cake Schema Shell
---------------------------------------------------------------
Schema is up to date.
<----end of log for "cakephp-mysql-example-1-hook-pre"/"lifecycle"
```

we also appear to see that the pre-deploy container failed+restarted (presumably the explanation for the discrepancy in the logs above):
```
Events:
  Type     Reason                 Age                From                                        Message
  ----     ------                 ----               ----                                        -------
  Normal   Scheduled              18m                default-scheduler                           Successfully assigned cakephp-mysql-example-1-hook-pre to ci-prtest-5a37c28-16232-ig-n-2msw
  Normal   SuccessfulMountVolume  18m                kubelet, ci-prtest-5a37c28-16232-ig-n-2msw  MountVolume.SetUp succeeded for volume "default-token-bg2t2"
  Normal   Pulling                18m                kubelet, ci-prtest-5a37c28-16232-ig-n-2msw  pulling image "docker-registry.default.svc:5000/extended-test-templates-p68cw-pcq6b/cakephp-mysql-example@sha256:6ee09b310ee65a81aa47b987158cd44ed40d059a217b8e6f19e35e26c2233039"
  Normal   Pulled                 18m                kubelet, ci-prtest-5a37c28-16232-ig-n-2msw  Successfully pulled image "docker-registry.default.svc:5000/extended-test-templates-p68cw-pcq6b/cakephp-mysql-example@sha256:6ee09b310ee65a81aa47b987158cd44ed40d059a217b8e6f19e35e26c2233039"
  Warning  BackOff                18m                kubelet, ci-prtest-5a37c28-16232-ig-n-2msw  Back-off restarting failed container
  Normal   Pulled                 18m (x2 over 18m)  kubelet, ci-prtest-5a37c28-16232-ig-n-2msw  Container image "docker-registry.default.svc:5000/extended-test-templates-p68cw-pcq6b/cakephp-mysql-example@sha256:6ee09b310ee65a81aa47b987158cd44ed40d059a217b8e6f19e35e26c2233039" already present on machine
  Normal   Created                18m (x3 over 18m)  kubelet, ci-prtest-5a37c28-16232-ig-n-2msw  Created container
  Normal   Started                18m (x3 over 18m)  kubelet, ci-prtest-5a37c28-16232-ig-n-2msw  Started container
```

So now even though the pre-deploy (eventually) succeeded, the deployment is stuck forever:

```
 &apps.DeploymentConfig{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cakephp-mysql-example", GenerateName:"", Namespace:"extended-test-templates-p68cw-pcq6b", SelfLink:"/oapi/v1/namespaces/extended-test-templates-p68cw-pcq6b/deploymentconfigs/cakephp-mysql-example", UID:"e5eb0160-118e-11e8-a993-42010a8e0005", ResourceVersion:"16685", Generation:3, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63654213407, loc:(*time.Location)(0x68d27e0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app":"cakephp-mysql-example", "template":"cakephp-mysql-example"}, Annotations:map[string]string{"description":"Defines how to deploy the application server", "template.alpha.openshift.io/wait-for-ready":"true"}, OwnerReferences:[]v1.OwnerReference{v1.OwnerReference{APIVersion:"template.openshift.io/v1", Kind:"TemplateInstance", Name:"templateinstance", UID:"e568104e-118e-11e8-a993-42010a8e0005", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(0xc421a4011c)}}, Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:apps.DeploymentConfigSpec{Strategy:apps.DeploymentStrategy{Type:"Recreate", CustomParams:(*apps.CustomDeploymentStrategyParams)(nil), RecreateParams:(*apps.RecreateDeploymentStrategyParams)(0xc420bcc920), RollingParams:(*apps.RollingDeploymentStrategyParams)(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, Labels:map[string]string(nil), Annotations:map[string]string(nil), ActiveDeadlineSeconds:(*int64)(0xc421a40178)}, MinReadySeconds:0, Triggers:[]apps.DeploymentTriggerPolicy{apps.DeploymentTriggerPolicy{Type:"ImageChange", ImageChangeParams:(*apps.DeploymentTriggerImageChangeParams)(0xc420e1a5a0)}, apps.DeploymentTriggerPolicy{Type:"ConfigChange", ImageChangeParams:(*apps.DeploymentTriggerImageChangeParams)(nil)}}, Replicas:1, RevisionHistoryLimit:(*int32)(nil), Test:false, Paused:false, Selector:map[string]string{"name":"cakephp-mysql-example"}, Template:(*core.PodTemplateSpec)(0xc420441200)}, Status:apps.DeploymentConfigStatus{LatestVersion:1, ObservedGeneration:3, Replicas:0, UpdatedReplicas:0, AvailableReplicas:0, UnavailableReplicas:0, Details:(*apps.DeploymentDetails)(0xc421592660), Conditions:[]apps.DeploymentCondition{apps.DeploymentCondition{Type:"Available", Status:"False", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63654213407, loc:(*time.Location)(0x68d27e0)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63654213407, loc:(*time.Location)(0x68d27e0)}}, Reason:"", Message:"Deployment config does not have minimum availability."}, apps.DeploymentCondition{Type:"Progressing", Status:"Unknown", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63654213469, loc:(*time.Location)(0x68d27e0)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63654213469, loc:(*time.Location)(0x68d27e0)}}, Reason:"", Message:"replication controller \"cakephp-mysql-example-1\" is waiting for pod \"cakephp-mysql-example-1-deploy\" to run"}}, ReadyReplicas:0}}
```

Specifically:
"Message:"replication controller \"cakephp-mysql-example-1\" is waiting for pod \"cakephp-mysql-example-1-deploy\" to run"}}"

(this also causes a test flake since we never get the deployment success we expect).

/cc @jim-minter since the flake is in the template readiness test.

A workaround is probably to make the cakephp pre-deploy step more resilient to the mysql DB not being available yet (i presume that is what happened here, though i'm not sure) but the current behavior makes it pretty confusing to an end user who sees their pre-deploy pod looks like it succeeded, yet the deployment just gets stuck(?)

**Comment by crazytaxii** [comment]
Was the problem solved later? I came across it too.
