### ISSUE TITLE
'osc login' fails with panic runtime error

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#1896]
**version**
openshift v0.4.4-9-g09f87e4
kubernetes v0.14.1-582-gb12d75d
"gitCommit": "b12d75d"

Log in as another user and inherit env vars from root / existing user (notice I did `su sspeiche` and not `su - sspeiche`).  It doesn't matter what I enter for a server location, taking the default causes the issue as does manually entering one

**stack trace**
```
$ su sspeiche
$ osc login
OpenShift server [https://localhost:8443]: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x4a5fe7]

goroutine 16 [running]:
runtime.panic(0x16a51e0, 0x2f67833)
	/usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
github.com/openshift/origin/pkg/cmd/cli/cmd.(*LoginOptions).getClientConfig(0xc2082a6270, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/loginoptions.go:71 +0x7f7
github.com/openshift/origin/pkg/cmd/cli/cmd.(*LoginOptions).gatherAuthInfo(0xc2082a6270, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/loginoptions.go:146 +0x4d
github.com/openshift/origin/pkg/cmd/cli/cmd.(*LoginOptions).GatherInfo(0xc2082a6270, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/loginoptions.go:31 +0x39
github.com/openshift/origin/pkg/cmd/cli/cmd.RunLogin(0xc2080889a0, 0xc2082a6270, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/login.go:179 +0x4a
github.com/openshift/origin/pkg/cmd/cli/cmd.func·005(0xc2080889a0, 0x3411cb0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/login.go:84 +0x190
github.com/spf13/cobra.(*Command).execute(0xc2080889a0, 0x3411cb0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:442 +0x352
github.com/spf13/cobra.(*Command).Execute(0xc208089600, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:507 +0x491
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:17 +0x13a

goroutine 19 [finalizer wait]:
runtime.park(0x414570, 0x340d778, 0x2f72da9)
	/usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x340d778, 0x2f72da9)
	/usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/lib/golang/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x3414e00)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x75
created by github.com/golang/glog.init·1
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2b2

goroutine 17 [syscall]:
runtime.goexit()
	/usr/lib/golang/src/pkg/runtime/proc.c:1445
[sspeiche@boot2docker openshift]$ osc login
OpenShift server [https://localhost:8443]: https://localhost:8443
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x4a5fe7]

goroutine 16 [running]:
runtime.panic(0x16a51e0, 0x2f67833)
	/usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
github.com/openshift/origin/pkg/cmd/cli/cmd.(*LoginOptions).getClientConfig(0xc2082871e0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/loginoptions.go:71 +0x7f7
github.com/openshift/origin/pkg/cmd/cli/cmd.(*LoginOptions).gatherAuthInfo(0xc2082871e0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/loginoptions.go:146 +0x4d
github.com/openshift/origin/pkg/cmd/cli/cmd.(*LoginOptions).GatherInfo(0xc2082871e0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/loginoptions.go:31 +0x39
github.com/openshift/origin/pkg/cmd/cli/cmd.RunLogin(0xc208054dc0, 0xc2082871e0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/login.go:179 +0x4a
github.com/openshift/origin/pkg/cmd/cli/cmd.func·005(0xc208054dc0, 0x3411cb0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/login.go:84 +0x190
github.com/spf13/cobra.(*Command).execute(0xc208054dc0, 0x3411cb0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:442 +0x352
github.com/spf13/cobra.(*Command).Execute(0xc208054c60, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:507 +0x491
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:17 +0x13a
```

**Comment by smarterclayton** [comment]
@deads2k  or @fabianofranz

**Comment by deads2k** [comment]
I think this was fixed by https://github.com/openshift/origin/commit/3d71ebb0e6059089df91d2b1098009fbdf739390
