### ISSUE TITLE
API server logs from oc cluster up contain stack dumps

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#19156]
Why do we contain stack dumps?

```
W0330 02:38:53.140032       1 admission.go:66] PersistentVolumeLabel admission controller is deprecated. Please remove this controller from your configuration files and scripts.
I0330 02:38:53.355440       1 master_config.go:355] Will report 10.0.2.15 as public IP address.
I0330 02:38:53.359556       1 server.go:54] Starting master on 0.0.0.0:8445 (v1.9.1+a0ce1bc657)
I0330 02:38:53.359592       1 server.go:55] Public master address is https://10.1.2.2:8443
I0330 02:38:53.359603       1 server.go:59] Using images from "openshift/origin-<component>:v3.10"
I0330 02:38:54.049625       1 openshift_apiserver.go:578] Started Origin API at /oapi/v1
E0330 02:38:54.624338       1 pathrecorder.go:107] registered "/swagger.json" from goroutine 1 [running]:
runtime/debug.Stack(0x4566ae0, 0xc42328b980, 0xc4210dcdd0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc4227380e0, 0xc4210dcdd0, 0xd)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:109 +0x88
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).Handle(0xc4227380e0, 0xc4210dcdd0, 0xd, 0xe4cb400, 0xc4228da060)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:173 +0x89
github.com/openshift/origin/vendor/k8s.io/kube-openapi/pkg/handler.RegisterOpenAPIService(0xc423583300, 0x4edb5ca, 0xd, 0xe4be340, 0xc4227380e0, 0x0, 0x0, 0xc423b0b320)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kube-openapi/pkg/handler/handler.go:120 +0x2bd
github.com/openshift/origin/vendor/k8s.io/kube-openapi/pkg/handler.BuildAndRegisterOpenAPIService(0x4edb5ca, 0xd, 0xc423b0b320, 0x4, 0x4, 0xc42051e750, 0xe4be340, 0xc4227380e0, 0x3674c10, 0xc4210ed480, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kube-openapi/pkg/handler/handler.go:87 +0xbe
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/routes.OpenAPI.Install(0xc42051e750, 0xc422e5c7e0, 0xc4227380e0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/routes/openapi.go:35 +0x8c
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc42217e420, 0xc421047e08)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:280 +0x7a
github.com/openshift/origin/pkg/cmd/server/origin.(*MasterConfig).withOpenshiftAPI(0xc420f96900, 0xe51bfc0, 0xc4210ec950, 0xc4205fcaa0, 0xc4209cf4a0, 0xe4bdc80, 0xc42159e630, 0xe4c9f80, 0xc4215af000, 0x0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master.go:134 +0x152
github.com/openshift/origin/pkg/cmd/server/origin.(*MasterConfig).RunOpenShift(0xc420f96900, 0xc4200c4000, 0xc421511888, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master.go:339 +0x11a
github.com/openshift/origin/pkg/cmd/openshift-apiserver.RunOpenShiftAPIServer(0xc420779080, 0x25, 0xc420779080)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/openshift-apiserver/server.go:61 +0x7b6
github.com/openshift/origin/pkg/cmd/openshift-apiserver.(*OpenShiftAPIServer).RunAPIServer(0xc421233440, 0x366e53c, 0x4eec58e)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/openshift-apiserver/cmd.go:92 +0x68
github.com/openshift/origin/pkg/cmd/openshift-apiserver.(*OpenShiftAPIServer).StartAPIServer(0xc421233440, 0x0, 0x554e31)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/openshift-apiserver/cmd.go:77 +0x2b
github.com/openshift/origin/pkg/cmd/openshift-apiserver.NewOpenShiftAPIServerCommand.func1(0xc42017d200, 0xc421233720, 0x0, 0x2)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/openshift-apiserver/cmd.go:43 +0x9a
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc42017d200, 0xc421233600, 0x2, 0x2, 0xc42017d200, 0xc421233600)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x234
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42017cb40, 0xe76f8d0, 0xc42017d8c0, 0xc42017d440)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42017cb40, 0x6, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/hypershift/main.go:40 +0x25c
E0330 02:38:54.624755       1 pathrecorder.go:107] registered "/swagger-2.0.0.json" from goroutine 1 [running]:
```

**Comment by deads2k** [comment]
> Why do we contain stack dumps?

Looks like multiple registrations for openapi.  Gift that just keeps giving.
