### ISSUE TITLE
Use 'hack/env hack/build-local-images.py' meet a mistake !!!

### ISSUE THREAD

**Issue by cucushift** [openshift/origin#19268]
when i use cmd `hack/env hack/build-base-images.sh`& `hack/env make release` is  fine, but `hack/env make release` cause a panic. i use the latest origin repo.
```
[root@qe-balabala origin]# hack/env hack/build-local-images.py
Traceback (most recent call last):
  File "hack/build-local-images.py", line 257, in <module>
    call(["docker", "build", "-t", full_name(image), "."], cwd=context_dir)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
[INFO] Building origin...
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[ERROR] [03:18:36-0400] PID 12667: hack/lib/build/environment.sh:172: `return "${exitcode}"` exited with status 1.
[INFO] [03:18:36-0400] 		Stack Trace: 
[INFO] [03:18:36-0400] 		  1: hack/lib/build/environment.sh:172: `return "${exitcode}"`
[INFO] [03:18:36-0400] 		  2: hack/lib/build/environment.sh:281: os::build::environment::withsource
[INFO] [03:18:36-0400] 		  3: hack/env:42: os::build::environment::run
[INFO] [03:18:36-0400]   Exiting with code 1.
```

**Comment by soltysh** [comment]
@cucushift base images are a pre-requisite for `make release`, see [here](https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#building-origin-binaries-rpms-and-images). 
The `hack/build-local-images.py`serves a different purpose described [here](https://github.com/openshift/origin/blob/master/HACKING.md#building-individual-images), and for that you need to have the binaries available locally (thus the error you're seeing).

**Comment by cucushift** [comment]
@soltysh thx.
