### ISSUE TITLE
diagnotics comamnd causes panic by missing error catch

### ISSUE THREAD

**Issue by nak3** [openshift/origin#19573]
##### Description

diagnotics comamnd causes panic by missing error catch. Please refer to reproduce steps below.

##### Version

Build by 26d7dd21707a165ed4a87edfd3e0dca525480943

##### Steps To Reproduce
1. Use invalid KUBECONFIG (e.g - pointing to wrong server URL or logout from the server) and run `oc adm diagnostics`

##### Current Result

~~~
ERROR: [CED7001 from controller openshift/origin/pkg/oc/admin/diagnostics/util/util.go]
       While running the ConfigContexts[local] diagnostic, a panic was encountered.
       This is a bug in diagnostics. Error and stack trace follow: 
       runtime error: invalid memory address or nil pointer dereference
       goroutine 1 [running]:
       runtime/debug.Stack(0x4b07df5, 0x2, 0xc42148f0b8)
       	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
       github.com/openshift/origin/pkg/oc/admin/diagnostics/util.RunDiagnostics.func1.1(0xc42124c000, 0xc42148fae0)
       	/home/knakayam/dev/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/admin/diagnostics/util/util.go:45 +0x100
       panic(0x41d5020, 0x7922610)
       	/usr/local/go/src/runtime/panic.go:502 +0x229
       github.com/openshift/origin/pkg/oc/admin/diagnostics/diagnostics/client.ConfigContext.Check(0xc421251020, 0xc420021fd0, 0x5, 0xc42028c880, 0x76)
       	/home/knakayam/dev/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/admin/diagnostics/diagnostics/client/config_contexts.go:268 +0x5c9
       github.com/openshift/origin/pkg/oc/admin/diagnostics/util.RunDiagnostics.func1(0xc42124c000, 0xc42148fae0, 0xc42148fac8)
       	/home/knakayam/dev/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/admin/diagnostics/util/util.go:60 +0x219
       github.com/openshift/origin/pkg/oc/admin/diagnostics/util.RunDiagnostics(0xc42124c000, 0xc421273320, 0x3, 0x3, 0x0, 0x0)
       	/home/knakayam/dev/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/admin/diagnostics/util/util.go:64 +0x78
       github.com/openshift/origin/pkg/oc/admin/diagnostics.DiagnosticsOptions.RunDiagnostics(0xc420a953b0, 0xc420a95410, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420e90f00, 0xc420a95830, ...)
       	/home/knakayam/dev/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/admin/diagnostics/diagnostics.go:303 +0xb9
       github.com/openshift/origin/pkg/oc/admin/diagnostics/util.CommandRunFunc.func1(0xc420ea4500, 0x7d22950, 0x0, 0x0)
       	/home/knakayam/dev/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/admin/diagnostics/util/util.go:84 +0xab
       github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420ea4500, 0x7d22950, 0x0, 0x0, 0xc420ea4500, 0x7d22950)
       	/home/knakayam/dev/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
       github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420c1cc80, 0x1ba1fa1, 0xc4203020c0, 0xc420c1cc80)
       	/home/knakayam/dev/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:843 +0x30a
       github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420c1cc80, 0x2, 0xc420c1cc80)
       	/home/knakayam/dev/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:791 +0x2b
       main.main()
       	/home/knakayam/dev/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:41 +0x293
~~~

##### Expected Result

- Catching the error as:

~~~
ERROR: [DCli0013 from diagnostic ConfigContexts@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/client/config_contexts.go:299]
       For client config context 'demo1/api-ded-stage-aws-openshift-com:443/knakayam@redhat.com':
       The server URL is 'https://api.ded-stage-aws.openshift.com:443'
       The user authentication is 'knakayam@redhat.com/api-ded-stage-aws-openshift-com:443'
       The current project is 'demo1'
       (*errors.StatusError) User "system:anonymous" cannot list projects.project.openshift.io at the cluster scope: User "system:anonymous" cannot list all projects.project.openshift.io in the cluster (get projects.project.openshift.io)

       This means that when we tried to make a request to the master API
       server, your kubeconfig did not present valid credentials to
       authenticate your client. Credentials generally consist of a client
       key/certificate or an access token. Your kubeconfig may not have
       presented any, or they may be invalid.
~~~

##### Additional Information
- Proposed fix: https://github.com/openshift/origin/pull/19574

**Comment by nak3** [comment]
This issue was introduced by this commit https://github.com/openshift/origin/commit/52649452cfa326e0d1930f66233b5313f66d656a

**Comment by jwforres** [comment]
@deads2k im assigning you since the commit referenced above was authored by you
