### ISSUE TITLE
`panic: runtime error: invalid memory address` when adding instant app

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#1988]
I have a simple environment running.

I have added a template for mongo where I was inserting some definitions for image streams.  The template loads fine.

As another user, I log onto the application and issue `osc new-project proj1`
From the web console, I select "Create +" -> "Instants apps -> Browse all templates" -> select "Mongo" and then "Create", then crash.

"gitCommit": "b12d75d"
openshift v0.4.4-108-g054bcbc
kubernetes v0.14.1-582-gb12d75d

full log and template at https://gist.github.com/sspeiche/0dd31d66320f38d01981

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x64d0a3]

goroutine 4824 [running]:
runtime.panic(0x16d4400, 0x392cf13)
        /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
github.com/GoogleCloudPlatform/kubernetes/pkg/api/meta.(*genericAccessor).SetLabels(0xc20933a550, 0xc20a413b90)
        <autogenerated>:16 +0xa3
github.com/openshift/origin/pkg/util.AddObjectLabels(0x7f2ab930d1c8, 0xc20a516000, 0xc20a412cc0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/util/labels.go:94 +0x2cd
github.com/openshift/origin/pkg/util.AddConfigLabels(0xc20a517f80, 0xc20a412cc0, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/util/labels.go:113 +0x169
github.com/openshift/origin/pkg/template/registry.(*REST).Create(0xc20845d0e1, 0x7f2ab9339de8, 0xc20a04ca20, 0x7f2ab930dd30, 0xc20c3cc960, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/template/registry/rest.go:115 +0x64c
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·022(0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:217 +0x8e
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·030()
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:487 +0x37
created by github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.finishRequest
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:492 +0x156

goroutine 16 [select (no cases), 9 minutes]:
github.com/openshift/origin/pkg/cmd/server/start.AllInOneOptions.StartAllInOne(0xc2080fe1e0, 0xc208196580, 0x1, 0x0, 0x1981f50, 0x16, 0x184e5c0, 0x0, 0x184e5c0, 0x0, ...)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_allinone.go:237 +0x227
github.com/openshift/origin/pkg/cmd/server/start.func·001(0xc208097080, 0xc2082c7700, 0x0, 0x2)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_allinone.go:79 +0x2b6
github.com/spf13/cobra.(*Command).execute(0xc208097080, 0xc2082c75e0, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:447 +0x352
github.com/spf13/cobra.(*Command).Execute(0xc208096dc0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:512 +0x491
main.main()
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:17 +0x13a

goroutine 19 [finalizer wait, 9 minutes]:
runtime.park(0x414570, 0x428c238, 0x39484e9)
        /usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x428c238, 0x39484e9)
        /usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 10 minutes]:
os/signal.loop()
        /usr/lib/golang/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/lib/golang/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x4293920)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x75
created by github.com/golang/glog.init·1
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2b2

goroutine 17 [syscall, 10 minutes]:
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 45 [select]:
github.com/coreos/etcd/raft.(*node).run(0xc2082369b0, 0xc2080ef8c0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/raft/node.go:265 +0xccf
created by github.com/coreos/etcd/raft.StartNode
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/raft/node.go:168 +0x4a9

goroutine 46 [chan receive, 9 minutes]:
github.com/coreos/etcd/pkg/osutil.func·001()
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:53 +0x64
created by github.com/coreos/etcd/pkg/osutil.HandleInterrupts
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:74 +0x147

goroutine 47 [select]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc20839a300)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/server.go:358 +0x1138
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/server.go:298 +0x1d2
```
(Continues for about 11k lines)

**Comment by smarterclayton** [comment]
This is fixed in https://github.com/openshift/origin/pull/1979
