### ISSUE TITLE
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher panic

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#20136]
See in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20033/pull-ci-origin-unit/542/ and others.

```
▼
panic: Fail in goroutine after  has completed4 §
panic: Fail in goroutine after  has completed

▼
goroutine 68 [running]:§
goroutine 68 [running]:
testing.(*common).Fail(0xc420184000)
	/usr/local/go/src/testing/testing.go:502 +0x1bd
testing.(*common).Fail(0xc4201840f0)
	/usr/local/go/src/testing/testing.go:496 +0x109
testing.(*common).FailNow(0xc4201840f0)
	/usr/local/go/src/testing/testing.go:522 +0x39
testing.(*common).Fatalf(0xc4201840f0, 0xbff93f, 0x2c, 0x0, 0x0, 0x0)
	/usr/local/go/src/testing/testing.go:588 +0x95
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.TestExamplePlugin.func1.1(0xc420416180, 0xc4201840f0)
	/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go:127 +0x149
created by github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.TestExamplePlugin.func1
	/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go:122 +0x9ad
```

/assign @sjenning 

This one is fairly common

**Comment by sjenning** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go#L127

**Comment by vikaschoudhary16** [comment]
@sjenning issue causing code has got changed in this PR which merged recently, https://github.com/kubernetes/kubernetes/pull/64660/files

Should we cherry-pick this origin?

**Comment by deads2k** [comment]
This is failing better than 1/10 jobs.  Bumping priority.

**Comment by vikaschoudhary16** [comment]
Fix merged!
