### ISSUE TITLE
vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher flake

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#20147]
seen frequently after the 1.11 rebase: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20145/pull-ci-origin-unit/573/?log#log

```
panic: Fail in goroutine after  has completed

goroutine 25 [running]:
testing.(*common).Fail(0xc4201a2000)
	/usr/local/go/src/testing/testing.go:502 +0x1bd
testing.(*common).Fail(0xc4201a20f0)
	/usr/local/go/src/testing/testing.go:496 +0x109
testing.(*common).FailNow(0xc4201a20f0)
	/usr/local/go/src/testing/testing.go:522 +0x39
testing.(*common).Fatalf(0xc4201a20f0, 0xbff93f, 0x2c, 0x0, 0x0, 0x0)
	/usr/local/go/src/testing/testing.go:588 +0x95
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.TestExamplePlugin.func1.1(0xc420080780, 0xc4201a20f0)
	/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go:127 +0x149
created by github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.TestExamplePlugin.func1
	/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go:122 +0x9ad
FAIL	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher	1.061s
```

/assign @sjenning  @vikaschoudhary16

**Comment by sjenning** [comment]
@deads2k already has an issue for this and @vikaschoudhary16 is working on it
https://github.com/openshift/origin/issues/20136
