### ISSUE TITLE
`oc process` panics on --local=true

### ISSUE THREAD

**Issue by surajssd** [openshift/origin#20303]
$sub. But when run without flag it works fine.

##### Version

```console
$ oc version
oc v3.10.0-rc.0+c20e215
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.122.1:8443
openshift v3.10.0-rc.0+e132a20-38
kubernetes v1.10.0+b81c8f8
```

##### Steps To Reproduce

Start openshift server, I did it using `oc cluster up`.

```console
$ oc process mysql-persistent --local=true -n openshift -o yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1ffabd0]                                                                                                                
               
goroutine 1 [running]:
github.com/openshift/origin/pkg/oc/cli/cmd.RunProcess(0xc420a1a480, 0x44335c0, 0xc42009c000, 0x4433600, 0xc42009c008, 0x4433600, 0xc42009c010, 0xc420f38f00, 0xc420c8e600, 0x1, ...)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/cmd/process.go:221 +0xb30
github.com/openshift/origin/pkg/oc/cli/cmd.NewCmdProcess.func1(0xc420f38f00, 0xc420c8e600, 0x1, 0x6)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/cmd/process.go:86 +0x95
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420f38f00, 0xc420c8e540, 0x6, 0x6, 0xc420f38f00, 0xc420c8e540)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42036cf00, 0xc42009c010, 0xc42036cf00, 0xc4202b6ed0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:843 +0x334
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42036cf00, 0x2, 0xc42036cf00)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()                                 
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:42 +0x334
```

##### Current Result

It panics.

##### Expected Result

Should mention what is wrong or should display the output of process.

**Comment by juanvallejo** [comment]
Will be fixed as part of https://github.com/openshift/origin/pull/20282
