### ISSUE TITLE
forbidden because system:anonymous cannot get on /osapi/

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#2123]
I'm running ose 0.5 as binary (openshift-origin-v0.5-cecef65-linux-amd64) on a fedora 21 machine but when I try to access the /osapi api (https://192.168.1.85:8443/osapi/v1beta3/namespaces/default/),  I get a HTTP error 403 
with this message

````
{
kind: "Status",
apiVersion: "v1beta3",
metadata: { },
status: "Failure",
message: ""/osapi/v1beta3/namespaces/default/" is forbidden because system:anonymous cannot get on namespaces with name "default" in default",
reason: "Forbidden",
details: { },
code: 403
}
````

The console of openshift also reports these related errors : 

`````
sudo ./openshift start
I0507 18:41:07.873996   29932 start_allinone.go:219] Starting an OpenShift all-in-one
I0507 18:41:10.787941   29932 start_master.go:296] Starting an OpenShift master, reachable at 0.0.0.0:8443 (etcd: [https://192.168.1.85:4001])
I0507 18:41:10.787967   29932 start_master.go:297] OpenShift master public address is https://192.168.1.85:8443
2015/05/07 18:41:11 etcdserver: datadir is valid for the 2.0.1 format
2015/05/07 18:41:11 etcdserver: recovered store from snapshot at index 10001
2015/05/07 18:41:11 etcdserver: name = openshift.local
2015/05/07 18:41:11 etcdserver: data dir = openshift.local.etcd
2015/05/07 18:41:11 etcdserver: member dir = openshift.local.etcd/member
2015/05/07 18:41:11 etcdserver: heartbeat = 100ms
2015/05/07 18:41:11 etcdserver: election = 1000ms
2015/05/07 18:41:11 etcdserver: snapshot count = 0
2015/05/07 18:41:11 etcdserver: advertise client URLs = https://192.168.1.85:4001
2015/05/07 18:41:11 etcdserver: loaded cluster information from store: openshift.local=https://192.168.1.85:7001
2015/05/07 18:41:11 etcdserver: restart member 61e27b62ba48fbca in cluster 59bc73b01eb39f22 at commit index 19202
2015/05/07 18:41:11 raft: 61e27b62ba48fbca became follower at term 8
2015/05/07 18:41:11 raft: newRaft 61e27b62ba48fbca [peers: [61e27b62ba48fbca], term: 8, commit: 19202, applied: 10001, lastindex: 19202, lastterm: 8]
2015/05/07 18:41:11 etcdserver: set snapshot count to default 10000
I0507 18:41:11.277448   29932 etcd.go:65] Started etcd at 192.168.1.85:4001
E0507 18:41:11.793704   29932 reflector.go:119] Failed to list *api.Namespace: Get https://192.168.1.85:8443/api/v1beta3/namespaces: dial tcp 192.168.1.85:8443: connection refused
I0507 18:41:11.948913   29932 start_master.go:342] Static Nodes: [localhost.localdomain]
E0507 18:41:12.099236   29932 reflector.go:119] Failed to list *api.Namespace: Get https://192.168.1.85:8443/api/v1beta3/namespaces: dial tcp 192.168.1.85:8443: connection refused
E0507 18:41:12.099236   29932 reflector.go:119] Failed to list *api.Namespace: Get https://192.168.1.85:8443/api/v1beta3/namespaces: dial tcp 192.168.1.85:8443: connection refused
E0507 18:41:12.099338   29932 reflector.go:119] Failed to list *api.ResourceQuota: Get https://192.168.1.85:8443/api/v1beta3/resourcequotas: dial tcp 192.168.1.85:8443: connection refused
E0507 18:41:12.099368   29932 reflector.go:119] Failed to list *api.LimitRange: Get https://192.168.1.85:8443/api/v1beta3/limitranges: dial tcp 192.168.1.85:8443: connection refused
````

192.168.1.85 is the IP address exposed by the em1 interface on that machine 

```
em1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.85  netmask 255.255.255.0  broadcast 192.168.1.255
```

**Comment by smarterclayton** [comment]
The errors in the console should be unrelated - startup races.

Are you trying to curl the API?  Did you make any changes to the default policy?

**Comment by liggitt** [comment]
Any non-api URL returns a forbidden error unless whitelisted... I don't think there is anything at `/osapi`, so even if we whitelisted it, you'd get a 404 instead.

**Comment by liggitt** [comment]
Oops, nevermind... I should read more than the issue title before commenting :)

**Comment by liggitt** [comment]
The message is accurate... the anonymous user isn't allowed to see that namespace. The question is why the auth layer thinks you are anonymous... how are you making the request?

**Comment by cmoulliard** [comment]
The fabric8 project has developed a maven plugin using the Kubernetes API and this is when the maven plugin is launched that we call the API and get it 

````
[INFO] Generated Kubernetes JSON resources:
[INFO]     Service app-library selector: {provider=fabric8, component=AppLibrary} ports: 80, 8778
[INFO]     ReplicationController app-library-controller replicas: 1, image: fabric8/app-library:2.2-SNAPSHOT
[INFO] Attaching kubernetes json file: /home/dabou/Temp/openshift-v3/quickstarts/app-groups/cdelivery/target/classes/kubernetes.json to the build
[INFO]
[INFO] --- fabric8-maven-plugin:2.2-SNAPSHOT:apply (default-cli) @ cdelivery ---
[INFO] Using kubernetes at: https://localhost:8443 in namespace default
[INFO] Kubernetes JSON: /home/dabou/Temp/openshift-v3/quickstarts/app-groups/cdelivery/target/classes/kubernetes.json
[WARNING] Could not load routes; we maybe are not connected to an OpenShift environment? javax.ws.rs.WebApplicationException: HTTP 403 "/osapi/v1beta3/namespaces/default/routes" is forbidden because system:anonymous cannot list on routes in default
javax.ws.rs.WebApplicationException: HTTP 403 "/osapi/v1beta3/namespaces/default/routes" is forbidden because system:anonymous cannot list on routes in default
	at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:25)
	at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:16)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:302)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:725)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:683)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
	at com.sun.proxy.$Proxy49.getRoutes(Unknown Source)
	at io.fabric8.kubernetes.api.KubernetesClient.getRoutes(KubernetesClient.java:476)
````

**Comment by smarterclayton** [comment]
Looks like the client is not applying credentials to the request.  I'm not sure how the plugin initializes its credentials, but by default you'll need them to talk to a server (or disable authorization on all resources).

**Comment by cmoulliard** [comment]
Problem solved after providing as parameters the cert & key

**Comment by Yashu5** [comment]
Hi I am also facing the same issue , can u please help how u resolved it or how to provide authentication(cert & key) to access the api._

**Comment by liggitt** [comment]
Are you trying to access the API from within a pod, as a logged in user, or as a cluster admin with access to the generated admin certificates?

**Comment by Yashu5** [comment]
Hi , I am accessing it inside the origin container after using 'oc login' , I can access web console but not the other APIs.

**Comment by liggitt** [comment]
Are you trying to access the API using a web browser or the command line?

**Comment by Yashu5** [comment]
From both it gives same response 403

**Comment by liggitt** [comment]
You need to send an OAuth token to the API to authenticate. When you log into the web console, the UI manages the OAuth token for you... you can't visit the API directly in the browser.

In the CLI, when you do `oc login`, it requests a token for you as well. You can see the token by running this, and loking for the "token" data
```
oc config view --flatten
```

You can use that token directly against the API as a bearer token:
```
curl https://localhost:8443/oapi/v1/... -H "Authorization: Bearer <token data here>"
```

**Comment by smarterclayton** [comment]
Which reminds me that we want a one liner command we can show to people to get the current token easily.

**Comment by liggitt** [comment]
https://github.com/openshift/origin/issues/3048

**Comment by liggitt** [comment]
```
token=$(oc config view --flatten -o template -t '{{with index .users 0}}{{.user.token}}{{end}}')
echo $token
```

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/pull/3055 adds `oc whoami -t`

----- Original Message -----

**Comment by mjangid** [comment]
Hi @liggitt I am trying same thing but still I am getting 403
I am trying this in ReST client Postman

URL
https://system1.myserver.com/oapi/v1/projects

Header
Authorization: "Bearer qb-xD60xWAf-QIiz5Zour24-H5Mh5Jzb9ISb2ThA3VM"

Response 403
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot list all projects in the cluster",
  "reason": "Forbidden",
  "details": {
    "kind": "projects"
  },
  "code": 403
} 



I got the token by this command 
> oc whoami --token

**Comment by liggitt** [comment]
your authorization header should not have a leading quote

**Comment by mjangid** [comment]
Hi @liggitt I tried with and without quote also

**Comment by abhishekvats007** [comment]
HI @liggitt  I tried with and without quote, its same issue
