### ISSUE TITLE
v3.11 oc cluster up fails on travis-ci (Ubuntu)

### ISSUE THREAD

**Issue by crobby** [openshift/origin#21260]
oc cluster up is failing on travis-ci for version v3.11 (Error message:  panic: assignment to entry in nil map --- full trace below).
The same job succeeds for version v3.10

##### Version
oc v3.11.0-alpha.0+1ff2229-9
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Set up Travis-ci job (.travis.yml) that contains an "oc cluster up" using v3.11
2. Note that the cluster doesn't come up as expected.

##### Current Result
v3.11: Pulling from openshift/origin
7dc0dca2b151: Pulling fs layer
89297ec2ab9b: Pulling fs layer
b0ad566301c1: Pulling fs layer
34795a676aa3: Pulling fs layer
dc2ca306d9f0: Pulling fs layer
34795a676aa3: Waiting
dc2ca306d9f0: Waiting
89297ec2ab9b: Verifying Checksum
89297ec2ab9b: Download complete
b0ad566301c1: Verifying Checksum
b0ad566301c1: Download complete
34795a676aa3: Verifying Checksum
34795a676aa3: Download complete
7dc0dca2b151: Verifying Checksum
7dc0dca2b151: Download complete
dc2ca306d9f0: Verifying Checksum
dc2ca306d9f0: Download complete
7dc0dca2b151: Pull complete
89297ec2ab9b: Pull complete
b0ad566301c1: Pull complete
34795a676aa3: Pull complete
dc2ca306d9f0: Pull complete
Digest: sha256:f99c544eff0c28d12593ebafd4cbf039a83b95cf2aa89d40c236caffbaf0c250
Status: Downloaded newer image for openshift/origin:v3.11
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Pulling image openshift/origin-control-plane:v3.11
Pulled 2/5 layers, 42% complete
Pulled 3/5 layers, 74% complete
Pulled 4/5 layers, 82% complete
Pulled 5/5 layers, 100% complete
Extracting
Image pull complete
Pulling image openshift/origin-cli:v3.11
Image pull complete
Pulling image openshift/origin-node:v3.11
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Creating shared mount directory on the remote host ...
Determining server IP ...
Using public hostname IP 10.20.1.126 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I1015 20:05:35.474303    6441 config.go:42] Running "create-master-config"
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/openshift/origin/pkg/oc/clusterup/coreinstall/kubeapiserver.KubeAPIServerStartConfig.MakeMasterConfig(0xc420fb9fb0, 0x24, 0xc420fbd5c0, 0x6, 0x6, 0x4758f60, 0xc42042e120, 0xc420028dc0, 0x41, 0x0, ...)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/coreinstall/kubeapiserver/config.go:91 +0xbea
github.com/openshift/origin/pkg/oc/clusterup.(*ClusterUpConfig).makeMasterConfig(0xc420b44a00, 0xc4210dc1b0, 0x1, 0x0, 0x4717fe0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/run_self_hosted.go:365 +0x530
github.com/openshift/origin/pkg/oc/clusterup.(*ClusterUpConfig).BuildConfig(0xc420b44a00, 0xc420000100, 0xc420e49800, 0xc420e498e0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/run_self_hosted.go:278 +0xf4f
github.com/openshift/origin/pkg/oc/clusterup.(*ClusterUpConfig).StartSelfHosted(0xc420b44a00, 0x4717f60, 0xc42008c008, 0x20, 0xc420e49b00)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/run_self_hosted.go:127 +0x43
github.com/openshift/origin/pkg/oc/clusterup.(*ClusterUpConfig).Start(0xc420b44a00, 0x4717f60, 0xc42008c008, 0x0, 0x4)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/up.go:473 +0x135
github.com/openshift/origin/pkg/oc/clusterup.NewCmdUp.func1(0xc420b44c80, 0xc420412dd0, 0x0, 0x1)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/up.go:112 +0xe7
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420b44c80, 0xc420412da0, 0x1, 0x1, 0xc420b44c80, 0xc420412da0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420b6a000, 0xc42008c010, 0xc420b6a000, 0xc42027d200)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:843 +0x334
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420b6a000, 0x2, 0xc420b6a000)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:42 +0x334
Server [https://localhost:8443]: 

##### Expected Result
Cluster comes up and works

##### Additional Information
To see the travis-ci run that failed on oc cluster up, look [here](https://travis-ci.org/crobby/oshinko-webui/jobs/441849124)

**Comment by crobby** [comment]
I think my problem may have been due to the way I get the oc binary...
docker cp $(docker create docker.io/openshift/origin:v3.11):/bin/oc .
was giving me
```
oc v3.11.0-alpha.0+1ff2229-9
kubernetes v1.10.0+b81c8f8
```
instead of the 
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
```
that I get when I directly download the client tools from the release page

When I use the oc from the proper version of client tools, my cluster comes up.
