### ISSUE TITLE
 response code: 422 Build

### ISSUE THREAD

**Issue by ududitjha** [openshift/origin#21318]
Hi All,

I am getting the Error when i was trying to execute pipeline for build config execution.

Below are the error which i was getting.

Starting the "Trigger OpenShift Build" step with build config "nicnspeap" from the project "new".
com.openshift.restclient.OpenShiftException: Exception trying to POST https://172.30.0.1/oapi/v1/namespaces/new/buildconfigs/nicnspeap/instantiate response code: 422 Build "nicnspeap-7" is invalid: spec.source: Invalid value: "": must provide a value for at least one source input(git, binary, dockerfile, images).
at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:114)
at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:65)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
at okhttp3.RealCall.execute(RealCall.java:60)
at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:258)

**Comment by ududitjha** [comment]
Can some one help me please...?
