### ISSUE TITLE
oc cluster down; oc delete pod/foo => SIGSEGV

### ISSUE THREAD

**Issue by cben** [openshift/origin#21323]
Using oc v3.9.0, after `oc cluster down`, instead of "connection refused" as most commands report, `oc delete` with specific target crashes with SIGSEGV:
```
$ oc delete pod/foo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x17fa12a]

goroutine 1 [running]:
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl.ReaperFor(0x0, 0x0, 0x38a6bcf, 0x3, 0x0, 0x0, 0x7a174e0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/delete.go:82 +0x120a
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ring1Factory).Reaper(0xc421357ad0, 0xc4201e5b20, 0x0, 0x1, 0x1, 0x0)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go:302 +0x148
github.com/openshift/origin/pkg/oc/cli/util/clientcmd.(*ring1Factory).Reaper(0xc420844100, 0xc4201e5b20, 0x3, 0x48dffad, 0x10, 0x48dffad)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/util/clientcmd/factory_object_mapping.go:287 +0x8bc
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.ReapResult.func1(0xc4201e5c70, 0x0, 0x0, 0x9, 0xc4215436c8)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:250 +0xe3
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit.func1(0xc4201e5c70, 0x0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:396 +0x113
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit.func1(0xc4201e5c70, 0x0, 0x0, 0x10000c421543788, 0x14)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:372 +0xd3
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit.func1(0xc4201e5c70, 0x0, 0x0, 0x0, 0xc420078c00)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:433 +0x498
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit.func1(0xc4201e5c70, 0x0, 0x0, 0xc4211b6401, 0xc42071a180)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:255 +0x113
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*Info).Visit(0xc4201e5c70, 0xc42071a180, 0x28, 0x28)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:105 +0x38
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc4206f3b60, 0x1, 0x1, 0xc4211b6480, 0xc42129ac01, 0xc4211b6480)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:250 +0xce
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x4f5bca0, 0xc42071a0c0, 0xc42129a1c0, 0xc42129ac80, 0x1, 0xc42129ac80)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:428 +0x97
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x4f5bce0, 0xc42071a0e0, 0xc4206f3b90, 0x2, 0x2, 0xc42071a140, 0xc4206f3b01, 0xc42071a140)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:363 +0x99
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x4f5bc60, 0xc4211b6450, 0xc4201e5ce0, 0x0, 0xc4206f3bd0)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:391 +0xcd
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc420286780, 0xc4201e5ce0, 0x2, 0x0)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/result.go:98 +0x62
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.ReapResult(0xc420286780, 0x4ffeae0, 0xc421357b00, 0x4f58780, 0xc4200dc008, 0xc421400001, 0x0, 0xffffffffffffffff, 0x0, 0x4fbd1c0, ...)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:245 +0x162
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.(*DeleteOptions).RunDelete(0xc420d83b80, 0xc420272d80, 0x0)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:235 +0xd2
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdDelete.func1(0xc420272d80, 0xc42033e2e0, 0x1, 0x1)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:142 +0x178
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420272d80, 0xc42033e200, 0x1, 0x1, 0xc420272d80, 0xc42033e200)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x234
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420010fc0, 0x1e703d1, 0xc4200e0900, 0xc420010fc0)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x2d4
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420010fc0, 0x2, 0xc420010fc0)
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/builddir/build/BUILD/origin-191fece9305a76f262baacc9de72c2c8cb4d5601/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:41 +0x293
```

However `oc status`, `oc get pod`, `oc delete pod --all` exit cleanly, as does kubectl delete (using kubernetes-client-1.10.1-0.fc28.x86_64 rpm):
```
$ oc get pod
The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?

$ kubectl delete pod/foo
The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"archive", BuildDate:"2018-04-26T09:29:05Z", GoVersion:"go1.10.1", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?
```

##### Version
I'm on Fedora 28, using oc from rpm.
```
$ rpm -qf (which oc)
origin-clients-3.9.0-4.fc28.x86_64
$ oc version
oc v3.9.0
kubernetes v1.9.1+cbc5b49
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. oc cluster down
2. oc delete pod/foo

##### Current Result
SIGSEGV panic: runtime error: invalid memory address or nil pointer dereference

##### Expected Result
The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?

**Comment by cben** [comment]
Fixed now, closing.
origin-clients-3.11.0-0.alpha1.0.fc29 returns "refused" message as expected.
