### ISSUE TITLE
Deployment failed when using Vert.x fat jar as s2i input

### ISSUE THREAD

**Issue by hakdogan** [openshift/origin#21444]
**oc version**
```
oc v3.7.0-rc.0+e92d5c5
kubernetes v1.7.6+a08f5eeb62
```

**docker version**
```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

I have a simple s2i build that has similar behavior to redhat-openjdk18-openshift. When I gave it a Vert.x fat jar as an input the app build failed. As you know, Vert.x tries to create a `.vertx` directory in the current working directory by default that's why failed.

> 20:32:21.957 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
> --
>   | 20:32:21.969 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
>   | 20:32:21.970 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
>   | 20:32:22.053 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 2
>   | 20:32:22.088 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
>   | 20:32:22.089 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
>   | 20:32:22.091 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
>   | 20:32:22.093 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
>   | 20:32:22.094 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
>   | 20:32:22.095 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
>   | 20:32:22.096 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
>   | 20:32:22.097 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
>   | 20:32:22.097 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
>   | 20:32:22.097 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
>   | 20:32:22.098 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
>   | 20:32:22.098 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
>   | 20:32:22.100 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
>   | 20:32:22.100 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 506855424 bytes
>   | 20:32:22.101 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
>   | 20:32:22.102 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
>   | 20:32:22.118 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
>   | 20:32:22.118 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
>   | 20:32:22.130 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
>   | Nov 07, 2018 8:32:22 PM io.vertx.core.impl.launcher.commands.RunCommand
>   | SEVERE: Failed to create the vert.x instance
>   | java.lang.IllegalStateException: Failed to create cache dir
>   | at io.vertx.core.impl.FileResolver.setupCacheDir(FileResolver.java:319)
>   | at io.vertx.core.impl.FileResolver.<init>(FileResolver.java:87)
>   | at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:186)
>   | at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:145)
>   | at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:38)
>   | at io.vertx.core.Vertx.vertx(Vertx.java:88)
>   | at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:113)
>   | at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:208)
>   | at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:141)
>   | at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:249)
>   | at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
>   | at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
>   | at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
>   | at io.vertx.core.Launcher.main(Launcher.java:45)
> 
> 

I think I've given the required permissions in the Docker file, but it didn't resolve the issue.

```
ARG USER=1001
ARG GROUP="s2i"
ARG APPDIR="/deployments"

...

RUN mkdir $APPDIR
RUN chmod 777 -R $APPDIR

RUN groupadd $GROUP
RUN useradd -ms /bin/bash $USER

RUN usermod -aG $GROUP $USER
RUN chgrp -hR $GROUP $APPDIR
RUN chown "$USER":"$USER" $APPDIR -R
RUN chmod g+rwx $APPDIR -R

USER $USER

...

```

The run file

```
exec java -jar /deployments/*.jar
```

**Comment by hakdogan** [comment]
I trying to get the active user info with commands such as `echo $USER` or `who | awk "{print $1}" | sort` in the run script to understand the source of this problem but there is no result.

Also, the permissions of `/deployments` directory looks like as follow
> 4 drwxrwxrwx   1 1001 1001 4096 Nov  9 19:45 deployments

I changed the relevant section of Dockerfile
```
RUN useradd $USER \
    && mkdir $APPDIR \
    && chown $USER:$USER $APPDIR \
    && addgroup $USER $USER

RUN chmod 777 -R $APPDIR
```

Do you have any idea what is the source of the problem?

**Comment by hakdogan** [comment]
I found the source of the problem and, then I solution.

My mistake is that I'm not setting workdir in dockerfile.

I'm closing this issue.

Thank you.
