### ISSUE TITLE
/healthz 500s early in cluster history

### ISSUE THREAD

**Issue by wking** [openshift/origin#21510]
I see `/healthz` 500s and stack dumps early in the API server container logs.

##### Version

In a cluster launched on libvirt with `openshift-install`:

```console
$ openshift-install version
openshift-install v0.3.0-241-gaaa3542cc870dcd7ff021f0df242a1f383201131
Terraform v0.11.8

Your version of Terraform is out of date! The latest version
is 0.11.10. You can update by downloading from www.terraform.io/downloads.html
$ export KUBECONFIG=wking/auth/kubeconfig
$ oc version
oc 
kubernetes v0.0.0-master+$Format:%h$
features: Basic-Auth

Server https://wking-api.installer.testing:6443
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce

```console
$ openshift-install --dir=wking --log-level=debug create cluster
$ export KUBECONFIG=wking/auth/kubeconfig
$ oc get imagestreamimages --all-namespaces
No resources found.
Error from server (NotFound): Unable to list {"image.openshift.io" "v1" "imagestreamimages"}: the server could not find the requested resource
$ oc get pods -n openshift-apiserver
NAME              READY     STATUS    RESTARTS   AGE
apiserver-fldgt   1/1       Running   0          33m
$ oc get pod -o "jsonpath={range .status.containerStatuses[*]}{.name}{'\t'}{.state}{'\t'}{.image}{'\n'}{end}" -n openshift-apiserver apiserver-fldgt
apiserver map[running:map[startedAt:2018-11-16T22:52:11Z]] registry.svc.ci.openshift.org/openshift/origin-v4.0-20181116214512@sha256:a05222c388cd4aba4765aa9176fabe0f6ed74ea4df3791a86c969bfaca2932bf
$ oc logs -n openshift-apiserver apiserver-fldgt -c apiserver
I1116 22:52:12.404770       1 plugins.go:158] Loaded 1 mutating admission controller(s) successfully in the following order: NamespaceLifecycle.
...
I1116 22:52:18.276344       1 clusterquotamapping.go:168] Starting workers for quota mapping controller workers
I1116 22:52:18.354278       1 wrap.go:42] GET /apis/image.openshift.io/v1/imagestreams?limit=500&resourceVersion=0: (253.341594ms) 200 [[hypershift/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0] 127.0.0.1:370
86]
I1116 22:52:18.358022       1 get.go:245] Starting watch for /apis/image.openshift.io/v1/imagestreams, rv=19676 labels= fields= timeout=5m40s
E1116 22:52:19.069564       1 cache.go:295] error synchronizing: clusterrole.rbac.authorization.k8s.io "aggregated-apiserver-clusterrole" not found
...
E1116 22:52:19.089338       1 cache.go:295] error synchronizing: clusterrole.rbac.authorization.k8s.io "aggregated-apiserver-clusterrole" not found
I1116 22:52:19.090384       1 wrap.go:42] POST /apis/security.openshift.io/v1/securitycontextconstraints: (21.260924ms) 409 [[hypershift/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0] 127.0.0.1:37086]
E1116 22:52:19.092048       1 cache.go:295] error synchronizing: clusterrole.rbac.authorization.k8s.io "aggregated-apiserver-clusterrole" not found
E1116 22:52:19.389481       1 cache.go:332] error synchronizing: clusterrole.rbac.authorization.k8s.io "aggregated-apiserver-clusterrole" not found
I1116 22:52:26.935816       1 wrap.go:42] GET /healthz: (26.75573ms) 500
goroutine 1339 [running]:
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc425176230, 0x1f4)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xd2
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc425176230, 0x1f4)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc4240cf5a0, 0x1f4)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:197 +0xac
net/http.Error(0x7fc1767dc2b8, 0xc423db2718, 0xc425dc6580, 0x284, 0x1f4)
        /usr/local/go/src/net/http/server.go:1959 +0xda
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/healthz.handleRootHealthz.func1(0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:161 +0x4c4
net/http.HandlerFunc.ServeHTTP(0xc42571fe60, 0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc42495cd40, 0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x514
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc424cb83f0, 0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x8a
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x5174ce0, 0x13, 0xc4258c9320, 0xc424cb83f0, 0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6a8
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x4bd
net/http.HandlerFunc.ServeHTTP(0xc424537840, 0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x3fc
net/http.HandlerFunc.ServeHTTP(0xc422012c60, 0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x1ce4
net/http.HandlerFunc.ServeHTTP(0xc424537880, 0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc700)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:75 +0x2b3
net/http.HandlerFunc.ServeHTTP(0xc424537980, 0x7fc1767dc2b8, 0xc423db2718, 0xc4215bc600)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc42584daa0, 0xc4207fa7a0, 0x9aa5740, 0xc423db2718, 0xc4215bc600)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:100 +0xb3
created by github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:96 +0x1b8

logging error output: "[+]ping ok\n[+]log ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/image.openshift.io-apiserver-caches ok\n[+]poststarthook/authorization.openshift.io-bootstrapclusterroles ok\n[+]poststarthook/authorization.openshift.io-ensureopenshift-infra ok\n[+]poststarthook/project.openshift.io-projectcache ok\n[+]poststarthook/project.openshift.io-projectauthorizationcache ok\n[+]poststarthook/security.openshift.io-bootstrapscc ok\n[+]poststarthook/openshift.io-startinformers ok\n[-]poststarthook/openshift.io-restmapperupdater failed: reason withheld\n[+]poststarthook/quota.openshift.io-clusterquotamapping ok\nhealthz check failed\n"
 [[kube-probe/1.11+] 10.2.0.1:56202]
I1116 22:52:36.899250       1 wrap.go:42] GET /healthz: (231.894µs) 500
goroutine 1347 [running]:
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc425176a80, 0x1f4)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xd2
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc425176a80, 0x1f4)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc425f28000, 0x1f4)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:197 +0xac
net/http.Error(0x7fc1767dc2b8, 0xc423db2828, 0xc420a2b8c0, 0x284, 0x1f4)
        /usr/local/go/src/net/http/server.go:1959 +0xda
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/healthz.handleRootHealthz.func1(0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:161 +0x4c4
net/http.HandlerFunc.ServeHTTP(0xc42571fe60, 0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc42495cd40, 0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x514
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc424cb83f0, 0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x8a
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x5174ce0, 0x13, 0xc4258c9320, 0xc424cb83f0, 0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6a8
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x4bd
net/http.HandlerFunc.ServeHTTP(0xc424537840, 0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x3fc
net/http.HandlerFunc.ServeHTTP(0xc422012c60, 0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x1ce4
net/http.HandlerFunc.ServeHTTP(0xc424537880, 0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd200)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:75 +0x2b3
net/http.HandlerFunc.ServeHTTP(0xc424537980, 0x7fc1767dc2b8, 0xc423db2828, 0xc4215bd100)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc42584df80, 0xc4207fa7a0, 0x9aa5740, 0xc423db2828, 0xc4215bd100)
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:100 +0xb3
created by github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:96 +0x1b8

logging error output: "[+]ping ok\n[+]log ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/image.openshift.io-apiserver-caches ok\n[+]poststarthook/authorization.openshift.io-bootstrapclusterroles ok\n[+]poststarthook/authorization.openshift.io-ensureopenshift-infra ok\n[+]poststarthook/project.openshift.io-projectcache ok\n[+]poststarthook/project.openshift.io-projectauthorizationcache ok\n[+]poststarthook/security.openshift.io-bootstrapscc ok\n[+]poststarthook/openshift.io-startinformers ok\n[-]poststarthook/openshift.io-restmapperupdater failed: reason withheld\n[+]poststarthook/quota.openshift.io-clusterquotamapping ok\nhealthz check failed\n"
 [[kube-probe/1.11+] 10.2.0.1:56672]
...
E1116 22:52:50.318145       1 memcache.go:147] couldn't get resource list for apps.openshift.io/v1: Get https://10.3.0.1:443/apis/apps.openshift.io/v1?timeout=32s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1116 22:52:50.319612       1 memcache.go:147] couldn't get resource list for authorization.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.320234       1 memcache.go:147] couldn't get resource list for build.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.321242       1 memcache.go:147] couldn't get resource list for image.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.322390       1 memcache.go:147] couldn't get resource list for oauth.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.323410       1 memcache.go:147] couldn't get resource list for project.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.324535       1 memcache.go:147] couldn't get resource list for quota.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.325543       1 memcache.go:147] couldn't get resource list for route.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.326657       1 memcache.go:147] couldn't get resource list for security.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.327778       1 memcache.go:147] couldn't get resource list for template.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.329055       1 memcache.go:147] couldn't get resource list for user.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.356045       1 memcache.go:147] couldn't get resource list for apps.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.356780       1 memcache.go:147] couldn't get resource list for authorization.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.357854       1 memcache.go:147] couldn't get resource list for build.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.359705       1 memcache.go:147] couldn't get resource list for image.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.360357       1 memcache.go:147] couldn't get resource list for oauth.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.361455       1 memcache.go:147] couldn't get resource list for project.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.362537       1 memcache.go:147] couldn't get resource list for quota.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.363571       1 memcache.go:147] couldn't get resource list for route.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.364624       1 memcache.go:147] couldn't get resource list for security.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.365717       1 memcache.go:147] couldn't get resource list for template.openshift.io/v1: the server is currently unable to handle the request
E1116 22:52:50.366795       1 memcache.go:147] couldn't get resource list for user.openshift.io/v1: the server is currently unable to handle the request
I1116 22:52:56.815290       1 wrap.go:42] GET /healthz: (105.698µs) 200 [[kube-probe/1.11+] 10.2.0.1:57144]
I1116 22:52:56.902960       1 wrap.go:42] GET /healthz: (4.997782ms) 200 [[kube-probe/1.11+] 10.2.0.1:57150]
```

##### Expected Result

No 500s?  Or maybe some just a better warning about why the 500 and no panic-like stack traces?  It's hard for me to tell if this is important or not.

**Comment by wking** [comment]
Oh, more version information:


```console
$ oc adm release info registry.svc.ci.openshift.org/openshift/origin-release:v4.0-20181116214512 --commits | grep openshift-apiserver
  cluster-openshift-apiserver-operator          https://github.com/openshift/cluster-openshift-apiserver-operator          236a1ac0b8b11855982829539316b49245fe7373
$ oc image info registry.svc.ci.openshift.org/openshift/origin-v4.0-20181116214512@sha256:a05222c388cd4aba4765aa9176fabe0f6ed74ea4df3791a86c969bfaca2932bf
Name:        registry.svc.ci.openshift.org/openshift/origin-v4.0-20181116214512@sha256:a05222c388cd4aba4765aa9176fabe0f6ed74ea4df3791a86c969bfaca2932bf
Media Type:  application/vnd.docker.distribution.manifest.v2+json
Created:     7h ago
Image Size:  139.1MB in 4 layers
Layers:      74.7MB  sha256:aeb7866da422acc7e93dcf7323f38d7646f6269af33bcdb6647f2094fc4b3bf7
             9.241MB sha256:27a564ef3cf140c2b84de6655f3b074ad1c39cd591255a0db6d4dcef8056b52e
             270B    sha256:d6197a75d13957d1cc2b68bc41e3733710d89f37cbb0f801a2b1c8526ab47abf
             55.18MB sha256:6ad3256f6bd0b8882c80a13a5c3cc904cbbafd72df93234f2cb58e19ecf9ddc6
OS:          linux
Arch:        amd64
Command:     /bin/bash
Environment: OPENSHIFT_BUILD_NAME=hypershift
             OPENSHIFT_BUILD_NAMESPACE=ci-op-9jxqt2vn
             PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Labels:      io.k8s.description=OpenShift is a platform for developing, building, and deploying containerized applications.
             io.k8s.display-name=OpenShift Server Commands
             io.openshift.build.commit.author=
             io.openshift.build.commit.date=
             io.openshift.build.commit.id=e3a1f204e5d66a706e249d5737203e9f3210f638
             io.openshift.build.commit.message=
             io.openshift.build.commit.ref=master
             io.openshift.build.name=
             io.openshift.build.namespace=
             io.openshift.build.source-context-dir=images/hypershift/
             io.openshift.build.source-location=https://github.com/openshift/origin
             io.openshift.tags=openshift,hypershift
             org.label-schema.build-date=20181006
             org.label-schema.license=GPLv2
             org.label-schema.name=CentOS Base Image
             org.label-schema.schema-version=1.0
             org.label-schema.vendor=CentOS
             vcs-ref=e3a1f204e5d66a706e249d5737203e9f3210f638
             vcs-type=git
             vcs-url=https://github.com/openshift/origin
```

**Comment by smarterclayton** [comment]
I think we can drop the stack trace now.  Logging the failed health check is generally useful

**Comment by wking** [comment]
> I think we can drop the stack trace now. Logging the failed health check is generally useful

Isn't the existing:

    logging error output: "[+]ping ok\n[+]log ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/image.openshift.io-apiserver-caches ok\n[+]poststarthook/authorization.openshift.io-bootstrapclusterroles ok\n[+]poststarthook/authorization.openshift.io-ensureopenshift-infra ok\n[+]poststarthook/project.openshift.io-projectcache ok\n[+]poststarthook/project.openshift.io-projectauthorizationcache ok\n[+]poststarthook/security.openshift.io-bootstrapscc ok\n[+]poststarthook/openshift.io-startinformers ok\n[-]poststarthook/openshift.io-restmapperupdater failed: reason withheld\n[+]poststarthook/quota.openshift.io-clusterquotamapping ok\nhealthz check failed\n"  [[kube-probe/1.11+] 10.2.0.1:56672] ...

sufficient?  If we keep the separate 500 log, it would be nice to have it mention restmapperupdater too.
