### ISSUE TITLE
oc rsync crashes using --type=tar

### ISSUE THREAD

**Issue by richm** [openshift/origin#22535]
The following command line causes `oc rsync` to crash:

`oc --loglevel=3 rsync --strategy=tar logging-ci-test-runner:/tmp/artifacts/ /tmp/artifacts`

The loglevel doesn't matter - I've tried without it and with several other log levels.

Here are the last few log lines and the stacktrace:
```
I0411 00:41:40.627385    9812 sibling.go:16] Found parent command: oc
I0411 00:41:40.627429    9812 sibling.go:22] Setting root command to: oc
I0411 00:41:40.627438    9812 sibling.go:27] The sibling command is: oc rsh
I0411 00:41:40.635882    9812 copy_tar.go:119] Copying files with tar
I0411 00:41:40.636149    9812 copy_tar.go:147] Creating local tar file /tmp/rsync348440340 from remote path /tmp/artifacts/
I0411 00:41:40.636176    9812 copy_tar.go:203] Tarring /tmp/artifacts/ remotely
I0411 00:41:40.636189    9812 copy_tar.go:227] Remote tar command: tar -C /tmp/artifacts/ -c .
I0411 00:41:40.636200    9812 exec_remote.go:30] Remote executor running command: tar -C /tmp/artifacts/ -c .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x21b3b0f]

goroutine 1 [running]:
github.com/openshift/origin/pkg/oc/cli/rsync.(*remoteExecutor).Execute(0xc4218968a0, 0xc421900200, 0x5, 0x8, 0x0, 0x0, 0x2cc52e0, 0xc4218635e8, 0x2cc0000, 0xc42025d3b0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/rsync/exec_remote.go:45 +0x13f
github.com/openshift/origin/pkg/oc/cli/rsync.tarRemote(0x2cc0d40, 0xc4218968a0, 0xc4218bbd27, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/rsync/copy_tar.go:228 +0x917
github.com/openshift/origin/pkg/oc/cli/rsync.(*tarStrategy).Copy(0xc4217b8630, 0xc421906240, 0xc4219062a0, 0x2cc52e0, 0xc4200f4008, 0x2cc52e0, 0xc4200f4010, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/rsync/copy_tar.go:149 +0xba9
github.com/openshift/origin/pkg/oc/cli/rsync.(*RsyncOptions).RunRsync(0xc421376400, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/rsync/rsync.go:260 +0x7a
github.com/openshift/origin/pkg/oc/cli/rsync.NewCmdRsync.func1(0xc42137a500, 0xc42148b300, 0x2, 0x4)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/rsync/rsync.go:123 +0xb9
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc42137a500, 0xc42148b2c0, 0x4, 0x4, 0xc42137a500, 0xc42148b2c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42126cc80, 0xc420f2fdf0, 0x13ff8a9, 0xc4202b48c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42126cc80, 0x2, 0xc42126cc80)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:68 +0x554
```

The crash is here: https://github.com/openshift/origin/blob/master/pkg/oc/cli/rsync/exec_remote.go#L45
Looks like the file changed very recently: https://github.com/openshift/origin/commit/b85af71f7db31e0840f36424719fabb463981000
And the crashing started happening very recently
@sanchezl any ideas?

##### Version
oc version
Client Version: version.Info{Major:"4", Minor:"0+", GitVersion:"v4.0.0-alpha.0+3e176c9-1989-dirty", GitCommit:"3e176c9", GitTreeState:"", BuildDate:"2019-04-10T22:23:49Z", GoVersion:"", Compiler:"", Platform:""}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+3e176c9", GitCommit:"3e176c9", GitTreeState:"clean", BuildDate:"2019-04-10T22:26:36Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

##### Steps To Reproduce
1. oc rsync ....
2. crash

Other than that, I have no idea how to reproduce outside of the api.ci environment.

**Comment by richm** [comment]
@bparees @jcantrill

**Comment by bparees** [comment]
moved to BZ https://bugzilla.redhat.com/show_bug.cgi?id=1699048
