### ISSUE TITLE
Null pointer reference when `oc login`

### ISSUE THREAD

**Issue by Allda** [openshift/origin#27166]
After updating to Fedora 36 with the latest `oc` I am getting null pointer reference error while using `oc login`

##### Version
oc v3.11.0+20c5b86
kubernetes v1.10.0+b3b92b2
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. oc login --token=XYZ --server=https://example.openshiftapps.com:6443

##### Current Result
```
Logged into "https://api.example.openshiftapps.com:6443" as "XYZ" using the token provided.

You have access to 112 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4145bc]

goroutine 1 [running]:
reflect.mapiternext(0x40?)
	/usr/lib/golang/src/runtime/map.go:1378 +0x19
github.com/openshift/origin/vendor/github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x0?)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/modern-go/reflect2/unsafe_map.go:136 +0x32
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc00155aa20, 0xc001394488, 0xc00168ed80)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_map.go:273 +0x335
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc000a4e370?, 0xc95047?, 0xc00168ed98?)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:325 +0x22
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc001562300, 0x213eb63?, 0xc00168ed80)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc001562450, 0xc000ba0100?, 0xc00168ed80)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x652
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc000a4e4e8?, 0xc95047?, 0xc00168ed98?)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:325 +0x22
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0015626c0, 0x20b0423?, 0xc00168ed80)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc001562720, 0xc000a4e620?, 0xc00168ed80)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x652
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*sliceEncoder).Encode(0xc0015548d0, 0xc00061c478, 0xc00168ed80)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_slice.go:42 +0x30d
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc001563230, 0x20bc8c6?, 0xc00168ed80)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc001563320, 0x0?, 0xc00168ed80)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x652
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc000a4e848?, 0x410025?, 0x2387c00?)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_optional.go:74 +0xa4
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc000542c80, 0xc00061c420, 0xc000a4e898?)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:213 +0x82
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*Stream).WriteVal(0xc00168ed80, {0x246f080, 0xc00061c420})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:93 +0x158
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*frozenConfig).Marshal(0xc00018a400, {0x246f080, 0xc00061c420})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/config.go:296 +0xc9
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc00045a5b0?, {0x2d1cf98?, 0xc00061c420?}, {0x2d0cca0, 0xc00185e600})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:226 +0x6d
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0001970e0, {0x2d1cf48?, 0xc000940e40}, {0x2d0cca0, 0xc00185e600})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:221 +0x7c6
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime.Encode({0x7f6a9c2f2a58, 0xc0001970e0}, {0x2d1cf48, 0xc000940e40})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:46 +0x64
github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd.Write(...)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd/loader.go:426
github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc00063a9f0}, 0xc001421d70, 0xc00155a480, 0xc00155b6b0, {0xc001083b40, ...}, ...}, ...)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd/loader.go:406 +0xa8
github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd.ModifyConfig({0x2d36840, 0xc000d5a9b0}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc000945350}, 0xc000945860, 0xc000945890, ...}, ...)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd/config.go:268 +0xb38
github.com/openshift/origin/pkg/oc/cli/login.(*LoginOptions).SaveConfig(0xc000a4f790)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/login/loginoptions.go:382 +0x227
github.com/openshift/origin/pkg/oc/cli/login.LoginOptions.Run({{0xc00151dfc0, 0x3a}, {0x0, 0x0}, 0x0, {0xc001b02960, 0x5}, {0x0, 0x0}, {0xc000b24da4, ...}, ...})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/login/login.go:179 +0x38
github.com/openshift/origin/pkg/oc/cli/login.NewCmdLogin.func1(0xc000f14500?, {0xc001419b60, 0x0, 0x2})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/login/login.go:59 +0x1c5
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc000f14500, {0xc001419b00, 0x2, 0x2})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:760 +0x663
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000f14280)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:846 +0x2dc
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:794
main.main()
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:70 +0x4db

oc project                          
error: You must be logged in to the server (Unauthorized)
```
##### Expected Result
User is successfully logged-in to the cluster.

**Comment by Kibblesnbitsnbits** [comment]
Same exact issue here, did either of you find a solution?

**Comment by djdevin** [comment]
The `origin-clients` packaged with Fedora doesn't seem to work.

The release here works: https://github.com/openshift/origin/releases/tag/v3.11.0

**Comment by sdstolworthy** [comment]
@Kibblesnbitsnbits I just reverted to an older version and that resolved the issue.

**Comment by Allda** [comment]
I can confirm the Fedora release is broken and the official release from Github of `v3.11.0` works fine.
