### ISSUE TITLE
openshift-tests run throws fatal error for dry run when OPENSHIFT_SKIP_EXTERNAL_TESTS is not set

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [openshift/origin#27975]
```
+ openshift-tests run kubernetes/conformance --dry-run
  Jun  9 00:36:21.245: INFO: Enabling in-tree volume drivers
Attempting to pull tests from external binary...
  goroutine 1 [running]:
  runtime/debug.Stack()
  	runtime/debug/stack.go:24 +0x6c
  github.com/openshift/origin/test/extended/util.FatalErr({0x17066aa0, 0xc00549d5f0})
  	github.com/openshift/origin/test/extended/util/client.go:922 +0x3c
  github.com/openshift/origin/test/extended/util.(*CLI).AdminConfig(0x0?)
  	github.com/openshift/origin/test/extended/util/client.go:750 +0x58
  github.com/openshift/origin/test/extended/util.(*CLI).AdminConfigClient(0xc005512f00)
  	github.com/openshift/origin/test/extended/util/client.go:663 +0x30
  github.com/openshift/origin/pkg/test/ginkgo.extractBinaryFromReleaseImage({0x17a86a03, 0x9}, {0x17ab5b37, 0x12})
  	github.com/openshift/origin/pkg/test/ginkgo/external.go:77 +0xa8
  github.com/openshift/origin/pkg/test/ginkgo.externalTestsForSuite({0x186bab70, 0x1bf4aa80})
  	github.com/openshift/origin/pkg/test/ginkgo/external.go:33 +0x58
  github.com/openshift/origin/pkg/test/ginkgo.(*Options).Run(0xc000ce4fc0, 0x1b51f2c0, {0x17aa27ac, 0xf})
  	github.com/openshift/origin/pkg/test/ginkgo/cmd_runsuite.go:168 +0x210
  main.newRunCommand.func1.1()
  	github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:330 +0x298
  main.mirrorToFile(0x0?, 0x0?)
  	github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:467 +0xf0
  main.newRunCommand.func1(0xc001275700?, {0xc00082eb60?, 0x4?, 0x17a77fdb?})
  	github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:311 +0x88
  github.com/spf13/cobra.(*Command).execute(0xc000b83200, {0xc00082eb40, 0x2, 0x2})
  	github.com/spf13/cobra@v1.6.0/command.go:916 +0x740
  github.com/spf13/cobra.(*Command).ExecuteC(0xc000b82f00)
  	github.com/spf13/cobra@v1.6.0/command.go:1040 +0x370
  github.com/spf13/cobra.(*Command).Execute(...)
  	github.com/spf13/cobra@v1.6.0/command.go:968
  main.main.func1(0xc000e86600?)
  	github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:96 +0x8c
  main.main()
  	github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:97 +0x498

panic: [1m[38;5;9mYour Test Panicked[0m
[38;5;243mgithub.com/openshift/origin/test/extended/util/client.go:923[0m
  When you, or your assertion library, calls Ginkgo's Fail(),
  Ginkgo panics to prevent subsequent assertions from running.

  Normally Ginkgo rescues this panic so you shouldn't see it.

  However, if you make an assertion in a goroutine, Ginkgo can't capture the
  panic.
  To circumvent this, you should call

  	defer GinkgoRecover()

  at the top of the goroutine that caused this panic.

  Alternatively, you may have made an assertion outside of a Ginkgo
  leaf node (e.g. in a container node or some out-of-band function) - please
  move your assertion to
  an appropriate Ginkgo node (e.g. a BeforeSuite, BeforeEach, It, etc...).

  [1mLearn more at:[0m
  [38;5;14m[4mhttp://onsi.github.io/ginkgo/#mental-model-how-ginkgo-handles-failure[0m


goroutine 1 [running]:
github.com/onsi/ginkgo/v2.Fail({0xc00550e620, 0x20}, {0xc0063624d8?, 0x1?, 0x1?})
	github.com/onsi/ginkgo/v2@v2.9.1/core_dsl.go:374 +0x1e0
k8s.io/kubernetes/test/e2e/framework.Failf({0x17a76d8e?, 0xc000808480?}, {0xc006362538?, 0x1?, 0x1?})
	k8s.io/kubernetes@v1.27.1/test/e2e/framework/log.go:44 +0x6c
github.com/openshift/origin/test/extended/util.FatalErr({0x17066aa0, 0xc00549d5f0})
	github.com/openshift/origin/test/extended/util/client.go:923 +0xe0
github.com/openshift/origin/test/extended/util.(*CLI).AdminConfig(0x0?)
	github.com/openshift/origin/test/extended/util/client.go:750 +0x58
github.com/openshift/origin/test/extended/util.(*CLI).AdminConfigClient(0xc005512f00)
	github.com/openshift/origin/test/extended/util/client.go:663 +0x30
github.com/openshift/origin/pkg/test/ginkgo.extractBinaryFromReleaseImage({0x17a86a03, 0x9}, {0x17ab5b37, 0x12})
	github.com/openshift/origin/pkg/test/ginkgo/external.go:77 +0xa8
github.com/openshift/origin/pkg/test/ginkgo.externalTestsForSuite({0x186bab70, 0x1bf4aa80})
	github.com/openshift/origin/pkg/test/ginkgo/external.go:33 +0x58
github.com/openshift/origin/pkg/test/ginkgo.(*Options).Run(0xc000ce4fc0, 0x1b51f2c0, {0x17aa27ac, 0xf})
	github.com/openshift/origin/pkg/test/ginkgo/cmd_runsuite.go:168 +0x210
main.newRunCommand.func1.1()
	github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:330 +0x298
main.mirrorToFile(0x0?, 0x0?)
	github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:467 +0xf0
main.newRunCommand.func1(0xc001275700?, {0xc00082eb60?, 0x4?, 0x17a77fdb?})
	github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:311 +0x88
github.com/spf13/cobra.(*Command).execute(0xc000b83200, {0xc00082eb40, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.0/command.go:916 +0x740
github.com/spf13/cobra.(*Command).ExecuteC(0xc000b82f00)
	github.com/spf13/cobra@v1.6.0/command.go:1040 +0x370
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.0/command.go:968
main.main.func1(0xc000e86600?)
	github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:96 +0x8c
main.main()
	github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:97 +0x498
```
This is after https://github.com/openshift/origin/pull/27570/commits/0060ccdd4d01b70980ee8b8108829e16b8714fa7

Looks like the line https://github.com/openshift/origin/blob/master/pkg/test/ginkgo/external.go#L77 panics as the config of cluster isnt' passed in above command.
The dry run should ideally not need config of cluster to list tests.

Also the variable `OPENSHIFT_SKIP_EXTERNAL_TESTS` should be mentioned in the output of `openshift-tests` binary help output.

**Comment by Rajalakshmi-Girish** [comment]
@soltysh Can you please have a look.
