### ISSUE TITLE
oc process panics when pointed to invalid? template

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3223]
I tried running `oc process` against a file like this: https://gist.github.com/deads2k/97bcb89212c5c13c3066 and I get a panic.

```
[deads@deads-dev-01 docker-nfs-server]$ oc process -f openshift-template.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4c6420]

goroutine 1 [running]:
github.com/openshift/origin/pkg/cmd/cli/cmd.RunProcess(0xc2082e23e0, 0x7f0077caa7b0, 0xc20802c008, 0xc2082fb380, 0xc2083a6e60, 0x0, 0x2, 0x0, 0x0)
	/home/deads/workspaces/openshift3/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/process.go:134 +0xfe0
github.com/openshift/origin/pkg/cmd/cli/cmd.func·023(0xc2082fb380, 0xc2083a6e60, 0x0, 0x2)
	/home/deads/workspaces/openshift3/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/process.go:54 +0x5f
github.com/spf13/cobra.(*Command).execute(0xc2082fb380, 0xc2083a6d80, 0x2, 0x2, 0x0, 0x0)
	/home/deads/workspaces/openshift3/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:476 +0x65c
github.com/spf13/cobra.(*Command).Execute(0xc20832a000, 0x0, 0x0)
	/home/deads/workspaces/openshift3/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:541 +0x18d
main.main()
	/home/deads/workspaces/openshift3/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:22 +0x175

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x3e07600)
	/home/deads/workspaces/openshift3/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/home/deads/workspaces/openshift3/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 37 [select]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).step(0xc2081ab5a0, 0x0)
	/home/deads/workspaces/openshift3/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:102 +0xfc
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).run(0xc2081ab5a0)
	/home/deads/workspaces/openshift3/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:95 +0x28
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.NewTokenBucketRateLimiter
	/home/deads/workspaces/openshift3/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:50 +0x81
```

@liggitt this is blocking me.  I'll take a look.

**Comment by deads2k** [comment]
Ah, invalid file content.  This is just terrible handling of the error case.
