### ISSUE TITLE
Test flake?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3959]
```
I0730 17:52:38.838585   22906 decoder.go:141] decoding stream as JSON
I0730 17:52:49.993936   22906 trace.go:57] Trace "Create *api.Policy" (started 2015-07-30 17:52:39.351684674 +0000 UTC):
[3.940809ms] [3.940809ms] About to create object
[10.642215891s] [10.638275082s] END
--- FAIL: TestTemplate-16 (14.00s)
panic: interface conversion: interface is nil, not *api.Role [recovered]
	panic: interface conversion: interface is nil, not *api.Role
goroutine 108 [running]:
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x181
github.com/openshift/origin/pkg/authorization/registry/role.(*storage).CreateRole(0xc2093822a0, 0x2ad147b346f0, 0xc209dca270, 0xc209a54f70, 0x16, 0x0, 0x0)
	/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/authorization/registry/role/registry.go:56 +0x101
github.com/openshift/origin/pkg/cmd/server/admin.func·017(0xc208fc8180, 0x0, 0x0)
	/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/admin/overwrite_bootstrappolicy.go:164 +0x1149
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource.func·003(0xc208fc8180, 0x0, 0x0)
```

**Comment by liggitt** [comment]
@deads2k was this related to your nil-checking?

**Comment by deads2k** [comment]
yeah. I forgot, were we still arguing over https://github.com/openshift/origin/pull/3922?

**Comment by liggitt** [comment]
yup :)
