### ISSUE TITLE
openshift master crashes with loglevel > 5

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#4340]
I was trying to debug something and bumped the loglevel to 6 in /etc/sysconfig/openshift-master... it wouldn't start. Lovely stack trace (this is compiled from current origin/HEAD) :

```
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: panic: interface conversion: http.RoundTripper is *client.DebuggingRoundTripper, not *http.Transport
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: goroutine 1 [running]:
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.gopanic(0x209dfc0, 0xc20802cb80)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/panic.go:425 +0x2a3 fp=0xc20869e6b8 sp=0xc20869e650
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.assertI2T(0x2308d40, 0x7f94fa383200, 0xc2083b9fe0)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/iface.go:181 +0x1f2 fp=0xc20869e6e8 sp=0xc20869e6b8
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: github.com/openshift/origin/pkg/cmd/server/etcd.EtcdClient(0xc2083de380, 0x1, 0x4, 0xc20833f700, 0x1c, 0xc208370990, 0x2c, 0xc2083709f0, 0x2c, 0x25
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/etcd/etcd.go:103 +0x1de fp=0xc20869
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: github.com/openshift/origin/pkg/cmd/server/origin.BuildMasterConfig(0x0, 0x0, 0x0, 0x0, 0xc2080cc780, 0xc, 0x241a0b0, 0x4, 0xc2083708d0, 0x27, ...)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master_config.go:132 +0x59 f
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: github.com/openshift/origin/pkg/cmd/server/start.(*Master).Start(0xc2083505d0, 0x0, 0x0)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:370 +0x12c fp
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: github.com/openshift/origin/pkg/cmd/server/start.MasterOptions.RunMaster(0xc208069680, 0x1, 0x7ffd52e06edb, 0x28, 0x7f94fa3666f0, 0xc20802e008, 0x0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:291 +0xbd6 fp
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: github.com/openshift/origin/pkg/cmd/server/start.MasterOptions.StartMaster(0xc208069680, 0x1, 0x7ffd52e06edb, 0x28, 0x7f94fa3666f0, 0xc20802e008, 0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:183 +0x4b fp=
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: github.com/openshift/origin/pkg/cmd/server/start.func·007(0xc2080376c0, 0xc2083f1740, 0x0, 0x2)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:91 +0x432 fp=
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: github.com/spf13/cobra.(*Command).execute(0xc2080376c0, 0xc2083f14a0, 0x2, 0x2, 0x0, 0x0)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:477 +0x3d4 fp=0xc20869fe28 sp=0xc20869fd60
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: github.com/spf13/cobra.(*Command).Execute(0xc208037040, 0x0, 0x0)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:551 +0x414 fp=0xc20869ff30 sp=0xc20869fe28
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: main.main()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:22 +0x175 fp=0xc20869ff
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.main()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/proc.go:63 +0xf3 fp=0xc20869ffe0 sp=0xc20869ff98
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goexit()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20869ffe8 sp=0xc20869ffe0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: goroutine 2 [force gc (idle)]:
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.gopark(0x4356e0, 0x401d4d0, 0x2480f70, 0xf)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc20801a798 sp=0xc20801a768
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goparkunlock(0x401d4d0, 0x2480f70, 0xf)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/proc.go:136 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.forcegchelper()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/proc.go:99 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goexit()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: created by runtime.init·4
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/proc.go:87 +0x25
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: goroutine 3 [runnable]:
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.Gosched()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/proc.go:113 +0x14 fp=0xc20801dfc0 sp=0xc20801dfb0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.bgsweep()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/mgc0.go:87 +0x59 fp=0xc20801dfe0 sp=0xc20801dfc0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goexit()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: created by gc
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/mgc0.c:1386
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: goroutine 4 [finalizer wait]:
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.gopark(0x4356e0, 0x402ebd8, 0x2480190, 0xe)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc208018f30 sp=0xc208018f00
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goparkunlock(0x402ebd8, 0x2480190, 0xe)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/proc.go:136 +0x48 fp=0xc208018f58 sp=0xc208018f30
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.runfinq()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/malloc.go:727 +0xba fp=0xc208018fe0 sp=0xc208018f58
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goexit()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fe8 sp=0xc208018fe0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: created by runtime.createfing
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/malloc.go:707 +0x5e
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: goroutine 5 [syscall]:
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.notetsleepg(0x4035520, 0xffffffffffffffff, 0x1)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/lock_futex.go:201 +0x52 fp=0xc208019768 sp=0xc208019740
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.signal_recv(0x0)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/sigqueue.go:109 +0x135 fp=0xc2080197a0 sp=0xc208019768
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: os/signal.loop()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f fp=0xc2080197e0 sp=0xc2080197a0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goexit()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080197e8 sp=0xc2080197e0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: created by os/signal.init·1
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: goroutine 8 [chan receive]:
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.gopark(0x4356e0, 0xc20800cc58, 0x2473cf0, 0xc)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc208018698 sp=0xc208018668
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goparkunlock(0xc20800cc58, 0x2473cf0, 0xc)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/proc.go:136 +0x48 fp=0xc2080186c0 sp=0xc208018698
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.chanrecv(0x1ade900, 0xc20800cc00, 0xc2080187b8, 0x1ae0901, 0xc208000000)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/chan.go:467 +0x82c fp=0xc208018760 sp=0xc2080186c0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.chanrecv2(0x1ade900, 0xc20800cc00, 0xc2080187b8, 0xb0089b)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/chan.go:316 +0x2b fp=0xc208018790 sp=0xc208018760
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: github.com/golang/glog.(*loggingT).flushDaemon(0x401e3e0)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78 fp=0xc2080187d8 sp=0xc208018790
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goexit()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080187e0 sp=0xc2080187d8
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: created by github.com/golang/glog.init·1
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /home/lmeyer/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: goroutine 17 [syscall, locked to thread]:
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goexit()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208061fe8 sp=0xc208061fe0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: goroutine 10 [syscall]:
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.notetsleepg(0x401dd98, 0x6fc239fc4, 0x0)
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/lock_futex.go:201 +0x52 fp=0xc20801af68 sp=0xc20801af40
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.timerproc()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/time.go:207 +0xfa fp=0xc20801afe0 sp=0xc20801af68
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: runtime.goexit()
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801afe8 sp=0xc20801afe0
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: created by runtime.addtimerLocked
Aug 24 10:05:08 master.dev.example.com openshift-master[15131]: /usr/lib/golang/src/runtime/time.go:113 +0x1ba
Aug 24 10:05:08 master.dev.example.com systemd[1]: openshift-master.service: main process exited, code=dumped, status=6/ABRT
Aug 24 10:05:08 master.dev.example.com systemd[1]: Failed to start OpenShift Master.
```

loglevel 5 and below is fine.

**Comment by liggitt** [comment]
@smarterclayton is there a better way to build transports for etcd yet?

**Comment by smarterclayton** [comment]
Supposedly yes, although someone needs to look into what they've done.

On Aug 24, 2015, at 3:21 PM, Jordan Liggitt <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> is there a better way
to build transports for etcd yet?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4340#issuecomment-134324966>.
