### ISSUE TITLE
Can kill OpenShift process with go panic by invalid json file

### ISSUE THREAD

**Issue by nak3** [openshift/origin#4374]
Env
---
~~~
# openshift version
openshift v1.0.5-27-g2cc96dc
kubernetes v1.1.0-alpha.0-1605-g44c91b1

# go version
go version go1.4.2 linux/amd64
~~~

**NOTE:** I couldn't reproduce this issue with OSE v3.0.1.0 due to another error.

Issue:
---
- We can kill OpenShift process by sending request with invalid json file.
- Please see following steps.

Reproduce steps
---

step-1. Start openshift origin with standalone mode, and create route and docker-registry. (Followed with [here](https://github.com/nak3/openshift-local-setup))

step-2. Send invalid json file by my [origin-killer.json](https://gist.githubusercontent.com/nak3/23de3850fd3abf5ed038/raw/eba398a3e778459ca21ff8f60371e708566f7950/origin-killer.json
)
~~~
[root@localhost ~]# oc create -f https://gist.githubusercontent.com/nak3/23de3850fd3abf5ed038/raw/eba398a3e778459ca21ff8f60371e708566f7950/origin-killer.json
imagestream "sti-python" created
Unable to connect to the server: EOF
The connection to the server 192.168.122.27:8443 was refused - did you specify the right host or port?
The connection to the server 192.168.122.27:8443 was refused - did you specify the right host or port?
~~~

step-3. You can see go panic and stop the OpenShift process

The log is here: https://kenjiro.fedorapeople.org/misc/logs/origin.log (Too long, please check from the bottom.)

**Comment by liggitt** [comment]
```
I0826 16:21:40.165796    2410 image_change_controller.go:47] Build image change controller detected ImageStream change 172.30.157.204:5000/default/sti-python
I0826 16:21:40.166325    2410 controller.go:38] Detecting changed images for DeploymentConfig default/docker-registry:1
I0826 16:21:40.166483    2410 controller.go:38] Detecting changed images for DeploymentConfig default/router:1
I0826 16:21:40.166497    2410 controller.go:86] Updated all DeploymentConfigs for trigger on ImageStream default/sti-python
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x66bbb8]

goroutine 6548 [running]:
github.com/openshift/origin/pkg/build/util.GetImageStreamForStrategy(0xc20a2fadda, 0x6, 0x0, 0x0, 0xc20e0d3720, 0x401ed10)
	/tmp/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/util/util.go:37 +0x128
github.com/openshift/origin/pkg/build/api/validation.ValidateBuildConfig(0xc20bf47200, 0x0, 0x0, 0x0)
	/tmp/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/api/validation/validation.go:67 +0x5e8
github.com/openshift/origin/pkg/build/registry/buildconfig.strategy.Validate(0x7f6b977fd3c8, 0xc2080d4af0, 0x7f6b977fb558, 0x401ed10, 0x7f6b9781cd30, 0xc20d53a090, 0x7f6b977fe438, 0xc20bf47200, 0x0, 0x0, ...)
	/tmp/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/registry/buildconfig/strategy.go:51 +0x67
github.com/openshift/origin/pkg/build/registry/buildconfig.(*strategy).Validate(0xc208f535c0, 0x7f6b9781cd30, 0xc20d53a090, 0x7f6b977fe438, 0xc20bf47200, 0x0, 0x0, 0x0)
	<autogenerated>:32 +0xef
k8s.io/kubernetes/pkg/api/rest.BeforeCreate(0x7f6b97672698, 0xc208f535c0, 0x7f6b9781cd30, 0xc20d53a090, 0x7f6b977fe438, 0xc20bf47200, 0x0, 0x0)
	/tmp/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/rest/create.go:66 +0x367
k8s.io/kubernetes/pkg/registry/generic/etcd.(*Etcd).Create(0xc208e45a20, 0x7f6b9781cd30, 0xc20d53a090, 0x7f6b977fe438, 0xc20bf47200, 0x0, 0x0, 0x0, 0x0)
	/tmp/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd.go:205 +0x193
k8s.io/kubernetes/pkg/apiserver.(*namedCreaterAdapter).Create(0xc2093a3970, 0x7f6b9781cd30, 0xc20d53a090, 0x0, 0x0, 0x7f6b977fe438, 0xc20bf47200, 0x0, 0x0, 0x0, ...)
	/tmp/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:357 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·025(0x0, 0x0, 0x0, 0x0)
	/tmp/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:322 +0xaa
k8s.io/kubernetes/pkg/apiserver.func·033()
	/tmp/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:622 +0x38
created by k8s.io/kubernetes/pkg/apiserver.finishRequest
	/tmp/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:627 +0x1e4
```

**Comment by liggitt** [comment]
should fix the assumption that strategy guaranteed a non-nil params field, but also find out why a panic handler wasn't catching this

**Comment by smarterclayton** [comment]
P0 - we may need to hot fix

**Comment by smarterclayton** [comment]
We may have lost the panic handler accidently in the API installer.  Could be upstream too.
