### ISSUE TITLE
UI e2e flakes

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4536]
Collecting various flakes seen

**Comment by liggitt** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/4781/
```
>> /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1761
>>       throw error;
>>             ^
>> Error: Timed out waiting for the WebDriver server at http://172.18.13.117:42208/wd/hub
>>     at Error (<anonymous>)
>>     at onResponse (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:87:11)
>>     at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:42:21
>>     at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
>>     at ClientRequest.<anonymous> (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145:7)
>>     at ClientRequest.emit (events.js:95:17)
>>     at Socket.socketErrorListener (http.js:1552:9)
>>     at Socket.emit (events.js:95:17)
>>     at net.js:441:14
>>     at process._tickCallback (node.js:442:13)
Fatal error: protractor exited with code: 8

**Comment by liggitt** [comment]
@fabianofranz @jwforres I'll let you fight over this one

**Comment by jwforres** [comment]
@liggitt have you still been seeing this?

**Comment by liggitt** [comment]
I haven't, but I haven't been scrubbing the test/merge failures as diligently

**Comment by liggitt** [comment]
I'm ok closing this... haven't seen it in a long time and no one has linked to it

**Comment by liggitt** [comment]
Figures: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/5670

**Comment by jwforres** [comment]
tracking the different kinds of timeouts separately, we have a more specific issue for webdriver timeout https://github.com/openshift/origin/issues/6053
