### ISSUE TITLE
Random Go panic after starting openshift and adding minion

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#478]
A new panic can be observed in Travis/Jenkins, that happens randomly, but the frequency gets higher:

```
I1126 14:21:21.461273 04815 log.go:151] POST /api/v1beta1/minions: (10.285526ms) 500

goroutine 84 [running]:

github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20837ec60, 0x1f4)

/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:180 +0x9c

github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f2763f9f908, 0xc208042b20, 0x7f2763f9fa80, 0xc20806ea80, 0x7f2763fab8f0, 0xc20837ec60)

/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:156 +0x132

github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.(*RESTHandler).finishReq(0xc2081a0cd0, 0xc208345220, 0xc2081da5b0, 0x7f2763fab8f0, 0xc20837ec60)

/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:265 +0x14b

github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.(*RESTHandler).handleRESTStorage(0xc2081a0cd0, 0xc208375710, 0x1, 0x1, 0xc2081da5b0, 0x7f2763fab8f0, 0xc20837ec60, 0x7f2763faa570, 0xc2081750a0)

/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:194 +0x111c

github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.(*RESTHandler).ServeHTTP(0xc2081a0cd0, 0x7f2763fab8f0, 0xc20837ec60, 0xc2081da5b0)

/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:56 +0x28d

net/http.func·012(0x7f2763fab8f0, 0xc20837ec60, 0xc2081da5b0)

/home/travis/.gvm/gos/go1.3.3/src/pkg/net/http/server.go:1267 +0xc4

net/http.HandlerFunc.ServeHTTP(0xc208102fe0, 0x7f2763fab8f0, 0xc20837ec60, 0xc2081da5b0)

/home/travis/.gvm/gos/go1.3.3/src/pkg/net/http/server.go:1235 +0x40

net/http.(*ServeMux).ServeHTTP(0xc2081680f0, 0x7f2763fab8f0, 0xc20837ec60, 0xc2081da5b0)

/home/travis/.gvm/gos/go1.3.3/src/pkg/net/http/server.go:1511 +0x1a3

github.com/GoogleCloudPlatform/kubernetes/pkg/

I1126 14:21:21.461713 04815 master.go:124] Started Kubernetes Minion Controller
```

I cannot reproduce this locally :-(

**Comment by smarterclayton** [comment]
Believe this is now resolved
