### ISSUE TITLE
Panic creating wildcard certificate

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4880]
I was following the instructions here to create a wildcard certificate:

https://docs.openshift.org/latest/install_config/install/deploy_router.html#using-wildcard-certificates

```
[vagrant@openshiftdev ~]$ CA=$PWD/openshift.local.config/master
[vagrant@openshiftdev ~]$ oadm ca create-server-cert --signer-cert=$CA/ca.crt --signer-key=$CA/ca.key --signer-serial=$CA/ca.serial.txt --hostnames='*.127.0.0.1.xip.io' --cert=xipio.cert --key=xipio.key
```

It's possible I've supplied bad data, but it resulted in a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xca8e1c]

goroutine 1 [running]:
github.com/openshift/origin/pkg/cmd/server/crypto.encodeCertificates(0xc208201050, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:429 +0x2bc
github.com/openshift/origin/pkg/cmd/server/crypto.writeCertificates(0x7fff9f6a754e, 0xa, 0xc208201050, 0x2, 0x2, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:463 +0xdf
github.com/openshift/origin/pkg/cmd/server/crypto.(*TLSCertificateConfig).writeCertConfig(0xc2082d90b0, 0x7fff9f6a754e, 0xa, 0x7fff9f6a755f, 0x9, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:43 +0x67
github.com/openshift/origin/pkg/cmd/server/crypto.(*CA).MakeServerCert(0xc208307ec0, 0x7fff9f6a754e, 0xa, 0x7fff9f6a755f, 0x9, 0xc2083009f0, 0x1, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:227 +0x5b2
github.com/openshift/origin/pkg/cmd/server/admin.CreateServerCertOptions.CreateServerCert(0xc2083ac9c0, 0x7fff9f6a754e, 0xa, 0x7fff9f6a755f, 0x9, 0xc2083c8b70, 0x1, 0x1, 0x1, 0x7f284bd89870, ...)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/admin/create_servercert.go:117 +0x224
github.com/openshift/origin/pkg/cmd/server/admin.func·014(0xc2083d6d20, 0xc20806b9e0, 0x0, 0x6)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/admin/create_servercert.go:60 +0x139
github.com/spf13/cobra.(*Command).execute(0xc2083d6d20, 0xc20806b8c0, 0x6, 0x6, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:547 +0x82f
github.com/spf13/cobra.(*Command).Execute(0xc2081c3e00, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:630 +0x414
main.main()
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:22 +0x175

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x4542f80)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by liggitt** [comment]
Probably caused by ownership issues on the ca cert. See https://bugzilla.redhat.com/show_bug.cgi?id=1256692

**Comment by spadgett** [comment]
Yeah, looks like it's probably the same. `root` owns the files, but I'm running the command as `vagrant`.

**Comment by spadgett** [comment]
Changed ownership to user `vagrant`, and the error goes away.

**Comment by danmcp** [comment]
@spadgett Still need this issue?

**Comment by spadgett** [comment]
Closing as duplicate.
