### ISSUE TITLE
TestStreamClosedDuringRead flake

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5088]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3575

```
2015/10/12 15:54:33 http: panic serving 127.0.0.1:38334: bad read
goroutine 56 [running]:
net/http.(*conn).serve.func1(0xc82011e000, 0x7fcf9020c3a8, 0xc8200a8008)
	/usr/lib/golang/src/net/http/server.go:1287 +0xc6
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.(*errorReader).Read(0xc8200a6280, 0xc820220800, 0x800, 0x800, 0xc820148200, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream_test.go:151 +0x113
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.messageCopy(0xc8200e4240, 0x7fcf91486ef0, 0xc8200a6280, 0x0, 0x0, 0x0, 0x0)
	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/_test/_obj_test/stream.go:105 +0x2a2
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.(*Reader).handle(0xc8200e23f0, 0xc8200e4240)
	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/_test/_obj_test/stream.go:79 +0x2d7
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.readWebSocket.func1(0xc8200e4240)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream_test.go:171 +0x11d
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaace90, ...)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/golang.org/x/net/websocket/server.go:89 +0x324
golang.org/x/net/websocket.Handler.ServeHTTP(0xc8200e2420, 0x7fcf9020c610, 0xc82011e0b0, 0xc82011a0e0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/golang.org/x/net/websocket/server.go:112 +0x98
net/http/httptest.(*waitGroupHandler).ServeHTTP(0xc8200a4560, 0x7fcf9020c610, 0xc82011e0b0, 0xc82011a0e0)
	/usr/lib/golang/src/net/http/httptest/server.go:200 +0xff
net/http.serverHandler.ServeHTTP(0xc8200a02a0, 0x7fcf9020c610, 0xc82011e0b0, 0xc82011a0e0)
	/usr/lib/golang/src/net/http/server.go:1862 +0x207
net/http.(*conn).serve(0xc82011e000)
	/usr/lib/golang/src/net/http/server.go:1361 +0x117d
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:1910 +0x465
--- FAIL: TestStreamClosedDuringRead (0.17s)
	stream_test.go:131: unexpected server read: []
FAIL
coverage: 70.5% of statements
FAIL	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream	0.622s
```

**Comment by liggitt** [comment]
I think the root cause is net/http/httptest.(*waitGroupHandler).ServeHTTP... we can probably combine all race flakes with that in the stack

**Comment by smarterclayton** [comment]
This was fixed upstream.  We were assuming we could predict how much data makes it into the connection by waiting.
