### ISSUE TITLE
oc fails when trying to export imageStreams

### ISSUE THREAD

**Issue by maxandersen** [openshift/origin#5098]
Trying to dump all info about imageStreams so I do:

`oc export is --all=true -o json`

and I get:

```
~/c/openshift-vagrant git:oo-setup ❯❯❯ oc export is --all=true -o json                                                                                   ◼
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/openshift/origin/pkg/cmd/cli/cmd.(*defaultExporter).Export(0x35b8b80, 0x3a55be8, 0xc208100c40, 0x0, 0x0, 0x0)
	/private/tmp/openshift20150617-10923-fmrw5x/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/exporter.go:178 +0xbae
github.com/openshift/origin/pkg/cmd/cli/cmd.RunExport(0xc2081dc440, 0x3a64758, 0x35b8b80, 0x3a5e018, 0xc20802e000, 0x3a53730, 0xc20802e008, 0xc20814fd40, 0xc2083b4200, 0x1, ...)
	/private/tmp/openshift20150617-10923-fmrw5x/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/export.go:121 +0x792
github.com/openshift/origin/pkg/cmd/cli/cmd.func·015(0xc20814fd40, 0xc2083b4200, 0x1, 0x4)
	/private/tmp/openshift20150617-10923-fmrw5x/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/export.go:61 +0x118
github.com/spf13/cobra.(*Command).execute(0xc20814fd40, 0xc2083b41c0, 0x4, 0x4, 0x0, 0x0)
	/private/tmp/openshift20150617-10923-fmrw5x/Godeps/_workspace/src/github.com/spf13/cobra/command.go:476 +0x65c
github.com/spf13/cobra.(*Command).Execute(0xc2082d9520, 0x0, 0x0)
	/private/tmp/openshift20150617-10923-fmrw5x/Godeps/_workspace/src/github.com/spf13/cobra/command.go:541 +0x18d
main.main()
	/private/tmp/openshift20150617-10923-fmrw5x/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:22 +0x175

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x35a83c0)
	/private/tmp/openshift20150617-10923-fmrw5x/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/private/tmp/openshift20150617-10923-fmrw5x/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 39 [IO wait]:
net.(*pollDesc).Wait(0xc208481aa0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208481aa0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208481a40, 0xc20824d000, 0x800, 0x800, 0x0, 0x3a53808, 0xc2084ca028)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802ff00, 0xc20824d000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc208488cf0, 0x3a66030, 0xc20802ff00, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208363340, 0x17, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208363340, 0xc208453000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x3a66468, 0xc208363340, 0xc208143d38, 0xc208453000, 0x1000, 0x1000, 0x1677520, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2084a1c60, 0xc208453000, 0x1000, 0x1000, 0xc208119b00, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2084636e0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2084636e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208143ce0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 40 [select]:
net/http.(*persistConn).writeLoop(0xc208143ce0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:661 +0xcbc
```

oc export of services works fine. but imagestreams fails.

**Comment by kargakis** [comment]
@maxandersen what version of OpenShift are you running?

**Comment by maxandersen** [comment]
@kargakis this is against https://console.engint.openshift.com/console/

**Comment by kargakis** [comment]
Hmm, it must be using an old version and should be updated because this issue was fixed in https://github.com/openshift/origin/pull/3925.

**Comment by maxandersen** [comment]
so updating the cli should work?

**Comment by kargakis** [comment]
yes

**Comment by maxandersen** [comment]
that did it. sorry for the noise.
