### ISSUE TITLE
k8s uti/wsstream test flakes

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5220]
```
2015/10/19 22:59:49 http: panic serving 127.0.0.1:49625: bad read
goroutine 35 [running]:
net/http.(*conn).serve.func1(0xc820144160, 0xaa1700, 0xc820140018)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1287 +0xb5
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.(*errorReader).Read(0xc8203320c0, 0xc820166800, 0x800, 0x800, 0xc82013a800, 0x0, 0x0)
	/Users/clayton/projects/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream_test.go:151 +0xcc
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.messageCopy(0xc820168240, 0xe80000, 0xc8203320c0, 0x0, 0x0, 0x0, 0x0)
	/Users/clayton/projects/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream.go:105 +0x1dd
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.(*Reader).handle(0xc820324150, 0xc820168240)
	/Users/clayton/projects/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream.go:86 +0x196
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.readWebSocket.func1(0xc820168240)
	/Users/clayton/projects/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream_test.go:171 +0xcf
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x53e280, ...)
	/Users/clayton/projects/go/src/github.com/openshift/origin/Godeps/_workspace/src/golang.org/x/net/websocket/server.go:89 +0x2d2
golang.org/x/net/websocket.Handler.ServeHTTP(0xc820324180, 0xe000d0, 0xc820144210, 0xc82015e2a0)
	/Users/clayton/projects/go/src/github.com/openshift/origin/Godeps/_workspace/src/golang.org/x/net/websocket/server.go:112 +0x83
net/http/httptest.(*waitGroupHandler).ServeHTTP(0xc82031e220, 0xe000d0, 0xc820144210, 0xc82015e2a0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/httptest/server.go:200 +0xc2
net/http.serverHandler.ServeHTTP(0xc82035a120, 0xe000d0, 0xc820144210, 0xc82015e2a0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820144160)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1910 +0x3f6
--- FAIL: TestStreamClosedDuringRead (0.00s)
	stream_test.go:131: unexpected server read: []
FAIL
FAIL	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream	0.023s
```

**Comment by liggitt** [comment]
this in jenkins or travis, go 1.4 or 1.5?

**Comment by smarterclayton** [comment]
1.5, local.

**Comment by smarterclayton** [comment]
Fixed with https://github.com/kubernetes/kubernetes/pull/16241
