### ISSUE TITLE
OpenShift eating my CPU

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5355]
When I run the latest OSE image in Docker container, everything works normally but after some time and after I start some builds and deploy stuff the "openshift" process start eating >100% CPU and it keeps doing that until I stop the container. This sometimes takes couple minutes to happen, sometimes it happens in few seconds...

Here is heap dump: http://omicron.mifo.sk/heap.txt
Here is goroutine dump: http://omicron.mifo.sk/go.txt
And here is loglevel=5 openshift log: http://omicron.mifo.sk/ose.txt

```console
[vagrant@localhost ~]$ docker run openshift3/ose version
openshift v3.0.2.902
kubernetes v1.2.0-alpha.1-1107-g4c8e6f4
etcd 2.1.2
```

The container is started like this (on the RHEL 7.1  VM with docker 1.7.1:

```console
$ docker run -d --name "ose" --privileged --net=host --pid=host \
  -v /:/rootfs:ro \
  -v /var/run:/var/run:rw \
  -v /sys:/sys:ro \
  -v /var/lib/docker:/var/lib/docker:rw \
  -v #{ORIGIN_DIR}/openshift.local.volumes:#{ORIGIN_DIR}/openshift.local.volumes:z \
  -v #{ORIGIN_DIR}/openshift.local.config:#{ORIGIN_DIR}/openshift.local.config:z \
  -v #{ORIGIN_DIR}/openshift.local.etcd:#{ORIGIN_DIR}/openshift.local.etcd:z \
  openshift3/ose start \
   --master="https://#{PUBLIC_ADDRESS}:8443" \
   --etcd-dir="#{ORIGIN_DIR}/openshift.local.etcd"
```

```console
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
24806 root      20   0 1456368 240616  19092 S 193.4 12.8   2:46.28 openshift 
```
The registry and router are also installed and running properly.

It seems like something got stuck on decoding/encoding JSON, but I can't see anything in the container logs...

@smarterclayton @deads2k FYI

(since this is very reproducible and it is happening with the OSE Docker image, this should get P1?)

**Comment by hferentschik** [comment]
+1 I have been experiencing the same. The only way to move on was to restart the container

**Comment by mfojtik** [comment]
@sdodson FYI

**Comment by liggitt** [comment]
Are you running the all in one, or can you tell whether it is the master or node process that is eating CPU?

**Comment by mfojtik** [comment]
@liggitt all-in-one

**Comment by smarterclayton** [comment]
Please capture a CPU dump

**Comment by maxandersen** [comment]
@smarterclayton sorry for my ignorance but what kind of CPU dump would like to have ? is a plain top dump enough ?

**Comment by smarterclayton** [comment]
Michal's on vacation unfortunately so I was mostly asking him - basically a
CPU profile from OpenShift when at 100% CPU so we can see what's hot.  I
don't think this is something you have to gather, whomever ends up owning
this will need to recreate and verify.

**Comment by maxandersen** [comment]
okey.

**Comment by liggitt** [comment]
Were you following build logs in the CLI or the web console? Seeing 250% CPU usage after viewing logs in the web console. I did this:

1. Start openshift
2. Run a build, letting it complete successfully and deploy
3. View logs for the completed build in the web console.
4. Logs took about 25 seconds to load, then the server process went to 250% CPU and I saw this in the server log:
```
I1026 12:22:41.723533   10467 server.go:1064] GET /containerLogs/bob/mynode-2-build/sti-build?follow=true: (2.11698ms) 500
goroutine 2627 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20e4ac480, 0x1f4)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc20e4ac7e0, 0x1f4, 0xc20e5cd340, 0x40, 0x0, 0x0)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:199 +0x5a
github.com/emicklei/go-restful.(*Response).WriteError(0xc20e4ac7e0, 0x1f4, 0x7fe448204700, 0xc20a4ad480, 0x0, 0x0)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:187 +0xa8
k8s.io/kubernetes/pkg/kubelet.(*Server).getContainerLogs(0xc209155800, 0xc20ecf8c90, 0xc20e4ac7e0)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server.go:477 +0x1440
k8s.io/kubernetes/pkg/kubelet.*Server.(k8s.io/kubernetes/pkg/kubelet.getContainerLogs)·fm(0xc20ecf8c90, 0xc20e4ac7e0)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server.go:317 +0x3b
github.com/emicklei/go-restful.func·009(0xc20ecf8c90, 0xc20e4ac7e0)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20ecf8d20, 0xc20ecf8c90, 0xc20e4ac7e0)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/kubelet.func·019(0xc20ecf8c90, 0xc20e4ac7e0, 0xc20ecf8d20)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server.go:207 +0x6e1
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20ecf8d20, 0xc20ecf8c90, 0xc20e4ac7e0)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restfu [[Go 1.1 package http] 127.0.0.1:38051]
2015-10-26 12:22:41.723634 I | http: WriteHeader called with both Transfer-Encoding of "chunked" and a Content-Length of 64
I1026 12:22:41.743989   10467 node_auth.go:142] Node request attributes: namespace=, user=system:openshift-node-admin, groups=[system:node-admins system:authenticated], attrs=authorizer.DefaultAuthorizationAttributes{Verb:"proxy", APIVersion:"v1", APIGroup:"", Resource:"nodes", ResourceName:"jliggitt-laptop", RequestAttributes:interface {}(nil), NonResourceURL:false, URL:"/containerLogs/bob/mynode-2-build/sti-build"}
I1026 12:22:41.744096   10467 authorizer.go:30] allowed=true, reason=allowed by cluster rule
I1026 12:22:41.744299   10467 server.go:1064] GET /containerLogs/bob/mynode-2-build/sti-build?follow=true: (553.331µs) 500
goroutine 2627 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20ddcd500, 0x1f4)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc20ddcd560, 0x1f4, 0xc20ac8b200, 0x40, 0x0, 0x0)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:199 +0x5a
github.com/emicklei/go-restful.(*Response).WriteError(0xc20ddcd560, 0x1f4, 0x7fe448204700, 0xc20ece80b0, 0x0, 0x0)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:187 +0xa8
k8s.io/kubernetes/pkg/kubelet.(*Server).getContainerLogs(0xc209155800, 0xc20d65e720, 0xc20ddcd560)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server.go:477 +0x1440
k8s.io/kubernetes/pkg/kubelet.*Server.(k8s.io/kubernetes/pkg/kubelet.getContainerLogs)·fm(0xc20d65e720, 0xc20ddcd560)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server.go:317 +0x3b
github.com/emicklei/go-restful.func·009(0xc20d65e720, 0xc20ddcd560)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20d65e7b0, 0xc20d65e720, 0xc20ddcd560)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/kubelet.func·019(0xc20d65e720, 0xc20ddcd560, 0xc20d65e7b0)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server.go:207 +0x6e1
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20d65e7b0, 0xc20d65e720, 0xc20ddcd560)
	/home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
```

**Comment by liggitt** [comment]
Captured profile by starting with `OPENSHIFT_PROFILE=web`, and grabbing with `go tool pprof http://localhost:6060/debug/pprof/profile` when at 250% CPU:

![profile](https://cloud.githubusercontent.com/assets/980082/10735223/5cf77118-7bdd-11e5-889c-0727910bec5f.png)

**Comment by smarterclayton** [comment]
Suspect this is a hot read loop for zero byte reads in the websocket code.

**Comment by smarterclayton** [comment]
Need to isolate where this is caused by a websocket client (browser vs not)
or the server.

**Comment by liggitt** [comment]
For the record, CLI log streaming doesn't cause it (`oc start-build ... --follow` or `oc build-logs ...`)

**Comment by liggitt** [comment]
Error being hotlooped:
```
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
read tcp4 10.13.129.51:55938: use of closed network connection
use of closed network connection
```

**Comment by liggitt** [comment]
Guessing this is the issue, since `wsstream.ignoreReceives` appears in @mfojtik's goroutine dump at https://github.com/openshift/origin/issues/5355#issue-112992105

**Comment by mfojtik** [comment]
@liggitt @smarterclayton this is not yet fixed in the OSE image @sdodson is building in RCM registry

**Comment by sdodson** [comment]
Michal,

I've rebuilt the image, please give it a shot. You should get
openshift v3.0.2.903-114-g2849767

**Comment by mfojtik** [comment]
@sdodson thanks, testing now
