### ISSUE TITLE
Build error: Failed to push image: unable to ping registry endpoint

### ISSUE THREAD

**Issue by johnjelinek** [openshift/origin#5383]
I spun up openshift with the docker image following the `Getting Started` instructions. I am not able to push the node-ex example to the docker registry. I added the options to allow insecure-registry in the docker daemon.

Running:
```
# oc version
oc v1.0.6-908-gc779c21
kubernetes v1.2.0-alpha.1-1107-g4c8e6f4

# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
```

```
[root@localhost openshift]# oc status
In project default on server https://localhost:8443

service/docker-registry - 172.30.2.76:5000
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:v1.0.6
    #1 deployed 3 hours ago - 1 pod

service/kubernetes - 172.30.0.1:443

[root@localhost openshift]# curl https://172.30.2.76:5000/v1/_ping
curl: (35) SSL received a record that exceeded the maximum permissible length.
```

```
[root@localhost openshift]# oc logs nodejs-ex-1-build
I1024 15:51:29.974857       1 sti.go:407] ---> Installing application source
I1024 15:51:29.979209       1 sti.go:407] ---> Building your Node application from source
E1024 15:51:30.400059       1 util.go:85] npm info it worked if it ends with ok
E1024 15:51:30.400675       1 util.go:85] npm info using npm@1.4.28
E1024 15:51:30.400701       1 util.go:85] npm info using node@v0.10.35
E1024 15:51:30.609138       1 util.go:85] npm info preinstall nodejs-ex@0.0.1
E1024 15:51:30.641861       1 util.go:85] npm info trying registry request attempt 1 at 15:51:30
...truncated for brevity...
I1024 15:51:36.586988       1 sti.go:407]
I1024 15:51:36.587013       1 sti.go:407] > kerberos@0.0.15 install /opt/app-root/src/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
I1024 15:51:36.587023       1 sti.go:407] > (node-gyp rebuild) || (exit 0)
I1024 15:51:36.587031       1 sti.go:407]
E1024 15:51:36.701924       1 util.go:85] gyp info it worked if it ends with ok
E1024 15:51:36.704885       1 util.go:85] gyp info using node-gyp@1.0.2
E1024 15:51:36.706291       1 util.go:85] gyp info using node@0.10.35 | linux | x64
E1024 15:51:36.819484       1 util.go:85] gyp info spawn python
E1024 15:51:36.821858       1 util.go:85] gyp info spawn args [ '/opt/rh/v8314/root/usr/bin/gyp',
E1024 15:51:36.821922       1 util.go:85] gyp info spawn args   'binding.gyp',
E1024 15:51:36.823785       1 util.go:85] gyp info spawn args   '-f',
E1024 15:51:36.823809       1 util.go:85] gyp info spawn args   'make',
E1024 15:51:36.823826       1 util.go:85] gyp info spawn args   '-I',
E1024 15:51:36.823856       1 util.go:85] gyp info spawn args   '/opt/app-root/src/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build/config.gypi',
E1024 15:51:36.823898       1 util.go:85] gyp info spawn args   '-I',
E1024 15:51:36.823934       1 util.go:85] gyp info spawn args   '/opt/rh/nodejs010/root/usr/lib/node_modules/node-gyp/addon-rpm.gypi',
E1024 15:51:36.823968       1 util.go:85] gyp info spawn args   '-I',
E1024 15:51:36.824009       1 util.go:85] gyp info spawn args   '/opt/rh/nodejs010/root/usr/share/node/common.gypi',
E1024 15:51:36.824044       1 util.go:85] gyp info spawn args   '-Dlibrary=shared_library',
E1024 15:51:36.824085       1 util.go:85] gyp info spawn args   '-Dvisibility=default',
E1024 15:51:36.824126       1 util.go:85] gyp info spawn args   '-Dnode_root_dir=/opt/rh/nodejs010/root/usr/share/node',
E1024 15:51:36.824579       1 util.go:85] gyp info spawn args   '-Dmodule_root_dir=/opt/app-root/src/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos',
E1024 15:51:36.824601       1 util.go:85] gyp info spawn args   '--depth=.',
E1024 15:51:36.824616       1 util.go:85] gyp info spawn args   '--no-parallel',
E1024 15:51:36.828613       1 util.go:85] gyp info spawn args   '--generator-output',
E1024 15:51:36.828647       1 util.go:85] gyp info spawn args   'build',
E1024 15:51:36.828678       1 util.go:85] gyp info spawn args   '-Goutput_dir=.' ]
E1024 15:51:36.838184       1 util.go:85] Traceback (most recent call last):
E1024 15:51:36.838221       1 util.go:85]   File "/opt/rh/v8314/root/usr/bin/gyp", line 15, in <module>
E1024 15:51:36.838245       1 util.go:85]     import gyp
E1024 15:51:36.838253       1 util.go:85] ImportError: No module named gyp
E1024 15:51:36.841325       1 util.go:85] gyp ERR! configure error
E1024 15:51:36.843902       1 util.go:85] gyp ERR! stack Error: `gyp` failed with exit code: 1
E1024 15:51:36.844009       1 util.go:85] gyp ERR! stack     at ChildProcess.onCpExit (/opt/rh/nodejs010/root/usr/lib/node_modules/node-gyp/lib/configure.js:343:16)
E1024 15:51:36.845638       1 util.go:85] gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
E1024 15:51:36.845680       1 util.go:85] gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
E1024 15:51:36.845697       1 util.go:85] gyp ERR! System Linux 3.10.0-229.14.1.el7.x86_64
E1024 15:51:36.845709       1 util.go:85] gyp ERR! command "node" "/opt/rh/nodejs010/root/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
E1024 15:51:36.845720       1 util.go:85] gyp ERR! cwd /opt/app-root/src/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
E1024 15:51:36.845731       1 util.go:85] gyp ERR! node -v v0.10.35
E1024 15:51:36.845741       1 util.go:85] gyp ERR! node-gyp -v v1.0.2
E1024 15:51:36.845751       1 util.go:85] gyp ERR! not ok
E1024 15:51:36.851706       1 util.go:85] npm info postinstall kerberos@0.0.15
E1024 15:51:36.851741       1 util.go:85] npm info build /opt/app-root/src/node_modules/mongodb/node_modules/mongodb-core
E1024 15:51:36.851972       1 util.go:85] npm info linkStuff mongodb-core@1.2.19
E1024 15:51:36.852773       1 util.go:85] npm info install mongodb-core@1.2.19
E1024 15:51:36.854315       1 util.go:85] npm info postinstall mongodb-core@1.2.19
E1024 15:51:36.856028       1 util.go:85] npm info build /opt/app-root/src/node_modules/mongodb
E1024 15:51:36.856314       1 util.go:85] npm info linkStuff mongodb@2.0.46
E1024 15:51:36.856928       1 util.go:85] npm info install mongodb@2.0.46
E1024 15:51:36.859832       1 util.go:85] npm info postinstall mongodb@2.0.46
E1024 15:51:36.861635       1 util.go:85] npm info build /opt/app-root/src
E1024 15:51:36.861808       1 util.go:85] npm info linkStuff nodejs-ex@0.0.1
E1024 15:51:36.862596       1 util.go:85] npm info install nodejs-ex@0.0.1
E1024 15:51:36.863772       1 util.go:85] npm info postinstall nodejs-ex@0.0.1
E1024 15:51:36.865120       1 util.go:85] npm info prepublish nodejs-ex@0.0.1
I1024 15:51:36.938646       1 sti.go:407] ejs@2.3.4 node_modules/ejs
I1024 15:51:36.938691       1 sti.go:407]
I1024 15:51:36.938699       1 sti.go:407] express@4.13.3 node_modules/express
I1024 15:51:36.938706       1 sti.go:407] ├── escape-html@1.0.2
I1024 15:51:36.938711       1 sti.go:407] ├── merge-descriptors@1.0.0
I1024 15:51:36.938718       1 sti.go:407] ├── array-flatten@1.1.1
I1024 15:51:36.938724       1 sti.go:407] ├── cookie@0.1.3
I1024 15:51:36.938730       1 sti.go:407] ├── utils-merge@1.0.0
I1024 15:51:36.938735       1 sti.go:407] ├── cookie-signature@1.0.6
I1024 15:51:36.938741       1 sti.go:407] ├── methods@1.1.1
I1024 15:51:36.938747       1 sti.go:407] ├── fresh@0.3.0
I1024 15:51:36.938753       1 sti.go:407] ├── range-parser@1.0.2
I1024 15:51:36.938758       1 sti.go:407] ├── vary@1.0.1
I1024 15:51:36.938764       1 sti.go:407] ├── path-to-regexp@0.1.7
I1024 15:51:36.938770       1 sti.go:407] ├── content-type@1.0.1
I1024 15:51:36.938776       1 sti.go:407] ├── etag@1.7.0
I1024 15:51:36.938781       1 sti.go:407] ├── parseurl@1.3.0
I1024 15:51:36.938787       1 sti.go:407] ├── content-disposition@0.5.0
I1024 15:51:36.938793       1 sti.go:407] ├── serve-static@1.10.0
I1024 15:51:36.938798       1 sti.go:407] ├── depd@1.0.1
I1024 15:51:36.938804       1 sti.go:407] ├── qs@4.0.0
I1024 15:51:36.938810       1 sti.go:407] ├── on-finished@2.3.0 (ee-first@1.1.1)
I1024 15:51:36.938815       1 sti.go:407] ├── finalhandler@0.4.0 (unpipe@1.0.0)
I1024 15:51:36.938821       1 sti.go:407] ├── debug@2.2.0 (ms@0.7.1)
I1024 15:51:36.938827       1 sti.go:407] ├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
I1024 15:51:36.938833       1 sti.go:407] ├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, mime@1.3.4, ms@0.7.1, http-errors@1.3.1)
I1024 15:51:36.938839       1 sti.go:407] ├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
I1024 15:51:36.938845       1 sti.go:407] └── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)
I1024 15:51:36.938851       1 sti.go:407]
I1024 15:51:36.938856       1 sti.go:407] mongodb@2.0.46 node_modules/mongodb
I1024 15:51:36.938862       1 sti.go:407] ├── es6-promise@2.1.1
I1024 15:51:36.938869       1 sti.go:407] ├── readable-stream@1.0.31 (inherits@2.0.1, isarray@0.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
I1024 15:51:36.938874       1 sti.go:407] └── mongodb-core@1.2.19 (bson@0.4.19, kerberos@0.0.15)
E1024 15:51:36.940605       1 util.go:85] npm info ok
I1024 15:51:52.677273       1 sti.go:149] Using provided push secret for pushing 172.30.2.76:5000/test/nodejs-ex:latest image
I1024 15:51:52.677328       1 sti.go:151] Pushing 172.30.2.76:5000/test/nodejs-ex:latest image ...
E1024 15:51:52.692496       1 dockerutil.go:73] push for image 172.30.2.76:5000/test/nodejs-ex:latest failed, will retry in 5s seconds ...
E1024 15:51:57.698213       1 dockerutil.go:73] push for image 172.30.2.76:5000/test/nodejs-ex:latest failed, will retry in 5s seconds ...
E1024 15:52:02.704664       1 dockerutil.go:73] push for image 172.30.2.76:5000/test/nodejs-ex:latest failed, will retry in 5s seconds ...
E1024 15:52:07.712062       1 dockerutil.go:73] push for image 172.30.2.76:5000/test/nodejs-ex:latest failed, will retry in 5s seconds ...
E1024 15:52:12.719322       1 dockerutil.go:73] push for image 172.30.2.76:5000/test/nodejs-ex:latest failed, will retry in 5s seconds ...
E1024 15:52:17.725471       1 dockerutil.go:73] push for image 172.30.2.76:5000/test/nodejs-ex:latest failed, will retry in 5s seconds ...
E1024 15:52:22.732399       1 dockerutil.go:73] push for image 172.30.2.76:5000/test/nodejs-ex:latest failed, will retry in 5s seconds ...
F1024 15:52:27.732645       1 builder.go:54] Build error: Failed to push image: unable to ping registry endpoint https://172.30.2.76:5000/v0/
v2 ping attempt failed with error: Get https://172.30.2.76:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://172.30.2.76:5000/v1/_ping: tls: oversized record received with length 20527
```

**Comment by smarterclayton** [comment]
How many nodes do you have?  In #3841 some of the nodes did not have --insecure-registry

**Comment by johnjelinek** [comment]
Just one node. I am running openshift via the all-in-one docker image.



—

**Comment by bparees** [comment]
looks like it can't reach the registry service at all... can you confirm 172.30.2.76 is the right ip for your registry service and see if there's anything interesting in the logs for the registry pod?

**Comment by Mangirdaz** [comment]
i get this when i rebuild internal registry and it gets new IP. and i cant get new route to new internal registry... Still looking how to update records.

**Comment by bparees** [comment]
@Mangirdaz normally when the registry gets a new ip you should just need to restart the openshift master.

@johnjelinek any update here?

**Comment by johnjelinek** [comment]
Sorry, I deleted my instance. I'll try again at 1.1.



—

**Comment by bparees** [comment]
closing based on age, please reopen if you are still having trouble after you move to 1.1.

**Comment by paralin** [comment]
I'm getting this now with a fresh cluster running kubernetes latest... openshift under kube.
