### ISSUE TITLE
Flake in framework controller test

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5389]
```
E1025 18:49:51.659382   17067 util.go:82] Recovered from panic: "sync: negative WaitGroup counter" (sync: negative WaitGroup counter)
/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:76
/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:64
/tmp/workdir/go/src/runtime/asm_amd64.s:437
/tmp/workdir/go/src/runtime/panic.go:423
/tmp/workdir/go/src/sync/waitgroup.go:70
/tmp/workdir/go/src/sync/waitgroup.go:95
/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:333
/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:182
<autogenerated>:23
/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:252
/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:126
/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96
/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:125
/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:126
/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96
/tmp/workdir/go/src/runtime/asm_amd64.s:1696
--- FAIL: TestUpdate (2.01s)
panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
	panic: sync: WaitGroup is reused before previous Wait has returned
goroutine 28 [running]:
testing.tRunner.func1(0xc820406900)
	/tmp/workdir/go/src/testing/testing.go:450 +0x1f5
sync.(*WaitGroup).Wait(0xc82040e510)
	/tmp/workdir/go/src/sync/waitgroup.go:128 +0x178
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework_test.TestUpdate(0xc820406900)
	/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/git
```

**Comment by ncdc** [comment]
Upstream issue: https://github.com/kubernetes/kubernetes/issues/17018

**Comment by ncdc** [comment]
Upstream has 1 change that we don't have that attempted to get rid of the flake, but on Kube master as of this morning, I'm still able to get a failure.

**Comment by smarterclayton** [comment]
Fixed
