### ISSUE TITLE
UI flake - chrome not reachable

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5854]
@jwforres 

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7053/consoleText

```
Running "protractor:chrome" (protractor) task
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://172.18.10.155:46072/wd/hub
ERROR - Unable to start a WebDriver session.

/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: chrome not reachable
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.10.0-229.7.2.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.40 seconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'ip-172-18-10-155.ec2.internal', ip: '172.18.10.155', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-229.7.2.el7.x86_64', java.version: '1.7.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at new bot.Error (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:152:24
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at fulfill (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
    at Function.webdriver.WebDriver.createSession (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
    at Builder.build (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/builder.js:294:22)
    at DriverProvider.getNewDriver (/data/src/github.com/openshift/origin/assets/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at Runner.createBrowser (/data/src/github.com/openshift/origin/assets/node_modules/protractor/lib/runner.js:180:37)
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/lib/runner.js:257:21
    at _fulfilled (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/q/q.js:759:13)
[launcher] Process exited with error code 1
>> 
Fatal error: protractor exited with code: 1
```

**Comment by spadgett** [comment]
This is no longer an issue.
