### ISSUE TITLE
UI Flake - Wait timed out

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#5881]
```
**************************************************
*                    Failures                    *
**************************************************

1)  authenticated e2e-user new project when creating a new project should validate taken name when trying to create
  - Error: Wait timed out after 3015ms
      at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1425:29
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at [object Object].then (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:522:7)
    at Object.webdriver.promise.asap (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:767:11)
    at newFrame.onComplete (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1670:25)
    at [object Object].webdriver.promise.Frame_.notify_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1914:5)
    at [object Object]._onTimeout (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1901:11)
==== async task ====
    at [object Object].webdriver.promise.ControlFlow.wait (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1410:15)
    at [object Object].webdriver.WebDriver.wait (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:646:21)
    at login (/data/src/github.com/openshift/origin/assets/test/e2e/test.js:38:12)
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/e2e/test.js:209:7)
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/jasminewd/index.js:94:14
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
    at [object Object].wrapper [as _onTimeout] (timers.js:261:14)
==== async task ====
Asynchronous test function: beforeEach()
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/jasminewd/index.js:93:33)
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/minijasminenode/lib/async-callback.js:45:37)
Error
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/e2e/test.js:207:5)
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/e2e/test.js:206:3)
    at Object.<anonymous> (/data/src/github.com/openshift/origin/assets/test/e2e/test.js:3:1)

```

**Comment by jwforres** [comment]
Next time someone sees this flake, please see if there are any screenshots available in the artifacts on the jenkins job.

**Comment by jwforres** [comment]
Example with a screenshot https://github.com/openshift/origin/pull/6120#issuecomment-166998621

**Comment by spadgett** [comment]
See also https://github.com/openshift/origin/pull/6407#issuecomment-169320796

**Comment by spadgett** [comment]
Also https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4506/console

```
1)  unauthenticated user should be able to log in
  - Error: Error while waiting for Protractor to sync with the page: "[ng:test] no injector found for element argument to getTestability\nhttp://errors.angularjs.org/1.3.8/ng/test"
      at Error (<anonymous>)
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1526:15
...
==== async task ====
Protractor.waitForAngular()
    at [object Object].webdriver.WebDriver.schedule (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
...
Error
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/e2e.js:21:5)
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/e2e.js:12:3)
    at Object.<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/e2e.js:4:1)
```

Screenshot:

![unauthenticated_user_should_be_able_to_log_in_png__1024x1987_](https://cloud.githubusercontent.com/assets/1167259/12144178/1659bfa4-b454-11e5-8e39-ed6e87460703.png)

**Comment by spadgett** [comment]
I wonder if adding the `ng-cloak` around the user dropdown made this worse. Looks like we're waiting for the presence of the `.username` element, which won't appear now until Angular is loaded and the template is compiled.

```
  driver.wait(function() {
    return driver.isElementPresent(by.css(".navbar-utility .username"));
  }, 3000);
```

I'm not sure 3s is long enough.

**Comment by spadgett** [comment]
I realize there are different errors here, but the most common seems to be login.

**Comment by spadgett** [comment]
Hm, maybe `isElementPresent` will still return true with `ng-cloak` because the element is there, just not visible.

**Comment by smarterclayton** [comment]
Haven't seen since.

**Comment by smarterclayton** [comment]
Nm, caps was new.

**Comment by soltysh** [comment]
Seen here: https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5023/console
And this screenshot appears relevant:
![](https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5023/artifact/origin/artifacts/screenshots/%20authenticated%20e2e-user%20with%20test%20project%20should%20have%20access%20to%20the%20test%20project.png)

**Comment by spadgett** [comment]
UI tests are looking for a deployment triggered by an image change, but it's not there.

https://github.com/openshift/origin/blob/master/assets/test/integration/e2e.js#L67

**Comment by jwforres** [comment]
@ironcladlou what would cause a deployment to say it got triggered by a config change when it was really triggered by an image change?? see the screenshot https://github.com/openshift/origin/issues/5881#issuecomment-186170437  the frontend deployment was the result of a build pushing an image.

**Comment by ironcladlou** [comment]
@jwforres 
>@ironcladlou what would cause a deployment to say it got triggered by a config change when it was really triggered by an image change?? see the screenshot #5881 (comment) the frontend deployment was the result of a build pushing an image.

I think we'll need to see the deploymentConfig itself to verify assumptions first (i.e. is the image trigger cause really missing from deploymentConfig.status). Possible to get?

**Comment by jwforres** [comment]
@ironcladlou should be in the etcd dump from test-end-to-end https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5023/artifact/origin/artifacts/test-end-to-end-docker/artifacts/etcd_dump.json

**Comment by ironcladlou** [comment]
>@jwforres 
@ironcladlou should be in the etcd dump from test-end-to-end https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5023/artifact/origin/artifacts/test-end-to-end-docker/artifacts/etcd_dump.json

Thanks. I made https://github.com/openshift/origin/issues/7464 to track it.

**Comment by danmcp** [comment]
I don't think this is valid here anymore.
