### ISSUE TITLE
panic on 'oc status' when BuildConfig with no output exists

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#5945]
After creating a build config with no output: 

```
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2015-11-18T14:41:17Z
  labels:
    app: gitauthtest
    template: gitserver
  name: gitauthtest
  namespace: devproj
  resourceVersion: "634"
  selfLink: /oapi/v1/namespaces/devproj/buildconfigs/gitauthtest
  uid: 6d487478-8e02-11e5-9cf2-3c970e88b00e
spec:
  output: {}
  resources: {}
  source:
    git:
      uri: http://gitserver-tokenauth.linux.xip.io/ruby-hello-world
    sourceSecret:
      name: builder-token-nbme5
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ruby:latest
        namespace: openshift
    type: Source
  triggers: []
status:
  lastVersion: 1
```

Run 'oc status', you get:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xe9e14c]

goroutine 1 [running]:
github.com/gonum/graph/concrete.(*DirectedGraph).Edge(0xc20837fc80, 0x7ffbe56ddb58, 0xc208320e80, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/gonum/graph/concrete/directed.go:176 +0xac
github.com/openshift/origin/pkg/api/graph.Graph.AddEdge(0x7ffbe56d0c18, 0xc20837fc80, 0x7ffbe56d0c70, 0x2207158, 0x7ffbe56d0bd0, 0xc20837fc80, 0xc20837fcb0, 0xc20837fc80, 0x7ffbe56ddb58, 0xc208320e80, ...)
	/data/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/api/graph/graph.go:345 +0x3e1
github.com/openshift/origin/pkg/api/graph.(*Graph).AddEdge(0xc2083c1c80, 0x7ffbe56ddb58, 0xc208320e80, 0x0, 0x0, 0x16bc6b0, 0xb)
	<autogenerated>:63 +0xee
github.com/openshift/origin/pkg/build/graph.AddOutputEdges(0x7ffbe56dd8e8, 0xc2083c1c80, 0xc208320e80)
	/data/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/graph/edges.go:83 +0xd0
github.com/openshift/origin/pkg/build/graph.AddInputOutputEdges(0x7ffbe56dd8e8, 0xc2083c1c80, 0xc208320e80, 0xc208320e80)
	/data/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/graph/edges.go:116 +0x80
github.com/openshift/origin/pkg/build/graph.AddAllInputOutputEdges(0x7ffbe56dd8e8, 0xc2083c1c80)
	/data/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/graph/edges.go:124 +0x136
github.com/openshift/origin/pkg/cmd/cli/describe.(*ProjectStatusDescriber).MakeGraph(0xc20837fb90, 0xc208376a40, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/data/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/describe/projectstatus.go:107 +0x15c8
github.com/openshift/origin/pkg/cmd/cli/describe.(*ProjectStatusDescriber).Describe(0xc20837fb90, 0xc208376a40, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/describe/projectstatus.go:119 +0x80
github.com/openshift/origin/pkg/cmd/cli/cmd.RunStatus(0xc20800b7a0, 0x7ffbe56c3130, 0xc20802c008, 0x0, 0x0)
	/data/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/status.go:77 +0x2b5
github.com/openshift/origin/pkg/cmd/cli/cmd.func·032(0xc2082350e0, 0x2207158, 0x0, 0x0)
	/data/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/status.go:50 +0xed
github.com/spf13/cobra.(*Command).execute(0xc2082350e0, 0x2207158, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:547 +0x82f
github.com/spf13/cobra.(*Command).Execute(0xc2082345a0, 0x0, 0x0)
	/data/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:630 +0x414
main.main()
	/data/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:22 +0x175

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 10 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x21f8ee0)
	/data/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/data/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 35 [IO wait]:
net.(*pollDesc).Wait(0xc2080ffa30, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080ffa30, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080ff9d0, 0xc2084ec000, 0x8000, 0x8000, 0x0, 0x7ffbe56c32e0, 0xc208429b60)
	/usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2082a6000, 0xc2084ec000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc2082a4690, 0x7ffbe56d0500, 0xc2082a6000, 0x5, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc2082ac000, 0x17, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc2082ac000, 0xc2082c8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7ffbe56d0890, 0xc2082ac000, 0xc2080c5398, 0xc2082c8000, 0x1000, 0x1000, 0x12dcb60, 0x0, 0x0)
	/usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2082a39e0, 0xc2082c8000, 0x1000, 0x1000, 0xc208254000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2082ae600)
	/usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2082ae600, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080c5340)
	/usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 36 [select]:
net/http.(*persistConn).writeLoop(0xc2080c5340)
	/usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 100 [IO wait]:
net.(*pollDesc).Wait(0xc2083b41b0, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2083b41b0, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2083b4150, 0xc208496c00, 0x400, 0x400, 0x0, 0x7ffbe56c32e0, 0xc20844a110)
	/usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20842a000, 0xc208496c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20837ec90, 0x7ffbe56d0500, 0xc20842a000, 0x5, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208446000, 0x17, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208446000, 0xc208582000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7ffbe56d0890, 0xc208446000, 0xc2080c5448, 0xc208582000, 0x1000, 0x1000, 0x7ffbe56b2c30, 0x0, 0x0)
	/usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20800a980, 0xc208582000, 0x1000, 0x1000, 0xc207fc17ff, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208082360)
	/usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208082360, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080c53f0)
	/usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 101 [select]:
net/http.(*persistConn).writeLoop(0xc2080c53f0)
	/usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:661 +0xcbc
```

**Comment by csrwng** [comment]
@gabemontero

**Comment by bparees** [comment]
@gabemontero since you're already mucking about in oc status, can you fix this while you're at it?  thanks.
