### ISSUE TITLE
For the sample-app it never runs

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#603]
So when I try to deploy the docker registry it never fully deploys and it has been over 5 minutes.
 ./openshift cli create -f ~/git/origin/examples/sample-app/docker-registry-config.json

 Then it eventually fails. 
(oh and the commands are wrong they should be use cli rather than kube)

**Comment by akostadinov** [comment]
I think I'm hitting the same issue running `hack/test-end-to-end.sh` against 3a68dcf57
I'm running it on fedora 21.

**Comment by smarterclayton** [comment]
Can you try pulling the latest docker-registry and rerunning hack/test-end-to-end.sh

**Comment by akostadinov** [comment]
sorry, I'm just exploring origin v3, how do I pull the latest docker-registry?

**Comment by smarterclayton** [comment]
Docker pull openshift/docker-registry

**Comment by akostadinov** [comment]
updated registry. killed all lingering processes.
I don't see the repeating messages `About to update endpoints for service docker-registry` but I'm still seeing:
```
 [ ERR] Gave up waiting for: 'osc get -n test pods | grep registrypod | grep -i Running'
[FAIL] !!!!! Test Failed !!!!
```
and in two of the container logs:
```
F0113 22:11:11.030263       1 deployer.go:42] Get http://192.168.122.11:8080/api/v1beta1/replicationControllers/docker-registry-1?namespace=test: dial tcp 192.168.122.11:8080: no route to host
```

Still I think something is running on that address:port because doing netstat -avnp on host I see a few:
```
tcp        0      0 192.168.122.11:33678    192.168.122.11:8080     ESTABLISHED - 
```

Could it be a firewall issue? Should I do anything special with firewall if there's any configured at all?

**Comment by smarterclayton** [comment]
If you run "docker run centos ping 192.168.122.11" from one of your hosts, what happens?

**Comment by akostadinov** [comment]
I've got a little further now. I disabled `firewalld` on fedora and that helped so I've reached a little further:
```
[INFO] Pulled centos7
FATA[0002] Error: Invalid registry endpoint https://172.30.17.3:5001/v1/: Get https://172.30.17.3:5001/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 172.30.17.3:5001` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/172.30.17.3:5001/ca.crt 
[FAIL] !!!!! Test Failed !!!!
[INFO] Dumping container logs to /tmp/openshift.local.logs.GEF0
[INFO] Dumping build log to /tmp/openshift.local.logs.GEF0
F0114 00:28:19.233340     769 get.go:82] unable to output the provided object: error executing template '{{with index .items 0}}{{.metadata.name}}{{end}}': 'template: output:1:7: executing "output" at <index .items 0>: error calling index: index out of range: 0'
----data----
map[kind:BuildList apiVersion:v1beta1 metadata:map[selfLink:/osapi/v1beta1/builds resourceVersion:26] items:[]]
```

**Comment by smarterclayton** [comment]
You need to set the insecure-registry flag on your docker daemon, as described in the readme https://github.com/openshift/origin/blob/master/examples/sample-app/README.md#setup

**Comment by akostadinov** [comment]
That helped. I think it would be better to add it under `HACKING` or at least a pointer to it. Do you mind that?

So I went a little further and hit a couple of more issues. I hope you can review them:

First is that `teardown()` function does not reliably kill `openshift` processes and docker containers. I tried to fix that and although `stop_openshift_server` is called `openshift` process is not killed , see the partial fix - https://github.com/akostadinov/origin/commit/5d24721974dac2a2dd4e34cfae31bd5742c791fd

Without the above modification, I'm getting from `teardown()`:
```
[INFO] Dumping build log to /tmp/openshift.local.logs.UzhI
F0114 13:47:33.219221   19939 get.go:82] unable to output the provided object: error executing template '{{with index .items 0}}{{.metadata.name}}{{end}}': 'template: output:1:7: executing "output" at <index .items 0>: error calling index: index out of range: 0'
----data----
map[apiVersion:v1beta1 metadata:map[selfLink:/osapi/v1beta1/builds resourceVersion:23] items:[] kind:BuildList]
```

Another issue I can't get fixed is registering `centos7` image in registry:
```
[INFO] Pulled centos7
FATA[0000] Error response from daemon: Conflict: Tag centos7 is already set to image 8efe422e6104930bd0975c199faa15da985b6694513d2e873aa2da9ee402174c, if you want to replace it, please use -f option
```
If I add the `-f` flag then the `tag` command is successful but the push command fails:
```
The push refers to a repository [172.30.17.3:5001/cached/centos] (len: 1)
Sending image list
FATA[0002]                                              
[FAIL] !!!!! Test Failed !!!!
```

I'm unfortunately not savvy enough and don't know how to clean the `openshift/docker-registry` image or associated data. Your advise is appreciated! It would be nice to include such clean-up in the `tierdown()` function as well.

Finally, when I tried removing the commands to push the image, tests still fail with:
```
centos:centos7: The image you are pulling has been verified
511136ea3c5a: Already exists 
5b12ef8fd570: Already exists 
8efe422e6104: Already exists 
Status: Image is up to date for centos:centos7
[INFO] Pulled centos7
[INFO] Pushed centos7
[INFO] Submitting application template json for processing...
[INFO] Applying application config
I0114 14:04:48.989991   21817 apply.go:59] Creation succeeded for Service with name frontend
I0114 14:04:48.990166   21817 apply.go:59] Creation succeeded for ImageRepository with name origin-ruby-sample
I0114 14:04:48.990303   21817 apply.go:59] Creation succeeded for BuildConfig with name ruby-sample-build
I0114 14:04:48.990516   21817 apply.go:59] Creation succeeded for DeploymentConfig with name frontend
I0114 14:04:48.990537   21817 apply.go:59] Creation succeeded for Service with name database
I0114 14:04:48.990549   21817 apply.go:59] Creation succeeded for DeploymentConfig with name database
[INFO] Invoking generic web hook to trigger new build using curl
[INFO] Waiting for build to complete
[INFO] Waiting for command to finish: 'osc get -n test builds | grep -i complete'...
89d4eae5-9be5-11e4-9702-5254003ff773   STI                 Failed              build-89d4eae5-9be5-11e4-9702-5254003ff773
[FAIL] Returning early. Command Failed 'osc get -n test builds | grep -i complete'
[FAIL] !!!!! Test Failed !!!!
```

**Comment by akostadinov** [comment]
As I said above, the push command always fails.
```
# docker push 172.30.17.3:5001/cached/centos:centos7
The push refers to a repository [172.30.17.3:5001/cached/centos] (len: 1)
Sending image list
FATA[0002]
```
Looking at `docker logs <my registry image>` I see:
```
14/Jan/2015:17:43:04 +0000 INFO: OpenShift tag_created extension enabled
172.17.42.1 - - [14/Jan/2015:17:43:45 +0000] "GET /v1/_ping HTTP/1.1" 200 4 "-" "Go 1.1 package http"
14/Jan/2015:17:43:45 +0000 DEBUG: args = {'namespace': u'cached', 'repository': u'centos'}
2015-01-14 17:43:46,123 ERROR: Exception on /v1/repositories/cached/centos/ [PUT]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 277, in wrapper
    return f(namespace=namespace, repository=repository, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 251, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker_registry/index.py", line 98, in put_repository
    update_index_images(namespace, repository, flask.request.data)
  File "/usr/lib/python2.7/site-packages/docker_registry/index.py", line 80, in update_index_images
    store.put_content(path, data)
  File "/usr/lib/python2.7/site-packages/docker_registry/drivers/file.py", line 61, in put_content
    path = self._init_path(path, create=True)
  File "/usr/lib/python2.7/site-packages/docker_registry/drivers/file.py", line 45, in _init_path
    os.makedirs(dirname)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/tmp/openshift.local.registry/repositories'
14/Jan/2015:17:43:46 +0000 ERROR: Exception on /v1/repositories/cached/centos/ [PUT]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 277, in wrapper
    return f(namespace=namespace, repository=repository, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 251, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker_registry/index.py", line 98, in put_repository
    update_index_images(namespace, repository, flask.request.data)
  File "/usr/lib/python2.7/site-packages/docker_registry/index.py", line 80, in update_index_images
    store.put_content(path, data)
  File "/usr/lib/python2.7/site-packages/docker_registry/drivers/file.py", line 61, in put_content
    path = self._init_path(path, create=True)
  File "/usr/lib/python2.7/site-packages/docker_registry/drivers/file.py", line 45, in _init_path
    os.makedirs(dirname)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/tmp/openshift.local.registry/repositories'
172.17.42.1 - - [14/Jan/2015:17:43:46 +0000] "PUT /v1/repositories/cached/centos/ HTTP/1.1" 500 291 "-" "docker/1.4.0 go/go1.3.3 kernel/3.17.8-300.fc21.x86_64 os/linux arch/amd64"
```

Any advice? I didn't create `/tmp/openshift.local.registry/repositories` so looks like a bug in the setup scripts to me. Removing that dir and starting over does not help. The dir is automatically created and error is the same.

**Comment by bparees** [comment]
I'm not sure why your registry can't write to that dir, but that dir is created as a host volume mount, if you look in docker-registry-config.json you'll see where it's coming from.  Did you remove the whole /tmp/openshift.local/registry dir?  or just the repositories subdir?

I would guess you're having an selinux issue, is "setenforce 0" set?

Also probably worth doing a "docker pull openshift/docker-registry" if you haven't done so lately.

**Comment by akostadinov** [comment]
@bparees, you were right. Setting selinux in permissive mode worked around the issue.

Still `docker tag` fails with:
```
FATA[0000] Error response from daemon: Conflict: Tag centos7 is already set to image 8efe422e6104930bd0975c199faa15da985b6694513d2e873aa2da9ee402174c, if you want to replace it, please use -f option
```
Should I add the `-f` option or setup script should be changed to clean-up tags? I've added that to #649 if you find it reasonable.

And the last issue I see is that the `teardown()` function does not kill `openshift` processes. Even after successful script execution.

**Comment by bparees** [comment]
merged 649.  not sure why you're having process kill issues if you're running the test script via sudo.

**Comment by smarterclayton** [comment]
I believe this is resolved, please reopen if you still see issues.
