### ISSUE TITLE
e2e flake: Error: Element not found: .breadcrumb li a

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6618]
Seen on #6615 

https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4606/console

Not sure what's the main problem there, whether this:

```
Running "protractor:chrome" (protractor) task
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://172.18.14.205:44490/wd/hub
Spec started

**************************************************
*                    Failures                    *
**************************************************

1)  authenticated e2e-user new project when creating a new project should successfully create a new project
  - Error: Element not found: .breadcrumb li a
Wait timed out after 5014ms
  Wait timed out after 5014ms
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1425:29
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at [object Object].then (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:522:7)
    at Object.webdriver.promise.asap (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:767:11)
    at newFrame.onComplete (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1670:25)
    at [object Object].webdriver.promise.Frame_.notify_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1914:5)
    at [object Object]._onTimeout (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1901:11)
==== async task ====
Element not found: .breadcrumb li a
    at [object Object].webdriver.promise.ControlFlow.wait (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1410:15)
    at [object Object].webdriver.WebDriver.wait (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:646:21)
    at [object Object].to.(anonymous function) [as wait] (/data/src/github.com/openshift/origin/assets/node_modules/protractor/lib/protractor.js:62:25)
    at Object.exports.waitForPresence (/data/src/github.com/openshift/origin/assets/test/integration/helpers.js:73:11)
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/rest_api/project.js:131:13)
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/jasminewd/index.js:94:14
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
    at [object Object].wrapper [as _onTimeout] (timers.js:261:14)
==== async task ====
Asynchronous test function: it()
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/jasminewd/index.js:93:33)
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/minijasminenode/lib/async-callback.js:45:37)
Error
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/rest_api/project.js:125:9)
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/rest_api/project.js:116:7)
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/rest_api/project.js:115:5)
```

or this:

```
Error from server: buildconfig "test" not found
W0112 10:41:35.833675    5595 cmd.go:200] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
W0112 10:41:37.908777    5783 cmd.go:200] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
STDIN is not a terminal
W0112 10:41:51.665993    6137 cmd.go:200] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
W0112 10:41:52.687713    6184 cmd.go:200] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
!!! Error in hack/../test/end-to-end/core.sh:346
	'grunt test-integration' exited with status 3
Call stack:
	1: hack/../test/end-to-end/core.sh:346 main(...)
Exiting with status 1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  946k    0  946k    0     0  7242k      0 --:--:-- --:--:-- --:--:-- 7225k
cp: cannot stat ‘’: No such file or directory
hack/../hack/util.sh: line 500: : No such file or directory
hack/../hack/util.sh: line 501: : No such file or directory
rm: cannot remove ‘.tmp’: No such file or directory
make: *** [test-int-plus] Error 1
```

**Comment by liggitt** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/11327/console

**Comment by jwforres** [comment]
@liggitt looks like the screenshot was an access denied error, looks like a 403 based on the message.  Think maybe we are beating out the project cache?  Cause it looks like in the test we hit Create and then immediately try to navigate to the project.

![e2e-error](https://cloud.githubusercontent.com/assets/1467629/13179424/eafe78fc-d6f1-11e5-91dc-b10d3e996cc7.png)

**Comment by liggitt** [comment]
wouldn't be the project cache, that's used for listing projects. might be the authz cache

**Comment by liggitt** [comment]
@spadgett needs to remove some of his performance optimizations to ensure the web console slows down a bit

**Comment by jwforres** [comment]
this could be a problem for real, when a user hits Create in the console we immediately go to "Add  to project"  im surprised we never hit this ourselves...

**Comment by spadgett** [comment]
@jwforres It's a real problem I've seen: #6193

**Comment by spadgett** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5084/

**Comment by danmcp** [comment]
I don't think this is an issue for this repo anymore.
