### ISSUE TITLE
OpenShift Metric Cassandra Failed to Start: Unable to gossip with any seeds

### ISSUE THREAD

**Issue by nichochen** [openshift/origin#6796]
I hit into an error when following the documentation to configure OpenShift metric. Cassandra failed with error "Unable to gossip with any seeds". I tried to verify the cassandra.yaml inside the container , the setting looks fine to me:

    listen_address: hawkular-cassandra-1-l7fq2

     - seeds: "hawkular-cassandra-1-l7fq2"

Exception (java.lang.RuntimeException) encountered during startup: Unable to gossip with any seeds
java.lang.RuntimeException: Unable to gossip with any seeds
	at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1328)
	at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:543)
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:754)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:688)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:580)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:292)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:488)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:595)
ERROR 10:44:12 Exception encountered during startup
java.lang.RuntimeException: Unable to gossip with any seeds
	at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1328) ~[apache-cassandra-2.2.1.redhat-2.jar:2.2.1.redhat-2]
	at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:543) ~[apache-cassandra-2.2.1.redhat-2.jar:2.2.1.redhat-2]
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:754) ~[apache-cassandra-2.2.1.redhat-2.jar:2.2.1.redhat-2]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:688) ~[apache-cassandra-2.2.1.redhat-2.jar:2.2.1.redhat-2]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:580) ~[apache-cassandra-2.2.1.redhat-2.jar:2.2.1.redhat-2]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:292) [apache-cassandra-2.2.1.redhat-2.jar:2.2.1.redhat-2]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:488) [apache-cassandra-2.2.1.redhat-2.jar:2.2.1.redhat-2]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:595) [apache-cassandra-2.2.1.redhat-2.jar:2.2.1.redhat-2]
WARN  10:44:12 No local state or state is in silent shutdown, not announcing shutdown
INFO  10:44:12 Waiting for messaging service to quiesce
INFO  10:44:12 MessagingService has terminated the accept() thread

**Comment by mwringe** [comment]
Are you sure the OpenShift dns is running?

**Comment by mwringe** [comment]
if the dns service is running, what deployment options did you specify when setting up metrics?

**Comment by nichochen** [comment]
OpenShift DNS sometimes cause tcp timeout while resolving the domain name of my master (master.example.com )during S2I builds, so I modified node-config.xml and replace dnsIP with my own DNS server IP. I tried oc rsh into the cassandra pod, curl did successfully resolved the host name hawkular-cassandra-1-l7fq2. Following is my deploy command:

oc process -f metrics.yaml -v HAWKULAR_METRICS_HOSTNAME=hawkular-metrics.example.com,USE_PERSISTENT_STORAGE=false,IMAGE_PREFIX=registry.access.redhat.com/openshift3/,IMAGE_VERSION=latest  | oc create -f -

**Comment by mwringe** [comment]
Any other modifications? Is anything set in the deployer secret?

**Comment by mwringe** [comment]
Closing this issue as out of date.
