### ISSUE TITLE
How to build rpms from sources ?

### ISSUE THREAD

**Issue by usawa** [openshift/origin#7268]
Hi,

I'm very disappointed because I don't understand how to build rpms packages from sources / git. I can't find documentation about it.
Actually, ansible way to install origin uses the maxamillion repository:

https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/epel-7-x86_64/

but, and that's a bug problem, some builds, like 1.1.1.1, were removed. 

I tried to rebuild them using two ways. First one is to modify the origin.spec file, replacing 0.0.1 with the expected release, after a git checkout v<release>. But the origin.spec file flags are not up to date. Resulting packages are not working as expected.

Second one is to use tito tool. I updaded .tito/packages/origin to <release> (1.1.1.1 ./). Then tito build --rpm --offline, but I get and error, saying origin-0.0.1.tar.gz can't be found.

Then, at least, I realized that with tito, rpmbuild line was different for each release, .e.g:

```
1.1.1.1 
rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "ldflags -X github.com/openshift/origin/pkg/version.majorFromGit 1 -X github.com/openshift/origin/pkg/version.minorFromGit 1+ -X github.com/openshift/origin/pkg/version.versionFromGit v1.1.1.1-dirty -X github.com/openshift/origin/pkg/version.commitFromGit 940be51 -X k8s.io/kubernetes/pkg/version.gitCommit 4c8e6f4 -X k8s.io/kubernetes/pkg/version.gitVersion v1.1.0-origin-1107-g4c8e6f4" --define "commit 940be513e42def2fdb3b83283d830d2c63abbad4"   --clean -ba ./origin.spec

1.1.2
rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "ldflags -X github.com/openshift/origin/pkg/version.majorFromGit 1 -X github.com/openshift/origin/pkg/version.minorFromGit 1+ -X github.com/openshift/origin/pkg/version.versionFromGit v1.1.2-dirty -X github.com/openshift/origin/pkg/version.commitFromGit 2711160 -X k8s.io/kubernetes/pkg/version.gitCommit 4a65fa1 -X k8s.io/kubernetes/pkg/version.gitVersion v1.2.0-alpha.4-851-g4a65fa1" --define "commit 2711160b6c02fedb4829481255b0e5e9679704cf"   --clean -ba ./origin.spec 

```

For 1.1.2, resulting rpms are not the same (changelog, size) as the one built by copr/maxamillion.

I'm lost.

How Can I achieve to build correct rpms packages from source by myself ? Thanks for your help.

**Comment by brenton** [comment]
What Troy was referring to in https://github.com/openshift/origin/issues/6695 is simply that you could download any SRPM from a previous build and then rebuild it.  This can be as simple as `rpmbuild --rebuild /path/to/SRPM`.  It's highly likely you'll need some dependent packages installed but you won't need to do anything with tito.

We should have a pull request fairly soon that will provide a documented way for Origin users to build all the RPMs.  That's what https://github.com/openshift/origin/issues/7219 is about.  In the short-term if you have additional rpmbuild questions please post them here and Troy or myself will respond.

**Comment by usawa** [comment]
Thanks,

but some srpms seem to be away. Look at the build https://copr.fedorainfracloud.org/coprs/maxamillion/origin-next/build/156035/

Because of : SRPM file upload

Where to find the rpm in this case ? 

Thanks.

--
Sébastien Rohaut

Le 15 février 2016 à 14:28:57, Brenton Leanhardt (notifications@github.com) a écrit:

What Troy was referring to in #6695 is simply that you could download any SRPM from a previous build and then rebuild it. This can be as simple as rpmbuild --rebuild /path/to/SRPM. It's highly likely you'll need some dependent packages installed but you won't need to do anything with tito.

We should have a pull request fairly soon that will provide a documented way for Origin users to build all the RPMs. That's what #7219 is about. In the short-term if you have additional rpmbuild questions please post them here and Troy or myself will respond.

**Comment by brenton** [comment]
@tdawson, I'm not familiar with copr.  It looks like some of the origin builds don't have SRPMs.  When you get a chance could you provide @usawa with a SRPM or build of the version needed?

**Comment by sdodson** [comment]
@usawa I built that package and unfortunately I uploaded the SRPM to COPR from my browser rather than posting it to sdodson.fedorapeople.org and having COPR build it from there.

I've rebuilt the SRPM and posted it there now. You should be able to build this by running `rpmbuild --rebuild` I'll make it a point to only do copr builds from the srpms in my fedorapeople.org account so that even when COPR removes the binary output you can download the SRPM and rebuild them as needed.

http://sdodson.fedorapeople.org/origin-1.1.1.1-0.git.0.ce0e67f.el7.src.rpm

You can see in other builds that it links to the original SRPM
https://copr.fedorainfracloud.org/coprs/maxamillion/origin-next/build/158874/

**Comment by usawa** [comment]
Thank you very much, I’ll download it and rebuilt it.

--
Sébastien Rohaut

Le 16 février 2016 à 16:39:15, Scott Dodson (notifications@github.com) a écrit:

@usawa I built that package and unfortunately I uploaded the SRPM to COPR from my browser rather than posting it to sdodson.fedorapeople.org and having COPR build it from there.

I've rebuilt the SRPM and posted it there now. You should be able to build this by running rpmbuild --rebuild I'll make it a point to only do copr builds from the srpms in my fedorapeople.org account so that even when COPR removes the binary output you can download the SRPM and rebuild them as needed.

http://sdodson.fedorapeople.org/origin-1.1.1.1-0.git.0.ce0e67f.el7.src.rpm

You can see in other builds that it links to the original SRPM
https://copr.fedorainfracloud.org/coprs/maxamillion/origin-next/build/158874/

**Comment by sureddy** [comment]
I am trying to build the RPMS for the source. I am using  <b>tito</b> tool to rebuild RPMS. 

`tito build --rpm `

i got the following errors:

<pre>
[quantiply@play origin]$ tito build --rpm
Checking for tag [v0.0.1] in git repo [git://github.com/openshift/origin]
Building package [v0.0.1]
ERROR: Error running command: git archive --format=tar --prefix=origin-0.0.1/ deef796523e481158a597dc39cec4d7eb74cecf9:None --output=/tmp/tito/rpmbuild-originN7IYEj/SOURCES/origin-0.0.1.tar.initial

Status code: 32768

Command output: fatal: Not a valid object name

Traceback (most recent call last):
  File "/usr/bin/tito", line 5, in <module>
    pkg_resources.run_script('tito==0.6.4', 'tito')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1491, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/tito-0.6.4-py2.7.egg/EGG-INFO/scripts/tito", line 23, in <module>
</pre>

Then I updated the version information .tito/packages/origin.  This time it went through much further, but it failed during the RPMBUILD. 

<pre>[quantiply@play origin]$ tito build --rpm
Checking for tag [v1.1.3] in git repo [git://github.com/openshift/origin]
Building package [v1.1.3]
Wrote: /tmp/tito/origin-1.1.3.tar.gz
error: File /tmp/tito/rpmbuild-originqEkhpM/SOURCES/origin-0.0.1.tar.gz: No such file or directory

ERROR: Error running command: rpmbuild --define "_source_filedigest_algorithm md5"  --define 
"_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-
originqEkhpM" --define "_sourcedir /tmp/tito/rpmbuild-originqEkhpM/SOURCES" --define "_builddir 
/tmp/tito/rpmbuild-originqEkhpM/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito" --define 
"ldflags -X github.com/openshift/origin/pkg/version.majorFromGit 1 -X 
github.com/openshift/origin/pkg/version.minorFromGit 1+ -X 
github.com/openshift/origin/pkg/version.versionFromGit v1.1.3-331-g00b18d9-dirty -X 
github.com/openshift/origin/pkg/version.commitFromGit 00b18d9 -X 
k8s.io/kubernetes/pkg/version.gitCommit bc4550d -X k8s.io/kubernetes/pkg/version.gitVersion v1.2.0-
alpha.7-703-gbc4550d" --define "commit 00b18d97d1e03cb275bce7c434c6f15e2fc36e00"   --clean -ba 
/tmp/tito/rpmbuild-originqEkhpM/SOURCES/origin-1.1.3/origin.spec </pre>

Looks like problem is it is writing the package at Wrote: /tmp/tito/origin-1.1.3.tar.gz
 and looking under different directory /tmp/tito/rpmbuild-originqEkhpM/SOURCES/origin-0.0.1.tar.gz. 
Where is this getting the version tag from? I updated the version to 1.1.3 in .tito/packages/origin.

Any help is appreciated.  Is there any other way i can build RPMS from the source.

**Comment by sureddy** [comment]
@sdodson any suggestions how to resolve this? is there any other way to build RPMS from Origin sources?

**Comment by brenton** [comment]
@sdodson, has this issue be resolved be the recent CentOS work?

**Comment by tdawson** [comment]
CentOS now has these rpms in their Paas/OpenShift repo.

http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/

The older rpm's do not expire.

If you want the source rpm's, or grab a newer package that is still being tested, you can get them from the CentOS koji site (called cbs)
https://cbs.centos.org/koji/packageinfo?packageID=3175

The one downside is this CentOS repo only starts at origin 1.1.6

**Comment by enlinxu** [comment]
hi,
I am having exactly the same output as @sureddy , any update on this issue?

**Comment by tdawson** [comment]
To build origin using tito you need to use the --test option

> $ tito build --test --rpm

If I don't use the --test option, I get the same error as @sureddy 
But using the above command, it builds correctly for me.

**Comment by enlinxu** [comment]
Thanks a lot @tdawson for your reply. Now I am moving few steps forward. But I am getting this error complaining about dependencies. Although I already have the correct go installed.

error: Failed build dependencies:
	golang = 1.6.2 is needed by origin-0.0.1-0.git.12711.214f70b.el7.x86_64



ERROR: Please run 'yum-builddep origin.spec' as root.
[root@OSMaster origin]# go version
go version go1.6.2 linux/amd64

**Comment by tdawson** [comment]
When building rpm's, it matters what rpms you have installed, not necessarily what language or language version is in your path.
Run

> rpm -q golang

and if it doesn't start with

> golang-1.6.2

Then you don't have the right rpm installed.
I suggest getting golang-1.6.2 from copr or CentOS.  I don't have the link for copr, but I do for CentOS
http://cbs.centos.org/koji/buildinfo?buildID=11982

**Comment by enlinxu** [comment]
Work like a charm! Thanks @tdawson !!

**Comment by enlinxu** [comment]
@tdawson One last question... I was able to build rpms for all packages from openshift/origin. Then I forked origin to my own github, and try with the same build, and I got:
+ go install -ldflags './hack/common.sh: line 771: OS_GIT_MAJOR: unbound variable' github.com/openshift/origin/cmd/dockerregistry

Do I need to modify anything in common.sh to make it work for forked repo?
Thanks again.

**Comment by tdawson** [comment]
Someone else will have to verify this, but I believe you need to have a tag.  Try doing 

> tito tag

As a side note, I'v started work on fixing that.

**Comment by enlinxu** [comment]
@tdawson the tito tag gives the same error about unbound variable.
[root@OSMaster origin]# tito tag
Tagging new version of origin: 1.2.1 -> 0.0.2-1
ERROR: Error running command: sed -i 's|^%global ldflags .*$|%global ldflags ./hack/common.sh: line 771: OS_GIT_MAJOR: unbound variable

**Comment by tdawson** [comment]
Since it's not failling for me, I'm not positive about the solution, but try the following before doing the tito build.
```
export OS_GIT_MAJOR='1'
export OS_GIT_MINOR='3+'
export OS_GIT_COMMIT=''

```

**Comment by tdawson** [comment]
It's take a while, but we now have a solution that works.  It works for both master branch (origin 3.6) and release-1.5 branch (origin 1.5)
1) Ensure you have tito 0.6.10 or later
https://koji.fedoraproject.org/koji/packageinfo?packageID=9382
2) Checkout the origin git repo
git clone git@github.com:openshift/origin.git
cd origin
3) tito tag using --use-version and --use-release (optional: --no-auto-changelog)
tito tag --use-version=1.6.0 --use-release=0.1 --no-auto-changelog
4) tito build ... with the options you want. (tito build --help)
-- Just get a src.rpm:  tito build --test --srpm
-- get a src.rpm with a nice release number: tito build --srpm --offline
-- Do an rpm build: tito build --test --rpm
I'll let the reader figure out all the ways they can build the rpm with tito.

**Comment by scheng1** [comment]
@scheng1
