### ISSUE TITLE
S2I builder crashes

### ISSUE THREAD

**Issue by vrutkovs** [openshift/origin#7674]
```
$ oc logs -f build/manageiq-s2i-25
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1291640]

goroutine 1 [running]:
github.com/openshift/origin/pkg/build/builder.(*S2IBuilder).Build(0xc2085fa690, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/build/builder/sti.go:176 +0x2fa0
github.com/openshift/origin/pkg/build/builder/cmd.s2iBuilder.Build(0x7f66991db860, 0xc2083a6f30, 0x349ad10, 0x1b, 0x7f66991db758, 0xc2085f75a0, 0xc208156000, 0x7f66991db8e0, 0xc2080353c8, 0xc2085f5260, ...)
	/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:194 +0xba
github.com/openshift/origin/pkg/build/builder/cmd.(*s2iBuilder).Build(0x57191d0, 0x7f66991db860, 0xc2083a6f30, 0x349ad10, 0x1b, 0x7f66991db758, 0xc2085f75a0, 0xc208156000, 0x7f66991db8e0, 0xc2080353c8, ...)
	<autogenerated>:3 +0x12f
github.com/openshift/origin/pkg/build/builder/cmd.(*builderConfig).execute(0xc2082558c0, 0x7f66991db308, 0x57191d0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:147 +0x3e0
github.com/openshift/origin/pkg/build/builder/cmd.runBuild(0x7f66991db308, 0x57191d0)
	/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:202 +0x120
github.com/openshift/origin/pkg/build/builder/cmd.RunSTIBuild()
	/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:215 +0x69
github.com/openshift/origin/pkg/cmd/infra/builder.func·001(0xc2085ce800, 0x57191d0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/cmd/infra/builder/builder.go:31 +0x1b
github.com/spf13/cobra.(*Command).execute(0xc2085ce800, 0xc20800a000, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f
github.com/spf13/cobra.(*Command).ExecuteC(0xc2085ce800, 0xc2085ce800, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db
github.com/spf13/cobra.(*Command).Execute(0xc2085ce800, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a
main.main()
	/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:27 +0x175

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x5705920)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 13 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35
```
```
$ oc get build/manageiq-s2i-24 -o yaml
apiVersion: v1
kind: Build
metadata:
  annotations:
    openshift.io/build.number: "27"
    openshift.io/build.pod-name: manageiq-s2i-27-build
  creationTimestamp: 2016-02-26T23:59:00Z
  labels:
    app: manageiq-base
    buildconfig: manageiq-s2i
    openshift.io/build-config.name: manageiq-s2i
  name: manageiq-s2i-27
  namespace: manageiq-blue
  resourceVersion: "595921"
  selfLink: /oapi/v1/namespaces/manageiq-blue/builds/manageiq-s2i-27
  uid: e7b29bc9-dce4-11e5-ab84-fa163e53fb34
spec:
  output:
    pushSecret:
      name: builder-dockercfg-n4x61
    to:
      kind: ImageStreamTag
      name: manageiq:latest
  resources: {}
  serviceAccount: builder
  source:
    git:
      ref: master
      uri: https://github.com/manageiq/manageiq
    type: Git
  strategy:
    customStrategy:
      env:
      - name: IMAGE_NAME
        value: manageiq:base
      - name: CONTEXT_DIR
        value: /var/www/miq/vmdb
      - name: OPENSHIFT_CUSTOM_BUILD_BASE_IMAGE
        value: openshift/origin-sti-builder
      from:
        kind: DockerImage
        name: openshift/origin-sti-builder
    type: Custom
status:
  completionTimestamp: 2016-02-27T00:00:25Z
  config:
    kind: BuildConfig
    name: manageiq-s2i
    namespace: manageiq-blue
  duration: 16000000000
  outputDockerImageReference: 172.30.27.70:5000/manageiq-blue/manageiq:latest
  phase: Failed
  startTimestamp: 2016-02-27T00:00:09Z
```

**Comment by mfojtik** [comment]
@vrutkovs interesting, the build config seems like custom build strategy but the error comes out from the s2i builder.

**Comment by mfojtik** [comment]
@vrutkovs can you please tell me what version of builder image you use?

**Comment by mfojtik** [comment]
OK, I think I see the issue, you're trying to use the S2I builder image with S2I build binary with custom build strategy. @smarterclayton @bparees is this something we want to support? To fix this, we will have to sanitize all code that queries `s.build.Spec.Strategy.SourceStrategy` and check for nil here.

**Comment by bparees** [comment]
@mfojtik no...  the origin-sti-builder image was not written to be used as a custom builder image, I don't see any reason to make it work as one.  

I think it would be good to understand what @vrutkovs was trying to accomplish that necessitated using it in this way, though, in case we have missed a use case somewhere.

**Comment by mfojtik** [comment]
@bparees it is actually not that hard to get this working, see the PR. I can see the use-case for example if you want to do git clone "your way" :-)

**Comment by bparees** [comment]
@mfojtik this still doesn't let you control git clone, does it? that's baked into the binary in the image...

**Comment by mfojtik** [comment]
@bparees yeah, just realized that git clone is done by the binary... I don't see any potential use-cases, but maybe @vrutkovs will have some :-) lets wait for him.

**Comment by vrutkovs** [comment]
Tried all versions up to v1.1.1, similar crashes.

>  I don't see any potential use-cases, but maybe @vrutkovs will have some :-) lets wait for him.

Right, all I needed was classic S2I, so I've rewritten the config to use a correct strategy - no more crashes occurred.

It would be nice to avoid the crash (and output some kind of usage synopsis) anyway

**Comment by mfojtik** [comment]
Thanks Vadim, I changed the PR to give users more human friendly error.

On Sun, Feb 28, 2016 at 10:28 PM, Vadim Rutkovsky <notifications@github.com>
wrote:

> Tried all versions up to v1.1.1, similar crashes.
>
> I don't see any potential use-cases, but maybe @vrutkovs
> <https://github.com/vrutkovs> will have some :-) lets wait for him.
>
> Right, all I needed was classic S2I, so I've rewritten the config to use a
> correct strategy - no more crashes occurred.
>
> It would be nice to avoid the crash (and output some kind of usage
> synopsis) anyway
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/7674#issuecomment-189947997>.
>



-- 
-----------------------------------------------
Michal Fojtik <mi@mifo.sk <mfojtik@mifo.sk>>
Red Hat OpenShift, Engineering
