### ISSUE TITLE
oc new-app --list dies

### ISSUE THREAD

**Issue by caruccio** [openshift/origin#7882]
Trying to list usable templates and imagestream gives a segfault with backtrace:

```
$ uname -a
Darwin MacBook-Air-de-Mateus.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

$ oc version
oc v1.1.3
kubernetes v1.2.0-origin

$ oc new-app --list
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x740e74]

goroutine 1 [running]:
github.com/fsouza/go-dockerclient.(*Client).do(0x0, 0x1664c70, 0x3, 0x169e990, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go:388 +0x634
github.com/fsouza/go-dockerclient.(*Client).ListImages(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/image.go:101 +0x15e
github.com/openshift/origin/pkg/generate/app.DockerClientSearcher.Search(0x26501e0, 0x0, 0x2650210, 0xc208846060, 0x0, 0xc208706e00, 0xc208402cf0, 0x1, 0x1, 0x0, ...)
	/go/src/github.com/openshift/origin/pkg/generate/app/dockerimagelookup.go:90 +0xf11
github.com/openshift/origin/pkg/generate/app.(*DockerClientSearcher).Search(0xc208846090, 0xc2084a4600, 0xc208402cf0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:54 +0x128
github.com/openshift/origin/pkg/generate/app.MultiWeightedSearcher.Search(0xc2084e8a20, 0x3, 0x4, 0x0, 0xc208402cf0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/pkg/generate/app/componentresolvers.go:231 +0x1b8
github.com/openshift/origin/pkg/generate/app.(*MultiWeightedSearcher).Search(0xc2084b26a0, 0x165ca00, 0xc208402cf0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:51 +0x11d
github.com/openshift/origin/pkg/generate/app.(*ComponentInput).Search(0xc208804090, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/generate/app/componentref.go:317 +0x1b2
github.com/openshift/origin/pkg/generate/app/cmd.Search(0xc208402cd0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/generate/app/cmd/newapp.go:488 +0x100
github.com/openshift/origin/pkg/generate/app/cmd.(*AppConfig).RunQuery(0xc208246a00, 0x262e250, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/generate/app/cmd/newapp.go:883 +0x993
github.com/openshift/origin/pkg/cmd/cli/cmd.RunNewApplication(0x7fff5fbff7f0, 0x2, 0xc20842e900, 0x262e250, 0xc208036008, 0xc208146a00, 0xc208420cd0, 0x0, 0x1, 0xc208246a00, ...)
	/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/newapp.go:189 +0x19b
github.com/openshift/origin/pkg/cmd/cli/cmd.func·013(0xc208146a00, 0xc208420cd0, 0x0, 0x1)
	/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/newapp.go:138 +0x1de
github.com/spf13/cobra.(*Command).execute(0xc208146a00, 0xc208420c80, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f
github.com/spf13/cobra.(*Command).ExecuteC(0xc208057800, 0xc208146a00, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db
github.com/spf13/cobra.(*Command).Execute(0xc208057800, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a
main.main()
	/go/src/github.com/openshift/origin/cmd/oc/oc.go:27 +0x175

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x22b3f80)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 15 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 51 [select]:
net/http.(*persistConn).writeLoop(0xc208094000)
	/usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 50 [IO wait]:
net.(*pollDesc).Wait(0xc20839fe20, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20839fe20, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20839fdc0, 0xc208736000, 0x8000, 0x8000, 0x0, 0x262e360, 0xc2083907f0)
	/usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208037d50, 0xc208736000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20856c150, 0x26412f8, 0xc208037d50, 0x5, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208364b00, 0x17, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208364b00, 0xc20835c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x264afc0, 0xc208364b00, 0xc208094058, 0xc20835c000, 0x1000, 0x1000, 0x11fe600, 0x0, 0x0)
	/usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208514620, 0xc20835c000, 0x1000, 0x1000, 0xc208168900, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20852c420)
	/usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20852c420, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208094000)
	/usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 36 [sleep]:
net.func·019()
	/usr/lib/golang/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
	/usr/lib/golang/src/net/dnsclient_unix.go:269 +0x20c
```

**Comment by csrwng** [comment]
@danmcp @caruccio this was fixed with https://github.com/openshift/origin/pull/7433

**Comment by caruccio** [comment]
Thanks. I could not find any issue related to this by searching for `new-app`.
