### ISSUE TITLE
Test flake: /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.5/lib/vagrant-openshift/action/download_artifacts_origin.rb:24:in `initialize': wrong number of arguments (2 for 3) (ArgumentError)

### ISSUE THREAD

**Issue by dcbw** [openshift/origin#8128]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13174/console

```
real	23m52.733s
user	0m5.986s
sys	0m0.549s
+ vagrant test-origin --extended networking -d --skip-check --skip-image-cleanup --image-registry ci.dev.openshift.redhat.com:5000
/var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.5/lib/vagrant-openshift/action/download_artifacts_origin.rb:24:in `initialize': wrong number of arguments (2 for 3) (ArgumentError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:90:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:90:in `finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:20:in `block in initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:20:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:20:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:170:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:170:in `to_app'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.5/lib/vagrant-openshift/command/test_origin.rb:94:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.5/lib/vagrant-openshift/command/test_origin.rb:92:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
Build step 'Execute shell' marked build as failure
```

**Comment by dcbw** [comment]
@eparis could you spare a second for flake tags?

**Comment by eparis** [comment]
@danmcp you are probably best to prioritize...

**Comment by dcbw** [comment]
https://github.com/openshift/vagrant-openshift/pull/428 seems to be involved here

**Comment by pweil-** [comment]
also seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13172/console

**Comment by miminar** [comment]
All the jenkin builds are failing now with this error.

**Comment by stevekuznetsov** [comment]
Should be fixed in https://github.com/openshift/vagrant-openshift/pull/432

**Comment by stevekuznetsov** [comment]
Seeing builds download artifacts on failure successfully: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13189/

**Comment by stevekuznetsov** [comment]
Seeing builds succeed: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13180

**Comment by stevekuznetsov** [comment]
@eparis this is fixed

**Comment by dcbw** [comment]
@stevekuznetsov thanks! closing then.
