### ISSUE TITLE
oc edit panics when using non yaml format (bypasses bc format validation)

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#8785]
whenever you oc edit a bc and add some random non yaml format characters it explodes
![screenshot from 2016-05-07 01-25-04](https://cloud.githubusercontent.com/assets/6294120/15088343/95b0d050-13f2-11e6-81f6-9d0f7e376e12.png)
 into a million pieces with:

```
~/origin (master)$: oc edit bc ruby-sample-build
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xa365b3]

goroutine 1 [running]:
panic(0x1d4bb20, 0xc82000e170)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
k8s.io/kubernetes/pkg/kubectl/resource.(*Mapper).InfoForData(0xc82000bcc0, 0xc8206e9800, 0x5c9, 0x7c9, 0x2095800, 0xb, 0x2061100, 0x0, 0x0)
	/home/ipalade/projects/golang/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/resource/mapper.go:57 +0x11e3
k8s.io/kubernetes/pkg/kubectl/cmd.RunEdit(0xc820179950, 0x7f4567540198, 0xc82008a008, 0x7f4567540198, 0xc82008a010, 0xc820113e00, 0xc8205f5b00, 0x2, 0x2, 0xc8202b8580, ...)
	/home/ipalade/projects/golang/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/edit.go:254 +0x1bca
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdEdit.func1(0xc820113e00, 0xc8205f5b00, 0x2, 0x2)
	/home/ipalade/projects/golang/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/edit.go:95 +0xa7
github.com/spf13/cobra.(*Command).execute(0xc820113e00, 0xc8205f59a0, 0x2, 0x2, 0x0, 0x0)
	/home/ipalade/projects/golang/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x85a
github.com/spf13/cobra.(*Command).ExecuteC(0xc8202b1400, 0xc820113e00, 0x0, 0x0)
	/home/ipalade/projects/golang/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x53f
github.com/spf13/cobra.(*Command).Execute(0xc8202b1400, 0x0, 0x0)
	/home/ipalade/projects/golang/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x2d
main.main()
	/home/ipalade/projects/golang/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:27 +0x180
```

**Comment by mfojtik** [comment]
@kargakis already fixed this in upstream

**Comment by PI-Victor** [comment]
@mfojtik ok, didn't know about that, thanks. closing
