### ISSUE TITLE
Router pods failing 40 times/day with  `concurrent map read and map write`

### ISSUE THREAD

**Issue by anthonyrisinger** [openshift/origin#8811]
I'm seeing router pods fail about 40 times a day with `fatal error: concurrent map read and map write`. It doesn't take out the cluster because we have a couple instances running but they both fail randomly. We are also having what appear to be fd limit problems on the infrastructure nodes (sometimes can't ssh, or sudo fails to open /etc/sudoers) so I can't 100% rule that out as part of the problem (the 2 registry pods restart too, albeit less frequently) but it's restarted 3 times in the last hour after a reboot. The first restart occured within 10 minutes.

```bash
# oc get pods -n default -l router
NAME             READY     STATUS    RESTARTS   AGE
router-6-ezpi2   1/1       Running   3          2h
router-6-n5xnu   1/1       Running   4          2h
```

```bash
# oc version
oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5
```

Reproduction is simply:

* `oc logs -f ANY-ROUTER-POD`
* Wait for crash

I'm not sure how to otherwise trigger it.

The stacktrace seems to suggest a map of pods is being updated at the moment a template is being written. Per https://blog.golang.org/go1.6 Go 1.6 added concurrent map detection.

Stacktrace:

```
fatal error: concurrent map read and map write

goroutine 77 [running]:
runtime.throw(0x38e04e0, 0x21)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8207d1248 sp=0xc8207d1230
runtime.mapaccess2(0x2820680, 0xc820011410, 0xc820750a00, 0x317ca60, 0xc8207716e0)
	/usr/local/go/src/runtime/hashmap.go:343 +0x5a fp=0xc8207d1290 sp=0xc8207d1248
reflect.mapaccess(0x2820680, 0xc820011410, 0xc820750a00, 0xc820011410)
	/usr/local/go/src/runtime/hashmap.go:993 +0x35 fp=0xc8207d12c0 sp=0xc8207d1290
reflect.Value.MapIndex(0x2820680, 0xc8203fe780, 0x95, 0x2828680, 0xc820750a00, 0x98, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:1041 +0x14a fp=0xc8207d1348 sp=0xc8207d12c0
text/template.(*state).walkRange(0xc8207d18d0, 0x329f660, 0xc8203fe770, 0x99, 0xc820546200)
	/usr/local/go/src/text/template/exec.go:327 +0x885 fp=0xc8207d1548 sp=0xc8207d1348
text/template.(*state).walk(0xc8207d18d0, 0x329f660, 0xc8203fe770, 0x99, 0x7f28657c20d8, 0xc820546200)
	/usr/local/go/src/text/template/exec.go:226 +0x264 fp=0xc8207d1690 sp=0xc8207d1548
text/template.(*state).walk(0xc8207d18d0, 0x329f660, 0xc8203fe770, 0x99, 0x7f28657d0ba8, 0xc8205e13b0)
	/usr/local/go/src/text/template/exec.go:223 +0x6a1 fp=0xc8207d17d8 sp=0xc8207d1690
text/template.(*Template).Execute(0xc820176a40, 0x7f2865806398, 0xc820024658, 0x329f660, 0xc8203fe770, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:178 +0x2a7 fp=0xc8207d1918 sp=0xc8207d17d8
github.com/openshift/origin/pkg/router/template.(*templateRouter).writeConfig(0xc8203bc9c0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/template/router.go:283 +0x892 fp=0xc8207d1d58 sp=0xc8207d1918
github.com/openshift/origin/pkg/router/template.(*templateRouter).commitAndReload(0xc8203bc9c0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/template/router.go:231 +0x14d fp=0xc8207d1dc0 sp=0xc8207d1d58
github.com/openshift/origin/pkg/router/template.(*templateRouter).(github.com/openshift/origin/pkg/router/template.commitAndReload)-fm(0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/template/router.go:157 +0x2e fp=0xc8207d1de0 sp=0xc8207d1dc0
github.com/openshift/origin/pkg/util/ratelimiter.(*RateLimitedFunction).handleOne(0xc820481bc0, 0x33272e0, 0xc820481bc0)
	/go/src/github.com/openshift/origin/pkg/util/ratelimiter/ratelimiter.go:49 +0x48 fp=0xc8207d1e18 sp=0xc8207d1de0
github.com/openshift/origin/pkg/util/ratelimiter.(*RateLimitedFunction).RunUntil.func1()
	/go/src/github.com/openshift/origin/pkg/util/ratelimiter/ratelimiter.go:42 +0x6a fp=0xc8207d1e60 sp=0xc8207d1e18
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820495960)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b fp=0xc8207d1e90 sp=0xc8207d1e60
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820495960, 0x0, 0x0, 0xc820296180)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68 fp=0xc8207d1f50 sp=0xc8207d1e90
k8s.io/kubernetes/pkg/util/wait.Until(0xc820495960, 0x0, 0xc820296180)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e fp=0xc8207d1f78 sp=0xc8207d1f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8207d1f80 sp=0xc8207d1f78
created by github.com/openshift/origin/pkg/util/ratelimiter.(*RateLimitedFunction).RunUntil
	/go/src/github.com/openshift/origin/pkg/util/ratelimiter/ratelimiter.go:42 +0x7d

goroutine 1 [select (no cases), 30 minutes]:
github.com/openshift/origin/pkg/cmd/infra/router.(*TemplateRouterOptions).Run(0xc8202af680, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/cmd/infra/router/template.go:203 +0x85e
github.com/openshift/origin/pkg/cmd/infra/router.NewCommandTemplateRouter.func1(0xc820146a00, 0x5b9a280, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/cmd/infra/router/template.go:111 +0x1ad
github.com/spf13/cobra.(*Command).execute(0xc820146a00, 0xc82000a1e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x85a
github.com/spf13/cobra.(*Command).ExecuteC(0xc820146a00, 0xc820146a00, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x53f
github.com/spf13/cobra.(*Command).Execute(0xc820146a00, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x2d
main.main()
	/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:27 +0x180

goroutine 17 [syscall, 30 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x5b72140)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 12 [syscall, 3 minutes]:
os/signal.signal_recv(0x7f2865802078)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 78 [select]:
net/http.(*persistConn).roundTrip(0xc8203bcc30, 0xc820a8bf30, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc8200f4a80, 0xc820730e00, 0xa, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:320 +0x9bb
k8s.io/kubernetes/pkg/client/transport.(*userAgentRoundTripper).RoundTrip(0xc8205daa80, 0xc820730e00, 0xc8205daa80, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/transport/round_trippers.go:89 +0x130
net/http.send(0xc820730d20, 0x7f2865815d30, 0xc8205daa80, 0x0, 0x0, 0x0, 0xc8201b3ab0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc8206059e0, 0xc820730d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc8206059e0, 0xc820730d20, 0x3e677f8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc8206059e0, 0xc820730d20, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:188 +0xff
k8s.io/kubernetes/pkg/client/restclient.(*Request).Watch(0xc82082cf00, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/restclient/request.go:649 +0x288
github.com/openshift/origin/pkg/client.(*routes).Watch(0xc8206d7d20, 0x0, 0x0, 0x0, 0x0, 0x7f28657d0170, 0xc8205b30c0, 0x7f28657d01b0, 0xc8205b30e0, 0x0, ...)
	/go/src/github.com/openshift/origin/pkg/client/routes.go:92 +0x1b2
github.com/openshift/origin/pkg/router/controller/factory.(*routeLW).Watch(0xc82056e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/pkg/router/controller/factory/factory.go:236 +0x12f
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc820539400, 0xc82005ae40, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:263 +0xb83
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x2c
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820280a00)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820280a00, 0x3b9aca00, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc820280a00, 0x3b9aca00, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x84

goroutine 79 [select]:
net/http.(*persistConn).roundTrip(0xc820818000, 0xc820494550, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc8200f4a80, 0xc820ae4e00, 0xa, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:320 +0x9bb
k8s.io/kubernetes/pkg/client/transport.(*userAgentRoundTripper).RoundTrip(0xc8205da340, 0xc820ae4e00, 0xc8205da340, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/transport/round_trippers.go:89 +0x130
net/http.send(0xc820ae4d20, 0x7f2865815d30, 0xc8205da340, 0x0, 0x0, 0x0, 0xc8203d9260, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc820605800, 0xc820ae4d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc820605800, 0xc820ae4d20, 0x3e677f8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc820605800, 0xc820ae4d20, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:188 +0xff
k8s.io/kubernetes/pkg/client/restclient.(*Request).Watch(0xc820ae8000, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/restclient/request.go:649 +0x288
k8s.io/kubernetes/pkg/client/unversioned.(*endpoints).Watch(0xc8207ff1a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/endpoints.go:88 +0x1b2
github.com/openshift/origin/pkg/router/controller/factory.(*endpointsLW).Watch(0xc82056e040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/pkg/router/controller/factory/factory.go:257 +0x12f
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc8205394a0, 0xc82005ae40, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:263 +0xb83
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x2c
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820280a30)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820280a30, 0x3b9aca00, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc820280a30, 0x3b9aca00, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x84

goroutine 80 [runnable]:
github.com/openshift/origin/pkg/router/template.(*templateRouter).cleanUpdates(0xc8203bc9c0, 0xc8207ff500, 0x1a, 0xc8207ff520, 0x12)
	/go/src/github.com/openshift/origin/pkg/router/template/router.go:471 +0x27c
github.com/openshift/origin/pkg/router/template.(*templateRouter).AddRoute(0xc8203bc9c0, 0xc8207ff500, 0x1a, 0xc820254b78, 0xc820ae28a0, 0x13, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/template/router.go:456 +0x4fe
github.com/openshift/origin/pkg/router/template.(*TemplatePlugin).HandleRoute(0xc8203ca940, 0x35937f0, 0x8, 0xc820254b78, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/template/plugin.go:173 +0x421
github.com/openshift/origin/pkg/router/controller.(*StatusAdmitter).HandleRoute(0xc820169f80, 0x35937f0, 0x8, 0xc820254b78, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/controller/status.go:295 +0x2e3
github.com/openshift/origin/pkg/router/controller.(*UniqueHost).HandleRoute(0xc820169fc0, 0x35937f0, 0x8, 0xc820254b78, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/controller/unique_host.go:170 +0x117a
github.com/openshift/origin/pkg/router/controller.(*RouterController).HandleRoute(0xc820606c80)
	/go/src/github.com/openshift/origin/pkg/router/controller/controller.go:84 +0x5ea
github.com/openshift/origin/pkg/router/controller.(*RouterController).HandleRoute-fm()
	/go/src/github.com/openshift/origin/pkg/router/controller/controller.go:46 +0x20
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820280a90)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820280a90, 0x0, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc820280a90, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
k8s.io/kubernetes/pkg/util/wait.Forever(0xc820280a90, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:41 +0x37
created by github.com/openshift/origin/pkg/router/controller.(*RouterController).Run
	/go/src/github.com/openshift/origin/pkg/router/controller/controller.go:46 +0x1da

goroutine 81 [select]:
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820280ac0, 0x0, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:74 +0x13c
k8s.io/kubernetes/pkg/util/wait.Until(0xc820280ac0, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
k8s.io/kubernetes/pkg/util/wait.Forever(0xc820280ac0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:41 +0x37
created by github.com/openshift/origin/pkg/router/controller.(*RouterController).Run
	/go/src/github.com/openshift/origin/pkg/router/controller/controller.go:47 +0x239

goroutine 82 [chan receive, 3 minutes]:
github.com/openshift/origin/pkg/util/proc.StartReaper.func1()
	/go/src/github.com/openshift/origin/pkg/util/proc/reaper.go:23 +0x193
created by github.com/openshift/origin/pkg/util/proc.StartReaper
	/go/src/github.com/openshift/origin/pkg/util/proc/reaper.go:35 +0x79

goroutine 83 [select, 30 minutes, locked to thread]:
runtime.gopark(0x3e67cf8, 0xc82001d728, 0x3573d80, 0x6, 0xc82020a218, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc82001d728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc82001d728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 156 [IO wait]:
net.runtime_pollWait(0x7f2865817460, 0x72, 0xc820599800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820548610, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820548610, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8205485b0, 0xc820599800, 0x800, 0x800, 0x0, 0x7f2865802050, 0xc82000a120)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200240d0, 0xc820599800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820902f30, 0x7f28658177d8, 0xc8200240d0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8205b8300, 0x3e67e17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8205b8300, 0xc82056c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x7f286581b988, 0xc8205b8300, 0xc8203bcc98, 0xc82056c000, 0x1000, 0x1000, 0x405963, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc820963740, 0xc82056c000, 0x1000, 0x1000, 0xc820561d0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820a76ae0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820a76ae0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8203bcc30)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 173 [select]:
net/http.(*persistConn).writeLoop(0xc820818000)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 172 [IO wait]:
net.runtime_pollWait(0x7f28658173a0, 0x72, 0xc8207be800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82054c3e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82054c3e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82054c380, 0xc8207be800, 0x800, 0x800, 0x0, 0x7f2865802050, 0xc82000a120)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200e66f8, 0xc8207be800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8207b8690, 0x7f28658177d8, 0xc8200e66f8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc82092a000, 0x3e67e17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc82092a000, 0xc82085b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x7f286581b988, 0xc82092a000, 0xc820818068, 0xc82085b000, 0x1000, 0x1000, 0x405963, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc8206f6440, 0xc82085b000, 0x1000, 0x1000, 0xc820669d0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8200e1b60)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8200e1b60, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820818000)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 157 [select]:
net/http.(*persistConn).writeLoop(0xc8203bcc30)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb
```

**Comment by knobunc** [comment]
What version are you running?  This PR added locking to the router reloads:
  https://github.com/openshift/origin/commit/437ead66376dc1941e593b7eb2a6fcf1ca1fabb2

**Comment by liggitt** [comment]
https://github.com/openshift/origin/pull/8893 fixed this issue, and was merged on 5/17

**Comment by knobunc** [comment]
Cool.  Thanks @liggitt
