### ISSUE TITLE
Panic on binary startbuild

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9072]
Looks like our logic for writingTarHeader fails to take into account certain paths:

```
	if prefix != "." {
		fileName = path[1+len(prefix):]
	}
```

```
$ oc start-build sample --from-dir=.
Uploading "." at commit "HEAD" as binary input for the build ...
Uploading directory "." as binary input for the build ...
panic: runtime error: slice bounds out of range

goroutine 68 [running]:
panic(0x1982560, 0xc820012090)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/openshift/source-to-image/pkg/tar.(*stiTar).writeTarHeader(0xc820706000, 0xc8201e2480, 0xc8204965a6, 0x4, 0xc8204965a6, 0x4, 0x334e008, 0xc8204cc0d0, 0x0, 0x0, ...)
	/Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go:256 +0x50c
github.com/openshift/source-to-image/pkg/tar.(*stiTar).CreateTarStreamWithLogging.func1(0xc8204965a6, 0x4, 0x334e008, 0xc8204cc0d0, 0x0, 0x0, 0x0, 0x0)
	/Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go:201 +0x1df
path/filepath.walk(0xc8204965a6, 0x4, 0x334e008, 0xc8204cc0d0, 0xc82020c0c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/path/filepath/path.go:349 +0x80
path/filepath.Walk(0xc8204965a6, 0x4, 0xc82020c0c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/path/filepath/path.go:396 +0xe1
github.com/openshift/source-to-image/pkg/tar.(*stiTar).CreateTarStreamWithLogging(0xc820706000, 0xc8204965a6, 0x4, 0x335ba00, 0x335ba00, 0xc8206e4000, 0x0, 0x0, 0x0, 0x0)
	/Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go:194 +0x2f3
github.com/openshift/source-to-image/pkg/tar.(*stiTar).CreateTarStream(0xc820706000, 0xc8204965a6, 0x4, 0x335ba00, 0x335ba00, 0xc8206e4000, 0x0, 0x0)
	/Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go:182 +0x77
```

**Comment by smarterclayton** [comment]
Also, those messages are wrong - we should only be printing one of them.

**Comment by mfojtik** [comment]
@smarterclayton interesting... I can see that we passing the `path` in:

```
if err := tar.New().CreateTarStream(path, false, w); err != nil {
```

where the `path` is filepath.Abs(), so the S2I tar package should receive the absolute path here.

**Comment by csrwng** [comment]
@smarterclayton can you please recreate with --loglevel=5 ? The basic assumption of the writeTarHeader function is that all paths passed to it are children of the parent 'dir'. Somehow it's not the case in this instance.

**Comment by smarterclayton** [comment]
Symlinks?

**Comment by csrwng** [comment]
I tried with symlinks and couldn't reproduce

**Comment by smarterclayton** [comment]
On a mac:

```
$ oc start-build ruby-hello-world --from-dir=/tmp
Uploading "/tmp" at commit "HEAD" as binary input for the build ...
Uploading directory "/tmp" as binary input for the build ...
panic: runtime error: slice bounds out of range

goroutine 62 [running]:
panic(0x19dd840, 0xc820012090)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/openshift/source-to-image/pkg/tar.(*stiTar).writeTarHeader(0xc8205bc000, 0xc82033f680, 0x7fff5fbff80b, 0x4, 0x7fff5fbff80b, 0x4, 0x3448910, 0xc8204a2270, 0x0, 0x0, ...)
	/Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go:256 +0x50c
github.com/openshift/source-to-image/pkg/tar.(*stiTar).CreateTarStreamWithLogging.func1(0x7fff5fbff80b, 0x4, 0x3448910, 0xc8204a2270, 0x0, 0x0, 0x0, 0x0)
	/Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go:201 +0x1df
path/filepath.walk(0x7fff5fbff80b, 0x4, 0x3448910, 0xc8204a2270, 0xc820606080, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/path/filepath/path.go:349 +0x80
path/filepath.Walk(0x7fff5fbff80b, 0x4, 0xc820606080, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/path/filepath/path.go:396 +0xe1
github.com/openshift/source-to-image/pkg/tar.(*stiTar).CreateTarStreamWithLogging(0xc8205bc000, 0x7fff5fbff80b, 0x4, 0x3455c00, 0x3455c08, 0xc8204002c0, 0x0, 0x0, 0x0, 0x0)
	/Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go:194 +0x2f3
github.com/openshift/source-to-image/pkg/tar.(*stiTar).CreateTarStream(0xc8205bc000, 0x7fff5fbff80b, 0x4, 0x3455c00, 0x3455c08, 0xc8204002c0, 0x0, 0x0)
	/Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go:182 +0x77
github.com/openshift/origin/pkg/cmd/cli/cmd.streamPathToBuild.func2(0xc820088120, 0x7fff5fbff80b, 0x4)
	/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/cmd/cli/cmd/startbuild.go:486 +0x177
created by github.com/openshift/origin/pkg/cmd/cli/cmd.streamPathToBuild
	/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/cmd/cli/cmd/startbuild.go:492 +0x1313
[Jun 16 11:05 origin]$ ls -al /tmp
lrwxr-xr-x@ 1 root  wheel  11 Nov 29  2015 /tmp -> private/tmp
```

**Comment by smarterclayton** [comment]
```
$ ls -al /private/tmp/
total 11344
drwxrwxrwt  310 root     wheel    10540 Jun  1 09:30 .
drwxr-xr-x@   6 root     wheel      204 Nov 29  2015 ..
drwx------    3 clayton  wheel      102 Apr  8 09:49 .vbox-clayton-ipc
lrwxr-xr-x    1 root     wheel       48 Apr  7 12:01 5706846d19587 -> /private/etc/cups/ppd/_16w206_rdu_redhat_com.ppd
lrwxr-xr-x    1 root     wheel       48 Apr 12 09:35 570cf99da0c17 -> /private/etc/cups/ppd/_16w206_rdu_redhat_com.ppd
lrwxr-xr-x    1 root     wheel       48 Apr 13 09:49 570e4e6833337 -> /private/etc/cups/ppd/_16w206_rdu_redhat_com.ppd
lrwxr-xr-x    1 root     wheel       48 Apr 20 10:06 57178cd5af79f -> /private/etc/cups/ppd/_16w206_rdu_redhat_com.ppd
drwx------    3 root     wheel      102 Jun  1 08:46 KSOutOfProcessFetcher.0.ppfIhqX0vjaTSb8AJYobDV7Cu68=
drwx------    3 clayton  wheel      102 Jun  1 08:46 KSOutOfProcessFetcher.501.ppfIhqX0vjaTSb8AJYobDV7Cu68=
```

**Comment by csrwng** [comment]
thx

**Comment by csrwng** [comment]
The panic happens because the directory itself is a symlink and we try to write its header. https://github.com/openshift/source-to-image/pull/511
