### ISSUE TITLE
End-to-End Tests Wedge on `oc run --attach` Call and Fail After 4h30m

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9108]
We don't seem to have an issue for this yet, so I'm making this one to track it so people experiencing this issue on their test runs know that this is a known flake.

There are many runs that exhibit this flake, for example [test_pull_requests_origin_integration:1318](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/1318/)

When this flake occurs, we see one of the `oc run --attach` commands ([1](https://github.com/openshift/origin/blob/master/test/end-to-end/core.sh#L170), [2](https://github.com/openshift/origin/blob/master/test/end-to-end/core.sh#L174), [3](https://github.com/openshift/origin/blob/master/test/end-to-end/core.sh#L177)) wedge and hang forever.

When running with `spdystream` debugging on, we see the following from the client:

```
(0xc82011f340) (0xc820826280) Create stream
(0xc82011f340) (0xc820826280) Stream added, broadcasting: 1
(0xc82011f340) Reply frame received for 1
(0xc82011f340) (0xc8204c8140) Create stream
(0xc82011f340) (0xc8204c8140) Stream added, broadcasting: 3
(0xc82011f340) Reply frame received for 3
(0xc82011f340) (0xc8204c8280) Create stream
(0xc82011f340) (0xc8204c8280) Stream added, broadcasting: 5
(0xc82011f340) Reply frame received for 5
(0xc82011f340) (0xc8201d0320) Create stream
(0xc82011f340) (0xc8201d0320) Stream added, broadcasting: 7
(0xc82011f340) Reply frame received for 7
(0xc8204c8140) (3) Writing data frame
(0xc82011f340) Data frame received for 5
(0xc8204c8280) (5) Data frame handling
(0xc8204c8280) (5) Data frame sent
```

And the following from the server:

```
I0527 18:34:40.635517   22522 utils.go:11] (0xc825749b80) Add stream frame: 1
I0527 18:34:40.635539   22522 utils.go:11] (0xc825749b80) (0xc8210f0640) Stream added, broadcasting: 1
I0527 18:34:40.639019   22522 utils.go:11] (0xc825749b80) Add stream frame: 3
I0527 18:34:40.639035   22522 utils.go:11] (0xc825749b80) (0xc8210f0a00) Stream added, broadcasting: 3
I0527 18:34:40.640232   22522 utils.go:11] (0xc825749b80) Add stream frame: 5
I0527 18:34:40.640247   22522 utils.go:11] (0xc825749b80) (0xc8210f0b40) Stream added, broadcasting: 5
I0527 18:34:40.640798   22522 utils.go:11] (0xc825749b80) Add stream frame: 7
I0527 18:34:40.640814   22522 utils.go:11] (0xc825749b80) (0xc8210f0c80) Stream added, broadcasting: 7
I0527 18:34:40.641505   22522 utils.go:11] (0xc825749b80) Data frame received for 3
I0527 18:34:40.641517   22522 utils.go:11] (0xc8210f0a00) (3) Data frame handling
I0527 18:34:40.713551   22522 utils.go:11] (0xc8210f0b40) (5) Writing data frame
```

This indicates that we're hung waiting for the `stderr` to close for the container. Stacktraces from OpenShift indicate the `go-dockerclient` has not noticed that the container exited:
```
goroutine 393960 [chan receive, 7138 minutes]:
github.com/fsouza/go-dockerclient.(*Client).hijack.func3(0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go:698 +0x4e
github.com/fsouza/go-dockerclient.waiterFunc.Wait(0xc8312bc300, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go:565 +0x29
go.(*struct { github.com/fsouza/go-dockerclient.closerFunc; github.com/fsouza/go-dockerclient.waiterFunc }).Wait(0xc8312bc310, 0x0, 0x0)
        <autogenerated>:23 +0x47
github.com/fsouza/go-dockerclient.(*Client).AttachToContainer(0xc8226f2240, 0xc829593d80, 0x40, 0x7f8eac1635c0, 0xc82329dac0, 0x7f8eac12e988, 0xc82a777420, 0x7f8eac12e988, 0xc82329dc20, 0x101010101, ...)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container.go:1052 +0xb2
k8s.io/kubernetes/pkg/kubelet/dockertools.instrumentedDockerInterface.AttachToContainer(0x7f8eb1bca018, 0xc8226f2240, 0xc829593d80, 0x40, 0x7f8eac1635c0, 0xc82329dac0, 0x7f8eac12e988, 0xc82a777420, 0x7f8eac12e988, 0xc82329dc20, ...)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/instrumented_docker.go:199 +0xdc
k8s.io/kubernetes/pkg/kubelet/dockertools.(*instrumentedDockerInterface).AttachToContainer(0xc8220cfd80, 0xc829593d80, 0x40, 0x7f8eac1635c0, 0xc82329dac0, 0x7f8eac12e988, 0xc82a777420, 0x7f8eac12e988, 0xc82329dc20, 0x101010101, ...)
        <autogenerated>:51 +0xc7
k8s.io/kubernetes/pkg/kubelet/dockertools.(*DockerManager).AttachContainer(0xc824e5cb40, 0x3779ed8, 0x6, 0xc829593d80, 0x40, 0x7f8eac1635c0, 0xc82329dac0, 0x7f8eac163538, 0xc82a777420, 0x7f8eac163538, ...)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/manager.go:1087 +0x1a0
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).AttachContainer(0xc82304a480, 0xc82329d580, 0x15, 0x0, 0x0, 0xc826d21883, 0x10, 0x7f8eac1635c0, 0xc82329dac0, 0x7f8eac163538, ...)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:3497 +0x317
k8s.io/kubernetes/pkg/kubelet/server/remotecommand.ServeAttach(0x7f8eac162e18, 0xc82d91e0e0, 0xc8252bb420, 0x7f8eac06b098, 0xc82304a480, 0xc82329d580, 0x15, 0x0, 0x0, 0xc826d21883, ...)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server/remotecommand/attach.go:47 +0x216
k8s.io/kubernetes/pkg/kubelet/server.(*Server).getAttach(0xc823520f40, 0xc82795c3c0, 0xc826d218c0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:563 +0x646
k8s.io/kubernetes/pkg/kubelet/server.(*Server).(k8s.io/kubernetes/pkg/kubelet/server.getAttach)-fm(0xc82795c3c0, 0xc826d218c0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:294 +0x34
github.com/emicklei/go-restful.(*Container).dispatch.func6(0xc82795c3c0, 0xc826d218c0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x34
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc82795c450, 0xc82795c3c0, 0xc826d218c0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0x9f
k8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0xc82795c3c0, 0xc826d218c0, 0xc82795c450)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:220 +0x79d
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc82795c450, 0xc82795c3c0, 0xc826d218c0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x81
github.com/emicklei/go-restful.(*Container).dispatch(0xc824d31e60, 0x7f8eac162e18, 0xc82d91e0e0, 0xc8252bb420)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246 +0xe67
github.com/emicklei/go-restful.(*Container).(github.com/emicklei/go-restful.dispatch)-fm(0x7f8eac162e18, 0xc82d91e0e0, 0xc8252bb420)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc82440b770, 0x7f8eac162e18, 0xc82d91e0e0, 0xc8252bb420)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc822551ef0, 0x7f8eac162e18, 0xc82d91e0e0, 0xc8252bb420)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
github.com/emicklei/go-restful.Container.ServeHTTP(0x0, 0x0, 0x0, 0xc825184e00, 0xb, 0x10, 0xc822551ef0, 0x0, 0xc8245f3280, 0x1, ...)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:264 +0x48
k8s.io/kubernetes/pkg/kubelet/server.(*filteringContainer).ServeHTTP(0xc820749860, 0x7f8eac162e18, 0xc82d91e0e0, 0xc8252bb420)
        <autogenerated>:30 +0x84
k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc823520f00, 0x7f8eac162e18, 0xc82d91e0e0, 0xc8252bb420)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:940 +0x138
net/http.serverHandler.ServeHTTP(0xc825185080, 0x7f8eb1cb7f28, 0xc830e12270, 0xc8252bb420)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc825735280)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 395653 [select, 7079 minutes]:
github.com/fsouza/go-dockerclient.(*Client).hijack.func1(0x7f8eb1bc9860, 0xc82641af18, 0xc82b76c700, 0xc824fe14f0, 0xc825c44ae0, 0xc825c44a80)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go:680 +0x5e5
created by github.com/fsouza/go-dockerclient.(*Client).hijack
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go:691 +0x615

goroutine 393965 [IO wait, 7138 minutes]:
net.runtime_pollWait(0x7f8eac1c9a40, 0x72, 0xc8300c6000)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8328dff70, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8328dff70, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8328dff10, 0xc8300c6000, 0x8009, 0x8009, 0x0, 0x7f8eb1c97028, 0xc82005a080)
        /usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc829cea950, 0xc8300c6000, 0x8009, 0x8009, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).Read(0xc82db51140, 0xc8300c6000, 0x8009, 0x8009, 0x23, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:197 +0x126
github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy.StdCopy(0x7f8eac12e988, 0xc82a777420, 0x7f8eac12e988, 0xc82329dc20, 0x7f8eb1ce6330, 0xc82db51140, 0x1f7d, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:97 +0x163
github.com/fsouza/go-dockerclient.(*Client).hijack.func1.1(0xc82b997180, 0xc82db51200, 0xc82db51140, 0xc82db511a0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go:655 +0x1b0
created by github.com/fsouza/go-dockerclient.(*Client).hijack.func1
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go:658 +0x6ca
```

The full OpenShift log is available [here](https://drive.google.com/open?id=0B796GVFxYkfAamFkLUNaOFVkVk0), and the full OpenShift stacktrace as dumped when the container was wedged is available [here](https://drive.google.com/open?id=0B796GVFxYkfARElOYWFjR2R4d3M2WkRTRklHQndjUHVKUU93).

**Comment by stevekuznetsov** [comment]
We seem to have fixed this by ignoring it for long enough
