### ISSUE TITLE
jenkins pipeline template 

### ISSUE THREAD

**Issue by xcoulon** [openshift/origin#9302]
When I apply the pipeline template for a project named 'kitchenink-html5-mobile' instead of 'pipelineproject', the failure happens in Jenkins when the 'pipeline' job is to be created: 

I found in the jenkinstemplate [1] that I use that the default project name is 'pipelineproject' and I believe that it is not set with the actual project name.
However, I have no idea how to pass such a parameter from my project template [2] to the jenkins one.

[1] https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/pipeline/jenkinstemplate.json 
[2] https://github.com/redhat-kontinuity/kitchensink-html5-mobile/blob/master/pipelinetemplate.json

##### Version
oc v1.3.0-alpha.0-637-gaf94826
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Steps To Reproduce
update the jenkins template:
```
oc delete template jenkins -n openshift
oc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/pipeline/jenkinstemplate.json -n openshift
```

create a new project:
`oc new-project kitchensink-cli`

retrieve and apply the pipeline template for the project ('oc new-app -f' did not work using a file pulled from github):
```
wget https://raw.githubusercontent.com/redhat-kontinuity/kitchensink-html5-mobile/master/pipelinetemplate.json
oc new-app -f pipelinetemplate.json -p NAME=kitchensink-cli -p SOURCE_REPOSITORY_URL=https://github.com/redhat-kontinuity/kitchensink-html5-mobile.git

```
locate the pod which runs Jenkins and check the logs:
`oc logs -f <jenkins_pod_id>`

##### Current Result
```
WARNING: Failed to instantiate Key[type=io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Guice provision errors:
Error injecting constructor, io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default/oapi/v1/namespaces/pipelineproject/buildconfigs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
  at io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration.<init>(GlobalPluginConfiguration.java:59)
  ...

```
##### Expected Result

The pipeline job should have been created in Jenkins.

##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by bparees** [comment]
> I found in the jenkinstemplate [1] that I use that the default project name is 'pipelineproject' and I believe that it is not set with the actual project name.

no it doesn't, i removed that from the file.  the template no longer specifies a project.

there are two plugins within jenkins that need to know the name of the project you are using:

1) the kubernetes plugin.  today you must configure that manually by going to "manage jenkins".  There is a PR in the works to update the k8s plugin to auto-default the project to your current project:
https://github.com/jenkinsci/kubernetes-plugin/pull/59

2) the fabric openshift sync plugin.  @jimmidyson is the one to ask about how that behaves, but again you can configure the project via manage jenkins.  It should also default to the current project when no value is provided, but i don't know if it does or not.

I don't think you should be seeing anything default to "pipelineproject" anymore (if that's not your project name), if you are on current versions of the image and templates.

**Comment by jimmidyson** [comment]
>  It should also default to the current project when no value is provided, but i don't know if it does or not.

It will default to the current namespace for the jenkins pod it is running in. I think though that is only enabled in the latest unreleased version - will release a new version tomorrow & update relevant images.

**Comment by xcoulon** [comment]
@bparees @jimmidyson thanks for your feedbacks. I'll try again tomorrow once the relevant images have been released. @jimmidyson can you let me know when they are available ?

**Comment by jimmidyson** [comment]
I'll release the plugin, not sure of the process for updating the image though. Will leave that to @bparees if he's OK with that.

**Comment by xcoulon** [comment]
Just to clarify, I opened the issue here because I thought it would be more convenient to follow-up on GitHub rather than by mail. 
That being said, let me repeat once again that I really appreciate your help on this matter !

**Comment by bparees** [comment]
Once you update the plugin binary in the fabric s2i jenkins config repo (if
you guys are still doing that), the image should auto build and push to the
dev tag.

Ben Parees | OpenShift

**Comment by jimmidyson** [comment]
Aha! Thanks!

**Comment by jimmidyson** [comment]
I've updated fabric8io/openshift-jenkins-s2i-config with latest plugin versions including required fixes.

**Comment by xcoulon** [comment]
@jimmidyson, can you provide me with the instructions to test this ? Should I just pull the latest version of the `docker.io/openshift/jenkins-1-centos7:dev` image to get all the fixes you've made ?

**Comment by bparees** [comment]
latest dev image has been rebuilt/pushed, so probably.

**Comment by xcoulon** [comment]
ok, so I pulled the latest image:
`docker pull docker.io/openshift/jenkins-1-centos7:dev`

created the project again (after deleting it)
`oc new-project kitchensink-cli`

applied the template
`oc new-app -f pipelinetemplate.json -p NAME=kitchensink-cli -p SOURCE_REPOSITORY_URL=https://github.com/redhat-kontinuity/kitchensink-html5-mobile.git`

and got the following error in the Jenkins pod:

```
INFO: Completed initialization
Jun 14, 2016 3:00:49 PM io.fabric8.jenkins.openshiftsync.PipelineJobListener upsertBuildConfigForJob
INFO: Updating BuildConfig in namespace: kitchensink-cli with name: pipeline
Jun 14, 2016 3:00:49 PM io.fabric8.jenkins.openshiftsync.PipelineJobListener upsertBuildConfigForJob
WARNING: Failed to update BuildConfig: NamespaceName{kitchensink-cli:pipeline}. io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:112)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:32)
	at io.fabric8.jenkins.openshiftsync.PipelineJobListener.upsertBuildConfigForJob(PipelineJobListener.java:117)
	at io.fabric8.jenkins.openshiftsync.PipelineJobListener.upsertItem(PipelineJobListener.java:93)
	at io.fabric8.jenkins.openshiftsync.PipelineJobListener.onCreated(PipelineJobListener.java:62)
	at hudson.model.listeners.ItemListener$2.apply(ItemListener.java:186)
	at hudson.model.listeners.ItemListener$2.apply(ItemListener.java:184)
	at hudson.model.listeners.ItemListener.forAll(ItemListener.java:167)
	at hudson.model.listeners.ItemListener.fireOnCreated(ItemListener.java:184)
	at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:280)
	at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3105)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:179)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:163)
	at hudson.security.ACL.impersonate(ACL.java:213)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfigWatcher.java:163)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.onInitialBuildConfigs(BuildConfigWatcher.java:132)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.run(BuildConfigWatcher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:93)
	... 23 more
Caused by: java.lang.ClassCastException: io.fabric8.openshift.api.model.BuildTriggerPolicy cannot be cast to io.fabric8.openshift.api.model.BuildTriggerPolicy
	at io.fabric8.openshift.api.model.BuildConfigSpecFluentImpl.withTriggers(BuildConfigSpecFluentImpl.java:203)
	at io.fabric8.openshift.api.model.BuildConfigSpecBuilder.<init>(BuildConfigSpecBuilder.java:62)
	at io.fabric8.openshift.api.model.BuildConfigSpecBuilder.<init>(BuildConfigSpecBuilder.java:49)
	at io.fabric8.openshift.api.model.BuildConfigFluentImpl.withSpec(BuildConfigFluentImpl.java:76)
	at io.fabric8.openshift.api.model.BuildConfigFluentImpl.<init>(BuildConfigFluentImpl.java:31)
	at io.fabric8.openshift.api.model.DoneableBuildConfig.<init>(DoneableBuildConfig.java:15)
	... 28 more

Jun 14, 2016 3:00:49 PM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2 call
INFO: Created job pipeline from BuildConfig NamespaceName{kitchensink-cli:pipeline} with revision: 88698
Jun 14, 2016 3:00:49 PM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1 run
INFO: loaded initial BuildConfigs resources
```

which is what https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/67 is about, AFAICS.

**Comment by jimmidyson** [comment]
Yes that's the correct issue which I'm working on fixing right now. It's to do with Jenkins non-isolated classloaders for (de-)serializing config & conflicting versions of same JAR in global classpath. Switching to only using classes internal to the sync plugin for config elements.

**Comment by bparees** [comment]
pretty sure this is resolved, @xcoulon let me know if it's not working for you.
