### ISSUE TITLE
Vagrant issue with etcd after the rebase

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9370]
```
I0616 11:05:00.816591    1760 start_master.go:393] Public master address is https://localhost:8443
I0616 11:05:00.817028    1760 start_master.go:397] Using images from "openshift/origin-<component>:latest"
I0616 11:05:00.839312    1760 backend.go:104] backend: cannot open database at openshift.local.etcd/member/snap/db (invalid argument)
panic: backend: cannot open database at openshift.local.etcd/member/snap/db (invalid argument)

goroutine 1 [running]:
panic(0x2cd9b40, 0xc8209397f0)
    /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
log.Panicf(0x407d1e0, 0x28, 0xc82075f630, 0x2, 0x2)
    /usr/lib/golang/src/log/log.go:327 +0xd8
github.com/coreos/etcd/storage/backend.newBackend(0xc820aab4d0, 0x23, 0x5f5e100, 0x2710, 0x2)
    /home/mkargaki/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/storage/backend/backend.go:104 +0x1e2
github.com/coreos/etcd/storage/backend.NewDefaultBackend(0xc820aab4d0, 0x23, 0x0, 0x0)
    /home/mkargaki/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/storage/backend/backend.go:98 +0x53
github.com/coreos/etcd/etcdserver.NewServer(0xc820166640, 0xc8201666f8, 0x0, 0x0)
    /home/mkargaki/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/server.go:372 +0x16a5
github.com/openshift/origin/pkg/cmd/server/etcd/etcdserver.startEtcd(0xc8207605e8, 0x0, 0x0, 0x0)
    /home/mkargaki/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/etcd/etcdserver/server.go:131 +0x1131
github.com/openshift/origin/pkg/cmd/server/etcd/etcdserver.RunEtcd(0xc8206e7500)
    /home/mkargaki/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/etcd/etcdserver/run.go:56 +0xca0
github.com/openshift/origin/pkg/cmd/server/start.StartAPI(0xc8206c8000, 0xc820b3f590, 0x0, 0x0)
    /home/mkargaki/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:439 +0x6d
github.com/openshift/origin/pkg/cmd/server/start.(*Master).Start(0xc8207615b8, 0x0, 0x0)
    /home/mkargaki/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:399 +0x96d
github.com/openshift/origin/pkg/cmd/server/start.MasterOptions.RunMaster(0xc8205bea00, 0x1, 0x0, 0x0, 0x7fb49ac761c0, 0xc820024010, 0x0, 0x0, 0x0, 0x0, ...)
    /home/mkargaki/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:295 +0xe34
github.com/openshift/origin/pkg/cmd/server/start.AllInOneOptions.StartAllInOne(0xc8205245f0, 0xc82028def0, 0x0, 0x3eb3820, 0x16, 0x0, 0x0, 0x0, 0x3bf4790, 0xd, ...)
    /home/mkargaki/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_allinone.go:270 +0x23d
github.com/openshift/origin/pkg/cmd/server/start.NewCommandStartAllInOne.func1(0xc8205be800, 0xc8205d9aa0, 0x0, 0x3)
    /home/mkargaki/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_allinone.go:78 +0x104
github.com/spf13/cobra.(*Command).execute(0xc8205be800, 0xc8205d9a10, 0x3, 0x3, 0x0, 0x0)
    /home/mkargaki/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:565 +0x85a
github.com/spf13/cobra.(*Command).ExecuteC(0xc8205be400, 0xc8205be800, 0x0, 0x0)
    /home/mkargaki/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:651 +0x55c
github.com/spf13/cobra.(*Command).Execute(0xc8205be400, 0x0, 0x0)
    /home/mkargaki/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:610 +0x2d
main.main()
    /home/mkargaki/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:33 +0x199
```

The workaround is to run with `--etcd-dir` pointing to a new etcd directory but I believe there is value in fixing it for the default case (without using `--etcd-dir`)

cc: @mfojtik @smarterclayton @danmcp @deads2k @liggitt @derekwaynecarr

**Comment by mfojtik** [comment]
@kargakis this is related to the vagrantfs, I reported this upstream.

**Comment by php-coder** [comment]
Failed to run sample-app because of that. Should we update our instructions?

**Comment by linearregression** [comment]
I am very new to this. So where to change under the origin repo to put in the workaround?

**Comment by maleck13** [comment]
@linearregression Not sure if you're still having an issue, but this got me past this issue. You need to change the start command to be something like:

```
cd $GOPATH/src/github.com/openshift/origin/_ouput/local/bin/linux/amd64
sudo ./openshift start --etcd-dir='/tmp/openshift.local.etcd'

```

**Comment by stevekuznetsov** [comment]
@kargakis still an issue>

**Comment by mfojtik** [comment]
@stevekuznetsov @kargakis the tmpfs/vagrantfs issue was fixed couple months ago in upstream etcd (the preallocate issue).

**Comment by php-coder** [comment]
Have seen it a minute ago.

```console
$ openshift version
openshift v3.6.0-alpha.1+decce00-130-dirty
kubernetes v1.5.2+43a9be4
etcd 3.1.0
```

**Comment by stevekuznetsov** [comment]
Can you post more than the version, please?

**Comment by php-coder** [comment]
What information do you need?

**Comment by stevekuznetsov** [comment]
Did you get the same error? Logs? Stacktrace? Is it intermittent? Has etcd version been updated since the last time you saw it? Can you comment on what @mfojtik said above?

**Comment by php-coder** [comment]
Yes, error is the same. The full log is here: https://gist.github.com/php-coder/0eba2c926d31777389087c462ebdc64b

I'm running OpenShift with the command `sudo `which openshift` start --public-master=localhost --volume-dir=/opt/openshift-volumes --loglevel=4 &> /opt/openshift-logs/openshift.log`

> Has etcd version been updated since the last time you saw it?

I do nothing related to etcd and I suspect that OpenShift uses its own version.

I believe that this issue should be 100% reproducible on our vagrant box with Fedora 23.

**Comment by php-coder** [comment]
P.S. `--etcd-dir` works for me.

If we don't have time to debug it, let's just update the instruction then.

**Comment by stevekuznetsov** [comment]
Vagrant box not supported any longer.

/close
