### ISSUE TITLE
Prehook pod with Retry policy doesn't get reported correctly in deployer logs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9422]
```
oc cluster up
oc new-project foo
oc new-app cakephp-mysql-template
# wait for deployment
```

The prehook (cakephp-mysql-example-1-hook-pre) for the web framework races against the database starting.  I am seeing it fail the first, time, get restarted (or deleted and recreated) and then succeed.  However, the deployment logs do *not* reflect a successful run

Deployment pod logs:

```
oc logs dc/cakephp-mysql-example
--> pre: Running hook pod ...
Generating database schema 'cake schema generate' ...
PHP Warning:  strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60
PHP Stack trace:
PHP   1. {main}() /opt/app-root/src/app/Console/cake.php:0
PHP   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
PHP   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
PHP   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
PHP   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
PHP   6. require() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
PHP   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
PHP   8. include() /opt/app-root/src/lib/Cake/Core/Configure.php:72
PHP   9. Cache::config() /opt/app-root/src/app/Config/core.php:405
PHP  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
PHP  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
PHP  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
PHP  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60
PHP Warning:  strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60
PHP Stack trace:
PHP   1. {main}() /opt/app-root/src/app/Console/cake.php:0
PHP   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
PHP   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
PHP   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
PHP   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
PHP   6. require() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
PHP   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
PHP   8. include() /opt/app-root/src/lib/Cake/Core/Configure.php:72
PHP   9. Cache::config() /opt/app-root/src/app/Config/core.php:417
PHP  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
PHP  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
PHP  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
PHP  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60

Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60

Call Stack:
    0.0001     233400   1. {main}() /opt/app-root/src/app/Console/cake.php:0
    0.0009     321728   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
    0.0009     321928   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
    0.0013     324512   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
    0.0013     325000   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
    0.0017     400880   6. require('/opt/app-root/src/lib/Cake/bootstrap.php') /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
    0.0050    1220424   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
    0.0052    1242288   8. include('/opt/app-root/src/app/Config/core.php') /opt/app-root/src/lib/Cake/Core/Configure.php:72
    0.0067    1337976   9. Cache::config() /opt/app-root/src/app/Config/core.php:405
    0.0067    1339208  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
    0.0074    1448040  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
    0.0074    1449312  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
    0.0074    1450704  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60


Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60

Call Stack:
    0.0001     233400   1. {main}() /opt/app-root/src/app/Console/cake.php:0
    0.0009     321728   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
    0.0009     321928   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
    0.0013     324512   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
    0.0013     325000   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
    0.0017     400880   6. require('/opt/app-root/src/lib/Cake/bootstrap.php') /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
    0.0050    1220424   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
    0.0052    1242288   8. include('/opt/app-root/src/app/Config/core.php') /opt/app-root/src/lib/Cake/Core/Configure.php:72
    0.0119    1449720   9. Cache::config() /opt/app-root/src/app/Config/core.php:417
    0.0119    1450600  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
    0.0119    1450968  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
    0.0119    1452032  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
    0.0119    1453424  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60


Welcome to CakePHP v2.4.2 Console
---------------------------------------------------------------
App : app
Path: /opt/app-root/src/app/
---------------------------------------------------------------
Cake Schema Shell
---------------------------------------------------------------
Generating Schema...
Error: Database connection "Mysql" is missing, or could not be created.
#0 /opt/app-root/src/lib/Cake/Model/Datasource/DboSource.php(262): Mysql->connect()
#1 /opt/app-root/src/lib/Cake/Model/ConnectionManager.php(107): DboSource->__construct(Array)
#2 /opt/app-root/src/lib/Cake/Model/CakeSchema.php(204): ConnectionManager::getDataSource('default')
#3 /opt/app-root/src/lib/Cake/Console/Command/SchemaShell.php(151): CakeSchema->read(Array)
#4 /opt/app-root/src/lib/Cake/Console/Shell.php(433): SchemaShell->generate()
#5 /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php(209): Shell->runCommand('generate', Array)
#6 /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php(68): ShellDispatcher->dispatch()
#7 /opt/app-root/src/app/Console/cake.php(37): ShellDispatcher::run(Array)
#8 {main}
--> pre: Success
--> Scaling cakephp-mysql-example-1 to 1
--> Waiting up to 10m0s for pods in deployment cakephp-mysql-example-1 to become ready
```

Actual hook pod (which reports success), probably from the retry.

```
oc logs cakephp-mysql-example-1-hook-pre
Generating database schema 'cake schema generate' ...
PHP Warning:  strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60
PHP Stack trace:
PHP   1. {main}() /opt/app-root/src/app/Console/cake.php:0
PHP   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
PHP   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
PHP   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
PHP   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
PHP   6. require() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
PHP   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
PHP   8. include() /opt/app-root/src/lib/Cake/Core/Configure.php:72
PHP   9. Cache::config() /opt/app-root/src/app/Config/core.php:405
PHP  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
PHP  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
PHP  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
PHP  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60

Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60

Call Stack:
    0.0001     233400   1. {main}() /opt/app-root/src/app/Console/cake.php:0
    0.0016     321728   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
    0.0016     321928   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
    0.0025     324512   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
    0.0025     325000   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
    0.0035     400880   6. require('/opt/app-root/src/lib/Cake/bootstrap.php') /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
    0.0089    1220424   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
    0.0095    1242288   8. include('/opt/app-root/src/app/Config/core.php') /opt/app-root/src/lib/Cake/Core/Configure.php:72
    0.0116    1337976   9. Cache::config() /opt/app-root/src/app/Config/core.php:405
    0.0117    1339208  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
    0.0130    1448040  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
    0.0130    1449312  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
    0.0130    1450704  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60


Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60

Call Stack:
    0.0001     233400   1. {main}() /opt/app-root/src/app/Console/cake.php:0
    0.0016     321728   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
    0.0016     321928   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
    0.0025     324512   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
    0.0025     325000   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
    0.0035     400880   6. require('/opt/app-root/src/lib/Cake/bootstrap.php') /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
    0.0089    1220424   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
    0.0095    1242288   8. include('/opt/app-root/src/app/Config/core.php') /opt/app-root/src/lib/Cake/Core/Configure.php:72
    0.0223    1449720   9. Cache::config() /opt/app-root/src/app/Config/core.php:417
    0.0223    1450600  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
    0.0224    1450968  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
    0.0224    1452032  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
    0.0225    1453424  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60

PHP Warning:  strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60
PHP Stack trace:
PHP   1. {main}() /opt/app-root/src/app/Console/cake.php:0
PHP   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
PHP   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
PHP   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
PHP   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
PHP   6. require() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
PHP   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
PHP   8. include() /opt/app-root/src/lib/Cake/Core/Configure.php:72
PHP   9. Cache::config() /opt/app-root/src/app/Config/core.php:417
PHP  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
PHP  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
PHP  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
PHP  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60

Welcome to CakePHP v2.4.2 Console
---------------------------------------------------------------
App : app
Path: /opt/app-root/src/app/
---------------------------------------------------------------
Cake Schema Shell
---------------------------------------------------------------
Generating Schema...
Schema file: schema.php generated
Migrating database 'cake schema create' ...
PHP Warning:  strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60
PHP Stack trace:
PHP   1. {main}() /opt/app-root/src/app/Console/cake.php:0
PHP   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
PHP   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
PHP   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
PHP   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100

Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60

Call Stack:
    0.0001     233400   1. {main}() /opt/app-root/src/app/Console/cake.php:0
    0.0005     321728   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
    0.0005     321928   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
    0.0007     324512   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
    0.0007     325000   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
    0.0010     400880   6. require('/opt/app-root/src/lib/Cake/bootstrap.php') /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
    0.0049    1220424   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
    0.0050    1242288   8. include('/opt/app-root/src/app/Config/core.php') /opt/app-root/src/lib/Cake/Core/Configure.php:72
    0.0062    1337976   9. Cache::config() /opt/app-root/src/app/Config/core.php:405
    0.0062    1339208  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
    0.0067    1448040  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
    0.0067    1449312  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
    0.0068    1450704  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60

PHP   6. require() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
PHP   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
PHP   8. include() /opt/app-root/src/lib/Cake/Core/Configure.php:72
PHP   9. Cache::config() /opt/app-root/src/app/Config/core.php:405
PHP  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
PHP  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
PHP  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
PHP  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60
PHP Warning:  strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60
PHP Stack trace:
PHP   1. {main}() /opt/app-root/src/app/Console/cake.php:0
PHP   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
PHP   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
PHP   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
PHP   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
PHP   6. require() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
PHP   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
PHP   8. include() /opt/app-root/src/lib/Cake/Core/Configure.php:72
PHP   9. Cache::config() /opt/app-root/src/app/Config/core.php:417
PHP  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
PHP  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
PHP  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
PHP  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60

Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/app-root/src/lib/Cake/Cache/CacheEngine.php on line 60

Call Stack:
    0.0001     233400   1. {main}() /opt/app-root/src/app/Console/cake.php:0
    0.0005     321728   2. ShellDispatcher::run() /opt/app-root/src/app/Console/cake.php:37
    0.0005     321928   3. ShellDispatcher->__construct() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:67
    0.0007     324512   4. ShellDispatcher->_initEnvironment() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:56
    0.0007     325000   5. ShellDispatcher->_bootstrap() /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:100
    0.0010     400880   6. require('/opt/app-root/src/lib/Cake/bootstrap.php') /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php:138
    0.0049    1220424   7. Configure::bootstrap() /opt/app-root/src/lib/Cake/bootstrap.php:177
    0.0050    1242288   8. include('/opt/app-root/src/app/Config/core.php') /opt/app-root/src/lib/Cake/Core/Configure.php:72
    0.0090    1449720   9. Cache::config() /opt/app-root/src/app/Config/core.php:417
    0.0090    1450600  10. Cache::_buildEngine() /opt/app-root/src/lib/Cake/Cache/Cache.php:151
    0.0090    1450968  11. FileEngine->init() /opt/app-root/src/lib/Cake/Cache/Cache.php:180
    0.0090    1452032  12. CacheEngine->init() /opt/app-root/src/lib/Cake/Cache/Engine/FileEngine.php:81
    0.0090    1453424  13. strtotime() /opt/app-root/src/lib/Cake/Cache/CacheEngine.php:60


Welcome to CakePHP v2.4.2 Console
---------------------------------------------------------------
App : app
Path: /opt/app-root/src/app/
---------------------------------------------------------------
Cake Schema Shell
---------------------------------------------------------------
Schema is up to date.
```

I think there's a bug in the deployer pod retry logic where it's either not outputting the latest logs, or not correctly blocking until the pre hook succeeds.

**Comment by smarterclayton** [comment]
@kargakis something to look at on monday (trying to get this scenario rock solid so we can make it our "demo openshift" scenario).

@bparees whoever is the owner of the cakephp example can we clean up these crappy messages?

**Comment by smarterclayton** [comment]
It looks like we're not re-reading the logs when the container restarts due to a failure (and we're prematurely saying success).

**Comment by bparees** [comment]
doesn't have an owner anymore (@jhadvig wrote it), so if he's feeling generous with this time he can fix it, otherwise i'll find someone on devex.... @oatmealraisin maybe you'd like to take a look at cleaning up the messages (not the main issue @smarterclayton is reporting here)?  the repo is https://github.com/openshift/cakephp-ex

**Comment by kargakis** [comment]
@smarterclayton currently we don't even retry on Retry: https://github.com/openshift/origin/blob/604ae179d78568dea1512e0b60fdf2b1d58b1ff1/pkg/deploy/strategy/support/lifecycle.go#L82-L85

How did you see the hook being retried?

**Comment by smarterclayton** [comment]
The pod has a restart on failure which cause it to retry.  But we aren't
properly handling repeat container executions.  So it does the right thing,
but the deployer log gives a very misleading output.

On Jun 19, 2016, at 6:46 AM, Michail Kargakis <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> currently we don't even
retry on Retry:
https://github.com/openshift/origin/blob/604ae179d78568dea1512e0b60fdf2b1d58b1ff1/pkg/deploy/strategy/support/lifecycle.go#L82-L85

How did you see the hook being retried?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9422#issuecomment-226990663>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_pxjGWrvnMdEfP8u0iJ46quE42Pjqks5qNR4TgaJpZM4I5E7h>
.

**Comment by kargakis** [comment]
I just skimmed through the logs and noticed the problem. Will work on a fix later today
