### ISSUE TITLE
unit test flake: TestRecreate_initialDeployment

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9804]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/3179/testReport/junit/github/com_openshift_origin_pkg_deploy_strategy_recreate/TestRecreate_initialDeployment/

```
github.com/openshift/origin/pkg/deploy/strategy/recreate.TestRecreate_initialDeployment (from github.com_openshift_origin_pkg_deploy_strategy_recreate)

Failing for the past 1 build (Since Failed#3179 )
Took 10 ms.
add description
Stacktrace

=== RUN   TestRecreate_initialDeployment
--- FAIL: TestRecreate_initialDeployment (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x6550b9]

goroutine 41 [running]:
panic(0x1a795e0, 0xc820010140)
	/usr/lib/golang/src/runtime/panic.go:481 +0x3ff
testing.tRunner.func1(0xc8201803f0)
	/usr/lib/golang/src/testing/testing.go:467 +0x22a
panic(0x1a795e0, 0xc820010140)
	/usr/lib/golang/src/runtime/panic.go:443 +0x521
github.com/openshift/origin/pkg/deploy/strategy/support.WaitForReadyConfig.func1(0x95595d, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:592 +0x99
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait.pollImmediateInternal(0xc820082cc0, 0xc8201d38a8, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:180 +0x3b
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait.PollImmediate(0xf4240, 0x3b9aca00, 0xc8201d38a8, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:176 +0x5d
github.com/openshift/origin/pkg/deploy/strategy/support.WaitForReadyConfig(0xc8201b31e0, 0x0, 0x0, 0xf4240, 0x3b9aca00, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:597 +0xf6
github.com/openshift/origin/pkg/deploy/strategy/recreate.(*RecreateDeploymentStrategy).DeployWithAcceptor(0xc8201d3ea0, 0x0, 0xc8202e98c0, 0x3, 0x7f9271eae4f8, 0xc8203e4ed0, 0x0, 0x0)
	github.com/openshift/origin/pkg/deploy/strategy/recreate/_test/_obj_test/recreate.go:235 +0x2bbc
github.com/openshift/origin/pkg/deploy/strategy/recreate.(*RecreateDeploymentStrategy).Deploy(0xc8201d3ea0, 0x0, 0xc8202e98c0, 0x3, 0x0, 0x0)
	github.com/openshift/origin/pkg/deploy/strategy/recreate/_test/_obj_test/recreate.go:101 +0x88
github.com/openshift/origin/pkg/deploy/strategy/recreate.TestRecreate_initialDeployment(0xc8201803f0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/deploy/strategy/recreate/recreate_test.go:41 +0x7b8
testing.tRunner(0xc8201803f0, 0x2a587e0)
	/usr/lib/golang/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/lib/golang/src/testing/testing.go:582 +0xae3
```

**Comment by kargakis** [comment]
I am wondering why people are hitting this since the code responsible for it is not in master yet.

**Comment by kargakis** [comment]
> I am wondering why people are hitting this since the code responsible for it is not in master yet.

https://github.com/openshift/origin/pull/9799

**Comment by kargakis** [comment]
Not a flake
