### ISSUE TITLE
TestBuildOutputCycleDetection

### ISSUE THREAD

**Issue by oatmealraisin** [openshift/origin#9879]
```
Running TestBuildOutputCycleDetection...
failed  TestBuildOutputCycleDetection
I0714 18:12:19.234252   29940 plugins.go:46] Registered cloud provider "aws"
I0714 18:12:19.234441   29940 plugins.go:46] Registered cloud provider "gce"
I0714 18:12:19.234619   29940 plugins.go:46] Registered cloud provider "mesos"
I0714 18:12:19.234705   29940 plugins.go:46] Registered cloud provider "openstack"
I0714 18:12:19.234723   29940 plugins.go:46] Registered cloud provider "ovirt"
I0714 18:12:19.234741   29940 plugins.go:46] Registered cloud provider "rackspace"
I0714 18:12:19.240996   29940 plugins.go:46] Registered cloud provider "vsphere"
I0714 18:12:19.243141   29940 plugins.go:41] Registered credential provider "google-jwt-key"
I0714 18:12:19.243162   29940 plugins.go:41] Registered credential provider "google-dockercfg"
I0714 18:12:19.243171   29940 plugins.go:41] Registered credential provider "google-dockercfg-url"
I0714 18:12:19.243180   29940 plugins.go:41] Registered credential provider "google-container-registry"
I0714 18:12:19.244100   29940 plugins.go:74] Registered admission plugin "BuildDefaults"
I0714 18:12:19.244124   29940 plugins.go:74] Registered admission plugin "JenkinsBootstrapper"
I0714 18:12:19.244136   29940 plugins.go:74] Registered admission plugin "BuildOverrides"
I0714 18:12:19.244158   29940 plugins.go:74] Registered admission plugin "BuildByStrategy"
I0714 18:12:19.244175   29940 plugins.go:74] Registered admission plugin "LimitRanger"
I0714 18:12:19.244187   29940 plugins.go:74] Registered admission plugin "ImageLimitRange"
I0714 18:12:19.244216   29940 plugins.go:74] Registered admission plugin "OriginNamespaceLifecycle"
I0714 18:12:19.244229   29940 plugins.go:74] Registered admission plugin "OriginPodNodeEnvironment"
I0714 18:12:19.244243   29940 plugins.go:74] Registered admission plugin "ProjectRequestLimit"
I0714 18:12:19.244263   29940 plugins.go:74] Registered admission plugin "ClusterResourceOverride"
I0714 18:12:19.244280   29940 plugins.go:74] Registered admission plugin "ResourceQuota"
I0714 18:12:19.244290   29940 plugins.go:74] Registered admission plugin "ClusterResourceQuota"
I0714 18:12:19.244299   29940 plugins.go:74] Registered admission plugin "OriginResourceQuota"
I0714 18:12:19.244311   29940 plugins.go:74] Registered admission plugin "RunOnceDuration"
I0714 18:12:19.244343   29940 plugins.go:74] Registered admission plugin "PodNodeConstraints"
I0714 18:12:19.244372   29940 plugins.go:74] Registered admission plugin "SecurityContextConstraint"
I0714 18:12:19.244387   29940 plugins.go:74] Registered admission plugin "SCCExecRestrictions"
I0714 18:12:19.244396   29940 plugins.go:74] Registered admission plugin "AlwaysAdmit"
I0714 18:12:19.244409   29940 plugins.go:74] Registered admission plugin "AlwaysPullImages"
I0714 18:12:19.244417   29940 plugins.go:74] Registered admission plugin "DenyEscalatingExec"
I0714 18:12:19.244429   29940 plugins.go:74] Registered admission plugin "DenyExecOnPrivileged"
I0714 18:12:19.244439   29940 plugins.go:74] Registered admission plugin "NamespaceExists"
I0714 18:12:19.244453   29940 plugins.go:74] Registered admission plugin "NamespaceLifecycle"
I0714 18:12:19.244463   29940 plugins.go:74] Registered admission plugin "PersistentVolumeLabel"
I0714 18:12:19.244477   29940 plugins.go:74] Registered admission plugin "ServiceAccount"
I0714 18:12:19.244492   29940 plugins.go:74] Registered admission plugin "LimitPodHardAntiAffinityTopology"
I0714 18:12:19.244507   29940 plugins.go:74] Registered admission plugin "AlwaysDeny"
I0714 18:12:19.244695   29940 plugins.go:74] Registered admission plugin "InitialResources"
I0714 18:12:19.244715   29940 plugins.go:74] Registered admission plugin "NamespaceAutoProvision"
I0714 18:12:19.244731   29940 plugins.go:74] Registered admission plugin "PodSecurityPolicy"
I0714 18:12:19.244742   29940 plugins.go:74] Registered admission plugin "SecurityContextDeny"
I0714 18:12:19.252126   29940 plugins.go:74] Registered admission plugin "RestrictedEndpointsAdmission"
I0714 18:12:19.252147   29940 plugins.go:74] Registered admission plugin "ExternalIPRanger"
I0714 18:12:19.255038   29940 imagestreamlookup.go:48] checking ImageStreams default/centos with ref "latest"
I0714 18:12:19.255085   29940 imagestreamlookup.go:64] unscored ruby: 1
I0714 18:12:19.255111   29940 dockerimagelookup.go:264] checking Docker registry for "centos", allow-insecure=false
I0714 18:12:19.312311   29940 client.go:320] Found registry v2 API at https://registry-1.docker.io/v2/
I0714 18:12:19.561836   29940 dockerimagelookup.go:293] found image: &dockerregistry.Image{Image:docker.Image{ID:"sha256:794a51dd9c12778b34a5f0ab76b974e772441e90ced95846ae6b3fed04bf74ce", RepoTags:[]string(nil), Parent:"6930af01dfa24433bf45c1b5d1316d332a821c1170b545301e07325149103435", Comment:"", Created:time.Time{sec:63603009264, nsec:684042882, loc:(*time.Location)(0x72894c0)}, Container:"6f58ffdf7151fb30260c32c5ec9e8e78436b97d8413b6812ee425e7a2e443a24", ContainerConfig:docker.Config{Hostname:"73b1fe371681", Domainname:"", User:"", Memory:0, MemorySwap:0, MemoryReservation:0, KernelMemory:0, CPUShares:0, CPUSet:"", AttachStdin:false, AttachStdout:false, AttachStderr:false, PortSpecs:[]string(nil), ExposedPorts:map[docker.Port]struct {}(nil), StopSignal:"", Tty:false, OpenStdin:false, StdinOnce:false, Env:[]string{"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}, Cmd:[]string{"/bin/sh", "-c", "#(nop) CMD [\"/bin/bash\"]"}, DNS:[]string(nil), Image:"sha256:1e4a53b4eea0f12671536ec11e5f0620eb81193f73963c95c1f1d92c3b2df9ea", Volumes:map[string]struct {}(nil), VolumeDriver:"", VolumesFrom:"", WorkingDir:"", MacAddress:"", Entrypoint:[]string(nil), NetworkDisabled:false, SecurityOpts:[]string(nil), OnBuild:[]string(nil), Mounts:[]docker.Mount(nil), Labels:map[string]string{"build-date":"20160701", "license":"GPLv2", "name":"CentOS Base Image", "vendor":"CentOS"}}, DockerVersion:"1.10.3", Author:"https://github.com/CentOS/sig-cloud-instance-images", Config:(*docker.Config)(0xc820892380), Architecture:"amd64", Size:0, VirtualSize:0, RepoDigests:[]string(nil)}, PullByID:true}
I0714 18:12:19.562327   29940 dockerimagelookup.go:312] Adding Docker image "centos" (tag "latest"), 794a51d, from Docker Hub, author https://github.com/CentOS/sig-cloud-instance-images as component match for "centos" with score 0
I0714 18:12:19.562354   29940 resolve.go:167] Code []
I0714 18:12:19.562372   29940 resolve.go:168] Components [centos]
I0714 18:12:19.562407   29940 newapp.go:291] found group: centos
I0714 18:12:19.562420   29940 newapp.go:300] will add "" secrets into a build for a source build of ""
I0714 18:12:19.562446   29940 newapp.go:322] will use "centos" as the base image for a source build of ""
I0714 18:12:19.562658   29940 imagestreamlookup.go:48] checking ImageStreams openshift/ruby-22-centos7 with ref "latest"
I0714 18:12:19.562684   29940 imagestreamlookup.go:64] unscored ruby: 1
I0714 18:12:19.562701   29940 dockerimagelookup.go:264] checking Docker registry for "openshift/ruby-22-centos7", allow-insecure=false
I0714 18:12:19.574367   29940 client.go:320] Found registry v2 API at https://registry-1.docker.io/v2/
I0714 18:12:19.801489   29940 dockerimagelookup.go:293] found image: &dockerregistry.Image{Image:docker.Image{ID:"sha256:5dc0856fea9551e102815863cceeabd3aee862ec4ad5f2625eb51564924f0360", RepoTags:[]string(nil), Parent:"87b73f98dc2cde92e06b47b36aec18eab55b7191a00015ede006c09953f7875d", Comment:"", Created:time.Time{sec:63579139986, nsec:857144000, loc:(*time.Location)(0x72894c0)}, Container:"", ContainerConfig:docker.Config{Hostname:"", Domainname:"", User:"", Memory:0, MemorySwap:0, MemoryReservation:0, KernelMemory:0, CPUShares:0, CPUSet:"", AttachStdin:false, AttachStdout:false, AttachStderr:false, PortSpecs:[]string(nil), ExposedPorts:map[docker.Port]struct {}(nil), StopSignal:"", Tty:false, OpenStdin:false, StdinOnce:false, Env:[]string(nil), Cmd:[]string(nil), DNS:[]string(nil), Image:"", Volumes:map[string]struct {}(nil), VolumeDriver:"", VolumesFrom:"", WorkingDir:"", MacAddress:"", Entrypoint:[]string(nil), NetworkDisabled:false, SecurityOpts:[]string(nil), OnBuild:[]string(nil), Mounts:[]docker.Mount(nil), Labels:map[string]string(nil)}, DockerVersion:"1.7.1", Author:"SoftwareCollections.org <sclorg@redhat.com>", Config:(*docker.Config)(0xc8208b2fc0), Architecture:"amd64", Size:54098009, VirtualSize:0, RepoDigests:[]string(nil)}, PullByID:true}
I0714 18:12:19.801859   29940 dockerimagelookup.go:312] Adding Docker image "openshift/ruby-22-centos7" (tag "latest"), 5dc0856, from Docker Hub, 51.592mb, author SoftwareCollections.org <sclorg@redhat.com> as component match for "openshift/ruby-22-centos7" with score 0
I0714 18:12:19.801886   29940 resolve.go:167] Code []
I0714 18:12:19.801903   29940 resolve.go:168] Components [openshift/ruby-22-centos7]
I0714 18:12:19.801928   29940 newapp.go:291] found group: openshift/ruby-22-centos7
I0714 18:12:19.801938   29940 newapp.go:300] will add "" secrets into a build for a source build of ""
I0714 18:12:19.801956   29940 newapp.go:322] will use "openshift/ruby-22-centos7" as the base image for a source build of ""
I0714 18:12:19.802124   29940 imagestreamlookup.go:48] checking ImageStreams default/centos with ref "latest"
I0714 18:12:19.802163   29940 imagestreamlookup.go:64] unscored ruby: 1
I0714 18:12:19.802177   29940 dockerimagelookup.go:264] checking Docker registry for "centos", allow-insecure=false
I0714 18:12:19.814326   29940 client.go:320] Found registry v2 API at https://registry-1.docker.io/v2/
I0714 18:12:19.947300   29940 dockerimagelookup.go:293] found image: &dockerregistry.Image{Image:docker.Image{ID:"sha256:794a51dd9c12778b34a5f0ab76b974e772441e90ced95846ae6b3fed04bf74ce", RepoTags:[]string(nil), Parent:"6930af01dfa24433bf45c1b5d1316d332a821c1170b545301e07325149103435", Comment:"", Created:time.Time{sec:63603009264, nsec:684042882, loc:(*time.Location)(0x72894c0)}, Container:"6f58ffdf7151fb30260c32c5ec9e8e78436b97d8413b6812ee425e7a2e443a24", ContainerConfig:docker.Config{Hostname:"73b1fe371681", Domainname:"", User:"", Memory:0, MemorySwap:0, MemoryReservation:0, KernelMemory:0, CPUShares:0, CPUSet:"", AttachStdin:false, AttachStdout:false, AttachStderr:false, PortSpecs:[]string(nil), ExposedPorts:map[docker.Port]struct {}(nil), StopSignal:"", Tty:false, OpenStdin:false, StdinOnce:false, Env:[]string{"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}, Cmd:[]string{"/bin/sh", "-c", "#(nop) CMD [\"/bin/bash\"]"}, DNS:[]string(nil), Image:"sha256:1e4a53b4eea0f12671536ec11e5f0620eb81193f73963c95c1f1d92c3b2df9ea", Volumes:map[string]struct {}(nil), VolumeDriver:"", VolumesFrom:"", WorkingDir:"", MacAddress:"", Entrypoint:[]string(nil), NetworkDisabled:false, SecurityOpts:[]string(nil), OnBuild:[]string(nil), Mounts:[]docker.Mount(nil), Labels:map[string]string{"vendor":"CentOS", "build-date":"20160701", "license":"GPLv2", "name":"CentOS Base Image"}}, DockerVersion:"1.10.3", Author:"https://github.com/CentOS/sig-cloud-instance-images", Config:(*docker.Config)(0xc8209da540), Architecture:"amd64", Size:0, VirtualSize:0, RepoDigests:[]string(nil)}, PullByID:true}
I0714 18:12:19.947653   29940 dockerimagelookup.go:312] Adding Docker image "centos" (tag "latest"), 794a51d, from Docker Hub, author https://github.com/CentOS/sig-cloud-instance-images as component match for "centos" with score 0
I0714 18:12:19.947696   29940 resolve.go:167] Code []
I0714 18:12:19.947712   29940 resolve.go:168] Components [centos]
I0714 18:12:19.947735   29940 newapp.go:291] found group: centos
I0714 18:12:19.947745   29940 newapp.go:300] will add "" secrets into a build for a source build of ""
I0714 18:12:19.947764   29940 newapp.go:322] will use "centos" as the base image for a source build of ""
--- FAIL: TestBuildOutputCycleDetection (0.69s)
	newapp_test.go:1347: stderr: got ""; want "--> WARNING: output image of \"default/centos:latest\" must be different than input\n"
	newapp_test.go:1347: stderr: got ""; want "--> WARNING: output image of \"default/ruby-22-centos7:latest\" must be different than input\n"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x5ff9da]

goroutine 89 [running]:
panic(0x3af9480, 0xc82000e180)
	/usr/lib/golang/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc820209b00)
	/usr/lib/golang/src/testing/testing.go:467 +0x192
panic(0x3af9480, 0xc82000e180)
	/usr/lib/golang/src/runtime/panic.go:443 +0x4e9
github.com/openshift/origin/test/integration.TestBuildOutputCycleDetection.func3(0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/integration/newapp_test.go:1316 +0x4a
github.com/openshift/origin/test/integration.TestBuildOutputCycleDetection(0xc820209b00)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/integration/newapp_test.go:1338 +0x981
testing.tRunner(0xc820209b00, 0x729ca98)
	/usr/lib/golang/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/lib/golang/src/testing/testing.go:582 +0x892
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3384/consoleFull#89091850056bf4006e4b05b79524e5923

**Comment by bparees** [comment]
this isn't a flake, it's a legit failure caused by the changes in the PR.

**Comment by stevekuznetsov** [comment]
@oatmealraisin promised me he didn't many any changes to that ... lol

**Comment by bparees** [comment]
@stevekuznetsov hopefully you learned a valuable lesson :)

**Comment by oatmealraisin** [comment]
@stevekuznetsov Promise is a strong word, I just checked the box saying "I believe the above information is accurate"
